BeatSaber-Hooks: shared/rapidjson/example/archiver/archivertest.cpp File Reference
archivertest.cpp File Reference
#include "archiver.h"
#include <iostream>
#include <vector>
Data Structures
struct Student
struct Group
class Shape
class Circle
class Box
class Canvas
Functions
template<typename Archiver >
Archiver & operator& (Archiver &ar, Student &s)
std::ostream & operator<< (std::ostream &os, const Student &s)
void test1 ()
template<typename Archiver >
Archiver & operator& (Archiver &ar, Group &g)
std::ostream & operator<< (std::ostream &os, const Group &g)
void test2 ()
template<typename Archiver >
Archiver & operator& (Archiver &ar, Shape &s)
template<typename Archiver >
Archiver & operator& (Archiver &ar, Circle &c)
template<typename Archiver >
Archiver & operator& (Archiver &ar, Box &b)
template<typename Archiver >
Archiver & operator& (Archiver &ar, Shape *&shape)
template<typename Archiver >
Archiver & operator& (Archiver &ar, Canvas &c)
void test3 ()
int main ()
Function Documentation
main()
int main ()
Definition at line 283 of file archivertest.cpp.
            {
     test1();
     test2();
     test3();
 }
References test1(), test2(), and test3().
operator&() [1/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Box & b)
Definition at line 195 of file archivertest.cpp.
{
     ar & static_cast<Shape&>(b);
     ar.Member("width") & b.width_;
     ar.Member("height") & b.height_;
     return ar;
 }
operator&() [2/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Canvas & c)
Definition at line 245 of file archivertest.cpp.
{
     size_t shapeCount = c.shapes_.size();
     ar.StartArray(&shapeCount);
     if (ar.IsReader) {
         c.Clear();
         c.shapes_.resize(shapeCount);
     }
     for (size_t i = 0; i < shapeCount; i++)
         ar & c.shapes_[i];
     return ar.EndArray();
 }
operator&() [3/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Circle & c)
Definition at line 169 of file archivertest.cpp.
{
     ar & static_cast<Shape&>(c);
     ar.Member("radius") & c.radius_;
     return ar;
 }
operator&() [4/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Group & g)
Definition at line 68 of file archivertest.cpp.
{
     ar.StartObject();
     ar.Member("groupName");
     ar & g.groupName;
     ar.Member("students");
     size_t studentCount = g.students.size();
     ar.StartArray(&studentCount);
     if (ar.IsReader)
         g.students.resize(studentCount);
     for (size_t i = 0; i < studentCount; i++)
         ar & g.students[i];
     ar.EndArray();
     return ar.EndObject();
 }
References Group::groupName, and Group::students.
operator&() [5/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Shape & s)
Definition at line 143 of file archivertest.cpp.
{
     ar.Member("x") & s.x_;
     ar.Member("y") & s.y_;
     return ar;
 }
operator&() [6/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Shape *& shape)
Definition at line 229 of file archivertest.cpp.
{
     std::string type = ar.IsReader ? "" : shape->GetType();
     ar.StartObject();
     ar.Member("type") & type;
     if (type == "Circle") {
         if (ar.IsReader) shape = new Circle;
         ar & static_cast<Circle&>(*shape);
     }
     else if (type == "Box") {
         if (ar.IsReader) shape = new Box;
         ar & static_cast<Box&>(*shape);
     }
     return ar.EndObject();
 }
References Shape::GetType().
operator&() [7/7]
template<typename Archiver > Archiver& operator& (Archiver & ar, Student & s)
Definition at line 21 of file archivertest.cpp.
{
     ar.StartObject();
     ar.Member("name") & s.name;
     ar.Member("age") & s.age;
     ar.Member("height") & s.height;
     ar.Member("canSwim") & s.canSwim;
     return ar.EndObject();
 }
References Student::age, Student::canSwim, Student::height, and Student::name.
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const Group & g)
Definition at line 86 of file archivertest.cpp.
{
     os << g.groupName << std::endl;
     for (std::vector<Student>::const_iterator itr = g.students.begin(); itr != g.students.end(); ++itr)
         os << *itr << std::endl;
     return os;
 }
References Group::groupName, and Group::students.
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const Student & s)
Definition at line 30 of file archivertest.cpp.
{
     return os << s.name << " " << s.age << " " << s.height << " " << s.canSwim;
 }
References Student::age, Student::canSwim, Student::height, and Student::name.
test1()
void test1 ()
Definition at line 34 of file archivertest.cpp.
              {
     std::string json;
     // Serialize
     {
         Student s("Lua", 9, 150.5, true);
         JsonWriter writer;
         writer & s;
         json = writer.GetString();
         std::cout << json << std::endl;
     }
     // Deserialize
     {
         Student s;
         JsonReader reader(json.c_str());
         reader & s;
         std::cout << s << std::endl;
     }
 }
References JsonWriter::GetString(), and json.
Referenced by main().
test2()
void test2 ()
Definition at line 93 of file archivertest.cpp.
              {
     std::string json;
     // Serialize
     {
         Group g;
         g.groupName = "Rainbow";
         Student s1("Lua", 9, 150.5, true);
         Student s2("Mio", 7, 120.0, false);
         g.students.push_back(s1);
         g.students.push_back(s2);
         JsonWriter writer;
         writer & g;
         json = writer.GetString();
         std::cout << json << std::endl;
     }
     // Deserialize
     {
         Group g;
         JsonReader reader(json.c_str());
         reader & g;
         std::cout << g << std::endl;
     }
 }
References JsonWriter::GetString(), Group::groupName, json, and Group::students.
Referenced by main().
test3()
void test3 ()
Definition at line 257 of file archivertest.cpp.
              {
     std::string json;
     // Serialize
     {
         Canvas c;
         c.AddShape(new Circle(1.0, 2.0, 3.0));
         c.AddShape(new Box(4.0, 5.0, 6.0, 7.0));
         JsonWriter writer;
         writer & c;
         json = writer.GetString();
         std::cout << json << std::endl;
     }
     // Deserialize
     {
         Canvas c;
         JsonReader reader(json.c_str());
         reader & c;
         c.Print(std::cout);
     }
 }
References Canvas::AddShape(), JsonWriter::GetString(), json, and Canvas::Print().
Referenced by main().