BeatSaber-Hooks: shared/rapidjson/test/unittest/bigintegertest.cpp File Reference
bigintegertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/internal/biginteger.h"
Macros
#define BIGINTEGER_LITERAL(s) BigInteger(s, sizeof(s) - 1)
Functions
TEST (BigInteger, Constructor)
TEST (BigInteger, AddUint64)
TEST (BigInteger, MultiplyUint64)
TEST (BigInteger, MultiplyUint32)
TEST (BigInteger, LeftShift)
TEST (BigInteger, Compare)
Variables
static const BigInteger kZero (0)
static const BigInteger kOne (1)
static const BigInteger kUint64Max = BigInteger("18446744073709551615" , sizeof("18446744073709551615") - 1)
static const BigInteger kTwo64 = BigInteger("18446744073709551616" , sizeof("18446744073709551616") - 1)
Macro Definition Documentation
BIGINTEGER_LITERAL
#define BIGINTEGER_LITERAL (s) BigInteger(s, sizeof(s) - 1)
Definition at line 21 of file bigintegertest.cpp.
Function Documentation
TEST() [1/6]
TEST (BigInteger , AddUint64)
Definition at line 44 of file bigintegertest.cpp.
{
     BigInteger a = kZero;
     a += 0u;
     EXPECT_TRUE(kZero == a);
     a += 1u;
     EXPECT_TRUE(kOne == a);
     a += 1u;
     EXPECT_TRUE(BigInteger(2) == a);
     EXPECT_TRUE(BigInteger(RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0xFFFFFFFF)) == kUint64Max);
     BigInteger b = kUint64Max;
     b += 1u;
     EXPECT_TRUE(kTwo64 == b);
     b += RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0xFFFFFFFF);
     EXPECT_TRUE(BIGINTEGER_LITERAL("36893488147419103231") == b);
 }
References rapidjson::a, BIGINTEGER_LITERAL, kOne, kTwo64, kUint64Max, kZero, and RAPIDJSON_UINT64_C2.
TEST() [2/6]
TEST (BigInteger , Compare)
Definition at line 130 of file bigintegertest.cpp.
{
     EXPECT_EQ(0, kZero.Compare(kZero));
     EXPECT_EQ(1, kOne.Compare(kZero));
     EXPECT_EQ(-1, kZero.Compare(kOne));
     EXPECT_EQ(0, kUint64Max.Compare(kUint64Max));
     EXPECT_EQ(0, kTwo64.Compare(kTwo64));
     EXPECT_EQ(-1, kUint64Max.Compare(kTwo64));
     EXPECT_EQ(1, kTwo64.Compare(kUint64Max));
 }
References rapidjson::internal::BigInteger::Compare(), kOne, kTwo64, kUint64Max, and kZero.
TEST() [3/6]
TEST (BigInteger , Constructor)
Definition at line 28 of file bigintegertest.cpp.
{
     EXPECT_TRUE(kZero.IsZero());
     EXPECT_TRUE(kZero == kZero);
     EXPECT_TRUE(kZero == BIGINTEGER_LITERAL("0"));
     EXPECT_TRUE(kZero == BIGINTEGER_LITERAL("00"));
     const BigInteger a(123);
     EXPECT_TRUE(a == a);
     EXPECT_TRUE(a == BIGINTEGER_LITERAL("123"));
     EXPECT_TRUE(a == BIGINTEGER_LITERAL("0123"));
     EXPECT_EQ(2u, kTwo64.GetCount());
     EXPECT_EQ(0u, kTwo64.GetDigit(0));
     EXPECT_EQ(1u, kTwo64.GetDigit(1));
 }
References rapidjson::a, BIGINTEGER_LITERAL, rapidjson::internal::BigInteger::GetCount(), rapidjson::internal::BigInteger::GetDigit(), rapidjson::internal::BigInteger::IsZero(), kTwo64, and kZero.
TEST() [4/6]
TEST (BigInteger , LeftShift)
Definition at line 107 of file bigintegertest.cpp.
{
     BigInteger a = kZero;
     a <<= 1;
     EXPECT_TRUE(kZero == a);
     a <<= 64;
     EXPECT_TRUE(kZero == a);
     a = BigInteger(123);
     a <<= 0;
     EXPECT_TRUE(BigInteger(123) == a);
     a <<= 1;
     EXPECT_TRUE(BigInteger(246) == a);
     a <<= 64;
     EXPECT_TRUE(BIGINTEGER_LITERAL("4537899042132549697536") == a);
     a <<= 99;
     EXPECT_TRUE(BIGINTEGER_LITERAL("2876235222267216943024851750785644982682875244576768") == a);
     a = 1;
     a <<= 64; // a.count_ != 1
     a <<= 256; // interShift == 0
     EXPECT_TRUE(BIGINTEGER_LITERAL("2135987035920910082395021706169552114602704522356652769947041607822219725780640550022962086936576") == a);
 }
References rapidjson::a, BIGINTEGER_LITERAL, and kZero.
TEST() [5/6]
TEST (BigInteger , MultiplyUint32)
Definition at line 85 of file bigintegertest.cpp.
{
     BigInteger a = kZero;
     a *= static_cast <uint32_t>(0);
     EXPECT_TRUE(kZero == a);
     a *= static_cast <uint32_t>(123);
     EXPECT_TRUE(kZero == a);
     BigInteger b = kOne;
     b *= static_cast<uint32_t>(1);
     EXPECT_TRUE(kOne == b);
     b *= static_cast<uint32_t>(0);
     EXPECT_TRUE(kZero == b);
     BigInteger c(123);
     c *= static_cast<uint32_t>(456u);
     EXPECT_TRUE(BigInteger(123u * 456u) == c);
     c *= 0xFFFFFFFFu;
     EXPECT_TRUE(BIGINTEGER_LITERAL("240896125641960") == c);
     c *= 0xFFFFFFFFu;
     EXPECT_TRUE(BIGINTEGER_LITERAL("1034640981124429079698200") == c);
 }
References rapidjson::a, BIGINTEGER_LITERAL, kOne, and kZero.
TEST() [6/6]
TEST (BigInteger , MultiplyUint64)
Definition at line 63 of file bigintegertest.cpp.
{
     BigInteger a = kZero;
     a *= static_cast <uint64_t>(0);
     EXPECT_TRUE(kZero == a);
     a *= static_cast <uint64_t>(123);
     EXPECT_TRUE(kZero == a);
     BigInteger b = kOne;
     b *= static_cast<uint64_t>(1);
     EXPECT_TRUE(kOne == b);
     b *= static_cast<uint64_t>(0);
     EXPECT_TRUE(kZero == b);
     BigInteger c(123);
     c *= static_cast<uint64_t>(456u);
     EXPECT_TRUE(BigInteger(123u * 456u) == c);
     c *= RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0xFFFFFFFF);
     EXPECT_TRUE(BIGINTEGER_LITERAL("1034640981606221330982120") == c);
     c *= RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0xFFFFFFFF);
     EXPECT_TRUE(BIGINTEGER_LITERAL("19085757395861596536664473018420572782123800") == c);
 }
References rapidjson::a, BIGINTEGER_LITERAL, kOne, kZero, and RAPIDJSON_UINT64_C2.
Variable Documentation
kOne
const BigInteger kOne(1) (1) static
Referenced by TEST().
kTwo64
const BigInteger kTwo64 = BigInteger("18446744073709551616" , sizeof("18446744073709551616") - 1) static
Definition at line 26 of file bigintegertest.cpp.
Referenced by TEST().
kUint64Max
const BigInteger kUint64Max = BigInteger("18446744073709551615" , sizeof("18446744073709551615") - 1) static
Definition at line 25 of file bigintegertest.cpp.
Referenced by TEST().
kZero
const BigInteger kZero(0) (0) static
Referenced by TEST().