BeatSaber-Hooks: shared/rapidjson/example/capitalize/capitalize.cpp File Reference
capitalize.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/writer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/error/en.h"
#include <vector>
#include <cctype>
Data Structures
struct CapitalizeFilter< OutputHandler >
Functions
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 48 of file capitalize.cpp.
{
     // Prepare JSON reader and input stream.
     Reader reader;
     char readBuffer[65536];
     FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
     // Prepare JSON writer and output stream.
     char writeBuffer[65536];
     FileWriteStream os(stdout, writeBuffer, sizeof(writeBuffer));
     Writer<FileWriteStream> writer(os);
     // JSON reader parse from the input stream and let writer generate the output.
     CapitalizeFilter<Writer<FileWriteStream> > filter(writer);
     if (!reader.Parse(is, filter)) {
         fprintf(stderr, "\nError(%u): %s\n", static_cast<unsigned>(reader.GetErrorOffset()), GetParseError_En(reader.GetParseErrorCode()));
         return 1;
     }
     return 0;
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), rapidjson::GetParseError_En(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().