BeatSaber-Hooks: LookaheadParserHandler Class Reference
LookaheadParserHandler Class Reference
Public Member Functions
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const char *, SizeType, bool)
bool String (const char *str, SizeType length, bool)
bool StartObject ()
bool Key (const char *str, SizeType length, bool)
bool EndObject (SizeType)
bool StartArray ()
bool EndArray (SizeType)
Protected Types
enum LookaheadParsingState {
kInit , kError , kHasNull , kHasBool ,
kHasNumber , kHasString , kHasKey , kEnteringObject ,
kExitingObject , kEnteringArray , kExitingArray
}
Protected Member Functions
LookaheadParserHandler (char *str)
void ParseNext ()
Protected Attributes
Value v_
LookaheadParsingState st_
Reader r_
InsituStringStream ss_
Static Protected Attributes
static const int parseFlags = kParseDefaultFlags | kParseInsituFlag
Detailed Description
Definition at line 43 of file lookaheadparser.cpp.
Member Enumeration Documentation
LookaheadParsingState
enum LookaheadParserHandler::LookaheadParsingState protected
Enumerator
kInit
kError
kHasNull
kHasBool
kHasNumber
kHasString
kHasKey
kEnteringObject
kExitingObject
kEnteringArray
kExitingArray
Definition at line 65 of file lookaheadparser.cpp.
{
         kInit,
         kError,
         kHasNull,
         kHasBool,
         kHasNumber,
         kHasString,
         kHasKey,
         kEnteringObject,
         kExitingObject,
         kEnteringArray,
         kExitingArray
     };
Constructor & Destructor Documentation
LookaheadParserHandler()
LookaheadParserHandler::LookaheadParserHandler (char * str) protected
Definition at line 87 of file lookaheadparser.cpp.
                                                         : v_(), st_(kInit), r_(), ss_(str) {
     r_.IterativeParseInit();
     ParseNext();
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), ParseNext(), and r_.
Member Function Documentation
Bool()
bool LookaheadParserHandler::Bool (bool b) inline
Definition at line 46 of file lookaheadparser.cpp.
 { st_ = kHasBool; v_.SetBool(b); return true; }
Double()
bool LookaheadParserHandler::Double (double d) inline
Definition at line 51 of file lookaheadparser.cpp.
 { st_ = kHasNumber; v_.SetDouble(d); return true; }
EndArray()
bool LookaheadParserHandler::EndArray (SizeType) inline
Definition at line 58 of file lookaheadparser.cpp.
 { st_ = kExitingArray; return true; }
EndObject()
bool LookaheadParserHandler::EndObject (SizeType) inline
Definition at line 56 of file lookaheadparser.cpp.
 { st_ = kExitingObject; return true; }
Int()
bool LookaheadParserHandler::Int (int i) inline
Definition at line 47 of file lookaheadparser.cpp.
 { st_ = kHasNumber; v_.SetInt(i); return true; }
Int64()
bool LookaheadParserHandler::Int64 (int64_t i) inline
Definition at line 49 of file lookaheadparser.cpp.
 { st_ = kHasNumber; v_.SetInt64(i); return true; }
Key()
bool LookaheadParserHandler::Key (const char * str, SizeType length, bool) inline
Definition at line 55 of file lookaheadparser.cpp.
 { st_ = kHasKey; v_.SetString(str, length); return true; }
Null()
bool LookaheadParserHandler::Null () inline
Definition at line 45 of file lookaheadparser.cpp.
 { st_ = kHasNull; v_.SetNull(); return true; }
ParseNext()
void LookaheadParserHandler::ParseNext () protected
Definition at line 92 of file lookaheadparser.cpp.
{
     if (r_.HasParseError()) {
         st_ = kError;
         return;
     }
     r_.IterativeParseNext<parseFlags>(ss_, *this);
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), kError, parseFlags, r_, ss_, and st_.
Referenced by LookaheadParser::EnterArray(), LookaheadParser::EnterObject(), LookaheadParser::GetBool(), LookaheadParser::GetDouble(), LookaheadParser::GetInt(), LookaheadParser::GetNull(), LookaheadParser::GetString(), LookaheadParserHandler(), LookaheadParser::NextArrayValue(), LookaheadParser::NextObjectKey(), and LookaheadParser::SkipOut().
RawNumber()
bool LookaheadParserHandler::RawNumber (const char * , SizeType , bool) inline
Definition at line 52 of file lookaheadparser.cpp.
 { return false; }
StartArray()
bool LookaheadParserHandler::StartArray () inline
Definition at line 57 of file lookaheadparser.cpp.
 { st_ = kEnteringArray; return true; }
StartObject()
bool LookaheadParserHandler::StartObject () inline
Definition at line 54 of file lookaheadparser.cpp.
 { st_ = kEnteringObject; return true; }
String()
bool LookaheadParserHandler::String (const char * str, SizeType length, bool) inline
Definition at line 53 of file lookaheadparser.cpp.
 { st_ = kHasString; v_.SetString(str, length); return true; }
Uint()
bool LookaheadParserHandler::Uint (unsigned u) inline
Definition at line 48 of file lookaheadparser.cpp.
 { st_ = kHasNumber; v_.SetUint(u); return true; }
Uint64()
bool LookaheadParserHandler::Uint64 (uint64_t u) inline
Definition at line 50 of file lookaheadparser.cpp.
 { st_ = kHasNumber; v_.SetUint64(u); return true; }
Field Documentation
parseFlags
const int LookaheadParserHandler::parseFlags = kParseDefaultFlags | kParseInsituFlag static protected
Definition at line 84 of file lookaheadparser.cpp.
Referenced by ParseNext().
r_
Reader LookaheadParserHandler::r_ protected
Definition at line 81 of file lookaheadparser.cpp.
Referenced by LookaheadParserHandler(), and ParseNext().
ss_
InsituStringStream LookaheadParserHandler::ss_ protected
Definition at line 82 of file lookaheadparser.cpp.
Referenced by ParseNext().
st_
LookaheadParsingState LookaheadParserHandler::st_ protected
Definition at line 80 of file lookaheadparser.cpp.
Referenced by LookaheadParser::EnterArray(), LookaheadParser::EnterObject(), LookaheadParser::GetBool(), LookaheadParser::GetDouble(), LookaheadParser::GetInt(), LookaheadParser::GetNull(), LookaheadParser::GetString(), LookaheadParser::IsValid(), LookaheadParser::NextArrayValue(), LookaheadParser::NextObjectKey(), ParseNext(), LookaheadParser::PeekType(), LookaheadParser::PeekValue(), and LookaheadParser::SkipOut().
v_
Value LookaheadParserHandler::v_ protected
Definition at line 79 of file lookaheadparser.cpp.
Referenced by LookaheadParser::GetBool(), LookaheadParser::GetDouble(), LookaheadParser::GetInt(), LookaheadParser::GetString(), LookaheadParser::NextObjectKey(), LookaheadParser::PeekType(), and LookaheadParser::PeekValue().
The documentation for this class was generated from the following file:
shared/rapidjson/example/lookaheadparser/lookaheadparser.cpp