BeatSaber-Hooks: LoggerBuffer Class Reference
LoggerBuffer Class Reference
#include <logging.hpp>
Public Member Functions
std::string get_path ()
std::size_t length ()
void addMessage (std::string_view msg)
void flush ()
LoggerBuffer (const ModInfo info)
Static Public Member Functions
static std::string get_logDir ()
Data Fields
std::list< std::string > messages
std::mutex messageLock
const ModInfo modInfo
bool closed = false
Private Attributes
friend Logger
std::string path
Detailed Description
Definition at line 47 of file logging.hpp.
Constructor & Destructor Documentation
LoggerBuffer()
LoggerBuffer::LoggerBuffer (const ModInfo info) inline
Definition at line 71 of file logging.hpp.
 : modInfo(info), path(get_path()) {}
Member Function Documentation
addMessage()
void LoggerBuffer::addMessage (std::string_view msg)
Definition at line 93 of file logging.cpp.
{
     if (closed) {
         return;
     }
     messageLock.lock();
     messages.emplace_back(msg.data());
     messageLock.unlock();
 }
References closed, messageLock, and messages.
Referenced by Logger::log().
flush()
void LoggerBuffer::flush ()
Definition at line 64 of file logging.cpp.
{
     if (length() == 0) {
         // If we have nothing to write, exit early.
         return;
     }
     // We can open the file without locking path, because it is only created on initialization.
     std::ofstream file(path, std::ios::app);
     if (!file.is_open()) {
         __android_log_print(Logging::CRITICAL, Logger::get().tag.c_str(), "Could not open file: %s when flushing buffer!", path.c_str());
     }
     // Then, iterate over all messages and write each of them to the file.
     // We already must hold the lock for this call.
     // Assuming we always append to the END of the list, we could theoretically get away without locking on this call (except for length 1)
     messageLock.lock();
     for (; !messages.empty(); messages.pop_front()) {
         file << messages.front().c_str() << '\n';
     }
     messageLock.unlock();
     file.close();
 }
References Logging::CRITICAL, Logger::get(), length(), messageLock, messages, and path.
Referenced by Logger::close(), Logger::closeAll(), Logger::flush(), Logger::flushAll(), and Consumer::operator()().
get_logDir()
static std::string LoggerBuffer::get_logDir () inline static
Definition at line 54 of file logging.hpp.
{
         // Copy it
         static std::string d = string_format(LOG_PATH, Modloader::getApplicationId().c_str());
         return d;
     }
References Modloader::getApplicationId(), LOG_PATH, and string_format().
Referenced by get_path(), and Logger::init().
get_path()
std::string LoggerBuffer::get_path () inline
Definition at line 59 of file logging.hpp.
{
         std::string cpy = modInfo.version;
         std::replace(cpy.begin(), cpy.end(), '.', '_');
         auto val = get_logDir() + modInfo.id + "_" + cpy + ".log";
         return val;
     }
References get_logDir(), ModInfo::id, modInfo, and ModInfo::version.
Referenced by Logger::init().
length()
std::size_t LoggerBuffer::length ()
Definition at line 85 of file logging.cpp.
{
     if (closed) {
         // Ignore messages to write if we are closed.
         return 0;
     }
     return messages.size();
 }
References closed, and messages.
Referenced by flush().
Field Documentation
closed
bool LoggerBuffer::closed = false
Definition at line 53 of file logging.hpp.
Referenced by addMessage(), Logger::close(), Logger::closeAll(), length(), and Logger::Logger().
Logger
friend LoggerBuffer::Logger private
Definition at line 48 of file logging.hpp.
messageLock
std::mutex LoggerBuffer::messageLock
Definition at line 51 of file logging.hpp.
Referenced by addMessage(), and flush().
messages
std::list<std::string> LoggerBuffer::messages
Definition at line 50 of file logging.hpp.
Referenced by addMessage(), flush(), and length().
modInfo
const ModInfo LoggerBuffer::modInfo
Definition at line 52 of file logging.hpp.
Referenced by get_path().
path
std::string LoggerBuffer::path private
Definition at line 69 of file logging.hpp.
Referenced by flush().
The documentation for this class was generated from the following files:
shared/utils/logging.hpp
src/utils/logging.cpp