BeatSaber-Hooks: Person Class Reference
Person Class Reference
Public Member Functions
Person (const std::string &name, unsigned age)
Person (const Person &rhs)
virtual ~Person ()
Person & operator= (const Person &rhs)
Protected Member Functions
template<typename Writer >
void Serialize (Writer &writer) const
Private Attributes
std::string name_
unsigned age_
Detailed Description
Definition at line 11 of file serialize.cpp.
Constructor & Destructor Documentation
Person() [1/2]
Person::Person (const std::string & name, unsigned age) inline
Definition at line 13 of file serialize.cpp.
 : name_(name), age_(age) {}
Person() [2/2]
Person::Person (const Person & rhs) inline
Definition at line 14 of file serialize.cpp.
 : name_(rhs.name_), age_(rhs.age_) {}
~Person()
Person::~Person () virtual
Definition at line 42 of file serialize.cpp.
                 {
 }
Member Function Documentation
operator=()
Person& Person::operator= (const Person & rhs) inline
Definition at line 17 of file serialize.cpp.
{
         name_ = rhs.name_;
         age_ = rhs.age_;
         return *this;
     }
References age_, and name_.
Serialize()
template<typename Writer > void Person::Serialize (Writer & writer) const inline protected
Definition at line 25 of file serialize.cpp.
{
         // This base class just write out name-value pairs, without wrapping within an object.
         writer.String("name");
 #if RAPIDJSON_HAS_STDSTRING
         writer.String(name_);
 #else
         writer.String(name_.c_str(), static_cast<SizeType>(name_.length())); // Supplying length of string is faster.
 #endif
         writer.String("age");
         writer.Uint(age_);
     }
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint().
Referenced by Dependent::Serialize(), and Employee::Serialize().
Field Documentation
age_
unsigned Person::age_ private
Definition at line 39 of file serialize.cpp.
Referenced by operator=().
name_
std::string Person::name_ private
Definition at line 38 of file serialize.cpp.
Referenced by operator=().
The documentation for this class was generated from the following file:
shared/rapidjson/example/serialize/serialize.cpp