BeatSaber-Hooks: Schema Class Reference
Schema Class Reference
Data Structures
struct TestSuite
Public Member Functions
Schema ()
virtual void SetUp ()
virtual void TearDown ()
Protected Types
typedef std::vector< Document * > DocumentList
typedef std::vector< TestSuite * > TestSuiteList
Protected Attributes
TestSuiteList testSuites
Private Member Functions
Schema (const Schema &)
Schema & operator= (const Schema &)
Static Private Member Functions
static bool IsExcludeTestSuite (const std::string &description)
static bool IsExcludeTest (const std::string &description)
Detailed Description
Definition at line 52 of file schematest.cpp.
Member Typedef Documentation
DocumentList
typedef std::vector<Document*> Schema::DocumentList protected
Definition at line 181 of file schematest.cpp.
TestSuiteList
typedef std::vector<TestSuite* > Schema::TestSuiteList protected
Definition at line 194 of file schematest.cpp.
Constructor & Destructor Documentation
Schema() [1/2]
Schema::Schema () inline
Definition at line 54 of file schematest.cpp.
 {}
Schema() [2/2]
Schema::Schema (const Schema &) private
Member Function Documentation
IsExcludeTest()
static bool Schema::IsExcludeTest (const std::string & description) inline static private
Definition at line 161 of file schematest.cpp.
{
         const char* excludeTests[] = {
             //lots of validators fail these
             "invalid definition, invalid definition schema",
             "maxLength validation, two supplementary Unicode code points is long enough",
             "minLength validation, one supplementary Unicode code point is not long enough",
             //this is to get tv4 in the benchmarks
             "heterogeneous enum validation, something else is invalid"
         };
         for (size_t i = 0; i < ARRAY_SIZE(excludeTests); i++)
             if (excludeTests[i] == description)
                 return true;
         return false;
     }
References ARRAY_SIZE.
IsExcludeTestSuite()
static bool Schema::IsExcludeTestSuite (const std::string & description) inline static private
Definition at line 140 of file schematest.cpp.
{
         const char* excludeTestSuites[] = {
             //lost failing these tests
             "remote ref",
             "remote ref, containing refs itself",
             "fragment within remote ref",
             "ref within remote ref",
             "change resolution scope",
             // these below were added to get jsck in the benchmarks)
             "uniqueItems validation",
             "valid definition",
             "invalid definition"
         };
         for (size_t i = 0; i < ARRAY_SIZE(excludeTestSuites); i++)
             if (excludeTestSuites[i] == description)
                 return true;
         return false;
     }
References ARRAY_SIZE.
operator=()
Schema& Schema::operator= (const Schema &) private
SetUp()
virtual void Schema::SetUp () inline virtual
Definition at line 56 of file schematest.cpp.
{
         PerfTest::SetUp();
         const char* filenames[] = {
             "additionalItems.json",
             "additionalProperties.json",
             "allOf.json",
             "anyOf.json",
             "default.json",
             "definitions.json",
             "dependencies.json",
             "enum.json",
             "items.json",
             "maximum.json",
             "maxItems.json",
             "maxLength.json",
             "maxProperties.json",
             "minimum.json",
             "minItems.json",
             "minLength.json",
             "minProperties.json",
             "multipleOf.json",
             "not.json",
             "oneOf.json",
             "pattern.json",
             "patternProperties.json",
             "properties.json",
             "ref.json",
             "refRemote.json",
             "required.json",
             "type.json",
             "uniqueItems.json"
         };
         char jsonBuffer[65536];
         MemoryPoolAllocator<> jsonAllocator(jsonBuffer, sizeof(jsonBuffer));
         for (size_t i = 0; i < ARRAY_SIZE(filenames); i++) {
             char filename[FILENAME_MAX];
             sprintf(filename, "jsonschema/tests/draft4/%s", filenames[i]);
             char* json = ReadFile(filename, jsonAllocator);
             if (!json) {
                 printf("json test suite file %s not found", filename);
                 return;
             }
             Document d;
             d.Parse(json);
             if (d.HasParseError()) {
                 printf("json test suite file %s has parse error", filename);
                 return;
             }
             for (Value::ConstValueIterator schemaItr = d.Begin(); schemaItr != d.End(); ++schemaItr) {
                 std::string schemaDescription = (*schemaItr)["description"].GetString();
                 if (IsExcludeTestSuite(schemaDescription))
                     continue;
                 TestSuite* ts = new TestSuite;
                 ts->schema = new SchemaDocument((*schemaItr)["schema"]);
                 const Value& tests = (*schemaItr)["tests"];
                 for (Value::ConstValueIterator testItr = tests.Begin(); testItr != tests.End(); ++testItr) {
                     if (IsExcludeTest(schemaDescription + ", " + (*testItr)["description"].GetString()))
                         continue;
                     Document* d2 = new Document;
                     d2->CopyFrom((*testItr)["data"], d2->GetAllocator());
                     ts->tests.push_back(d2);
                 }
                 testSuites.push_back(ts);
             }
         }
     }
References ARRAY_SIZE, rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse(), ReadFile(), Schema::TestSuite::schema, and Schema::TestSuite::tests.
TearDown()
virtual void Schema::TearDown () inline virtual
Definition at line 131 of file schematest.cpp.
{
         PerfTest::TearDown();
         for (TestSuiteList::const_iterator itr = testSuites.begin(); itr != testSuites.end(); ++itr)
             delete *itr;
         testSuites.clear();
     }
Field Documentation
testSuites
TestSuiteList Schema::testSuites protected
Definition at line 195 of file schematest.cpp.
The documentation for this class was generated from the following file:
shared/rapidjson/test/perftest/schematest.cpp