BeatSaber-Hooks: LookaheadParser Class Reference
LookaheadParser Class Reference
Public Member Functions
LookaheadParser (char *str)
bool EnterObject ()
bool EnterArray ()
const char * NextObjectKey ()
bool NextArrayValue ()
int GetInt ()
double GetDouble ()
const char * GetString ()
bool GetBool ()
void GetNull ()
void SkipObject ()
void SkipArray ()
void SkipValue ()
Value * PeekValue ()
int PeekType ()
bool IsValid ()
Protected Member Functions
void SkipOut (int depth)
Protected Member Functions inherited from LookaheadParserHandler
LookaheadParserHandler (char *str)
void ParseNext ()
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const char *, SizeType, bool)
bool String (const char *str, SizeType length, bool)
bool StartObject ()
bool Key (const char *str, SizeType length, bool)
bool EndObject (SizeType)
bool StartArray ()
bool EndArray (SizeType)
Additional Inherited Members
Protected Types inherited from LookaheadParserHandler
enum LookaheadParsingState {
kInit , kError , kHasNull , kHasBool ,
kHasNumber , kHasString , kHasKey , kEnteringObject ,
kExitingObject , kEnteringArray , kExitingArray
}
Protected Attributes inherited from LookaheadParserHandler
Value v_
LookaheadParsingState st_
Reader r_
InsituStringStream ss_
Static Protected Attributes inherited from LookaheadParserHandler
static const int parseFlags = kParseDefaultFlags | kParseInsituFlag
Detailed Description
Definition at line 101 of file lookaheadparser.cpp.
Constructor & Destructor Documentation
LookaheadParser()
LookaheadParser::LookaheadParser (char * str) inline
Definition at line 103 of file lookaheadparser.cpp.
 : LookaheadParserHandler(str) {}
Member Function Documentation
EnterArray()
bool LookaheadParser::EnterArray ()
Definition at line 137 of file lookaheadparser.cpp.
{
     if (st_ != kEnteringArray) {
         st_  = kError;
         return false;
     }
     ParseNext();
     return true;
 }
References LookaheadParserHandler::kEnteringArray, LookaheadParserHandler::kError, LookaheadParserHandler::ParseNext(), and LookaheadParserHandler::st_.
Referenced by main().
EnterObject()
bool LookaheadParser::EnterObject ()
Definition at line 127 of file lookaheadparser.cpp.
{
     if (st_ != kEnteringObject) {
         st_  = kError;
         return false;
     }
     ParseNext();
     return true;
 }
References LookaheadParserHandler::kEnteringObject, LookaheadParserHandler::kError, LookaheadParserHandler::ParseNext(), and LookaheadParserHandler::st_.
Referenced by main().
GetBool()
bool LookaheadParser::GetBool ()
Definition at line 199 of file lookaheadparser.cpp.
{
     if (st_ != kHasBool) {
         st_  = kError;
         return false;
     }
     bool result = v_.GetBool();
     ParseNext();
     return result;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kHasBool, LookaheadParserHandler::ParseNext(), LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
Referenced by main().
GetDouble()
double LookaheadParser::GetDouble ()
Definition at line 188 of file lookaheadparser.cpp.
{
     if (st_ != kHasNumber) {
         st_  = kError;
         return 0.;
     }
     double result = v_.GetDouble();
     ParseNext();
     return result;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kHasNumber, LookaheadParserHandler::ParseNext(), LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
Referenced by main().
GetInt()
int LookaheadParser::GetInt ()
Definition at line 177 of file lookaheadparser.cpp.
{
     if (st_ != kHasNumber || !v_.IsInt()) {
         st_ = kError;
         return 0;
     }
     int result = v_.GetInt();
     ParseNext();
     return result;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kHasNumber, LookaheadParserHandler::ParseNext(), LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
GetNull()
void LookaheadParser::GetNull ()
Definition at line 210 of file lookaheadparser.cpp.
{
     if (st_ != kHasNull) {
         st_  = kError;
         return;
     }
     ParseNext();
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kHasNull, LookaheadParserHandler::ParseNext(), and LookaheadParserHandler::st_.
Referenced by main().
GetString()
const char * LookaheadParser::GetString ()
Definition at line 219 of file lookaheadparser.cpp.
{
     if (st_ != kHasString) {
         st_  = kError;
         return 0;
     }
     const char* result = v_.GetString();
     ParseNext();
     return result;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kHasString, LookaheadParserHandler::ParseNext(), LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
Referenced by main().
IsValid()
bool LookaheadParser::IsValid () inline
Definition at line 121 of file lookaheadparser.cpp.
 { return st_ != kError; }
References LookaheadParserHandler::kError, and LookaheadParserHandler::st_.
NextArrayValue()
bool LookaheadParser::NextArrayValue ()
Definition at line 163 of file lookaheadparser.cpp.
{
     if (st_ == kExitingArray) {
         ParseNext();
         return false;
     }
     if (st_ == kError || st_ == kExitingObject || st_ == kHasKey) {
         st_ = kError;
         return false;
     }
     return true;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kExitingArray, LookaheadParserHandler::kExitingObject, LookaheadParserHandler::kHasKey, LookaheadParserHandler::ParseNext(), and LookaheadParserHandler::st_.
Referenced by main().
NextObjectKey()
const char * LookaheadParser::NextObjectKey ()
Definition at line 147 of file lookaheadparser.cpp.
{
     if (st_ == kHasKey) {
         const char* result = v_.GetString();
         ParseNext();
         return result;
     }
     if (st_ != kExitingObject) {
         st_ = kError;
         return 0;
     }
     ParseNext();
     return 0;
 }
References LookaheadParserHandler::kError, LookaheadParserHandler::kExitingObject, LookaheadParserHandler::kHasKey, LookaheadParserHandler::ParseNext(), LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
Referenced by main().
PeekType()
int LookaheadParser::PeekType ()
Definition at line 267 of file lookaheadparser.cpp.
{
     if (st_ >= kHasNull && st_ <= kHasKey) {
         return v_.GetType();
     }
     if (st_ == kEnteringArray) {
         return kArrayType;
     }
     if (st_ == kEnteringObject) {
         return kObjectType;
     }
     return -1;
 }
References rapidjson::kArrayType, LookaheadParserHandler::kEnteringArray, LookaheadParserHandler::kEnteringObject, LookaheadParserHandler::kHasKey, LookaheadParserHandler::kHasNull, rapidjson::kObjectType, LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
Referenced by main().
PeekValue()
Value * LookaheadParser::PeekValue ()
Definition at line 259 of file lookaheadparser.cpp.
{
     if (st_ >= kHasNull && st_ <= kHasKey) {
         return &v_;
     }
     return 0;
 }
References LookaheadParserHandler::kHasKey, LookaheadParserHandler::kHasNull, LookaheadParserHandler::st_, and LookaheadParserHandler::v_.
SkipArray()
void LookaheadParser::SkipArray ()
Definition at line 251 of file lookaheadparser.cpp.
{
     SkipOut(1);
 }
References SkipOut().
Referenced by main().
SkipObject()
void LookaheadParser::SkipObject ()
Definition at line 255 of file lookaheadparser.cpp.
{
     SkipOut(1);
 }
References SkipOut().
SkipOut()
void LookaheadParser::SkipOut (int depth) protected
Definition at line 230 of file lookaheadparser.cpp.
{
     do {
         if (st_ == kEnteringArray || st_ == kEnteringObject) {
             ++depth;
         }
         else if (st_ == kExitingArray || st_ == kExitingObject) {
             --depth;
         }
         else if (st_ == kError) {
             return;
         }
         ParseNext();
     }
     while (depth > 0);
 }
References LookaheadParserHandler::kEnteringArray, LookaheadParserHandler::kEnteringObject, LookaheadParserHandler::kError, LookaheadParserHandler::kExitingArray, LookaheadParserHandler::kExitingObject, LookaheadParserHandler::ParseNext(), and LookaheadParserHandler::st_.
Referenced by SkipArray(), SkipObject(), and SkipValue().
SkipValue()
void LookaheadParser::SkipValue ()
Definition at line 247 of file lookaheadparser.cpp.
{
     SkipOut(0);
 }
References SkipOut().
Referenced by main().
The documentation for this class was generated from the following file:
shared/rapidjson/example/lookaheadparser/lookaheadparser.cpp