BeatSaber-Hooks: rapidjson::GenericDocument< Encoding, Allocator, StackAllocator > Class Template Reference
rapidjson::GenericDocument< Encoding, Allocator, StackAllocator > Class Template Reference
A document for parsing JSON text as DOM.
#include <document.h>
Data Structures
struct ClearStackOnExit
Public Types
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericValue< Encoding, Allocator > ValueType
Value type of the document.
typedef Allocator AllocatorType
Allocator type from template parameter.
Public Types inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator< CrtAllocator > >
typedef GenericMember< Encoding, MemoryPoolAllocator< CrtAllocator > > Member
Name-value pair in an object.
typedef Encoding EncodingType
Encoding type from template parameter.
typedef MemoryPoolAllocator< CrtAllocator > AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericStringRef< Ch > StringRefType
Reference to a constant string.
typedef GenericMemberIterator< false, Encoding, MemoryPoolAllocator< CrtAllocator > >::Iterator MemberIterator
Member iterator for iterating in object.
typedef GenericMemberIterator< true, Encoding, MemoryPoolAllocator< CrtAllocator > >::Iterator ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
typedef GenericValue< Encoding, MemoryPoolAllocator< CrtAllocator > > ValueType
Value type of itself.
typedef GenericArray< false, ValueType > Array
typedef GenericArray< true, ValueType > ConstArray
typedef GenericObject< false, ValueType > Object
typedef GenericObject< true, ValueType > ConstObject
enum
Public Member Functions
GenericDocument (Type type, Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity, StackAllocator *stackAllocator=0)
Constructor.
GenericDocument (Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity, StackAllocator *stackAllocator=0)
Constructor.
~GenericDocument ()
GenericDocument & Swap (GenericDocument &rhs) RAPIDJSON_NOEXCEPT
Exchange the contents of this document with those of another.
template<typename Generator >
GenericDocument & Populate (Generator &g)
Populate this document by a generator which produces SAX events.
Allocator & GetAllocator ()
Get the allocator of this document.
size_t GetStackCapacity () const
Get the capacity of stack in bytes.
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned i)
bool Int64 (int64_t i)
bool Uint64 (uint64_t i)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy)
bool String (const Ch *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType length, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
Parse from stream
template<unsigned parseFlags, typename SourceEncoding , typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream (with Encoding conversion)
template<unsigned parseFlags, typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream.
template<typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream (with kParseDefaultFlags)
Parse in-place from mutable string
template<unsigned parseFlags>
GenericDocument & ParseInsitu (Ch *str)
Parse JSON text from a mutable string.
GenericDocument & ParseInsitu (Ch *str)
Parse JSON text from a mutable string (with kParseDefaultFlags)
Parse from read-only string
template<unsigned parseFlags, typename SourceEncoding >
GenericDocument & Parse (const typename SourceEncoding::Ch *str)
Parse JSON text from a read-only string (with Encoding conversion)
template<unsigned parseFlags>
GenericDocument & Parse (const Ch *str)
Parse JSON text from a read-only string.
GenericDocument & Parse (const Ch *str)
Parse JSON text from a read-only string (with kParseDefaultFlags)
template<unsigned parseFlags, typename SourceEncoding >
GenericDocument & Parse (const typename SourceEncoding::Ch *str, size_t length)
template<unsigned parseFlags>
GenericDocument & Parse (const Ch *str, size_t length)
GenericDocument & Parse (const Ch *str, size_t length)
template<unsigned parseFlags, typename SourceEncoding >
GenericDocument & Parse (const std::basic_string< typename SourceEncoding::Ch > &str)
template<unsigned parseFlags>
GenericDocument & Parse (const std::basic_string< Ch > &str)
GenericDocument & Parse (const std::basic_string< Ch > &str)
Handling parse errors
bool HasParseError () const
Whether a parse error has occurred in the last parsing.
ParseErrorCode GetParseError () const
Get the ParseErrorCode of last parsing.
size_t GetErrorOffset () const
Get the position of last parsing error in input, 0 otherwise.
operator ParseResult () const
Implicit conversion to get the last parse result.
Public Member Functions inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator< CrtAllocator > >
GenericValue & operator= (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment with move semantics.
GenericValue & operator= (StringRefType str) RAPIDJSON_NOEXCEPT
Assignment of constant string reference (no copy)
RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >),(GenericValue &)) operator
Assignment with primitive types.
RAPIDJSON_FORCEINLINE const Ch * GetStringPointer () const
RAPIDJSON_FORCEINLINE const Ch * SetStringPointer (const Ch *str)
RAPIDJSON_FORCEINLINE GenericValue * GetElementsPointer () const
RAPIDJSON_FORCEINLINE GenericValue * SetElementsPointer (GenericValue *elements)
RAPIDJSON_FORCEINLINE Member * GetMembersPointer () const
RAPIDJSON_FORCEINLINE Member * SetMembersPointer (Member *members)
void SetArrayRaw (GenericValue *values, SizeType count, MemoryPoolAllocator< CrtAllocator > &allocator)
void SetObjectRaw (Member *members, SizeType count, MemoryPoolAllocator< CrtAllocator > &allocator)
Initialize this value as object with initial data, without calling destructor.
void SetStringRaw (StringRefType s) RAPIDJSON_NOEXCEPT
Initialize this value as constant string, without calling destructor.
void SetStringRaw (StringRefType s, MemoryPoolAllocator< CrtAllocator > &allocator)
Initialize this value as copy string with initial data, without calling destructor.
void RawAssign (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment without calling destructor.
bool StringEqual (const GenericValue< Encoding, SourceAllocator > &rhs) const
GenericValue () RAPIDJSON_NOEXCEPT
Default constructor creates a null value.
GenericValue (Type type) RAPIDJSON_NOEXCEPT
Constructor with JSON value type.
GenericValue (const GenericValue< Encoding, SourceAllocator > &rhs, MemoryPoolAllocator< CrtAllocator > &allocator, bool copyConstStrings=false)
Explicit copy constructor (with allocator)
GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) RAPIDJSON_NOEXCEPT
Constructor for boolean value.
GenericValue (int i) RAPIDJSON_NOEXCEPT
Constructor for int value.
GenericValue (unsigned u) RAPIDJSON_NOEXCEPT
Constructor for unsigned value.
GenericValue (int64_t i64) RAPIDJSON_NOEXCEPT
Constructor for int64_t value.
GenericValue (uint64_t u64) RAPIDJSON_NOEXCEPT
Constructor for uint64_t value.
GenericValue (double d) RAPIDJSON_NOEXCEPT
Constructor for double value.
GenericValue (float f) RAPIDJSON_NOEXCEPT
Constructor for float value.
GenericValue (const Ch *s, SizeType length) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (StringRefType s) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, MemoryPoolAllocator< CrtAllocator > &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, MemoryPoolAllocator< CrtAllocator > &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const std::basic_string< Ch > &s, MemoryPoolAllocator< CrtAllocator > &allocator)
Constructor for copy-string from a string object (i.e. do make a copy of string)
GenericValue (Array a) RAPIDJSON_NOEXCEPT
Constructor for Array.
GenericValue (Object o) RAPIDJSON_NOEXCEPT
Constructor for Object.
~GenericValue ()
Destructor.
Private Member Functions
GenericDocument (const GenericDocument &)
Prohibit copying.
GenericDocument & operator= (const GenericDocument &)
Prohibit assignment.
void ClearStack ()
void Destroy ()
Private Attributes
Allocator * allocator_
Allocator * ownAllocator_
internal::Stack< StackAllocator > stack_
ParseResult parseResult_
Static Private Attributes
static const size_t kDefaultStackCapacity = 1024
Friends
template<typename , typename >
class GenericValue
void swap (GenericDocument &a, GenericDocument &b) RAPIDJSON_NOEXCEPT
free-standing swap function helper
Additional Inherited Members
Data Fields inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator< CrtAllocator > >
Data data_
Static Public Attributes inherited from rapidjson::GenericValue< Encoding, MemoryPoolAllocator< CrtAllocator > >
static const SizeType kDefaultArrayCapacity
static const SizeType kDefaultObjectCapacity
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator>
class rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >
A document for parsing JSON text as DOM.
Note
implements Handler concept
Template Parameters
Encoding Encoding for both parsing and string storage.
Allocator Allocator for allocating memory for the DOM
StackAllocator Allocator for allocating memory for stack during parsing.
Warning
Although GenericDocument inherits from GenericValue, the API does not provide any virtual functions, especially no virtual destructor. To avoid memory leaks, do not delete a GenericDocument object via a pointer to a GenericValue.
Definition at line 2203 of file document.h.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> typedef Allocator rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::AllocatorType
Allocator type from template parameter.
Definition at line 2207 of file document.h.
Ch
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> typedef Encoding::Ch rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Ch
Character type derived from Encoding.
Definition at line 2205 of file document.h.
ValueType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> typedef GenericValue<Encoding, Allocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ValueType
Value type of the document.
Definition at line 2206 of file document.h.
Constructor & Destructor Documentation
GenericDocument() [1/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (Type type, Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator * stackAllocator = 0) inline explicit
Constructor.
Creates an empty document of specified type.
Parameters
type Mandatory type of object to create.
allocator Optional allocator for allocating memory.
stackCapacity Optional initial capacity of stack in bytes.
stackAllocator Optional allocator for allocating memory for stack.
Definition at line 2216 of file document.h.
                                                                                                                                                     :
         GenericValue<Encoding, Allocator>(type),  allocator_(allocator), ownAllocator_(0), stack_(stackAllocator, stackCapacity), parseResult_()
     {
         if (!allocator_)
             ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
     }
References RAPIDJSON_NEW.
GenericDocument() [2/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator * stackAllocator = 0) inline
Constructor.
Creates an empty document which type is Null.
Parameters
allocator Optional allocator for allocating memory.
stackCapacity Optional initial capacity of stack in bytes.
stackAllocator Optional allocator for allocating memory for stack.
Definition at line 2229 of file document.h.
                                                                                                                                 :
         allocator_(allocator), ownAllocator_(0), stack_(stackAllocator, stackCapacity), parseResult_()
     {
         if (!allocator_)
             ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
     }
References RAPIDJSON_NEW.
~GenericDocument()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::~GenericDocument () inline
Definition at line 2251 of file document.h.
{
         Destroy();
     }
GenericDocument() [3/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (const GenericDocument< Encoding, Allocator, StackAllocator > &) private
Prohibit copying.
Member Function Documentation
Bool()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Bool (bool b) inline
Definition at line 2517 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(b); return true; }
ClearStack()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> void rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack () inline private
Definition at line 2564 of file document.h.
                       {
         if (Allocator::kNeedFree)
             while (stack_.GetSize() > 0)    // Here assumes all elements in stack array are GenericValue (Member is actually 2 GenericValue objects)
                 (stack_.template Pop<ValueType>(1))->~ValueType();
         else
             stack_.Clear();
         stack_.ShrinkToFit();
     }
Destroy()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> void rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Destroy () inline private
Definition at line 2573 of file document.h.
                    {
         RAPIDJSON_DELETE(ownAllocator_);
     }
References RAPIDJSON_DELETE.
Double()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Double (double d) inline
Definition at line 2522 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(d); return true; }
EndArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::EndArray (SizeType elementCount) inline
Definition at line 2552 of file document.h.
{
         ValueType* elements = stack_.template Pop<ValueType>(elementCount);
         stack_.template Top<ValueType>()->SetArrayRaw(elements, elementCount, GetAllocator());
         return true;
     }
EndObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::EndObject (SizeType memberCount) inline
Definition at line 2544 of file document.h.
{
         typename ValueType::Member* members = stack_.template Pop<typename ValueType::Member>(memberCount);
         stack_.template Top<ValueType>()->SetObjectRaw(members, memberCount, GetAllocator());
         return true;
     }
GetAllocator()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> Allocator& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator () inline
Get the allocator of this document.
Definition at line 2491 of file document.h.
{
         RAPIDJSON_ASSERT(allocator_);
         return *allocator_;
     }
References RAPIDJSON_ASSERT.
Referenced by Configuration::Configuration(), main(), Schema::SetUp(), TEST(), and TestShortStringOptimization().
GetErrorOffset()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> size_t rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetErrorOffset () const inline
Get the position of last parsing error in input, 0 otherwise.
Definition at line 2473 of file document.h.
 { return parseResult_.Offset(); }
Referenced by main(), and TEST().
GetParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> ParseErrorCode rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetParseError () const inline
Get the ParseErrorCode of last parsing.
Definition at line 2470 of file document.h.
 { return parseResult_.Code(); }
Referenced by main(), and TEST().
GetStackCapacity()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> size_t rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetStackCapacity () const inline
Get the capacity of stack in bytes.
Definition at line 2497 of file document.h.
 { return stack_.GetCapacity(); }
HasParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError () const inline
Whether a parse error has occurred in the last parsing.
Definition at line 2467 of file document.h.
 { return parseResult_.IsError(); }
Referenced by main(), parsejson(), parsejsonfile(), Schema::SetUp(), TEST(), and testJson().
Int()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Int (int i) inline
Definition at line 2518 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(i); return true; }
Int64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Int64 (int64_t i) inline
Definition at line 2520 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(i); return true; }
Key()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Key (const Ch * str, SizeType length, bool copy) inline
Definition at line 2542 of file document.h.
 { return String(str, length, copy); }
Null()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Null () inline
Definition at line 2516 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(); return true; }
operator ParseResult()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::operator ParseResult () const inline
Implicit conversion to get the last parse result.
Returns
ParseResult of the last parse operation
Document doc;
ParseResult ok = doc.Parse(json);
if (!ok)
  printf( "JSON parse error: %s (%u)\n", GetParseError_En(ok.Code()), ok.Offset());
Definition at line 2487 of file document.h.
 { return parseResult_; }
operator=()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::operator= (const GenericDocument< Encoding, Allocator, StackAllocator > &) private
Prohibit assignment.
Parse() [1/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str) inline
Parse JSON text from a read-only string.
Template Parameters
parseFlags Combination of ParseFlag (must not contain kParseInsituFlag).
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2415 of file document.h.
{
         return Parse<parseFlags, Encoding>(str);
     }
Parse() [2/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str) inline
Parse JSON text from a read-only string (with kParseDefaultFlags)
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2422 of file document.h.
{
         return Parse<kParseDefaultFlags>(str);
     }
Parse() [3/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str, size_t length) inline
Definition at line 2436 of file document.h.
{
         return Parse<parseFlags, Encoding>(str, length);
     }
Parse() [4/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str, size_t length) inline
Definition at line 2440 of file document.h.
{
         return Parse<kParseDefaultFlags>(str, length);
     }
Parse() [5/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const std::basic_string< Ch > & str) inline
Definition at line 2452 of file document.h.
{
         return Parse<parseFlags, Encoding>(str.c_str());
     }
Parse() [6/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const std::basic_string< Ch > & str) inline
Definition at line 2456 of file document.h.
{
         return Parse<kParseDefaultFlags>(str);
     }
Parse() [7/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const std::basic_string< typename SourceEncoding::Ch > & str) inline
Definition at line 2446 of file document.h.
{
         // c_str() is constant complexity according to standard. Should be faster than Parse(const char*, size_t)
         return Parse<parseFlags, SourceEncoding>(str.c_str());
     }
Parse() [8/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const typename SourceEncoding::Ch * str) inline
Parse JSON text from a read-only string (with Encoding conversion)
Template Parameters
parseFlags Combination of ParseFlag (must not contain kParseInsituFlag).
SourceEncoding Transcoding from input Encoding
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2404 of file document.h.
{
         RAPIDJSON_ASSERT(!(parseFlags & kParseInsituFlag));
         GenericStringStream<SourceEncoding> s(str);
         return ParseStream<parseFlags, SourceEncoding>(s);
     }
References rapidjson::kParseInsituFlag, and RAPIDJSON_ASSERT.
Referenced by main(), Schema::SetUp(), TEST(), and TEST_F().
Parse() [9/9]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const typename SourceEncoding::Ch * str, size_t length) inline
Definition at line 2427 of file document.h.
{
         RAPIDJSON_ASSERT(!(parseFlags & kParseInsituFlag));
         MemoryStream ms(reinterpret_cast<const char*>(str), length * sizeof(typename SourceEncoding::Ch));
         EncodedInputStream<SourceEncoding, MemoryStream> is(ms);
         ParseStream<parseFlags, SourceEncoding>(is);
         return *this;
     }
References rapidjson::kParseInsituFlag, and RAPIDJSON_ASSERT.
ParseInsitu() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu (Ch * str) inline
Parse JSON text from a mutable string.
Template Parameters
parseFlags Combination of ParseFlag.
Parameters
str Mutable zero-terminated string to be parsed.
Returns
The document itself for fluent API.
Definition at line 2381 of file document.h.
{
         GenericInsituStringStream<Encoding> s(str);
         return ParseStream<parseFlags | kParseInsituFlag>(s);
     }
Referenced by main(), parsejson(), and TEST_F().
ParseInsitu() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu (Ch * str) inline
Parse JSON text from a mutable string (with kParseDefaultFlags)
Parameters
str Mutable zero-terminated string to be parsed.
Returns
The document itself for fluent API.
Definition at line 2390 of file document.h.
{
         return ParseInsitu<kParseDefaultFlags>(str);
     }
ParseStream() [1/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding , typename InputStream > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream (with Encoding conversion)
Template Parameters
parseFlags Combination of ParseFlag.
SourceEncoding Encoding of input stream
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2338 of file document.h.
{
         GenericReader<SourceEncoding, Encoding, StackAllocator> reader(
             stack_.HasAllocator() ? &stack_.GetAllocator() : 0);
         ClearStackOnExit scope(*this);
         parseResult_ = reader.template Parse<parseFlags>(is, *this);
         if (parseResult_) {
             RAPIDJSON_ASSERT(stack_.GetSize() == sizeof(ValueType)); // Got one and only one root object
             ValueType::operator=(*stack_.template Pop<ValueType>(1));// Move value from stack to document
         }
         return *this;
     }
References RAPIDJSON_ASSERT.
Referenced by main(), parsejsonfile(), TEST(), TEST_F(), and testJson().
ParseStream() [2/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream.
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2357 of file document.h.
{
         return ParseStream<parseFlags, Encoding, InputStream>(is);
     }
ParseStream() [3/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<typename InputStream > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream (with kParseDefaultFlags)
Template Parameters
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2367 of file document.h.
{
         return ParseStream<kParseDefaultFlags, Encoding, InputStream>(is);
     }
Populate()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<typename Generator > GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Populate (Generator & g) inline
Populate this document by a generator which produces SAX events.
Template Parameters
Generator A functor with bool f(Handler) prototype.
Parameters
g Generator functor which sends SAX events to the parameter.
Returns
The document itself for fluent API.
Definition at line 2318 of file document.h.
{
         ClearStackOnExit scope(*this);
         if (g(*this)) {
             RAPIDJSON_ASSERT(stack_.GetSize() == sizeof(ValueType)); // Got one and only one root object
             ValueType::operator=(*stack_.template Pop<ValueType>(1));// Move value from stack to document
         }
         return *this;
     }
References RAPIDJSON_ASSERT.
Referenced by main().
RawNumber()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::RawNumber (const Ch * str, SizeType length, bool copy) inline
Definition at line 2524 of file document.h.
{
         if (copy)
             new (stack_.template Push<ValueType>()) ValueType(str, length, GetAllocator());
         else
             new (stack_.template Push<ValueType>()) ValueType(str, length);
         return true;
     }
StartArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::StartArray () inline
Definition at line 2550 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(kArrayType); return true; }
References rapidjson::kArrayType.
StartObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::StartObject () inline
Definition at line 2540 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(kObjectType); return true; }
References rapidjson::kObjectType.
String()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::String (const Ch * str, SizeType length, bool copy) inline
Definition at line 2532 of file document.h.
{
         if (copy)
             new (stack_.template Push<ValueType>()) ValueType(str, length, GetAllocator());
         else
             new (stack_.template Push<ValueType>()) ValueType(str, length);
         return true;
     }
Swap()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> GenericDocument& rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Swap (GenericDocument< Encoding, Allocator, StackAllocator > & rhs) inline
Exchange the contents of this document with those of another.
Parameters
rhs Another document.
Note
Constant complexity.
See also
GenericValue::Swap
Definition at line 2285 of file document.h.
{
         ValueType::Swap(rhs);
         stack_.Swap(rhs.stack_);
         internal::Swap(allocator_, rhs.allocator_);
         internal::Swap(ownAllocator_, rhs.ownAllocator_);
         internal::Swap(parseResult_, rhs.parseResult_);
         return *this;
     }
References rapidjson::internal::Swap().
Referenced by Configuration::Configuration(), and TEST().
Uint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Uint (unsigned i) inline
Definition at line 2519 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(i); return true; }
Uint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> bool rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Uint64 (uint64_t i) inline
Definition at line 2521 of file document.h.
 { new (stack_.template Push<ValueType>()) ValueType(i); return true; }
Friends And Related Function Documentation
GenericValue
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> template<typename , typename > friend class GenericValue friend
Definition at line 2512 of file document.h.
swap
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> void swap (GenericDocument< Encoding, Allocator, StackAllocator > & a, GenericDocument< Encoding, Allocator, StackAllocator > & b) friend
free-standing swap function helper
Helper function to enable support for common swap implementation pattern based on std::swap:
void swap(MyClass& a, MyClass& b) {
    using std::swap;
    swap(a.doc, b.doc);
    // ...
}
See also
Swap()
Definition at line 2310 of file document.h.
 { a.Swap(b); }
Field Documentation
allocator_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> Allocator* rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::allocator_ private
Definition at line 2578 of file document.h.
kDefaultStackCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> const size_t rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::kDefaultStackCapacity = 1024 static private
Definition at line 2577 of file document.h.
ownAllocator_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> Allocator* rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_ private
Definition at line 2579 of file document.h.
parseResult_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> ParseResult rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_ private
Definition at line 2581 of file document.h.
stack_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<CrtAllocator>, typename StackAllocator = CrtAllocator> internal::Stack<StackAllocator> rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::stack_ private
Definition at line 2580 of file document.h.
The documentation for this class was generated from the following file:
shared/rapidjson/include/rapidjson/document.h