BeatSaber-Hooks: Configuration Class Reference
Configuration Class Reference
#include <config-utils.hpp>
Public Member Functions
Configuration (const ModInfo &info_)
Configuration (Configuration &&other)
Configuration (const Configuration &other)
void Load ()
void Reload ()
void Write ()
Static Public Member Functions
static std::string getConfigFilePath (const ModInfo &info)
Data Fields
const ModInfo info
ConfigDocument config
bool readJson = false
Private Member Functions
bool ensureObject ()
Private Attributes
std::string filePath
Static Private Attributes
static std::optional< std::string > configDir
Detailed Description
Definition at line 27 of file config-utils.hpp.
Constructor & Destructor Documentation
Configuration() [1/3]
Configuration::Configuration (const ModInfo & info_) inline
Definition at line 34 of file config-utils.hpp.
                                         : info(info_) {
         filePath = Configuration::getConfigFilePath(info_);
     }
References filePath, and getConfigFilePath().
Configuration() [2/3]
Configuration::Configuration (Configuration && other) inline
Definition at line 37 of file config-utils.hpp.
                                          :
         info(std::move(other.info)),
         filePath(std::move(other.filePath))
     {
         config.Swap(other.config);
     }
References config, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
Configuration() [3/3]
Configuration::Configuration (const Configuration & other) inline
Definition at line 43 of file config-utils.hpp.
                                               :
         info(other.info),
         filePath(other.filePath)
     {
         config.CopyFrom(other.config, config.GetAllocator());
     }
References config, and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator().
Member Function Documentation
ensureObject()
bool Configuration::ensureObject () private
Definition at line 23 of file config-utils.cpp.
{
     if (!config.IsObject()) {
         Logger::get().warning("Config data for mod was invalid! Clearing.");
         config.SetObject();
         return false;
     }
     return true;
 }
References Logger::get(), and Logger::warning().
getConfigFilePath()
std::string Configuration::getConfigFilePath (const ModInfo & info) static
Definition at line 81 of file config-utils.cpp.
{
     if (!Configuration::configDir) {
         Configuration::configDir = string_format(CONFIG_PATH_FORMAT, Modloader::getApplicationId().c_str());
         if (!direxists(Configuration::configDir->c_str())) {
             mkpath(Configuration::configDir->c_str());
         }
     }
     return *Configuration::configDir + info.id + ".json";
 }
References CONFIG_PATH_FORMAT, configDir, direxists(), Modloader::getApplicationId(), info, mkpath(), and string_format().
Referenced by Configuration().
Load()
void Configuration::Load ()
Definition at line 33 of file config-utils.cpp.
{
     if (readJson) {
         return;
     }
     if (!fileexists(filePath)) {
         writefile(filePath, "{}");
     }
     Configuration::Reload();
 }
References fileexists(), readJson, Reload(), and writefile().
Reload()
void Configuration::Reload ()
Definition at line 44 of file config-utils.cpp.
{
     readJson = parsejsonfile(config, filePath);
     ensureObject();
 }
References parsejsonfile(), and readJson.
Referenced by Load().
Write()
void Configuration::Write ()
Definition at line 49 of file config-utils.cpp.
{
     ensureObject();
     StringBuffer buf;
     PrettyWriter<StringBuffer> writer(buf);
     config.Accept(writer);
     writefile(filePath, buf.GetString());
 }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and writefile().
Field Documentation
config
ConfigDocument Configuration::config
Definition at line 32 of file config-utils.hpp.
Referenced by Configuration().
configDir
std::optional<std::string> Configuration::configDir static private
Definition at line 56 of file config-utils.hpp.
Referenced by getConfigFilePath().
filePath
std::string Configuration::filePath private
Definition at line 58 of file config-utils.hpp.
Referenced by Configuration().
info
const ModInfo Configuration::info
Definition at line 31 of file config-utils.hpp.
readJson
bool Configuration::readJson = false
Definition at line 33 of file config-utils.hpp.
The documentation for this class was generated from the following files:
shared/config/config-utils.hpp
src/config/config-utils.cpp