BeatSaber-Hooks: Education Class Reference
Education Class Reference
Public Member Functions
Education (const std::string &school, double GPA)
Education (const Education &rhs)
template<typename Writer >
void Serialize (Writer &writer) const
Private Attributes
std::string school_
double GPA_
Detailed Description
Definition at line 45 of file serialize.cpp.
Constructor & Destructor Documentation
Education() [1/2]
Education::Education (const std::string & school, double GPA) inline
Definition at line 47 of file serialize.cpp.
 : school_(school), GPA_(GPA) {}
Education() [2/2]
Education::Education (const Education & rhs) inline
Definition at line 48 of file serialize.cpp.
 : school_(rhs.school_), GPA_(rhs.GPA_) {}
Member Function Documentation
Serialize()
template<typename Writer > void Education::Serialize (Writer & writer) const inline
Definition at line 51 of file serialize.cpp.
{
         writer.StartObject();
         writer.String("school");
 #if RAPIDJSON_HAS_STDSTRING
         writer.String(school_);
 #else
         writer.String(school_.c_str(), static_cast<SizeType>(school_.length()));
 #endif
         writer.String("GPA");
         writer.Double(GPA_);
         writer.EndObject();
     }
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Field Documentation
GPA_
double Education::GPA_ private
Definition at line 69 of file serialize.cpp.
school_
std::string Education::school_ private
Definition at line 68 of file serialize.cpp.
The documentation for this class was generated from the following file:
shared/rapidjson/example/serialize/serialize.cpp