BeatSaber-Hooks: il2cpp_functions Class Reference
il2cpp_functions Class Reference
#include <il2cpp-functions.hpp>
Static Public Member Functions
static char * Type_GetName (const Il2CppType *type, Il2CppTypeNameFormat format)
static void CheckS_GlobalMetadata ()
static const char * MetadataCache_GetStringFromIndex (StringIndex index)
static const Il2CppTypeDefinition * MetadataCache_GetTypeDefinitionFromIndex (TypeDefinitionIndex index)
static TypeDefinitionIndex MetadataCache_GetExportedTypeFromIndex (TypeDefinitionIndex index)
static const Il2CppGenericContainer * MetadataCache_GetGenericContainerFromIndex (GenericContainerIndex index)
static const Il2CppGenericParameter * MetadataCache_GetGenericParameterFromIndex (GenericParameterIndex index)
static Il2CppClass * MetadataCache_GetNestedTypeFromIndex (NestedTypeIndex index)
static TypeDefinitionIndex MetadataCache_GetIndexForTypeDefinition (const Il2CppClass *typeDefinition)
static void Init ()
static LoggerContextObject & getFuncLogger ()
Static Public Attributes
static void(* init)(const char *domain_name)
static void(* init_utf16)(const Il2CppChar *domain_name)
static void(* shutdown)()
static void(* set_config_dir)(const char *config_path)
static void(* set_data_dir)(const char *data_path)
static void(* set_temp_dir)(const char *temp_path)
static void(* set_commandline_arguments)(int argc, const char *const argv[], const char *basedir)
static void(* set_commandline_arguments_utf16)(int argc, const Il2CppChar *const argv[], const char *basedir)
static void(* set_config_utf16)(const Il2CppChar *executablePath)
static void(* set_config)(const char *executablePath)
static void(* set_memory_callbacks)(Il2CppMemoryCallbacks *callbacks)
static const Il2CppImage *(* get_corlib)()
static void(* add_internal_call)(const char *name, Il2CppMethodPointer method)
static Il2CppMethodPointer(* resolve_icall)(const char *name)
static void *(* alloc)(size_t size)
static void(* free)(void *ptr)
static Il2CppClass *(* array_class_get)(Il2CppClass *element_class, uint32_t rank)
static uint32_t(* array_length)(Il2CppArray *array)
static uint32_t(* array_get_byte_length)(Il2CppArray *array)
static Il2CppArray *(* array_new)(Il2CppClass *elementTypeInfo, il2cpp_array_size_t length)
static Il2CppArray *(* array_new_specific)(Il2CppClass *arrayTypeInfo, il2cpp_array_size_t length)
static Il2CppArray *(* array_new_full)(Il2CppClass *array_class, il2cpp_array_size_t *lengths, il2cpp_array_size_t *lower_bounds)
static Il2CppClass *(* bounded_array_class_get)(Il2CppClass *element_class, uint32_t rank, bool bounded)
static int(* array_element_size)(const Il2CppClass *array_class)
static const Il2CppImage *(* assembly_get_image)(const Il2CppAssembly *assembly)
static const Il2CppType *(* class_enum_basetype)(Il2CppClass *klass)
static bool(* class_is_generic)(const Il2CppClass *klass)
static bool(* class_is_inflated)(const Il2CppClass *klass)
static bool(* class_is_assignable_from)(Il2CppClass *klass, Il2CppClass *oklass)
static bool(* class_is_subclass_of)(Il2CppClass *klass, Il2CppClass *klassc, bool check_interfaces)
static bool(* class_has_parent)(Il2CppClass *klass, Il2CppClass *klassc)
static Il2CppClass *(* class_from_il2cpp_type)(const Il2CppType *type)
static Il2CppClass *(* class_from_name)(const Il2CppImage *image, const char *namespaze, const char *name)
static Il2CppClass *(* class_from_system_type)(Il2CppReflectionType *type)
static Il2CppClass *(* class_get_element_class)(Il2CppClass *klass)
static const EventInfo *(* class_get_events)(Il2CppClass *klass, void **iter)
static FieldInfo *(* class_get_fields)(Il2CppClass *klass, void **iter)
static Il2CppClass *(* class_get_nested_types)(Il2CppClass *klass, void **iter)
static Il2CppClass *(* class_get_interfaces)(Il2CppClass *klass, void **iter)
static const PropertyInfo *(* class_get_properties)(Il2CppClass *klass, void **iter)
static const PropertyInfo *(* class_get_property_from_name)(Il2CppClass *klass, const char *name)
static FieldInfo *(* class_get_field_from_name)(Il2CppClass *klass, const char *name)
static const MethodInfo *(* class_get_methods)(Il2CppClass *klass, void **iter)
static const MethodInfo *(* class_get_method_from_name)(const Il2CppClass *klass, const char *name, int argsCount)
static const char *(* class_get_name)(const Il2CppClass *klass)
static const char *(* class_get_namespace)(const Il2CppClass *klass)
static Il2CppClass *(* class_get_parent)(Il2CppClass *klass)
static Il2CppClass *(* class_get_declaring_type)(const Il2CppClass *klass)
static int32_t(* class_instance_size)(Il2CppClass *klass)
static size_t(* class_num_fields)(const Il2CppClass *enumKlass)
static bool(* class_is_valuetype)(const Il2CppClass *klass)
static int32_t(* class_value_size)(Il2CppClass *klass, uint32_t *align)
static bool(* class_is_blittable)(const Il2CppClass *klass)
static int(* class_get_flags)(const Il2CppClass *klass)
static bool(* class_is_abstract)(const Il2CppClass *klass)
static bool(* class_is_interface)(const Il2CppClass *klass)
static int(* class_array_element_size)(const Il2CppClass *klass)
static Il2CppClass *(* class_from_type)(const Il2CppType *type)
static const Il2CppType *(* class_get_type)(Il2CppClass *klass)
static uint32_t(* class_get_type_token)(Il2CppClass *klass)
static bool(* class_has_attribute)(Il2CppClass *klass, Il2CppClass *attr_class)
static bool(* class_has_references)(Il2CppClass *klass)
static bool(* class_is_enum)(const Il2CppClass *klass)
static const Il2CppImage *(* class_get_image)(Il2CppClass *klass)
static const char *(* class_get_assemblyname)(const Il2CppClass *klass)
static int(* class_get_rank)(const Il2CppClass *klass)
static size_t(* class_get_bitmap_size)(const Il2CppClass *klass)
static void(* class_get_bitmap)(Il2CppClass *klass, size_t *bitmap)
static bool(* stats_dump_to_file)(const char *path)
static uint64_t(* stats_get_value)(Il2CppStat stat)
static Il2CppDomain *(* domain_get)()
static const Il2CppAssembly *(* domain_assembly_open)(Il2CppDomain *domain, const char *name)
static const Il2CppAssembly **(* domain_get_assemblies)(const Il2CppDomain *domain, size_t *size)
static Il2CppException *(* exception_from_name_msg)(const Il2CppImage *image, const char *name_space, const char *name, const char *msg)
static Il2CppException *(* get_exception_argument_null)(const char *arg)
static void(* format_exception)(const Il2CppException *ex, char *message, int message_size)
static void(* format_stack_trace)(const Il2CppException *ex, char *output, int output_size)
static void(* unhandled_exception)(Il2CppException *)
static int(* field_get_flags)(FieldInfo *field)
static const char *(* field_get_name)(FieldInfo *field)
static Il2CppClass *(* field_get_parent)(FieldInfo *field)
static size_t(* field_get_offset)(FieldInfo *field)
static const Il2CppType *(* field_get_type)(FieldInfo *field)
static void(* field_get_value)(Il2CppObject *obj, FieldInfo *field, void *value)
static Il2CppObject *(* field_get_value_object)(FieldInfo *field, Il2CppObject *obj)
static bool(* field_has_attribute)(FieldInfo *field, Il2CppClass *attr_class)
static void(* field_set_value)(Il2CppObject *obj, FieldInfo *field, void *value)
static void(* field_static_get_value)(FieldInfo *field, void *value)
static void(* field_static_set_value)(FieldInfo *field, void *value)
static void(* field_set_value_object)(Il2CppObject *instance, FieldInfo *field, Il2CppObject *value)
static void(* gc_collect)(int maxGenerations)
static int32_t(* gc_collect_a_little)()
static void(* gc_disable)()
static void(* gc_enable)()
static bool(* gc_is_disabled)()
static int64_t(* gc_get_used_size)()
static int64_t(* gc_get_heap_size)()
static void(* gc_wbarrier_set_field)(Il2CppObject *obj, void **targetAddress, void *object)
static uint32_t(* gchandle_new)(Il2CppObject *obj, bool pinned)
static uint32_t(* gchandle_new_weakref)(Il2CppObject *obj, bool track_resurrection)
static Il2CppObject *(* gchandle_get_target)(uint32_t gchandle)
static void(* gchandle_free)(uint32_t gchandle)
static void *(* unity_liveness_calculation_begin)(Il2CppClass *filter, int max_object_count, il2cpp_register_object_callback callback, void *userdata, il2cpp_WorldChangedCallback onWorldStarted, il2cpp_WorldChangedCallback onWorldStopped)
static void(* unity_liveness_calculation_end)(void *state)
static void(* unity_liveness_calculation_from_root)(Il2CppObject *root, void *state)
static void(* unity_liveness_calculation_from_statics)(void *state)
static const Il2CppType *(* method_get_return_type)(const MethodInfo *method)
static Il2CppClass *(* method_get_declaring_type)(const MethodInfo *method)
static const char *(* method_get_name)(const MethodInfo *method)
static const MethodInfo *(* method_get_from_reflection)(const Il2CppReflectionMethod *method)
static Il2CppReflectionMethod *(* method_get_object)(const MethodInfo *method, Il2CppClass *refclass)
static bool(* method_is_generic)(const MethodInfo *method)
static bool(* method_is_inflated)(const MethodInfo *method)
static bool(* method_is_instance)(const MethodInfo *method)
static uint32_t(* method_get_param_count)(const MethodInfo *method)
static const Il2CppType *(* method_get_param)(const MethodInfo *method, uint32_t index)
static Il2CppClass *(* method_get_class)(const MethodInfo *method)
static bool(* method_has_attribute)(const MethodInfo *method, Il2CppClass *attr_class)
static uint32_t(* method_get_flags)(const MethodInfo *method, uint32_t *iflags)
static uint32_t(* method_get_token)(const MethodInfo *method)
static const char *(* method_get_param_name)(const MethodInfo *method, uint32_t index)
static void(* profiler_install)(Il2CppProfiler *prof, Il2CppProfileFunc shutdown_callback)
static void(* profiler_set_events)(Il2CppProfileFlags events)
static void(* profiler_install_enter_leave)(Il2CppProfileMethodFunc enter, Il2CppProfileMethodFunc fleave)
static void(* profiler_install_allocation)(Il2CppProfileAllocFunc callback)
static void(* profiler_install_gc)(Il2CppProfileGCFunc callback, Il2CppProfileGCResizeFunc heap_resize_callback)
static void(* profiler_install_fileio)(Il2CppProfileFileIOFunc callback)
static void(* profiler_install_thread)(Il2CppProfileThreadFunc start, Il2CppProfileThreadFunc end)
static uint32_t(* property_get_flags)(const PropertyInfo *prop)
static const MethodInfo *(* property_get_get_method)(const PropertyInfo *prop)
static const MethodInfo *(* property_get_set_method)(const PropertyInfo *prop)
static const char *(* property_get_name)(const PropertyInfo *prop)
static Il2CppClass *(* property_get_parent)(const PropertyInfo *prop)
static Il2CppClass *(* object_get_class)(Il2CppObject *obj)
static uint32_t(* object_get_size)(Il2CppObject *obj)
static const MethodInfo *(* object_get_virtual_method)(Il2CppObject *obj, const MethodInfo *method)
static Il2CppObject *(* object_new)(const Il2CppClass *klass)
static void *(* object_unbox)(Il2CppObject *obj)
static Il2CppObject *(* value_box)(Il2CppClass *klass, void *data)
static void(* monitor_enter)(Il2CppObject *obj)
static bool(* monitor_try_enter)(Il2CppObject *obj, uint32_t timeout)
static void(* monitor_exit)(Il2CppObject *obj)
static void(* monitor_pulse)(Il2CppObject *obj)
static void(* monitor_pulse_all)(Il2CppObject *obj)
static void(* monitor_wait)(Il2CppObject *obj)
static bool(* monitor_try_wait)(Il2CppObject *obj, uint32_t timeout)
static Il2CppObject *(* runtime_invoke)(const MethodInfo *method, void *obj, void **params, Il2CppException **exc)
static Il2CppObject *(* runtime_invoke_convert_args)(const MethodInfo *method, void *obj, Il2CppObject **params, int paramCount, Il2CppException **exc)
static void(* runtime_class_init)(Il2CppClass *klass)
static void(* runtime_object_init)(Il2CppObject *obj)
static void(* runtime_object_init_exception)(Il2CppObject *obj, Il2CppException **exc)
static void(* runtime_unhandled_exception_policy_set)(Il2CppRuntimeUnhandledExceptionPolicy value)
static int32_t(* string_length)(Il2CppString *str)
static Il2CppChar *(* string_chars)(Il2CppString *str)
static Il2CppString *(* string_new)(const char *str)
static Il2CppString *(* string_new_len)(const char *str, uint32_t length)
static Il2CppString *(* string_new_utf16)(const Il2CppChar *text, int32_t len)
static Il2CppString *(* string_new_wrapper)(const char *str)
static Il2CppString *(* string_intern)(Il2CppString *str)
static Il2CppString *(* string_is_interned)(Il2CppString *str)
static Il2CppThread *(* thread_current)()
static Il2CppThread *(* thread_attach)(Il2CppDomain *domain)
static void(* thread_detach)(Il2CppThread *thread)
static Il2CppThread **(* thread_get_all_attached_threads)(size_t *size)
static bool(* is_vm_thread)(Il2CppThread *thread)
static void(* current_thread_walk_frame_stack)(Il2CppFrameWalkFunc func, void *user_data)
static void(* thread_walk_frame_stack)(Il2CppThread *thread, Il2CppFrameWalkFunc func, void *user_data)
static bool(* current_thread_get_top_frame)(Il2CppStackFrameInfo *frame)
static bool(* thread_get_top_frame)(Il2CppThread *thread, Il2CppStackFrameInfo *frame)
static bool(* current_thread_get_frame_at)(int32_t offset, Il2CppStackFrameInfo *frame)
static bool(* thread_get_frame_at)(Il2CppThread *thread, int32_t offset, Il2CppStackFrameInfo *frame)
static int32_t(* current_thread_get_stack_depth)()
static int32_t(* thread_get_stack_depth)(Il2CppThread *thread)
static Il2CppObject *(* type_get_object)(const Il2CppType *type)
static int(* type_get_type)(const Il2CppType *type)
static Il2CppClass *(* type_get_class_or_element_class)(const Il2CppType *type)
static char *(* type_get_name)(const Il2CppType *type)
static bool(* type_is_byref)(const Il2CppType *type)
static uint32_t(* type_get_attrs)(const Il2CppType *type)
static bool(* type_equals)(const Il2CppType *type, const Il2CppType *otherType)
static char *(* type_get_assembly_qualified_name)(const Il2CppType *type)
static const Il2CppAssembly *(* image_get_assembly)(const Il2CppImage *image)
static const char *(* image_get_name)(const Il2CppImage *image)
static const char *(* image_get_filename)(const Il2CppImage *image)
static const MethodInfo *(* image_get_entry_point)(const Il2CppImage *image)
static size_t(* image_get_class_count)(const Il2CppImage *image)
static const Il2CppClass *(* image_get_class)(const Il2CppImage *image, size_t index)
static Il2CppManagedMemorySnapshot *(* capture_memory_snapshot)()
static void(* free_captured_memory_snapshot)(Il2CppManagedMemorySnapshot *snapshot)
static void(* set_find_plugin_callback)(Il2CppSetFindPlugInCallback method)
static void(* register_log_callback)(Il2CppLogCallback method)
static void(* debugger_set_agent_options)(const char *options)
static bool(* is_debugger_attached)()
static void(* unity_install_unitytls_interface)(const void *unitytlsInterfaceStruct)
static Il2CppCustomAttrInfo *(* custom_attrs_from_class)(Il2CppClass *klass)
static Il2CppCustomAttrInfo *(* custom_attrs_from_method)(const MethodInfo *method)
static Il2CppObject *(* custom_attrs_get_attr)(Il2CppCustomAttrInfo *ainfo, Il2CppClass *attr_klass)
static bool(* custom_attrs_has_attr)(Il2CppCustomAttrInfo *ainfo, Il2CppClass *attr_klass)
static Il2CppArray *(* custom_attrs_construct)(Il2CppCustomAttrInfo *cinfo)
static void(* custom_attrs_free)(Il2CppCustomAttrInfo *ainfo)
static const Il2CppType *(* class_get_type_const)(const Il2CppClass *klass)
static const char *(* class_get_name_const)(const Il2CppClass *klass)
static bool(* Class_Init)(Il2CppClass *klass)
static Il2CppClass *(* MetadataCache_GetTypeInfoFromTypeDefinitionIndex)(TypeDefinitionIndex index)
static Il2CppClass *(* MetadataCache_GetTypeInfoFromTypeIndex)(TypeIndex index)
static gnu_string(* _Type_GetName_)(const Il2CppType *type, Il2CppTypeNameFormat format)
static void(* GC_free)(void *addr)
static void(* GarbageCollector_SetWriteBarrier)(void **ptr)
static void *(* GarbageCollector_AllocateFixed)(size_t sz, void *descr)
static Il2CppClass *(* Class_FromIl2CppType)(Il2CppType *typ)
static Il2CppClass *(* Class_GetPtrClass)(Il2CppClass *elementClass)
static Il2CppClass *(* GenericClass_GetClass)(Il2CppGenericClass *gclass)
static AssemblyVector *(* Assembly_GetAllAssemblies)()
static const Il2CppMetadataRegistration ** s_Il2CppMetadataRegistrationPtr
static const void ** s_GlobalMetadataPtr
static const Il2CppGlobalMetadataHeader ** s_GlobalMetadataHeaderPtr
static std::remove_pointer_t< decltype(il2cpp_functions::s_GlobalMetadataPtr)> s_GlobalMetadata
static std::remove_pointer_t< decltype(il2cpp_functions::s_GlobalMetadataHeaderPtr)> s_GlobalMetadataHeader
static const Il2CppDefaults * defaults
static bool initialized
Detailed Description
Definition at line 89 of file il2cpp-functions.hpp.
Member Function Documentation
CheckS_GlobalMetadata()
static void il2cpp_functions::CheckS_GlobalMetadata () inline static
Definition at line 391 of file il2cpp-functions.hpp.
{
         if (!s_GlobalMetadataHeader) {
             static auto& logger = getFuncLogger();
             s_GlobalMetadata = *(il2cpp_functions::s_GlobalMetadataPtr);
             s_GlobalMetadataHeader = *(il2cpp_functions::s_GlobalMetadataHeaderPtr);
             logger.debug("sanity: %X (should be 0xFAB11BAF)", s_GlobalMetadataHeader->sanity);
             logger.debug("version: %i", s_GlobalMetadataHeader->version);
             assert(s_GlobalMetadataHeader->sanity == 0xFAB11BAF);
             logger.debug("typeDefinitionsOffset: %i", s_GlobalMetadataHeader->typeDefinitionsOffset);
             logger.debug("exportedTypeDefinitionsOffset: %i", s_GlobalMetadataHeader->exportedTypeDefinitionsOffset);
             logger.debug("nestedTypesOffset: %i", s_GlobalMetadataHeader->nestedTypesOffset);
             // TODO: use il2cpp_functions::defaults to define the il2cpp_defaults variable mentioned in il2cpp-class-internals.h
         }
     }
References getFuncLogger(), s_GlobalMetadata, s_GlobalMetadataHeader, s_GlobalMetadataHeaderPtr, and s_GlobalMetadataPtr.
Referenced by MetadataCache_GetExportedTypeFromIndex(), MetadataCache_GetGenericContainerFromIndex(), MetadataCache_GetGenericParameterFromIndex(), MetadataCache_GetIndexForTypeDefinition(), MetadataCache_GetNestedTypeFromIndex(), MetadataCache_GetStringFromIndex(), and MetadataCache_GetTypeDefinitionFromIndex().
getFuncLogger()
LoggerContextObject & il2cpp_functions::getFuncLogger () static
Definition at line 447 of file il2cpp-functions.cpp.
{
     static auto logger = Logger::get().WithContext("il2cpp_functions");
     return logger;
 }
References Logger::get(), and Logger::WithContext().
Referenced by CheckS_GlobalMetadata(), find_GC_free(), find_GC_SetWriteBarrier(), Init(), and trace_GC_AllocFixed().
Init()
void il2cpp_functions::Init () static
Definition at line 461 of file il2cpp-functions.cpp.
{
     if (initialized) {
         return;
     }
     static auto logger = getFuncLogger().WithContext("Init");
     logger.info("il2cpp_functions: Init: Initializing all IL2CPP Functions...");
     dlerror();  // clears existing errors
     auto path = Modloader::getLibIl2CppPath();
     void *imagehandle = dlopen(path.c_str(), RTLD_GLOBAL | RTLD_LAZY);
     if (!imagehandle) {
         logger.error("Failed to dlopen %s: %s!", path.c_str(), dlerror());
         return;
     }
     // Please verify that these have more than 1 instruction to their name before attempting to hook them!
     *(void**)(&init) = dlsym(imagehandle, "il2cpp_init");
     logger.info("Loaded: il2cpp_init, error: %s", dlerror());
     *(void**)(&shutdown) = dlsym(imagehandle, "il2cpp_shutdown");
     logger.info("Loaded: il2cpp_shutdown, error: %s", dlerror());
     *(void**)(&init_utf16) = dlsym(imagehandle, "il2cpp_init_utf16");
     logger.info("Loaded: il2cpp_init_utf16");
     *(void**)(&set_config_dir) = dlsym(imagehandle, "il2cpp_set_config_dir");
     logger.info("Loaded: il2cpp_set_config_dir");
     *(void**)(&set_data_dir) = dlsym(imagehandle, "il2cpp_set_data_dir");
     logger.info("Loaded: il2cpp_set_data_dir");
     *(void**)(&set_temp_dir) = dlsym(imagehandle, "il2cpp_set_temp_dir");
     logger.info("Loaded: il2cpp_set_temp_dir");
     *(void**)(&set_commandline_arguments) = dlsym(imagehandle, "il2cpp_set_commandline_arguments");
     logger.info("Loaded: il2cpp_set_commandline_arguments");
     *(void**)(&set_commandline_arguments_utf16) = dlsym(imagehandle, "il2cpp_set_commandline_arguments_utf16");
     logger.info("Loaded: il2cpp_set_commandline_arguments_utf16");
     *(void**)(&set_config_utf16) = dlsym(imagehandle, "il2cpp_set_config_utf16");
     logger.info("Loaded: il2cpp_set_config_utf16");
     *(void**)(&set_config) = dlsym(imagehandle, "il2cpp_set_config");
     logger.info("Loaded: il2cpp_set_config");
     *(void**)(&set_memory_callbacks) = dlsym(imagehandle, "il2cpp_set_memory_callbacks");
     logger.info("Loaded: il2cpp_set_memory_callbacks");
     *(void**)(&get_corlib) = dlsym(imagehandle, "il2cpp_get_corlib");
     logger.info("Loaded: il2cpp_get_corlib");
     *(void**)(&add_internal_call) = dlsym(imagehandle, "il2cpp_add_internal_call");
     logger.info("Loaded: il2cpp_add_internal_call");
     *(void**)(&resolve_icall) = dlsym(imagehandle, "il2cpp_resolve_icall");
     logger.info("Loaded: il2cpp_resolve_icall");
     *(void**)(&alloc) = dlsym(imagehandle, "il2cpp_alloc");
     logger.info("Loaded: il2cpp_alloc");
     *(void**)(&free) = dlsym(imagehandle, "il2cpp_free");
     logger.info("Loaded: il2cpp_free");
     *(void**)(&array_class_get) = dlsym(imagehandle, "il2cpp_array_class_get");
     logger.info("Loaded: il2cpp_array_class_get");
     *(void**)(&array_length) = dlsym(imagehandle, "il2cpp_array_length");
     logger.info("Loaded: il2cpp_array_length");
     *(void**)(&array_get_byte_length) = dlsym(imagehandle, "il2cpp_array_get_byte_length");
     logger.info("Loaded: il2cpp_array_get_byte_length");
     *(void**)(&array_new) = dlsym(imagehandle, "il2cpp_array_new");
     logger.info("Loaded: il2cpp_array_new");
     *(void**)(&array_new_specific) = dlsym(imagehandle, "il2cpp_array_new_specific");
     logger.info("Loaded: il2cpp_array_new_specific");
     *(void**)(&array_new_full) = dlsym(imagehandle, "il2cpp_array_new_full");
     logger.info("Loaded: il2cpp_array_new_full");
     *(void**)(&bounded_array_class_get) = dlsym(imagehandle, "il2cpp_bounded_array_class_get");
     logger.info("Loaded: il2cpp_bounded_array_class_get");
     *(void**)(&array_element_size) = dlsym(imagehandle, "il2cpp_array_element_size");
     logger.info("Loaded: il2cpp_array_element_size");
     *(void**)(&assembly_get_image) = dlsym(imagehandle, "il2cpp_assembly_get_image");
     logger.info("Loaded: il2cpp_assembly_get_image");
     #ifdef UNITY_2019
     *(void**)(&class_for_each) = dlsym(imagehandle, "il2cpp_class_for_each");
     logger.info("Loaded: il2cpp_class_for_each");
     #endif
     *(void**)(&class_enum_basetype) = dlsym(imagehandle, "il2cpp_class_enum_basetype");
     logger.info("Loaded: il2cpp_class_enum_basetype");
     *(void**)(&class_is_generic) = dlsym(imagehandle, "il2cpp_class_is_generic");
     logger.info("Loaded: il2cpp_class_is_generic");
     *(void**)(&class_is_inflated) = dlsym(imagehandle, "il2cpp_class_is_inflated");
     logger.info("Loaded: il2cpp_class_is_inflated");
     *(void**)(&class_is_assignable_from) = dlsym(imagehandle, "il2cpp_class_is_assignable_from");
     logger.info("Loaded: il2cpp_class_is_assignable_from");
     *(void**)(&class_is_subclass_of) = dlsym(imagehandle, "il2cpp_class_is_subclass_of");
     logger.info("Loaded: il2cpp_class_is_subclass_of");
     *(void**)(&class_has_parent) = dlsym(imagehandle, "il2cpp_class_has_parent");
     logger.info("Loaded: il2cpp_class_has_parent");
     *(void**)(&class_from_il2cpp_type) = dlsym(imagehandle, "il2cpp_class_from_il2cpp_type");
     logger.info("Loaded: il2cpp_class_from_il2cpp_type");
     *(void**)(&class_from_name) = dlsym(imagehandle, "il2cpp_class_from_name");
     logger.info("Loaded: il2cpp_class_from_name");
     *(void**)(&class_from_system_type) = dlsym(imagehandle, "il2cpp_class_from_system_type");
     logger.info("Loaded: il2cpp_class_from_system_type");
     *(void**)(&class_get_element_class) = dlsym(imagehandle, "il2cpp_class_get_element_class");
     logger.info("Loaded: il2cpp_class_get_element_class");
     *(void**)(&class_get_events) = dlsym(imagehandle, "il2cpp_class_get_events");
     logger.info("Loaded: il2cpp_class_get_events");
     *(void**)(&class_get_fields) = dlsym(imagehandle, "il2cpp_class_get_fields");
     logger.info("Loaded: il2cpp_class_get_fields");
     *(void**)(&class_get_nested_types) = dlsym(imagehandle, "il2cpp_class_get_nested_types");
     logger.info("Loaded: il2cpp_class_get_nested_types");
     *(void**)(&class_get_interfaces) = dlsym(imagehandle, "il2cpp_class_get_interfaces");
     logger.info("Loaded: il2cpp_class_get_interfaces");
     *(void**)(&class_get_properties) = dlsym(imagehandle, "il2cpp_class_get_properties");
     logger.info("Loaded: il2cpp_class_get_properties");
     *(void**)(&class_get_property_from_name) = dlsym(imagehandle, "il2cpp_class_get_property_from_name");
     logger.info("Loaded: il2cpp_class_get_property_from_name");
     *(void**)(&class_get_field_from_name) = dlsym(imagehandle, "il2cpp_class_get_field_from_name");
     logger.info("Loaded: il2cpp_class_get_field_from_name");
     *(void**)(&class_get_methods) = dlsym(imagehandle, "il2cpp_class_get_methods");
     logger.info("Loaded: il2cpp_class_get_methods");
     *(void**)(&class_get_method_from_name) = dlsym(imagehandle, "il2cpp_class_get_method_from_name");
     logger.info("Loaded: il2cpp_class_get_method_from_name");
     *(void**)(&class_get_name) = dlsym(imagehandle, "il2cpp_class_get_name");
     logger.info("Loaded: il2cpp_class_get_name");
     #ifdef UNITY_2019
     *(void**)(&type_get_name_chunked) = dlsym(imagehandle, "il2cpp_type_get_name_chunked");
     logger.info("Loaded: il2cpp_type_get_name_chunked");
     #endif
     *(void**)(&class_get_namespace) = dlsym(imagehandle, "il2cpp_class_get_namespace");
     logger.info("Loaded: il2cpp_class_get_namespace");
     *(void**)(&class_get_parent) = dlsym(imagehandle, "il2cpp_class_get_parent");
     logger.info("Loaded: il2cpp_class_get_parent");
     *(void**)(&class_get_declaring_type) = dlsym(imagehandle, "il2cpp_class_get_declaring_type");
     logger.info("Loaded: il2cpp_class_get_declaring_type");
     *(void**)(&class_instance_size) = dlsym(imagehandle, "il2cpp_class_instance_size");
     logger.info("Loaded: il2cpp_class_instance_size");
     *(void**)(&class_num_fields) = dlsym(imagehandle, "il2cpp_class_num_fields");
     logger.info("Loaded: il2cpp_class_num_fields");
     *(void**)(&class_is_valuetype) = dlsym(imagehandle, "il2cpp_class_is_valuetype");
     logger.info("Loaded: il2cpp_class_is_valuetype");
     *(void**)(&class_value_size) = dlsym(imagehandle, "il2cpp_class_value_size");
     logger.info("Loaded: il2cpp_class_value_size");
     *(void**)(&class_is_blittable) = dlsym(imagehandle, "il2cpp_class_is_blittable");
     logger.info("Loaded: il2cpp_class_is_blittable");
     *(void**)(&class_get_flags) = dlsym(imagehandle, "il2cpp_class_get_flags");
     logger.info("Loaded: il2cpp_class_get_flags");
     *(void**)(&class_is_abstract) = dlsym(imagehandle, "il2cpp_class_is_abstract");
     logger.info("Loaded: il2cpp_class_is_abstract");
     *(void**)(&class_is_interface) = dlsym(imagehandle, "il2cpp_class_is_interface");
     logger.info("Loaded: il2cpp_class_is_interface");
     *(void**)(&class_array_element_size) = dlsym(imagehandle, "il2cpp_class_array_element_size");
     logger.info("Loaded: il2cpp_class_array_element_size");
     *(void**)(&class_from_type) = dlsym(imagehandle, "il2cpp_class_from_type");
     logger.info("Loaded: il2cpp_class_from_type");
     *(void**)(&class_get_type) = dlsym(imagehandle, "il2cpp_class_get_type");
     logger.info("Loaded: il2cpp_class_get_type");
     *(void**)(&class_get_type_token) = dlsym(imagehandle, "il2cpp_class_get_type_token");
     logger.info("Loaded: il2cpp_class_get_type_token");
     *(void**)(&class_has_attribute) = dlsym(imagehandle, "il2cpp_class_has_attribute");
     logger.info("Loaded: il2cpp_class_has_attribute");
     *(void**)(&class_has_references) = dlsym(imagehandle, "il2cpp_class_has_references");
     logger.info("Loaded: il2cpp_class_has_references");
     *(void**)(&class_is_enum) = dlsym(imagehandle, "il2cpp_class_is_enum");
     logger.info("Loaded: il2cpp_class_is_enum");
     *(void**)(&class_get_image) = dlsym(imagehandle, "il2cpp_class_get_image");
     logger.info("Loaded: il2cpp_class_get_image");
     *(void**)(&class_get_assemblyname) = dlsym(imagehandle, "il2cpp_class_get_assemblyname");
     logger.info("Loaded: il2cpp_class_get_assemblyname");
     *(void**)(&class_get_rank) = dlsym(imagehandle, "il2cpp_class_get_rank");
     logger.info("Loaded: il2cpp_class_get_rank");
     #ifdef UNITY_2019
     *(void**)(&class_get_data_size) = dlsym(imagehandle, "il2cpp_class_get_data_size");
     logger.info("Loaded: il2cpp_class_get_data_size");
     *(void**)(&class_get_static_field_data) = dlsym(imagehandle, "il2cpp_class_get_static_field_data");
     logger.info("Loaded: il2cpp_class_get_static_field_data");
     #endif
     *(void**)(&class_get_bitmap_size) = dlsym(imagehandle, "il2cpp_class_get_bitmap_size");
     logger.info("Loaded: il2cpp_class_get_bitmap_size");
     *(void**)(&class_get_bitmap) = dlsym(imagehandle, "il2cpp_class_get_bitmap");
     logger.info("Loaded: il2cpp_class_get_bitmap");
     *(void**)(&stats_dump_to_file) = dlsym(imagehandle, "il2cpp_stats_dump_to_file");
     logger.info("Loaded: il2cpp_stats_dump_to_file");
     *(void**)(&stats_get_value) = dlsym(imagehandle, "il2cpp_stats_get_value");
     logger.info("Loaded: il2cpp_stats_get_value");
     *(void**)(&domain_get) = dlsym(imagehandle, "il2cpp_domain_get");
     logger.info("Loaded: il2cpp_domain_get");
     *(void**)(&domain_assembly_open) = dlsym(imagehandle, "il2cpp_domain_assembly_open");
     logger.info("Loaded: il2cpp_domain_assembly_open");
     *(void**)(&domain_get_assemblies) = dlsym(imagehandle, "il2cpp_domain_get_assemblies");
     logger.info("Loaded: il2cpp_domain_get_assemblies");
     #ifdef UNITY_2019
     *(void**)(&raise_exception) = dlsym(imagehandle, "il2cpp_raise_exception");
     logger.info("Loaded: il2cpp_raise_exception");
     #endif
     *(void**)(&exception_from_name_msg) = dlsym(imagehandle, "il2cpp_exception_from_name_msg");
     logger.info("Loaded: il2cpp_exception_from_name_msg");
     *(void**)(&get_exception_argument_null) = dlsym(imagehandle, "il2cpp_get_exception_argument_null");
     logger.info("Loaded: il2cpp_get_exception_argument_null");
     *(void**)(&format_exception) = dlsym(imagehandle, "il2cpp_format_exception");
     logger.info("Loaded: il2cpp_format_exception");
     *(void**)(&format_stack_trace) = dlsym(imagehandle, "il2cpp_format_stack_trace");
     logger.info("Loaded: il2cpp_format_stack_trace");
     *(void**)(&unhandled_exception) = dlsym(imagehandle, "il2cpp_unhandled_exception");
     logger.info("Loaded: il2cpp_unhandled_exception");
     *(void**)(&field_get_flags) = dlsym(imagehandle, "il2cpp_field_get_flags");
     logger.info("Loaded: il2cpp_field_get_flags");
     *(void**)(&field_get_name) = dlsym(imagehandle, "il2cpp_field_get_name");
     logger.info("Loaded: il2cpp_field_get_name");
     *(void**)(&field_get_parent) = dlsym(imagehandle, "il2cpp_field_get_parent");
     logger.info("Loaded: il2cpp_field_get_parent");
     *(void**)(&field_get_offset) = dlsym(imagehandle, "il2cpp_field_get_offset");
     logger.info("Loaded: il2cpp_field_get_offset");
     *(void**)(&field_get_type) = dlsym(imagehandle, "il2cpp_field_get_type");
     logger.info("Loaded: il2cpp_field_get_type");
     *(void**)(&field_get_value) = dlsym(imagehandle, "il2cpp_field_get_value");
     logger.info("Loaded: il2cpp_field_get_value");
     *(void**)(&field_get_value_object) = dlsym(imagehandle, "il2cpp_field_get_value_object");
     logger.info("Loaded: il2cpp_field_get_value_object");
     *(void**)(&field_has_attribute) = dlsym(imagehandle, "il2cpp_field_has_attribute");
     logger.info("Loaded: il2cpp_field_has_attribute");
     *(void**)(&field_set_value) = dlsym(imagehandle, "il2cpp_field_set_value");
     logger.info("Loaded: il2cpp_field_set_value");
     *(void**)(&field_static_get_value) = dlsym(imagehandle, "il2cpp_field_static_get_value");
     logger.info("Loaded: il2cpp_field_static_get_value");
     *(void**)(&field_static_set_value) = dlsym(imagehandle, "il2cpp_field_static_set_value");
     logger.info("Loaded: il2cpp_field_static_set_value");
     *(void**)(&field_set_value_object) = dlsym(imagehandle, "il2cpp_field_set_value_object");
     logger.info("Loaded: il2cpp_field_set_value_object");
     #ifdef UNITY_2019
     *(void**)(&field_is_literal) = dlsym(imagehandle, "il2cpp_field_is_literal");
     logger.info("Loaded: il2cpp_field_is_literal");
     #endif
     *(void**)(&gc_collect) = dlsym(imagehandle, "il2cpp_gc_collect");
     logger.info("Loaded: il2cpp_gc_collect");
     *(void**)(&gc_collect_a_little) = dlsym(imagehandle, "il2cpp_gc_collect_a_little");
     logger.info("Loaded: il2cpp_gc_collect_a_little");
     *(void**)(&gc_disable) = dlsym(imagehandle, "il2cpp_gc_disable");
     logger.info("Loaded: il2cpp_gc_disable");
     *(void**)(&gc_enable) = dlsym(imagehandle, "il2cpp_gc_enable");
     logger.info("Loaded: il2cpp_gc_enable");
     *(void**)(&gc_is_disabled) = dlsym(imagehandle, "il2cpp_gc_is_disabled");
     logger.info("Loaded: il2cpp_gc_is_disabled");
     #ifdef UNITY_2019
     *(void**)(&gc_get_max_time_slice_ns) = dlsym(imagehandle, "il2cpp_gc_get_max_time_slice_ns");
     logger.info("Loaded: il2cpp_gc_get_max_time_slice_ns");
     *(void**)(&gc_set_max_time_slice_ns) = dlsym(imagehandle, "il2cpp_gc_set_max_time_slice_ns");
     logger.info("Loaded: il2cpp_gc_set_max_time_slice_ns");
     *(void**)(&gc_is_incremental) = dlsym(imagehandle, "il2cpp_gc_is_incremental");
     logger.info("Loaded: il2cpp_gc_is_incremental");
     #endif
     *(void**)(&gc_get_used_size) = dlsym(imagehandle, "il2cpp_gc_get_used_size");
     logger.info("Loaded: il2cpp_gc_get_used_size");
     *(void**)(&gc_get_heap_size) = dlsym(imagehandle, "il2cpp_gc_get_heap_size");
     logger.info("Loaded: il2cpp_gc_get_heap_size");
     *(void**)(&gc_wbarrier_set_field) = dlsym(imagehandle, "il2cpp_gc_wbarrier_set_field");
     logger.info("Loaded: il2cpp_gc_wbarrier_set_field");
     #ifdef UNITY_2019
     *(void**)(&gc_has_strict_wbarriers) = dlsym(imagehandle, "il2cpp_gc_has_strict_wbarriers");
     logger.info("Loaded: il2cpp_gc_has_strict_wbarriers");
     *(void**)(&gc_set_external_allocation_tracker) = dlsym(imagehandle, "il2cpp_gc_set_external_allocation_tracker");
     logger.info("Loaded: il2cpp_gc_set_external_allocation_tracker");
     *(void**)(&gc_set_external_wbarrier_tracker) = dlsym(imagehandle, "il2cpp_gc_set_external_wbarrier_tracker");
     logger.info("Loaded: il2cpp_gc_set_external_wbarrier_tracker");
     *(void**)(&gc_foreach_heap) = dlsym(imagehandle, "il2cpp_gc_foreach_heap");
     logger.info("Loaded: il2cpp_gc_foreach_heap");
     *(void**)(&stop_gc_world) = dlsym(imagehandle, "il2cpp_stop_gc_world");
     logger.info("Loaded: il2cpp_stop_gc_world");
     *(void**)(&start_gc_world) = dlsym(imagehandle, "il2cpp_start_gc_world");
     logger.info("Loaded: il2cpp_start_gc_world");
     #endif
     *(void**)(&gchandle_new) = dlsym(imagehandle, "il2cpp_gchandle_new");
     logger.info("Loaded: il2cpp_gchandle_new");
     *(void**)(&gchandle_new_weakref) = dlsym(imagehandle, "il2cpp_gchandle_new_weakref");
     logger.info("Loaded: il2cpp_gchandle_new_weakref");
     *(void**)(&gchandle_get_target) = dlsym(imagehandle, "il2cpp_gchandle_get_target");
     logger.info("Loaded: il2cpp_gchandle_get_target");
     *(void**)(&gchandle_free) = dlsym(imagehandle, "il2cpp_gchandle_free");
     logger.info("Loaded: il2cpp_gchandle_free");
     #ifdef UNITY_2019
     *(void**)(&gchandle_foreach_get_target) = dlsym(imagehandle, "il2cpp_gchandle_foreach_get_target");
     logger.info("Loaded: il2cpp_gchandle_foreach_get_target");
     *(void**)(&object_header_size) = dlsym(imagehandle, "il2cpp_object_header_size");
     logger.info("Loaded: il2cpp_object_header_size");
     *(void**)(&array_object_header_size) = dlsym(imagehandle, "il2cpp_array_object_header_size");
     logger.info("Loaded: il2cpp_array_object_header_size");
     *(void**)(&offset_of_array_length_in_array_object_header) = dlsym(imagehandle, "il2cpp_offset_of_array_length_in_array_object_header");
     logger.info("Loaded: il2cpp_offset_of_array_length_in_array_object_header");
     *(void**)(&offset_of_array_bounds_in_array_object_header) = dlsym(imagehandle, "il2cpp_offset_of_array_bounds_in_array_object_header");
     logger.info("Loaded: il2cpp_offset_of_array_bounds_in_array_object_header");
     *(void**)(&allocation_granularity) = dlsym(imagehandle, "il2cpp_allocation_granularity");
     logger.info("Loaded: il2cpp_allocation_granularity");
     #endif
     *(void**)(&unity_liveness_calculation_begin) = dlsym(imagehandle, "il2cpp_unity_liveness_calculation_begin");
     logger.info("Loaded: il2cpp_unity_liveness_calculation_begin");
     *(void**)(&unity_liveness_calculation_end) = dlsym(imagehandle, "il2cpp_unity_liveness_calculation_end");
     logger.info("Loaded: il2cpp_unity_liveness_calculation_end");
     *(void**)(&unity_liveness_calculation_from_root) = dlsym(imagehandle, "il2cpp_unity_liveness_calculation_from_root");
     logger.info("Loaded: il2cpp_unity_liveness_calculation_from_root");
     *(void**)(&unity_liveness_calculation_from_statics) = dlsym(imagehandle, "il2cpp_unity_liveness_calculation_from_statics");
     logger.info("Loaded: il2cpp_unity_liveness_calculation_from_statics");
     *(void**)(&method_get_return_type) = dlsym(imagehandle, "il2cpp_method_get_return_type");
     logger.info("Loaded: il2cpp_method_get_return_type");
     *(void**)(&method_get_declaring_type) = dlsym(imagehandle, "il2cpp_method_get_declaring_type");
     logger.info("Loaded: il2cpp_method_get_declaring_type");
     *(void**)(&method_get_name) = dlsym(imagehandle, "il2cpp_method_get_name");
     logger.info("Loaded: il2cpp_method_get_name");
     *(void**)(&method_get_from_reflection) = dlsym(imagehandle, "il2cpp_method_get_from_reflection");
     logger.info("Loaded: il2cpp_method_get_from_reflection");
     *(void**)(&method_get_object) = dlsym(imagehandle, "il2cpp_method_get_object");
     logger.info("Loaded: il2cpp_method_get_object");
     *(void**)(&method_is_generic) = dlsym(imagehandle, "il2cpp_method_is_generic");
     logger.info("Loaded: il2cpp_method_is_generic");
     *(void**)(&method_is_inflated) = dlsym(imagehandle, "il2cpp_method_is_inflated");
     logger.info("Loaded: il2cpp_method_is_inflated");
     *(void**)(&method_is_instance) = dlsym(imagehandle, "il2cpp_method_is_instance");
     logger.info("Loaded: il2cpp_method_is_instance");
     *(void**)(&method_get_param_count) = dlsym(imagehandle, "il2cpp_method_get_param_count");
     logger.info("Loaded: il2cpp_method_get_param_count");
     *(void**)(&method_get_param) = dlsym(imagehandle, "il2cpp_method_get_param");
     logger.info("Loaded: il2cpp_method_get_param");
     *(void**)(&method_get_class) = dlsym(imagehandle, "il2cpp_method_get_class");
     logger.info("Loaded: il2cpp_method_get_class");
     *(void**)(&method_has_attribute) = dlsym(imagehandle, "il2cpp_method_has_attribute");
     logger.info("Loaded: il2cpp_method_has_attribute");
     *(void**)(&method_get_flags) = dlsym(imagehandle, "il2cpp_method_get_flags");
     logger.info("Loaded: il2cpp_method_get_flags");
     *(void**)(&method_get_token) = dlsym(imagehandle, "il2cpp_method_get_token");
     logger.info("Loaded: il2cpp_method_get_token");
     *(void**)(&method_get_param_name) = dlsym(imagehandle, "il2cpp_method_get_param_name");
     logger.info("Loaded: il2cpp_method_get_param_name");
     *(void**)(&profiler_install) = dlsym(imagehandle, "il2cpp_profiler_install");
     logger.info("Loaded: il2cpp_profiler_install");
     *(void**)(&profiler_set_events) = dlsym(imagehandle, "il2cpp_profiler_set_events");
     logger.info("Loaded: il2cpp_profiler_set_events");
     *(void**)(&profiler_install_enter_leave) = dlsym(imagehandle, "il2cpp_profiler_install_enter_leave");
     logger.info("Loaded: il2cpp_profiler_install_enter_leave");
     *(void**)(&profiler_install_allocation) = dlsym(imagehandle, "il2cpp_profiler_install_allocation");
     logger.info("Loaded: il2cpp_profiler_install_allocation");
     *(void**)(&profiler_install_gc) = dlsym(imagehandle, "il2cpp_profiler_install_gc");
     logger.info("Loaded: il2cpp_profiler_install_gc");
     *(void**)(&profiler_install_fileio) = dlsym(imagehandle, "il2cpp_profiler_install_fileio");
     logger.info("Loaded: il2cpp_profiler_install_fileio");
     *(void**)(&profiler_install_thread) = dlsym(imagehandle, "il2cpp_profiler_install_thread");
     logger.info("Loaded: il2cpp_profiler_install_thread");
     *(void**)(&property_get_flags) = dlsym(imagehandle, "il2cpp_property_get_flags");
     logger.info("Loaded: il2cpp_property_get_flags");
     *(void**)(&property_get_get_method) = dlsym(imagehandle, "il2cpp_property_get_get_method");
     logger.info("Loaded: il2cpp_property_get_get_method");
     *(void**)(&property_get_set_method) = dlsym(imagehandle, "il2cpp_property_get_set_method");
     logger.info("Loaded: il2cpp_property_get_set_method");
     *(void**)(&property_get_name) = dlsym(imagehandle, "il2cpp_property_get_name");
     logger.info("Loaded: il2cpp_property_get_name");
     *(void**)(&property_get_parent) = dlsym(imagehandle, "il2cpp_property_get_parent");
     logger.info("Loaded: il2cpp_property_get_parent");
     *(void**)(&object_get_class) = dlsym(imagehandle, "il2cpp_object_get_class");
     logger.info("Loaded: il2cpp_object_get_class");
     *(void**)(&object_get_size) = dlsym(imagehandle, "il2cpp_object_get_size");
     logger.info("Loaded: il2cpp_object_get_size");
     *(void**)(&object_get_virtual_method) = dlsym(imagehandle, "il2cpp_object_get_virtual_method");
     logger.info("Loaded: il2cpp_object_get_virtual_method");
     *(void**)(&object_new) = dlsym(imagehandle, "il2cpp_object_new");
     logger.info("Loaded: il2cpp_object_new");
     *(void**)(&object_unbox) = dlsym(imagehandle, "il2cpp_object_unbox");
     logger.info("Loaded: il2cpp_object_unbox");
     *(void**)(&value_box) = dlsym(imagehandle, "il2cpp_value_box");
     logger.info("Loaded: il2cpp_value_box");
     *(void**)(&monitor_enter) = dlsym(imagehandle, "il2cpp_monitor_enter");
     logger.info("Loaded: il2cpp_monitor_enter");
     *(void**)(&monitor_try_enter) = dlsym(imagehandle, "il2cpp_monitor_try_enter");
     logger.info("Loaded: il2cpp_monitor_try_enter");
     *(void**)(&monitor_exit) = dlsym(imagehandle, "il2cpp_monitor_exit");
     logger.info("Loaded: il2cpp_monitor_exit");
     *(void**)(&monitor_pulse) = dlsym(imagehandle, "il2cpp_monitor_pulse");
     logger.info("Loaded: il2cpp_monitor_pulse");
     *(void**)(&monitor_pulse_all) = dlsym(imagehandle, "il2cpp_monitor_pulse_all");
     logger.info("Loaded: il2cpp_monitor_pulse_all");
     *(void**)(&monitor_wait) = dlsym(imagehandle, "il2cpp_monitor_wait");
     logger.info("Loaded: il2cpp_monitor_wait");
     *(void**)(&monitor_try_wait) = dlsym(imagehandle, "il2cpp_monitor_try_wait");
     logger.info("Loaded: il2cpp_monitor_try_wait");
     *(void**)(&runtime_invoke) = dlsym(imagehandle, "il2cpp_runtime_invoke");
     logger.info("Loaded: il2cpp_runtime_invoke");
     *(void**)(&runtime_invoke_convert_args) = dlsym(imagehandle, "il2cpp_runtime_invoke_convert_args");
     logger.info("Loaded: il2cpp_runtime_invoke_convert_args");
     *(void**)(&runtime_class_init) = dlsym(imagehandle, "il2cpp_runtime_class_init");
     logger.info("Loaded: il2cpp_runtime_class_init");
     *(void**)(&runtime_object_init) = dlsym(imagehandle, "il2cpp_runtime_object_init");
     logger.info("Loaded: il2cpp_runtime_object_init");
     *(void**)(&runtime_object_init_exception) = dlsym(imagehandle, "il2cpp_runtime_object_init_exception");
     logger.info("Loaded: il2cpp_runtime_object_init_exception");
     *(void**)(&runtime_unhandled_exception_policy_set) = dlsym(imagehandle, "il2cpp_runtime_unhandled_exception_policy_set");
     logger.info("Loaded: il2cpp_runtime_unhandled_exception_policy_set");
     *(void**)(&string_length) = dlsym(imagehandle, "il2cpp_string_length");
     logger.info("Loaded: il2cpp_string_length");
     *(void**)(&string_chars) = dlsym(imagehandle, "il2cpp_string_chars");
     logger.info("Loaded: il2cpp_string_chars");
     *(void**)(&string_new) = dlsym(imagehandle, "il2cpp_string_new");
     logger.info("Loaded: il2cpp_string_new");
     *(void**)(&string_new_len) = dlsym(imagehandle, "il2cpp_string_new_len");
     logger.info("Loaded: il2cpp_string_new_len");
     *(void**)(&string_new_utf16) = dlsym(imagehandle, "il2cpp_string_new_utf16");
     logger.info("Loaded: il2cpp_string_new_utf16");
     *(void**)(&string_new_wrapper) = dlsym(imagehandle, "il2cpp_string_new_wrapper");
     logger.info("Loaded: il2cpp_string_new_wrapper");
     *(void**)(&string_intern) = dlsym(imagehandle, "il2cpp_string_intern");
     logger.info("Loaded: il2cpp_string_intern");
     *(void**)(&string_is_interned) = dlsym(imagehandle, "il2cpp_string_is_interned");
     logger.info("Loaded: il2cpp_string_is_interned");
     *(void**)(&thread_current) = dlsym(imagehandle, "il2cpp_thread_current");
     logger.info("Loaded: il2cpp_thread_current");
     *(void**)(&thread_attach) = dlsym(imagehandle, "il2cpp_thread_attach");
     logger.info("Loaded: il2cpp_thread_attach");
     *(void**)(&thread_detach) = dlsym(imagehandle, "il2cpp_thread_detach");
     logger.info("Loaded: il2cpp_thread_detach");
     *(void**)(&thread_get_all_attached_threads) = dlsym(imagehandle, "il2cpp_thread_get_all_attached_threads");
     logger.info("Loaded: il2cpp_thread_get_all_attached_threads");
     *(void**)(&is_vm_thread) = dlsym(imagehandle, "il2cpp_is_vm_thread");
     logger.info("Loaded: il2cpp_is_vm_thread");
     *(void**)(&current_thread_walk_frame_stack) = dlsym(imagehandle, "il2cpp_current_thread_walk_frame_stack");
     logger.info("Loaded: il2cpp_current_thread_walk_frame_stack");
     *(void**)(&thread_walk_frame_stack) = dlsym(imagehandle, "il2cpp_thread_walk_frame_stack");
     logger.info("Loaded: il2cpp_thread_walk_frame_stack");
     *(void**)(&current_thread_get_top_frame) = dlsym(imagehandle, "il2cpp_current_thread_get_top_frame");
     logger.info("Loaded: il2cpp_current_thread_get_top_frame");
     *(void**)(&thread_get_top_frame) = dlsym(imagehandle, "il2cpp_thread_get_top_frame");
     logger.info("Loaded: il2cpp_thread_get_top_frame");
     *(void**)(&current_thread_get_frame_at) = dlsym(imagehandle, "il2cpp_current_thread_get_frame_at");
     logger.info("Loaded: il2cpp_current_thread_get_frame_at");
     *(void**)(&thread_get_frame_at) = dlsym(imagehandle, "il2cpp_thread_get_frame_at");
     logger.info("Loaded: il2cpp_thread_get_frame_at");
     *(void**)(&current_thread_get_stack_depth) = dlsym(imagehandle, "il2cpp_current_thread_get_stack_depth");
     logger.info("Loaded: il2cpp_current_thread_get_stack_depth");
     *(void**)(&thread_get_stack_depth) = dlsym(imagehandle, "il2cpp_thread_get_stack_depth");
     logger.info("Loaded: il2cpp_thread_get_stack_depth");
     #ifdef UNITY_2019
     *(void**)(&override_stack_backtrace) = dlsym(imagehandle, "il2cpp_override_stack_backtrace");
     logger.info("Loaded: il2cpp_override_stack_backtrace");
     #endif
     *(void**)(&type_get_object) = dlsym(imagehandle, "il2cpp_type_get_object");
     logger.info("Loaded: il2cpp_type_get_object");
     *(void**)(&type_get_type) = dlsym(imagehandle, "il2cpp_type_get_type");
     logger.info("Loaded: il2cpp_type_get_type");
     *(void**)(&type_get_class_or_element_class) = dlsym(imagehandle, "il2cpp_type_get_class_or_element_class");
     logger.info("Loaded: il2cpp_type_get_class_or_element_class");
     *(void**)(&type_get_name) = dlsym(imagehandle, "il2cpp_type_get_name");
     logger.info("Loaded: il2cpp_type_get_name");
     *(void**)(&type_is_byref) = dlsym(imagehandle, "il2cpp_type_is_byref");
     logger.info("Loaded: il2cpp_type_is_byref");
     *(void**)(&type_get_attrs) = dlsym(imagehandle, "il2cpp_type_get_attrs");
     logger.info("Loaded: il2cpp_type_get_attrs");
     *(void**)(&type_equals) = dlsym(imagehandle, "il2cpp_type_equals");
     logger.info("Loaded: il2cpp_type_equals");
     *(void**)(&type_get_assembly_qualified_name) = dlsym(imagehandle, "il2cpp_type_get_assembly_qualified_name");
     logger.info("Loaded: il2cpp_type_get_assembly_qualified_name");
     #ifdef UNITY_2019
     *(void**)(&type_is_static) = dlsym(imagehandle, "il2cpp_type_is_static");
     logger.info("Loaded: il2cpp_type_is_static");
     *(void**)(&type_is_pointer_type) = dlsym(imagehandle, "il2cpp_type_is_pointer_type");
     logger.info("Loaded: il2cpp_type_is_pointer_type");
     #endif
     *(void**)(&image_get_assembly) = dlsym(imagehandle, "il2cpp_image_get_assembly");
     logger.info("Loaded: il2cpp_image_get_assembly");
     *(void**)(&image_get_name) = dlsym(imagehandle, "il2cpp_image_get_name");
     logger.info("Loaded: il2cpp_image_get_name");
     *(void**)(&image_get_filename) = dlsym(imagehandle, "il2cpp_image_get_filename");
     logger.info("Loaded: il2cpp_image_get_filename");
     *(void**)(&image_get_entry_point) = dlsym(imagehandle, "il2cpp_image_get_entry_point");
     logger.info("Loaded: il2cpp_image_get_entry_point");
     *(void**)(&image_get_class_count) = dlsym(imagehandle, "il2cpp_image_get_class_count");
     logger.info("Loaded: il2cpp_image_get_class_count");
     *(void**)(&image_get_class) = dlsym(imagehandle, "il2cpp_image_get_class");
     logger.info("Loaded: il2cpp_image_get_class");
     *(void**)(&capture_memory_snapshot) = dlsym(imagehandle, "il2cpp_capture_memory_snapshot");
     logger.info("Loaded: il2cpp_capture_memory_snapshot");
     *(void**)(&free_captured_memory_snapshot) = dlsym(imagehandle, "il2cpp_free_captured_memory_snapshot");
     logger.info("Loaded: il2cpp_free_captured_memory_snapshot");
     *(void**)(&set_find_plugin_callback) = dlsym(imagehandle, "il2cpp_set_find_plugin_callback");
     logger.info("Loaded: il2cpp_set_find_plugin_callback");
     *(void**)(&register_log_callback) = dlsym(imagehandle, "il2cpp_register_log_callback");
     logger.info("Loaded: il2cpp_register_log_callback");
     *(void**)(&debugger_set_agent_options) = dlsym(imagehandle, "il2cpp_debugger_set_agent_options");
     logger.info("Loaded: il2cpp_debugger_set_agent_options");
     *(void**)(&is_debugger_attached) = dlsym(imagehandle, "il2cpp_is_debugger_attached");
     logger.info("Loaded: il2cpp_is_debugger_attached");
     #ifdef UNITY_2019
     *(void**)(&register_debugger_agent_transport) = dlsym(imagehandle, "il2cpp_register_debugger_agent_transport");
     logger.info("Loaded: il2cpp_register_debugger_agent_transport");
     *(void**)(&debug_get_method_info) = dlsym(imagehandle, "il2cpp_debug_get_method_info");
     logger.info("Loaded: il2cpp_debug_get_method_info");
     #endif
     *(void**)(&unity_install_unitytls_interface) = dlsym(imagehandle, "il2cpp_unity_install_unitytls_interface");
     logger.info("Loaded: il2cpp_unity_install_unitytls_interface");
     *(void**)(&custom_attrs_from_class) = dlsym(imagehandle, "il2cpp_custom_attrs_from_class");
     logger.info("Loaded: il2cpp_custom_attrs_from_class");
     *(void**)(&custom_attrs_from_method) = dlsym(imagehandle, "il2cpp_custom_attrs_from_method");
     logger.info("Loaded: il2cpp_custom_attrs_from_method");
     *(void**)(&custom_attrs_get_attr) = dlsym(imagehandle, "il2cpp_custom_attrs_get_attr");
     logger.info("Loaded: il2cpp_custom_attrs_get_attr");
     *(void**)(&custom_attrs_has_attr) = dlsym(imagehandle, "il2cpp_custom_attrs_has_attr");
     logger.info("Loaded: il2cpp_custom_attrs_has_attr");
     *(void**)(&custom_attrs_construct) = dlsym(imagehandle, "il2cpp_custom_attrs_construct");
     logger.info("Loaded: il2cpp_custom_attrs_construct");
     *(void**)(&custom_attrs_free) = dlsym(imagehandle, "il2cpp_custom_attrs_free");
     logger.info("Loaded: il2cpp_custom_attrs_free");
     #ifdef UNITY_2019
     *(void**)(&class_set_userdata) = dlsym(imagehandle, "il2cpp_class_set_userdata");
     logger.info("Loaded: il2cpp_class_set_userdata");
     *(void**)(&class_get_userdata_offset) = dlsym(imagehandle, "il2cpp_class_get_userdata_offset");
     logger.info("Loaded: il2cpp_class_get_userdata_offset");
     #endif
     // MANUALLY DEFINED CONST DEFINITIONS
     *(void**)(&class_get_type_const) = dlsym(imagehandle, "il2cpp_class_get_type");
     logger.info("Loaded: il2cpp_class_get_type CONST VERSION!");
     *(void**)(&il2cpp_functions::class_get_name_const) = dlsym(imagehandle, "il2cpp_class_get_name");
     logger.info("Loaded: il2cpp_class_get_name CONST VERSION!");
     const char* err = dlerror();
     if (err) {
         logger.critical("A dlsym failed! dlerror: %s", err);
     }
     // XREF TRACES
     // Class::Init. 0x846A68 in 1.5, 0x9EC0A4 in 1.7.0, 0xA6D1B8 in 1.8.0b1
     Instruction ans((const int32_t*)HookTracker::GetOrig(array_new_specific));
     Instruction Array_NewSpecific(CRASH_UNLESS(ans.label));
     logger.debug("Array::NewSpecific offset: %lX", ((uintptr_t)Array_NewSpecific.addr) - getRealOffset(0));
     auto j2Cl_I = CRASH_UNLESS(Array_NewSpecific.findNthCall(1));  // also the 113th call in Runtime::Init
     Class_Init = (decltype(Class_Init))CRASH_UNLESS(j2Cl_I->label);
     logger.debug("Class::Init found? offset: %lX", ((uintptr_t)Class_Init) - getRealOffset(0));
     if (j2Cl_I != &Array_NewSpecific) delete j2Cl_I;
     usleep(1000);  // 0.001s
     // MetadataCache::GetTypeInfoFromTypeIndex. offset 0x84F764 in 1.5, 0x9F5250 in 1.7.0, 0xA7A79C in 1.8.0b1
     Instruction caha((const int32_t*)HookTracker::GetOrig(custom_attrs_has_attr));
     auto mchab = CRASH_UNLESS(caha.findNthDirectBranchWithoutLink(1));
     Instruction MetadataCache_HasAttribute(CRASH_UNLESS(mchab->label));
     if (mchab != &caha) delete mchab;
     auto j2MC_GTIFTI = CRASH_UNLESS(MetadataCache_HasAttribute.findNthCall(1));
     MetadataCache_GetTypeInfoFromTypeIndex = (decltype(MetadataCache_GetTypeInfoFromTypeIndex))CRASH_UNLESS(j2MC_GTIFTI->label);
     logger.debug("MetadataCache::GetTypeInfoFromTypeIndex found? offset: %lX",
         ((uintptr_t)MetadataCache_GetTypeInfoFromTypeIndex) - getRealOffset(0));
     if (j2MC_GTIFTI != &MetadataCache_HasAttribute) delete j2MC_GTIFTI;
     usleep(1000);  // 0.001s
     // MetadataCache::GetTypeInfoFromTypeDefinitionIndex. offset 0x84FBA4 in 1.5, 0x9F5690 in 1.7.0, 0xA75958 in 1.8.0b1
     Instruction tgcoec((const int32_t*)HookTracker::GetOrig(type_get_class_or_element_class));
     auto tgoecb = CRASH_UNLESS(tgcoec.findNthDirectBranchWithoutLink(1));
     Instruction Type_GetClassOrElementClass(CRASH_UNLESS(tgoecb->label));
     if (tgoecb != &tgcoec) delete tgoecb;
     auto j2MC_GTIFTDI = CRASH_UNLESS(Type_GetClassOrElementClass.findNthDirectBranchWithoutLink(5));
     MetadataCache_GetTypeInfoFromTypeDefinitionIndex =
         (decltype(MetadataCache_GetTypeInfoFromTypeDefinitionIndex))CRASH_UNLESS(j2MC_GTIFTDI->label);
     logger.debug("MetadataCache::GetTypeInfoFromTypeDefinitionIndex found? offset: %lX",
         ((uintptr_t)MetadataCache_GetTypeInfoFromTypeDefinitionIndex) - getRealOffset(0));
     if (j2MC_GTIFTDI != &Type_GetClassOrElementClass) delete j2MC_GTIFTDI;
     usleep(1000);  // 0.001s
     // Type::GetName. offset 0x8735DC in 1.5, 0xA1A458 in 1.7.0, 0xA7B634 in 1.8.0b1
     Instruction tanq((const int32_t*)HookTracker::GetOrig(type_get_assembly_qualified_name));
     auto j2T_GN = CRASH_UNLESS(tanq.findNthCall(1));
     _Type_GetName_ = (decltype(_Type_GetName_))CRASH_UNLESS(j2T_GN->label);
     logger.debug("Type::GetName found? offset: %lX", ((uintptr_t)_Type_GetName_) - getRealOffset(0));
     if (j2T_GN != &tanq) delete j2T_GN;
     usleep(1000);  // 0.001s
     // GenericClass::GetClass. offset 0x88DF64 in 1.5, 0xA34F20 in 1.7.0, 0xA6E4EC in 1.8.0b1
     Instruction cfit((const int32_t*)HookTracker::GetOrig(class_from_il2cpp_type));
     auto b = CRASH_UNLESS(cfit.findNthDirectBranchWithoutLink(1));
     Class_FromIl2CppType = (decltype(Class_FromIl2CppType))CRASH_UNLESS(b->label);
     if (b != &cfit) delete b;
     auto caseStart = CRASH_UNLESS(EvalSwitch(Class_FromIl2CppType, 1, 1, IL2CPP_TYPE_GENERICINST));
     auto j2GC_GC = CRASH_UNLESS(caseStart->findNthDirectBranchWithoutLink(1));
     delete caseStart;
     logger.debug("j2GC_GC: %s", j2GC_GC->toString().c_str());
     GenericClass_GetClass = (decltype(GenericClass_GetClass))CRASH_UNLESS(j2GC_GC->label);
     logger.debug("GenericClass::GetClass found? offset: %lX", ((uintptr_t)GenericClass_GetClass) - getRealOffset(0));
     if (j2GC_GC != caseStart) delete j2GC_GC;
     usleep(1000);  // 0.001s
     // Class::GetPtrClass.
     auto ptrCase = CRASH_UNLESS(EvalSwitch(Class_FromIl2CppType, 1, 1, IL2CPP_TYPE_PTR));
     auto j2C_GPC = CRASH_UNLESS(ptrCase->findNthDirectBranchWithoutLink(1));
     delete ptrCase;
     logger.debug("j2C_GPC: %s", j2C_GPC->toString().c_str());
     Class_GetPtrClass = (decltype(Class_GetPtrClass))CRASH_UNLESS(j2C_GPC->label);
     logger.debug("Class::GetPtrClass(Il2CppClass*) found? offset: %lX", ((uintptr_t)Class_GetPtrClass) - getRealOffset(0));
     if (j2C_GPC != ptrCase) delete j2C_GPC;
     usleep(1000);  // 0.001s
     // Assembly::GetAllAssemblies
     Instruction dga((const int32_t*)HookTracker::GetOrig(domain_get_assemblies));
     auto* j2A_GAA = CRASH_UNLESS(dga.findNthCall(1));
     Assembly_GetAllAssemblies = (decltype(Assembly_GetAllAssemblies))CRASH_UNLESS(j2A_GAA->label);
     logger.debug("Assembly::GetAllAssemblies found? offset: %lX", ((uintptr_t)Assembly_GetAllAssemblies) - getRealOffset(0));
     if (j2A_GAA != &dga) delete j2A_GAA;
     usleep(1000);  // 0.001s
     CRASH_UNLESS(shutdown);
     // GC_free
     Instruction sd((const int32_t*)HookTracker::GetOrig(shutdown));
     auto sdb = CRASH_UNLESS(sd.findNthDirectBranchWithoutLink(1));
     auto* Runtime_Shutdown = CRASH_UNLESS(sdb->label);
     if (sdb != &sd) delete sdb;
     if (find_GC_free(Runtime_Shutdown)) {
         logger.debug("gc::GarbageCollector::FreeFixed found? offset: %lX", ((uintptr_t)GC_free) - getRealOffset(0));
         usleep(1000);  // 0.001s
     }
     // GarbageCollector::SetWriteBarrier(void*)
     if (find_GC_SetWriteBarrier((const int32_t*)HookTracker::GetOrig(gc_wbarrier_set_field))) {
         logger.debug("GarbageCollector::SetWriteBarrier found? offset: %lX", ((uintptr_t)GarbageCollector_SetWriteBarrier) - getRealOffset(0));
         usleep(1000);  // 0.001s
     }
     // GarbageCollector::AllocateFixed(size_t, void*)
     Instruction localDomainGet((const int32_t*)HookTracker::GetOrig(domain_get));
     auto* inst = CRASH_UNLESS(localDomainGet.findNthDirectBranchWithoutLink(1));
     if (find_GC_AllocFixed(inst)) {
         logger.debug("GarbageCollector::AllocateFixed found? offset: %lX", ((uintptr_t)GarbageCollector_AllocateFixed) - getRealOffset(0));
         usleep(1000);  // 0.001s
     }
     if (inst != &localDomainGet) delete inst;
     // il2cpp_defaults
     Instruction iu16((const int32_t*)HookTracker::GetOrig(init_utf16));
     auto j2R_I = CRASH_UNLESS(iu16.findNthCall(3));
     Instruction Runtime_Init(CRASH_UNLESS(j2R_I->label));
     if (j2R_I != &iu16) delete j2R_I;
     // alternatively, could just get the 1st ADRP in Runtime::Init with dest reg x20 (or the 9th ADRP)
     // We DO need to skip at least one ret, though.
     auto ldr = CRASH_UNLESS(Runtime_Init.findNth(6, std::mem_fn(&Instruction::isLoad), 1));  // the load for the malloc that precedes our adrp
     il2cpp_functions::defaults = (decltype(il2cpp_functions::defaults))ExtractAddress(ldr->addr, 1, 1);
     logger.debug("il2cpp_defaults found? offset: %lX", ((uintptr_t)defaults) - getRealOffset(0));
     if (ldr != &Runtime_Init) delete ldr;
     usleep(1000);  // 0.001s
     // FIELDS
     // Extract locations of s_GlobalMetadataHeader, s_Il2CppMetadataRegistration, & s_GlobalMetadata
     // TODO: refactor to reduce instruction re-parsing?
     il2cpp_functions::s_GlobalMetadataHeaderPtr = (decltype(il2cpp_functions::s_GlobalMetadataHeaderPtr))CRASH_UNLESS(
         ExtractAddress(il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex, 3, 1));
     usleep(1000);  // 0.001s
     il2cpp_functions::s_Il2CppMetadataRegistrationPtr = (decltype(il2cpp_functions::s_Il2CppMetadataRegistrationPtr))CRASH_UNLESS(
         ExtractAddress(il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex, 4, 1));
     usleep(1000);  // 0.001s
     il2cpp_functions::s_GlobalMetadataPtr = (decltype(il2cpp_functions::s_GlobalMetadataPtr))CRASH_UNLESS(
         ExtractAddress(il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex, 5, 1));
     usleep(1000);  // 0.001s
     logger.debug("All global constants found!");
     // NOTE: Runtime.Shutdown is NOT CALLED even for exceptions!
     // There is practically no use in hooking this becuase of that.
     // Runtime.Shutdown (for file loggers)
     // if (Runtime_Shutdown) {
     //     logger.info("hook installing to: %p (offset %lX)", Runtime_Shutdown, ((uintptr_t)Runtime_Shutdown) - getRealOffset(0));
     //     INSTALL_HOOK_DIRECT(shutdown_hook, Runtime_Shutdown);
     // } else {
     //     logger.critical("Failed to parse il2cpp_shutdown's implementation address! Could not install shutdown hook for closing file logs.");
     // }
     dlclose(imagehandle);
     initialized = true;
     logger.info("il2cpp_functions: Init: Successfully loaded all il2cpp functions!");
     usleep(100);  // 0.0001s
 }
References _Type_GetName_, add_internal_call, Instruction::addr, alloc, array_class_get, array_element_size, array_get_byte_length, array_length, array_new, array_new_full, array_new_specific, assembly_get_image, Assembly_GetAllAssemblies, bounded_array_class_get, capture_memory_snapshot, class_array_element_size, class_enum_basetype, class_from_il2cpp_type, class_from_name, class_from_system_type, class_from_type, Class_FromIl2CppType, class_get_assemblyname, class_get_bitmap, class_get_bitmap_size, class_get_declaring_type, class_get_element_class, class_get_events, class_get_field_from_name, class_get_fields, class_get_flags, class_get_image, class_get_interfaces, class_get_method_from_name, class_get_methods, class_get_name, class_get_name_const, class_get_namespace, class_get_nested_types, class_get_parent, class_get_properties, class_get_property_from_name, class_get_rank, class_get_type, class_get_type_const, class_get_type_token, Class_GetPtrClass, class_has_attribute, class_has_parent, class_has_references, Class_Init, class_instance_size, class_is_abstract, class_is_assignable_from, class_is_blittable, class_is_enum, class_is_generic, class_is_inflated, class_is_interface, class_is_subclass_of, class_is_valuetype, class_num_fields, class_value_size, current_thread_get_frame_at, current_thread_get_stack_depth, current_thread_get_top_frame, current_thread_walk_frame_stack, custom_attrs_construct, custom_attrs_free, custom_attrs_from_class, custom_attrs_from_method, custom_attrs_get_attr, custom_attrs_has_attr, debugger_set_agent_options, defaults, domain_assembly_open, domain_get, domain_get_assemblies, EvalSwitch(), exception_from_name_msg, ExtractAddress(), field_get_flags, field_get_name, field_get_offset, field_get_parent, field_get_type, field_get_value, field_get_value_object, field_has_attribute, field_set_value, field_set_value_object, field_static_get_value, field_static_set_value, find_GC_AllocFixed(), find_GC_free(), find_GC_SetWriteBarrier(), Instruction::findNth(), Instruction::findNthCall(), Instruction::findNthDirectBranchWithoutLink(), format_exception, format_stack_trace, free, free_captured_memory_snapshot, GarbageCollector_AllocateFixed, GarbageCollector_SetWriteBarrier, gc_collect, gc_collect_a_little, gc_disable, gc_enable, GC_free, gc_get_heap_size, gc_get_used_size, gc_is_disabled, gc_wbarrier_set_field, gchandle_free, gchandle_get_target, gchandle_new, gchandle_new_weakref, GenericClass_GetClass, get_corlib, get_exception_argument_null, getFuncLogger(), Modloader::getLibIl2CppPath(), HookTracker::GetOrig(), getRealOffset(), image_get_assembly, image_get_class, image_get_class_count, image_get_entry_point, image_get_filename, image_get_name, LoggerContextObject::info(), init, init_utf16, initialized, is_debugger_attached, is_vm_thread, Instruction::isLoad(), Instruction::label, MetadataCache_GetTypeInfoFromTypeDefinitionIndex, MetadataCache_GetTypeInfoFromTypeIndex, method_get_class, method_get_declaring_type, method_get_flags, method_get_from_reflection, method_get_name, method_get_object, method_get_param, method_get_param_count, method_get_param_name, method_get_return_type, method_get_token, method_has_attribute, method_is_generic, method_is_inflated, method_is_instance, monitor_enter, monitor_exit, monitor_pulse, monitor_pulse_all, monitor_try_enter, monitor_try_wait, monitor_wait, object_get_class, object_get_size, object_get_virtual_method, object_new, object_unbox, profiler_install, profiler_install_allocation, profiler_install_enter_leave, profiler_install_fileio, profiler_install_gc, profiler_install_thread, profiler_set_events, property_get_flags, property_get_get_method, property_get_name, property_get_parent, property_get_set_method, register_log_callback, resolve_icall, runtime_class_init, runtime_invoke, runtime_invoke_convert_args, runtime_object_init, runtime_object_init_exception, runtime_unhandled_exception_policy_set, s_GlobalMetadataHeaderPtr, s_GlobalMetadataPtr, s_Il2CppMetadataRegistrationPtr, set_commandline_arguments, set_commandline_arguments_utf16, set_config, set_config_dir, set_config_utf16, set_data_dir, set_find_plugin_callback, set_memory_callbacks, set_temp_dir, shutdown, stats_dump_to_file, stats_get_value, string_chars, string_intern, string_is_interned, string_length, string_new, string_new_len, string_new_utf16, string_new_wrapper, thread_attach, thread_current, thread_detach, thread_get_all_attached_threads, thread_get_frame_at, thread_get_stack_depth, thread_get_top_frame, thread_walk_frame_stack, type_equals, type_get_assembly_qualified_name, type_get_attrs, type_get_class_or_element_class, type_get_name, type_get_object, type_get_type, type_is_byref, unhandled_exception, unity_install_unitytls_interface, unity_liveness_calculation_begin, unity_liveness_calculation_end, unity_liveness_calculation_from_root, unity_liveness_calculation_from_statics, value_box, and LoggerContextObject::WithContext().
Referenced by il2cpp_utils::__AllocateUnsafe(), il2cpp_utils::AddNestedTypesToNametoClassHashTable(), il2cpp_utils::AddTypeToNametoClassHashTable(), il2cpp_utils::AssertMatch(), il2cpp_utils::BuildGenericsMap(), il2cpp_utils::ClassStandardName(), il2cpp_utils::ClassVecToTypes(), il2cpp_utils::createcsstr(), il2cpp_utils::ExceptionToString(), il2cpp_utils::ExtractIndependentType(), il2cpp_utils::ExtractValue(), il2cpp_utils::FindField(), il2cpp_utils::FindMethod(), il2cpp_utils::FindMethodUnsafe(), il2cpp_utils::FindProperty(), il2cpp_utils::FromIl2CppObject(), il2cpp_utils::GenericClassStandardName(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T *, typename std::enable_if_t< has_get< il2cpp_no_arg_class< T > > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T, typename std::enable_if_t< std::is_base_of_v< NestedType, T > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< S< TArgs... > * >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< Il2CppType * >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T * >::get(), il2cpp_utils::GetClassFromName(), il2cpp_utils::GetFieldValue(), il2cpp_utils::GetPropertyValue(), il2cpp_utils::GetSystemType(), il2cpp_utils::IsConvertible(), il2cpp_utils::LogClass(), il2cpp_utils::LogClasses(), il2cpp_utils::LogField(), il2cpp_utils::LogFields(), il2cpp_utils::LogMethod(), il2cpp_utils::LogMethods(), il2cpp_utils::LogProperties(), il2cpp_utils::LogProperty(), il2cpp_utils::MakeDelegate(), il2cpp_utils::MakeGeneric(), il2cpp_utils::MakeGenericMethod(), il2cpp_utils::MakeGenericType(), il2cpp_utils::MakeRef(), il2cpp_utils::New(), Array< T >::New(), SafePtr< T >::SafePointerWrapper::New(), il2cpp_utils::newcsstr(), Array< T >::NewLength(), il2cpp_utils::NewUnsafe(), il2cpp_utils::ParameterMatch(), il2cpp_utils::RunMethod(), il2cpp_utils::RuntimeInvoke(), il2cpp_utils::SetFieldValue(), il2cpp_utils::SetPropertyValue(), il2cpp_utils::ToIl2CppObject(), il2cpp_utils::TypeGetSimpleName(), il2cpp_utils::TypesFrom(), il2cpp_utils::UnRef(), il2cpp_utils::vectorToArray(), and SafePtr< T >::~SafePtr().
MetadataCache_GetExportedTypeFromIndex()
TypeDefinitionIndex il2cpp_functions::MetadataCache_GetExportedTypeFromIndex (TypeDefinitionIndex index) static
Definition at line 341 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     if (index == kTypeDefinitionIndexInvalid) return kTypeDefinitionIndexInvalid;
     IL2CPP_ASSERT(index >= 0 && static_cast<uint32_t>(index) < s_GlobalMetadataHeader->exportedTypeDefinitionsCount / sizeof(TypeDefinitionIndex));
     auto exportedTypes = (TypeDefinitionIndex*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->exportedTypeDefinitionsOffset);
     return *(exportedTypes + index);
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::LogClasses().
MetadataCache_GetGenericContainerFromIndex()
const Il2CppGenericContainer * il2cpp_functions::MetadataCache_GetGenericContainerFromIndex (GenericContainerIndex index) static
Definition at line 323 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     if (index == kGenericContainerIndexInvalid) return NULL;
     IL2CPP_ASSERT(index >= 0 && static_cast<uint32_t>(index) <= s_GlobalMetadataHeader->genericContainersCount / sizeof(Il2CppGenericContainer));
     const Il2CppGenericContainer* genericContainers = (const Il2CppGenericContainer*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->genericContainersOffset);
     return genericContainers + index;
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::LogClass().
MetadataCache_GetGenericParameterFromIndex()
const Il2CppGenericParameter * il2cpp_functions::MetadataCache_GetGenericParameterFromIndex (GenericParameterIndex index) static
Definition at line 332 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     if (index == kGenericParameterIndexInvalid) return NULL;
     IL2CPP_ASSERT(index >= 0 && static_cast<uint32_t>(index) <= s_GlobalMetadataHeader->genericParametersCount / sizeof(Il2CppGenericParameter));
     const Il2CppGenericParameter* genericParameters = (const Il2CppGenericParameter*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->genericParametersOffset);
     return genericParameters + index;
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::LogClass().
MetadataCache_GetIndexForTypeDefinition()
TypeDefinitionIndex il2cpp_functions::MetadataCache_GetIndexForTypeDefinition (const Il2CppClass * typeDefinition) static
Definition at line 358 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     IL2CPP_ASSERT(typeDefinition->typeDefinition);
     const Il2CppTypeDefinition* typeDefinitions = (const Il2CppTypeDefinition*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->typeDefinitionsOffset);
     IL2CPP_ASSERT(typeDefinition->typeDefinition >= typeDefinitions && typeDefinition->typeDefinition < typeDefinitions + s_GlobalMetadataHeader->typeDefinitionsCount);
     ptrdiff_t index = typeDefinition->typeDefinition - typeDefinitions;
     IL2CPP_ASSERT(index <= std::numeric_limits<TypeDefinitionIndex>::max());
     return static_cast<TypeDefinitionIndex>(index);
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::AddNestedTypesToNametoClassHashTable(), and il2cpp_utils::LogClass().
MetadataCache_GetNestedTypeFromIndex()
Il2CppClass * il2cpp_functions::MetadataCache_GetNestedTypeFromIndex (NestedTypeIndex index) static
Definition at line 350 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     IL2CPP_ASSERT(index >= 0 && static_cast<uint32_t>(index) <= s_GlobalMetadataHeader->nestedTypesCount / sizeof(TypeDefinitionIndex));
     auto nestedTypeIndices = (const TypeDefinitionIndex*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->nestedTypesOffset);
     return il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex(nestedTypeIndices[index]);
 }
References CheckS_GlobalMetadata(), MetadataCache_GetTypeInfoFromTypeDefinitionIndex, s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::AddNestedTypesToNametoClassHashTable().
MetadataCache_GetStringFromIndex()
const char * il2cpp_functions::MetadataCache_GetStringFromIndex (StringIndex index) static
Definition at line 316 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     IL2CPP_ASSERT(index <= s_GlobalMetadataHeader->stringCount);
     const char* strings = ((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->stringOffset) + index;
     return strings;
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::AddNestedTypesToNametoClassHashTable(), il2cpp_utils::AddTypeToNametoClassHashTable(), and il2cpp_utils::LogClass().
MetadataCache_GetTypeDefinitionFromIndex()
const Il2CppTypeDefinition * il2cpp_functions::MetadataCache_GetTypeDefinitionFromIndex (TypeDefinitionIndex index) static
Definition at line 307 of file il2cpp-functions.cpp.
{
     CheckS_GlobalMetadata();
     if (index == kTypeDefinitionIndexInvalid) return NULL;
     IL2CPP_ASSERT(index >= 0 && static_cast<uint32_t>(index) < s_GlobalMetadataHeader->typeDefinitionsCount / sizeof(Il2CppTypeDefinition));
     auto typeDefinitions = (const Il2CppTypeDefinition*)((const char*)s_GlobalMetadata + s_GlobalMetadataHeader->typeDefinitionsOffset);
     return typeDefinitions + index;
 }
References CheckS_GlobalMetadata(), s_GlobalMetadata, and s_GlobalMetadataHeader.
Referenced by il2cpp_utils::AddTypeToNametoClassHashTable(), and il2cpp_utils::LogClass().
Type_GetName()
char * il2cpp_functions::Type_GetName (const Il2CppType * type, Il2CppTypeNameFormat format) static
Definition at line 370 of file il2cpp-functions.cpp.
{
     if (!il2cpp_functions::_Type_GetName_) return nullptr;
     // TODO debug the ref/lifetime weirdness with _Type_GetName_ to avoid the need for explicit allocation
     const auto str = il2cpp_functions::_Type_GetName_(type, format);
     char* buffer = static_cast<char*>(il2cpp_functions::alloc(str.length() + 1));
     memcpy(buffer, str.c_str(), str.length() + 1);
     return buffer;
 }
References _Type_GetName_, and alloc.
Referenced by il2cpp_utils::LogClass().
Field Documentation
_Type_GetName_
gnu_string(* il2cpp_functions::_Type_GetName_)(const Il2CppType *type, Il2CppTypeNameFormat format) static
Definition at line 368 of file il2cpp-functions.hpp.
Referenced by Init(), and Type_GetName().
add_internal_call
void(* il2cpp_functions::add_internal_call)(const char *name, Il2CppMethodPointer method) static
Definition at line 109 of file il2cpp-functions.hpp.
Referenced by Init().
alloc
void *(* il2cpp_functions::alloc)(size_t size) static
Definition at line 111 of file il2cpp-functions.hpp.
Referenced by Init(), and Type_GetName().
array_class_get
Il2CppClass *(* il2cpp_functions::array_class_get)(Il2CppClass *element_class, uint32_t rank) static
Definition at line 113 of file il2cpp-functions.hpp.
Referenced by Init().
array_element_size
int(* il2cpp_functions::array_element_size)(const Il2CppClass *array_class) static
Definition at line 120 of file il2cpp-functions.hpp.
Referenced by Init().
array_get_byte_length
uint32_t(* il2cpp_functions::array_get_byte_length)(Il2CppArray *array) static
Definition at line 115 of file il2cpp-functions.hpp.
Referenced by Init().
array_length
uint32_t(* il2cpp_functions::array_length)(Il2CppArray *array) static
Definition at line 114 of file il2cpp-functions.hpp.
Referenced by Init().
array_new
Il2CppArray *(* il2cpp_functions::array_new)(Il2CppClass *elementTypeInfo, il2cpp_array_size_t length) static
Definition at line 116 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::MakeGenericMethod(), Array< T >::New(), Array< T >::NewLength(), and il2cpp_utils::vectorToArray().
array_new_full
Il2CppArray *(* il2cpp_functions::array_new_full)(Il2CppClass *array_class, il2cpp_array_size_t *lengths, il2cpp_array_size_t *lower_bounds) static
Definition at line 118 of file il2cpp-functions.hpp.
Referenced by Init().
array_new_specific
Il2CppArray *(* il2cpp_functions::array_new_specific)(Il2CppClass *arrayTypeInfo, il2cpp_array_size_t length) static
Definition at line 117 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::MakeGeneric().
assembly_get_image
const Il2CppImage *(* il2cpp_functions::assembly_get_image)(const Il2CppAssembly *assembly) static
Definition at line 121 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetClassFromName(), Init(), and il2cpp_utils::LogClasses().
Assembly_GetAllAssemblies
AssemblyVector *(* il2cpp_functions::Assembly_GetAllAssemblies)() static
Definition at line 380 of file il2cpp-functions.hpp.
Referenced by Init().
bounded_array_class_get
Il2CppClass *(* il2cpp_functions::bounded_array_class_get)(Il2CppClass *element_class, uint32_t rank, bool bounded) static
Definition at line 119 of file il2cpp-functions.hpp.
Referenced by Init().
capture_memory_snapshot
Il2CppManagedMemorySnapshot *(* il2cpp_functions::capture_memory_snapshot)() static
Definition at line 333 of file il2cpp-functions.hpp.
Referenced by Init().
class_array_element_size
int(* il2cpp_functions::class_array_element_size)(const Il2CppClass *klass) static
Definition at line 159 of file il2cpp-functions.hpp.
Referenced by Init().
class_enum_basetype
const Il2CppType *(* il2cpp_functions::class_enum_basetype)(Il2CppClass *klass) static
Definition at line 125 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::IsConvertible().
class_from_il2cpp_type
Il2CppClass *(* il2cpp_functions::class_from_il2cpp_type)(const Il2CppType *type) static
Definition at line 131 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindMethod(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< Il2CppType * >::get(), il2cpp_utils::GetFieldClass(), il2cpp_utils::GetParamClass(), Init(), il2cpp_utils::IsConvertible(), il2cpp_utils::MakeDelegate(), il2cpp_utils::MakeRef(), il2cpp_utils::TypeGetSimpleName(), and il2cpp_utils::UnRef().
class_from_name
Il2CppClass *(* il2cpp_functions::class_from_name)(const Il2CppImage *image, const char *namespaze, const char *name) static
Definition at line 132 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetClassFromName(), and Init().
class_from_system_type
Il2CppClass *(* il2cpp_functions::class_from_system_type)(Il2CppReflectionType *type) static
Definition at line 133 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::MakeGeneric().
class_from_type
Il2CppClass *(* il2cpp_functions::class_from_type)(const Il2CppType *type) static
Definition at line 160 of file il2cpp-functions.hpp.
Referenced by Init().
Class_FromIl2CppType
Il2CppClass *(* il2cpp_functions::Class_FromIl2CppType)(Il2CppType *typ) static
Definition at line 377 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_assemblyname
const char *(* il2cpp_functions::class_get_assemblyname)(const Il2CppClass *klass) static
Definition at line 167 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_get_bitmap
void(* il2cpp_functions::class_get_bitmap)(Il2CppClass *klass, size_t *bitmap) static
Definition at line 174 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_bitmap_size
size_t(* il2cpp_functions::class_get_bitmap_size)(const Il2CppClass *klass) static
Definition at line 173 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_declaring_type
Il2CppClass *(* il2cpp_functions::class_get_declaring_type)(const Il2CppClass *klass) static
Definition at line 150 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ClassStandardName(), Init(), and il2cpp_utils::LogClass().
class_get_element_class
Il2CppClass *(* il2cpp_functions::class_get_element_class)(Il2CppClass *klass) static
Definition at line 134 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_get_events
const EventInfo *(* il2cpp_functions::class_get_events)(Il2CppClass *klass, void **iter) static
Definition at line 135 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_field_from_name
FieldInfo *(* il2cpp_functions::class_get_field_from_name)(Il2CppClass *klass, const char *name) static
Definition at line 141 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindField(), and Init().
class_get_fields
FieldInfo *(* il2cpp_functions::class_get_fields)(Il2CppClass *klass, void **iter) static
Definition at line 136 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogFields().
class_get_flags
int(* il2cpp_functions::class_get_flags)(const Il2CppClass *klass) static
Definition at line 156 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_get_image
const Il2CppImage *(* il2cpp_functions::class_get_image)(Il2CppClass *klass) static
Definition at line 166 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_interfaces
Il2CppClass *(* il2cpp_functions::class_get_interfaces)(Il2CppClass *klass, void **iter) static
Definition at line 138 of file il2cpp-functions.hpp.
Referenced by Init().
class_get_method_from_name
const MethodInfo *(* il2cpp_functions::class_get_method_from_name)(const Il2CppClass *klass, const char *name, int argsCount) static
Definition at line 143 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindMethodUnsafe(), and Init().
class_get_methods
const MethodInfo *(* il2cpp_functions::class_get_methods)(Il2CppClass *klass, void **iter) static
Definition at line 142 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindMethod(), Init(), and il2cpp_utils::LogClass().
class_get_name
const char *(* il2cpp_functions::class_get_name)(const Il2CppClass *klass) static
Definition at line 144 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ClassStandardName(), and Init().
class_get_name_const
const char *(* il2cpp_functions::class_get_name_const)(const Il2CppClass *klass) static
Definition at line 357 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::MakeGeneric(), and il2cpp_utils::MakeGenericMethod().
class_get_namespace
const char *(* il2cpp_functions::class_get_namespace)(const Il2CppClass *klass) static
Definition at line 148 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ClassStandardName(), and Init().
class_get_nested_types
Il2CppClass *(* il2cpp_functions::class_get_nested_types)(Il2CppClass *klass, void **iter) static
Definition at line 137 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::AddNestedTypesToNametoClassHashTable(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T, typename std::enable_if_t< std::is_base_of_v< NestedType, T > > >::get(), and Init().
class_get_parent
Il2CppClass *(* il2cpp_functions::class_get_parent)(Il2CppClass *klass) static
Definition at line 149 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_get_properties
const PropertyInfo *(* il2cpp_functions::class_get_properties)(Il2CppClass *klass, void **iter) static
Definition at line 139 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogProperties().
class_get_property_from_name
const PropertyInfo *(* il2cpp_functions::class_get_property_from_name)(Il2CppClass *klass, const char *name) static
Definition at line 140 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindProperty(), and Init().
class_get_rank
int(* il2cpp_functions::class_get_rank)(const Il2CppClass *klass) static
Definition at line 168 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_get_type
const Il2CppType *(* il2cpp_functions::class_get_type)(Il2CppClass *klass) static
Definition at line 161 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ExtractIndependentType(), Init(), il2cpp_utils::LogClass(), il2cpp_utils::TypesFrom(), and il2cpp_utils::UnRef().
class_get_type_const
const Il2CppType *(* il2cpp_functions::class_get_type_const)(const Il2CppClass *klass) static
Definition at line 356 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ClassVecToTypes(), il2cpp_utils::GetSystemType(), and Init().
class_get_type_token
uint32_t(* il2cpp_functions::class_get_type_token)(Il2CppClass *klass) static
Definition at line 162 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
Class_GetPtrClass
Il2CppClass *(* il2cpp_functions::Class_GetPtrClass)(Il2CppClass *elementClass) static
Definition at line 378 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T *, typename std::enable_if_t< has_get< il2cpp_no_arg_class< T > > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< S< TArgs... > * >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T * >::get(), and Init().
class_has_attribute
bool(* il2cpp_functions::class_has_attribute)(Il2CppClass *klass, Il2CppClass *attr_class) static
Definition at line 163 of file il2cpp-functions.hpp.
Referenced by Init().
class_has_parent
bool(* il2cpp_functions::class_has_parent)(Il2CppClass *klass, Il2CppClass *klassc) static
Definition at line 130 of file il2cpp-functions.hpp.
Referenced by Init().
class_has_references
bool(* il2cpp_functions::class_has_references)(Il2CppClass *klass) static
Definition at line 164 of file il2cpp-functions.hpp.
Referenced by Init().
Class_Init
bool(* il2cpp_functions::Class_Init)(Il2CppClass *klass) static
Definition at line 360 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::LogClass(), il2cpp_utils::LogFields(), il2cpp_utils::LogMethods(), and il2cpp_utils::LogProperties().
class_instance_size
int32_t(* il2cpp_functions::class_instance_size)(Il2CppClass *klass) static
Definition at line 151 of file il2cpp-functions.hpp.
Referenced by Init().
class_is_abstract
bool(* il2cpp_functions::class_is_abstract)(const Il2CppClass *klass) static
Definition at line 157 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
class_is_assignable_from
bool(* il2cpp_functions::class_is_assignable_from)(Il2CppClass *klass, Il2CppClass *oklass) static
Definition at line 128 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FindMethod(), Init(), and il2cpp_utils::IsConvertible().
class_is_blittable
bool(* il2cpp_functions::class_is_blittable)(const Il2CppClass *klass) static
Definition at line 155 of file il2cpp-functions.hpp.
Referenced by Init().
class_is_enum
bool(* il2cpp_functions::class_is_enum)(const Il2CppClass *klass) static
Definition at line 165 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::IsConvertible().
class_is_generic
bool(* il2cpp_functions::class_is_generic)(const Il2CppClass *klass) static
Definition at line 126 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ClassStandardName(), Init(), and il2cpp_utils::LogClass().
class_is_inflated
bool(* il2cpp_functions::class_is_inflated)(const Il2CppClass *klass) static
Definition at line 127 of file il2cpp-functions.hpp.
Referenced by Init().
class_is_interface
bool(* il2cpp_functions::class_is_interface)(const Il2CppClass *klass) static
Definition at line 158 of file il2cpp-functions.hpp.
Referenced by Init().
class_is_subclass_of
bool(* il2cpp_functions::class_is_subclass_of)(Il2CppClass *klass, Il2CppClass *klassc, bool check_interfaces) static
Definition at line 129 of file il2cpp-functions.hpp.
Referenced by Init().
class_is_valuetype
bool(* il2cpp_functions::class_is_valuetype)(const Il2CppClass *klass) static
Definition at line 153 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::FromIl2CppObject(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T *, typename std::enable_if_t< has_get< il2cpp_no_arg_class< T > > > >::get(), and Init().
class_num_fields
size_t(* il2cpp_functions::class_num_fields)(const Il2CppClass *enumKlass) static
Definition at line 152 of file il2cpp-functions.hpp.
Referenced by Init().
class_value_size
int32_t(* il2cpp_functions::class_value_size)(Il2CppClass *klass, uint32_t *align) static
Definition at line 154 of file il2cpp-functions.hpp.
Referenced by Init().
current_thread_get_frame_at
bool(* il2cpp_functions::current_thread_get_frame_at)(int32_t offset, Il2CppStackFrameInfo *frame) static
Definition at line 308 of file il2cpp-functions.hpp.
Referenced by Init().
current_thread_get_stack_depth
int32_t(* il2cpp_functions::current_thread_get_stack_depth)() static
Definition at line 310 of file il2cpp-functions.hpp.
Referenced by Init().
current_thread_get_top_frame
bool(* il2cpp_functions::current_thread_get_top_frame)(Il2CppStackFrameInfo *frame) static
Definition at line 306 of file il2cpp-functions.hpp.
Referenced by Init().
current_thread_walk_frame_stack
void(* il2cpp_functions::current_thread_walk_frame_stack)(Il2CppFrameWalkFunc func, void *user_data) static
Definition at line 304 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_construct
Il2CppArray *(* il2cpp_functions::custom_attrs_construct)(Il2CppCustomAttrInfo *cinfo) static
Definition at line 348 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_free
void(* il2cpp_functions::custom_attrs_free)(Il2CppCustomAttrInfo *ainfo) static
Definition at line 349 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_from_class
Il2CppCustomAttrInfo *(* il2cpp_functions::custom_attrs_from_class)(Il2CppClass *klass) static
Definition at line 344 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_from_method
Il2CppCustomAttrInfo *(* il2cpp_functions::custom_attrs_from_method)(const MethodInfo *method) static
Definition at line 345 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_get_attr
Il2CppObject *(* il2cpp_functions::custom_attrs_get_attr)(Il2CppCustomAttrInfo *ainfo, Il2CppClass *attr_klass) static
Definition at line 346 of file il2cpp-functions.hpp.
Referenced by Init().
custom_attrs_has_attr
bool(* il2cpp_functions::custom_attrs_has_attr)(Il2CppCustomAttrInfo *ainfo, Il2CppClass *attr_klass) static
Definition at line 347 of file il2cpp-functions.hpp.
Referenced by Init().
debugger_set_agent_options
void(* il2cpp_functions::debugger_set_agent_options)(const char *options) static
Definition at line 337 of file il2cpp-functions.hpp.
Referenced by Init().
defaults
const Il2CppDefaults * il2cpp_functions::defaults static
Definition at line 388 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::MakeGeneric(), il2cpp_utils::MakeGenericMethod(), il2cpp_utils::MakeGenericType(), il2cpp_utils::newcsstr(), and il2cpp_utils::TypeGetSimpleName().
domain_assembly_open
const Il2CppAssembly *(* il2cpp_functions::domain_assembly_open)(Il2CppDomain *domain, const char *name) static
Definition at line 178 of file il2cpp-functions.hpp.
Referenced by Init().
domain_get
Il2CppDomain *(* il2cpp_functions::domain_get)() static
Definition at line 177 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetClassFromName(), Init(), and il2cpp_utils::LogClasses().
domain_get_assemblies
const Il2CppAssembly **(* il2cpp_functions::domain_get_assemblies)(const Il2CppDomain *domain, size_t *size) static
Definition at line 179 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetClassFromName(), Init(), and il2cpp_utils::LogClasses().
exception_from_name_msg
Il2CppException *(* il2cpp_functions::exception_from_name_msg)(const Il2CppImage *image, const char *name_space, const char *name, const char *msg) static
Definition at line 183 of file il2cpp-functions.hpp.
Referenced by Init().
field_get_flags
int(* il2cpp_functions::field_get_flags)(FieldInfo *field) static
Definition at line 188 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogField().
field_get_name
const char *(* il2cpp_functions::field_get_name)(FieldInfo *field) static
Definition at line 189 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogField().
field_get_offset
size_t(* il2cpp_functions::field_get_offset)(FieldInfo *field) static
Definition at line 191 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogField().
field_get_parent
Il2CppClass *(* il2cpp_functions::field_get_parent)(FieldInfo *field) static
Definition at line 190 of file il2cpp-functions.hpp.
Referenced by Init().
field_get_type
const Il2CppType *(* il2cpp_functions::field_get_type)(FieldInfo *field) static
Definition at line 192 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetFieldClass(), Init(), il2cpp_utils::LogField(), and il2cpp_utils::MakeDelegate().
field_get_value
void(* il2cpp_functions::field_get_value)(Il2CppObject *obj, FieldInfo *field, void *value) static
Definition at line 193 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetFieldValue(), and Init().
field_get_value_object
Il2CppObject *(* il2cpp_functions::field_get_value_object)(FieldInfo *field, Il2CppObject *obj) static
Definition at line 194 of file il2cpp-functions.hpp.
Referenced by Init().
field_has_attribute
bool(* il2cpp_functions::field_has_attribute)(FieldInfo *field, Il2CppClass *attr_class) static
Definition at line 195 of file il2cpp-functions.hpp.
Referenced by Init().
field_set_value
void(* il2cpp_functions::field_set_value)(Il2CppObject *obj, FieldInfo *field, void *value) static
Definition at line 196 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::SetFieldValue().
field_set_value_object
void(* il2cpp_functions::field_set_value_object)(Il2CppObject *instance, FieldInfo *field, Il2CppObject *value) static
Definition at line 199 of file il2cpp-functions.hpp.
Referenced by Init().
field_static_get_value
void(* il2cpp_functions::field_static_get_value)(FieldInfo *field, void *value) static
Definition at line 197 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetFieldValue(), and Init().
field_static_set_value
void(* il2cpp_functions::field_static_set_value)(FieldInfo *field, void *value) static
Definition at line 198 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::SetFieldValue().
format_exception
void(* il2cpp_functions::format_exception)(const Il2CppException *ex, char *message, int message_size) static
Definition at line 185 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ExceptionToString(), and Init().
format_stack_trace
void(* il2cpp_functions::format_stack_trace)(const Il2CppException *ex, char *output, int output_size) static
Definition at line 186 of file il2cpp-functions.hpp.
Referenced by Init().
free
void(* il2cpp_functions::free)(void *ptr) static
Definition at line 112 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
free_captured_memory_snapshot
void(* il2cpp_functions::free_captured_memory_snapshot)(Il2CppManagedMemorySnapshot *snapshot) static
Definition at line 334 of file il2cpp-functions.hpp.
Referenced by Init().
GarbageCollector_AllocateFixed
void *(* il2cpp_functions::GarbageCollector_AllocateFixed)(size_t sz, void *desc) static
Definition at line 375 of file il2cpp-functions.hpp.
Referenced by find_GC_AllocFixed(), gc_alloc_specific(), gc_free_specific(), Init(), SafePtr< T >::SafePointerWrapper::New(), and trace_GC_AllocFixed().
GarbageCollector_SetWriteBarrier
void(* il2cpp_functions::GarbageCollector_SetWriteBarrier)(void **ptr) static
Definition at line 374 of file il2cpp-functions.hpp.
Referenced by find_GC_SetWriteBarrier(), and Init().
gc_collect
void(* il2cpp_functions::gc_collect)(int maxGenerations) static
Definition at line 203 of file il2cpp-functions.hpp.
Referenced by Init().
gc_collect_a_little
int32_t(* il2cpp_functions::gc_collect_a_little)() static
Definition at line 204 of file il2cpp-functions.hpp.
Referenced by Init().
gc_disable
void(* il2cpp_functions::gc_disable)() static
Definition at line 205 of file il2cpp-functions.hpp.
Referenced by Init().
gc_enable
void(* il2cpp_functions::gc_enable)() static
Definition at line 206 of file il2cpp-functions.hpp.
Referenced by Init().
GC_free
void(* il2cpp_functions::GC_free)(void *addr) static
Definition at line 372 of file il2cpp-functions.hpp.
Referenced by find_GC_free(), gc_alloc_specific(), gc_free_specific(), Init(), and SafePtr< T >::~SafePtr().
gc_get_heap_size
int64_t(* il2cpp_functions::gc_get_heap_size)() static
Definition at line 214 of file il2cpp-functions.hpp.
Referenced by Init().
gc_get_used_size
int64_t(* il2cpp_functions::gc_get_used_size)() static
Definition at line 213 of file il2cpp-functions.hpp.
Referenced by Init().
gc_is_disabled
bool(* il2cpp_functions::gc_is_disabled)() static
Definition at line 207 of file il2cpp-functions.hpp.
Referenced by Init().
gc_wbarrier_set_field
void(* il2cpp_functions::gc_wbarrier_set_field)(Il2CppObject *obj, void **targetAddress, void *object) static
Definition at line 215 of file il2cpp-functions.hpp.
Referenced by Init().
gchandle_free
void(* il2cpp_functions::gchandle_free)(uint32_t gchandle) static
Definition at line 227 of file il2cpp-functions.hpp.
Referenced by Init().
gchandle_get_target
Il2CppObject *(* il2cpp_functions::gchandle_get_target)(uint32_t gchandle) static
Definition at line 226 of file il2cpp-functions.hpp.
Referenced by Init().
gchandle_new
uint32_t(* il2cpp_functions::gchandle_new)(Il2CppObject *obj, bool pinned) static
Definition at line 224 of file il2cpp-functions.hpp.
Referenced by Init().
gchandle_new_weakref
uint32_t(* il2cpp_functions::gchandle_new_weakref)(Il2CppObject *obj, bool track_resurrection) static
Definition at line 225 of file il2cpp-functions.hpp.
Referenced by Init().
GenericClass_GetClass
Il2CppClass *(* il2cpp_functions::GenericClass_GetClass)(Il2CppGenericClass *gclass) static
Definition at line 379 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GenericClassStandardName(), and Init().
get_corlib
const Il2CppImage *(* il2cpp_functions::get_corlib)() static
Definition at line 108 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::AddTypeToNametoClassHashTable(), and Init().
get_exception_argument_null
Il2CppException *(* il2cpp_functions::get_exception_argument_null)(const char *arg) static
Definition at line 184 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_assembly
const Il2CppAssembly *(* il2cpp_functions::image_get_assembly)(const Il2CppImage *image) static
Definition at line 327 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_class
const Il2CppClass *(* il2cpp_functions::image_get_class)(const Il2CppImage *image, size_t index) static
Definition at line 332 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_class_count
size_t(* il2cpp_functions::image_get_class_count)(const Il2CppImage *image) static
Definition at line 331 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_entry_point
const MethodInfo *(* il2cpp_functions::image_get_entry_point)(const Il2CppImage *image) static
Definition at line 330 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_filename
const char *(* il2cpp_functions::image_get_filename)(const Il2CppImage *image) static
Definition at line 329 of file il2cpp-functions.hpp.
Referenced by Init().
image_get_name
const char *(* il2cpp_functions::image_get_name)(const Il2CppImage *image) static
Definition at line 328 of file il2cpp-functions.hpp.
Referenced by Init().
init
void(* il2cpp_functions::init)(const char *domain_name) static
Definition at line 96 of file il2cpp-functions.hpp.
Referenced by Init().
init_utf16
void(* il2cpp_functions::init_utf16)(const Il2CppChar *domain_name) static
Definition at line 97 of file il2cpp-functions.hpp.
Referenced by Init().
initialized
bool il2cpp_functions::initialized static
Definition at line 416 of file il2cpp-functions.hpp.
Referenced by Init().
is_debugger_attached
bool(* il2cpp_functions::is_debugger_attached)() static
Definition at line 338 of file il2cpp-functions.hpp.
Referenced by Init().
is_vm_thread
bool(* il2cpp_functions::is_vm_thread)(Il2CppThread *thread) static
Definition at line 303 of file il2cpp-functions.hpp.
Referenced by Init().
MetadataCache_GetTypeInfoFromTypeDefinitionIndex
Il2CppClass *(* il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex)(TypeDefinitionIndex index) static
Definition at line 362 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::BuildGenericsMap(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T, typename std::enable_if_t< std::is_base_of_v< NestedType, T > > >::get(), Init(), il2cpp_utils::LogClasses(), and MetadataCache_GetNestedTypeFromIndex().
MetadataCache_GetTypeInfoFromTypeIndex
Il2CppClass *(* il2cpp_functions::MetadataCache_GetTypeInfoFromTypeIndex)(TypeIndex index) static
Definition at line 363 of file il2cpp-functions.hpp.
Referenced by Init().
method_get_class
Il2CppClass *(* il2cpp_functions::method_get_class)(const MethodInfo *method) static
Definition at line 250 of file il2cpp-functions.hpp.
Referenced by Init().
method_get_declaring_type
Il2CppClass *(* il2cpp_functions::method_get_declaring_type)(const MethodInfo *method) static
Definition at line 241 of file il2cpp-functions.hpp.
Referenced by Init().
method_get_flags
uint32_t(* il2cpp_functions::method_get_flags)(const MethodInfo *method, uint32_t *iflags) static
Definition at line 252 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogMethod().
method_get_from_reflection
const MethodInfo *(* il2cpp_functions::method_get_from_reflection)(const Il2CppReflectionMethod *method) static
Definition at line 243 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::MakeGenericMethod().
method_get_name
const char *(* il2cpp_functions::method_get_name)(const MethodInfo *method) static
Definition at line 242 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::LogMethod(), il2cpp_utils::LogProperty(), and il2cpp_utils::RunMethod().
method_get_object
Il2CppReflectionMethod *(* il2cpp_functions::method_get_object)(const MethodInfo *method, Il2CppClass *refclass) static
Definition at line 244 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::MakeGenericMethod().
method_get_param
const Il2CppType *(* il2cpp_functions::method_get_param)(const MethodInfo *method, uint32_t index) static
Definition at line 249 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetParamClass(), Init(), il2cpp_utils::LogMethod(), il2cpp_utils::LogProperty(), and il2cpp_utils::MakeDelegate().
method_get_param_count
uint32_t(* il2cpp_functions::method_get_param_count)(const MethodInfo *method) static
Definition at line 248 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogMethod().
method_get_param_name
const char *(* il2cpp_functions::method_get_param_name)(const MethodInfo *method, uint32_t index) static
Definition at line 254 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogMethod().
method_get_return_type
const Il2CppType *(* il2cpp_functions::method_get_return_type)(const MethodInfo *method) static
Definition at line 240 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::LogMethod(), and il2cpp_utils::LogProperty().
method_get_token
uint32_t(* il2cpp_functions::method_get_token)(const MethodInfo *method) static
Definition at line 253 of file il2cpp-functions.hpp.
Referenced by Init().
method_has_attribute
bool(* il2cpp_functions::method_has_attribute)(const MethodInfo *method, Il2CppClass *attr_class) static
Definition at line 251 of file il2cpp-functions.hpp.
Referenced by Init().
method_is_generic
bool(* il2cpp_functions::method_is_generic)(const MethodInfo *method) static
Definition at line 245 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::MakeGenericMethod().
method_is_inflated
bool(* il2cpp_functions::method_is_inflated)(const MethodInfo *method) static
Definition at line 246 of file il2cpp-functions.hpp.
Referenced by Init().
method_is_instance
bool(* il2cpp_functions::method_is_instance)(const MethodInfo *method) static
Definition at line 247 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_enter
void(* il2cpp_functions::monitor_enter)(Il2CppObject *obj) static
Definition at line 278 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_exit
void(* il2cpp_functions::monitor_exit)(Il2CppObject *obj) static
Definition at line 280 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_pulse
void(* il2cpp_functions::monitor_pulse)(Il2CppObject *obj) static
Definition at line 281 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_pulse_all
void(* il2cpp_functions::monitor_pulse_all)(Il2CppObject *obj) static
Definition at line 282 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_try_enter
bool(* il2cpp_functions::monitor_try_enter)(Il2CppObject *obj, uint32_t timeout) static
Definition at line 279 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_try_wait
bool(* il2cpp_functions::monitor_try_wait)(Il2CppObject *obj, uint32_t timeout) static
Definition at line 284 of file il2cpp-functions.hpp.
Referenced by Init().
monitor_wait
void(* il2cpp_functions::monitor_wait)(Il2CppObject *obj) static
Definition at line 283 of file il2cpp-functions.hpp.
Referenced by Init().
object_get_class
Il2CppClass *(* il2cpp_functions::object_get_class)(Il2CppObject *obj) static
Definition at line 270 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ExtractValue(), il2cpp_utils::FindMethodUnsafe(), il2cpp_utils::FromIl2CppObject(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T * >::get(), and Init().
object_get_size
uint32_t(* il2cpp_functions::object_get_size)(Il2CppObject *obj) static
Definition at line 271 of file il2cpp-functions.hpp.
Referenced by Init().
object_get_virtual_method
const MethodInfo *(* il2cpp_functions::object_get_virtual_method)(Il2CppObject *obj, const MethodInfo *method) static
Definition at line 272 of file il2cpp-functions.hpp.
Referenced by Init().
object_new
Il2CppObject *(* il2cpp_functions::object_new)(const Il2CppClass *klass) static
Definition at line 273 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::__AllocateUnsafe(), Init(), il2cpp_utils::New(), and il2cpp_utils::NewUnsafe().
object_unbox
void *(* il2cpp_functions::object_unbox)(Il2CppObject *obj) static
Definition at line 275 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::ExtractValue(), il2cpp_utils::FromIl2CppObject(), and Init().
profiler_install
void(* il2cpp_functions::profiler_install)(Il2CppProfiler *prof, Il2CppProfileFunc shutdown_callback) static
Definition at line 257 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_install_allocation
void(* il2cpp_functions::profiler_install_allocation)(Il2CppProfileAllocFunc callback) static
Definition at line 260 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_install_enter_leave
void(* il2cpp_functions::profiler_install_enter_leave)(Il2CppProfileMethodFunc enter, Il2CppProfileMethodFunc fleave) static
Definition at line 259 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_install_fileio
void(* il2cpp_functions::profiler_install_fileio)(Il2CppProfileFileIOFunc callback) static
Definition at line 262 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_install_gc
void(* il2cpp_functions::profiler_install_gc)(Il2CppProfileGCFunc callback, Il2CppProfileGCResizeFunc heap_resize_callback) static
Definition at line 261 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_install_thread
void(* il2cpp_functions::profiler_install_thread)(Il2CppProfileThreadFunc start, Il2CppProfileThreadFunc end) static
Definition at line 263 of file il2cpp-functions.hpp.
Referenced by Init().
profiler_set_events
void(* il2cpp_functions::profiler_set_events)(Il2CppProfileFlags events) static
Definition at line 258 of file il2cpp-functions.hpp.
Referenced by Init().
property_get_flags
uint32_t(* il2cpp_functions::property_get_flags)(const PropertyInfo *prop) static
Definition at line 265 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogProperty().
property_get_get_method
const MethodInfo *(* il2cpp_functions::property_get_get_method)(const PropertyInfo *prop) static
Definition at line 266 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetPropertyValue(), Init(), and il2cpp_utils::LogProperty().
property_get_name
const char *(* il2cpp_functions::property_get_name)(const PropertyInfo *prop) static
Definition at line 268 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogProperty().
property_get_parent
Il2CppClass *(* il2cpp_functions::property_get_parent)(const PropertyInfo *prop) static
Definition at line 269 of file il2cpp-functions.hpp.
Referenced by Init().
property_get_set_method
const MethodInfo *(* il2cpp_functions::property_get_set_method)(const PropertyInfo *prop) static
Definition at line 267 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::LogProperty(), and il2cpp_utils::SetPropertyValue().
register_log_callback
void(* il2cpp_functions::register_log_callback)(Il2CppLogCallback method) static
Definition at line 336 of file il2cpp-functions.hpp.
Referenced by Init().
resolve_icall
Il2CppMethodPointer(* il2cpp_functions::resolve_icall)(const char *name) static
Definition at line 110 of file il2cpp-functions.hpp.
Referenced by Init().
runtime_class_init
void(* il2cpp_functions::runtime_class_init)(Il2CppClass *klass) static
Definition at line 287 of file il2cpp-functions.hpp.
Referenced by Init().
runtime_invoke
Il2CppObject *(* il2cpp_functions::runtime_invoke)(const MethodInfo *method, void *obj, void **params, Il2CppException **exc) static
Definition at line 285 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::MakeGenericType(), il2cpp_utils::RunMethod(), and il2cpp_utils::RuntimeInvoke().
runtime_invoke_convert_args
Il2CppObject *(* il2cpp_functions::runtime_invoke_convert_args)(const MethodInfo *method, void *obj, Il2CppObject **params, int paramCount, Il2CppException **exc) static
Definition at line 286 of file il2cpp-functions.hpp.
Referenced by Init().
runtime_object_init
void(* il2cpp_functions::runtime_object_init)(Il2CppObject *obj) static
Definition at line 288 of file il2cpp-functions.hpp.
Referenced by Init().
runtime_object_init_exception
void(* il2cpp_functions::runtime_object_init_exception)(Il2CppObject *obj, Il2CppException **exc) static
Definition at line 289 of file il2cpp-functions.hpp.
Referenced by Init().
runtime_unhandled_exception_policy_set
void(* il2cpp_functions::runtime_unhandled_exception_policy_set)(Il2CppRuntimeUnhandledExceptionPolicy value) static
Definition at line 290 of file il2cpp-functions.hpp.
Referenced by Init().
s_GlobalMetadata
std::remove_pointer_t< decltype(il2cpp_functions::s_GlobalMetadataPtr)> il2cpp_functions::s_GlobalMetadata static
Definition at line 386 of file il2cpp-functions.hpp.
Referenced by CheckS_GlobalMetadata(), MetadataCache_GetExportedTypeFromIndex(), MetadataCache_GetGenericContainerFromIndex(), MetadataCache_GetGenericParameterFromIndex(), MetadataCache_GetIndexForTypeDefinition(), MetadataCache_GetNestedTypeFromIndex(), MetadataCache_GetStringFromIndex(), and MetadataCache_GetTypeDefinitionFromIndex().
s_GlobalMetadataHeader
std::remove_pointer_t< decltype(il2cpp_functions::s_GlobalMetadataHeaderPtr)> il2cpp_functions::s_GlobalMetadataHeader static
Definition at line 387 of file il2cpp-functions.hpp.
Referenced by CheckS_GlobalMetadata(), MetadataCache_GetExportedTypeFromIndex(), MetadataCache_GetGenericContainerFromIndex(), MetadataCache_GetGenericParameterFromIndex(), MetadataCache_GetIndexForTypeDefinition(), MetadataCache_GetNestedTypeFromIndex(), MetadataCache_GetStringFromIndex(), and MetadataCache_GetTypeDefinitionFromIndex().
s_GlobalMetadataHeaderPtr
const Il2CppGlobalMetadataHeader ** il2cpp_functions::s_GlobalMetadataHeaderPtr static
Definition at line 384 of file il2cpp-functions.hpp.
Referenced by CheckS_GlobalMetadata(), and Init().
s_GlobalMetadataPtr
const void ** il2cpp_functions::s_GlobalMetadataPtr static
Definition at line 383 of file il2cpp-functions.hpp.
Referenced by CheckS_GlobalMetadata(), and Init().
s_Il2CppMetadataRegistrationPtr
const Il2CppMetadataRegistration ** il2cpp_functions::s_Il2CppMetadataRegistrationPtr static
Definition at line 382 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::BuildGenericsMap(), and Init().
set_commandline_arguments
void(* il2cpp_functions::set_commandline_arguments)(int argc, const char *const argv[], const char *basedir) static
Definition at line 103 of file il2cpp-functions.hpp.
Referenced by Init().
set_commandline_arguments_utf16
void(* il2cpp_functions::set_commandline_arguments_utf16)(int argc, const Il2CppChar *const argv[], const char *basedir) static
Definition at line 104 of file il2cpp-functions.hpp.
Referenced by Init().
set_config
void(* il2cpp_functions::set_config)(const char *executablePath) static
Definition at line 106 of file il2cpp-functions.hpp.
Referenced by Init().
set_config_dir
void(* il2cpp_functions::set_config_dir)(const char *config_path) static
Definition at line 100 of file il2cpp-functions.hpp.
Referenced by Init().
set_config_utf16
void(* il2cpp_functions::set_config_utf16)(const Il2CppChar *executablePath) static
Definition at line 105 of file il2cpp-functions.hpp.
Referenced by Init().
set_data_dir
void(* il2cpp_functions::set_data_dir)(const char *data_path) static
Definition at line 101 of file il2cpp-functions.hpp.
Referenced by Init().
set_find_plugin_callback
void(* il2cpp_functions::set_find_plugin_callback)(Il2CppSetFindPlugInCallback method) static
Definition at line 335 of file il2cpp-functions.hpp.
Referenced by Init().
set_memory_callbacks
void(* il2cpp_functions::set_memory_callbacks)(Il2CppMemoryCallbacks *callbacks) static
Definition at line 107 of file il2cpp-functions.hpp.
Referenced by Init().
set_temp_dir
void(* il2cpp_functions::set_temp_dir)(const char *temp_path) static
Definition at line 102 of file il2cpp-functions.hpp.
Referenced by Init().
shutdown
void(* il2cpp_functions::shutdown)() static
Definition at line 99 of file il2cpp-functions.hpp.
Referenced by Init().
stats_dump_to_file
bool(* il2cpp_functions::stats_dump_to_file)(const char *path) static
Definition at line 175 of file il2cpp-functions.hpp.
Referenced by Init().
stats_get_value
uint64_t(* il2cpp_functions::stats_get_value)(Il2CppStat stat) static
Definition at line 176 of file il2cpp-functions.hpp.
Referenced by Init().
string_chars
Il2CppChar *(* il2cpp_functions::string_chars)(Il2CppString *str) static
Definition at line 292 of file il2cpp-functions.hpp.
Referenced by Init().
string_intern
Il2CppString *(* il2cpp_functions::string_intern)(Il2CppString *str) static
Definition at line 297 of file il2cpp-functions.hpp.
Referenced by Init().
string_is_interned
Il2CppString *(* il2cpp_functions::string_is_interned)(Il2CppString *str) static
Definition at line 298 of file il2cpp-functions.hpp.
Referenced by Init().
string_length
int32_t(* il2cpp_functions::string_length)(Il2CppString *str) static
Definition at line 291 of file il2cpp-functions.hpp.
Referenced by Init().
string_new
Il2CppString *(* il2cpp_functions::string_new)(const char *str) static
Definition at line 293 of file il2cpp-functions.hpp.
Referenced by Init().
string_new_len
Il2CppString *(* il2cpp_functions::string_new_len)(const char *str, uint32_t length) static
Definition at line 294 of file il2cpp-functions.hpp.
Referenced by Init().
string_new_utf16
Il2CppString *(* il2cpp_functions::string_new_utf16)(const Il2CppChar *text, int32_t len) static
Definition at line 295 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::newcsstr().
string_new_wrapper
Il2CppString *(* il2cpp_functions::string_new_wrapper)(const char *str) static
Definition at line 296 of file il2cpp-functions.hpp.
Referenced by Init().
thread_attach
Il2CppThread *(* il2cpp_functions::thread_attach)(Il2CppDomain *domain) static
Definition at line 300 of file il2cpp-functions.hpp.
Referenced by Init().
thread_current
Il2CppThread *(* il2cpp_functions::thread_current)() static
Definition at line 299 of file il2cpp-functions.hpp.
Referenced by Init().
thread_detach
void(* il2cpp_functions::thread_detach)(Il2CppThread *thread) static
Definition at line 301 of file il2cpp-functions.hpp.
Referenced by Init().
thread_get_all_attached_threads
Il2CppThread **(* il2cpp_functions::thread_get_all_attached_threads)(size_t *size) static
Definition at line 302 of file il2cpp-functions.hpp.
Referenced by Init().
thread_get_frame_at
bool(* il2cpp_functions::thread_get_frame_at)(Il2CppThread *thread, int32_t offset, Il2CppStackFrameInfo *frame) static
Definition at line 309 of file il2cpp-functions.hpp.
Referenced by Init().
thread_get_stack_depth
int32_t(* il2cpp_functions::thread_get_stack_depth)(Il2CppThread *thread) static
Definition at line 311 of file il2cpp-functions.hpp.
Referenced by Init().
thread_get_top_frame
bool(* il2cpp_functions::thread_get_top_frame)(Il2CppThread *thread, Il2CppStackFrameInfo *frame) static
Definition at line 307 of file il2cpp-functions.hpp.
Referenced by Init().
thread_walk_frame_stack
void(* il2cpp_functions::thread_walk_frame_stack)(Il2CppThread *thread, Il2CppFrameWalkFunc func, void *user_data) static
Definition at line 305 of file il2cpp-functions.hpp.
Referenced by Init().
type_equals
bool(* il2cpp_functions::type_equals)(const Il2CppType *type, const Il2CppType *otherType) static
Definition at line 321 of file il2cpp-functions.hpp.
Referenced by Init().
type_get_assembly_qualified_name
char *(* il2cpp_functions::type_get_assembly_qualified_name)(const Il2CppType *type) static
Definition at line 322 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogClass().
type_get_attrs
uint32_t(* il2cpp_functions::type_get_attrs)(const Il2CppType *type) static
Definition at line 320 of file il2cpp-functions.hpp.
Referenced by Init().
type_get_class_or_element_class
Il2CppClass *(* il2cpp_functions::type_get_class_or_element_class)(const Il2CppType *type) static
Definition at line 317 of file il2cpp-functions.hpp.
Referenced by Init().
type_get_name
char *(* il2cpp_functions::type_get_name)(const Il2CppType *type) static
Definition at line 318 of file il2cpp-functions.hpp.
Referenced by Init(), il2cpp_utils::LogClass(), il2cpp_utils::MakeGeneric(), and il2cpp_utils::TypeGetSimpleName().
type_get_object
Il2CppObject *(* il2cpp_functions::type_get_object)(const Il2CppType *type) static
Definition at line 315 of file il2cpp-functions.hpp.
Referenced by il2cpp_utils::GetSystemType(), and Init().
type_get_type
int(* il2cpp_functions::type_get_type)(const Il2CppType *type) static
Definition at line 316 of file il2cpp-functions.hpp.
Referenced by Init().
type_is_byref
bool(* il2cpp_functions::type_is_byref)(const Il2CppType *type) static
Definition at line 319 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::LogMethod().
unhandled_exception
void(* il2cpp_functions::unhandled_exception)(Il2CppException *) static
Definition at line 187 of file il2cpp-functions.hpp.
Referenced by Init().
unity_install_unitytls_interface
void(* il2cpp_functions::unity_install_unitytls_interface)(const void *unitytlsInterfaceStruct) static
Definition at line 343 of file il2cpp-functions.hpp.
Referenced by Init().
unity_liveness_calculation_begin
void *(* il2cpp_functions::unity_liveness_calculation_begin)(Il2CppClass *filter, int max_object_count, il2cpp_register_object_callback callback, void *userdata, il2cpp_WorldChangedCallback onWorldStarted, il2cpp_WorldChangedCallback onWorldStopped) static
Definition at line 236 of file il2cpp-functions.hpp.
Referenced by Init().
unity_liveness_calculation_end
void(* il2cpp_functions::unity_liveness_calculation_end)(void *state) static
Definition at line 237 of file il2cpp-functions.hpp.
Referenced by Init().
unity_liveness_calculation_from_root
void(* il2cpp_functions::unity_liveness_calculation_from_root)(Il2CppObject *root, void *state) static
Definition at line 238 of file il2cpp-functions.hpp.
Referenced by Init().
unity_liveness_calculation_from_statics
void(* il2cpp_functions::unity_liveness_calculation_from_statics)(void *state) static
Definition at line 239 of file il2cpp-functions.hpp.
Referenced by Init().
value_box
Il2CppObject *(* il2cpp_functions::value_box)(Il2CppClass *klass, void *data) static
Definition at line 277 of file il2cpp-functions.hpp.
Referenced by Init(), and il2cpp_utils::ToIl2CppObject().
The documentation for this class was generated from the following files:
shared/utils/il2cpp-functions.hpp
src/utils/il2cpp-functions.cpp