BeatSaber-Hooks: rapidjson::internal::DecodedStream< SourceStream, Encoding > Class Template Reference
rapidjson::internal::DecodedStream< SourceStream, Encoding > Class Template Reference
#include <regex.h>
Public Member Functions
DecodedStream (SourceStream &ss)
unsigned Peek ()
unsigned Take ()
Private Member Functions
void Decode ()
Private Attributes
SourceStream & ss_
unsigned codepoint_
Detailed Description
template<typename SourceStream, typename Encoding>
class rapidjson::internal::DecodedStream< SourceStream, Encoding >
Definition at line 47 of file regex.h.
Constructor & Destructor Documentation
DecodedStream()
template<typename SourceStream , typename Encoding > rapidjson::internal::DecodedStream< SourceStream, Encoding >::DecodedStream (SourceStream & ss) inline
Definition at line 49 of file regex.h.
 : ss_(ss), codepoint_() { Decode(); }
Member Function Documentation
Decode()
template<typename SourceStream , typename Encoding > void rapidjson::internal::DecodedStream< SourceStream, Encoding >::Decode () inline private
Definition at line 59 of file regex.h.
                   {
         if (!Encoding::Decode(ss_, &codepoint_))
             codepoint_ = 0;
     }
Peek()
template<typename SourceStream , typename Encoding > unsigned rapidjson::internal::DecodedStream< SourceStream, Encoding >::Peek () inline
Definition at line 50 of file regex.h.
 { return codepoint_; }
Referenced by rapidjson::internal::GenericRegex< Encoding, Allocator >::Parse(), rapidjson::internal::GenericRegex< Encoding, Allocator >::ParseRange(), and rapidjson::internal::GenericRegex< Encoding, Allocator >::ParseUnsigned().
Take()
template<typename SourceStream , typename Encoding > unsigned rapidjson::internal::DecodedStream< SourceStream, Encoding >::Take () inline
Definition at line 51 of file regex.h.
                     {
         unsigned c = codepoint_;
         if (c) // No further decoding when '\0'
             Decode();
         return c;
     }
Referenced by rapidjson::internal::GenericRegex< Encoding, Allocator >::CharacterEscape(), rapidjson::internal::GenericRegex< Encoding, Allocator >::Parse(), rapidjson::internal::GenericRegex< Encoding, Allocator >::ParseRange(), rapidjson::internal::GenericRegex< Encoding, Allocator >::ParseUnsigned(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::SearchWithAnchoring().
Field Documentation
codepoint_
template<typename SourceStream , typename Encoding > unsigned rapidjson::internal::DecodedStream< SourceStream, Encoding >::codepoint_ private
Definition at line 65 of file regex.h.
ss_
template<typename SourceStream , typename Encoding > SourceStream& rapidjson::internal::DecodedStream< SourceStream, Encoding >::ss_ private
Definition at line 64 of file regex.h.
The documentation for this class was generated from the following file:
shared/rapidjson/include/rapidjson/internal/regex.h