BeatSaber-Hooks: Logger Struct Reference
Logger Struct Reference
A buffer for logger data. Used for logging to file in a buffered fashion. Each LoggerBuffer exists to wrap around a single logger instance. Every time log is called on the instance, this buffer is updated (assuming options.toFile is true for the instance) Each buffer contains multiple messages that need to be written out, stored as an std::list.
#include <logging.hpp>
Public Member Functions
Logger (const ModInfo info, LoggerOptions options_)
Logger (const ModInfo info)
~Logger ()=delete
void log (Logging::Level lvl, std::string str)
template<typename... TArgs>
void log (Logging::Level lvl, std::string_view fmt, TArgs... args)
template<typename... TArgs>
void critical (std::string_view fmt, TArgs... args)
template<typename... TArgs>
void error (std::string_view fmt, TArgs... args)
template<typename... TArgs>
void warning (std::string_view fmt, TArgs... args)
template<typename... TArgs>
void info (std::string_view fmt, TArgs... args)
template<typename... TArgs>
void debug (std::string_view fmt, TArgs... args)
void flush ()
Flushes the buffer for this logger instance.
void close ()
Closes the buffer for this logger instance, flushing as necessary. After this call, this logger will no longer log to a buffer, nor will it log to a file.
bool init ()
Initialize this logger. Deletes existing file logs. This happens on default when this instance is constructed. This should also be called anytime the options field is modified.
constexpr void disable ()
Call this to silence logs from this logger. Should improve performance slightly. Note that this call causes ALL calls to this particular logger to be silent, including from other mods. Should only be used in particular cases.
constexpr void enable ()
Call this to re-enable logs for this logger. Decreases performance slightly, but provides debug information. Note that this call causes ALL calls to this particular logger to be enabled again, including from other mods that want silence. Should only be used in particular cases.
const LoggerOptions getOptions () const
Returns the current options for this logger.
LoggerContextObject WithContext (std::string_view context)
Enters a logging context. Should be used for more specific logging information. Avoid entering contexts with names that contain % characters.
void DisableContext (std::string_view context)
Disable logging for any contexts that start with the provided string. This is thread independent, and will silence across all threads.
void EnableContext (std::string_view context)
Enables logging for the context. This function does nothing if DisableContext was not called with an exactly matching string before this call.
const std::unordered_set< std::string > GetDisabledContexts ()
Gets all disabled contexts on this instance.
Static Public Member Functions
static Logger & get ()
Returns the logger that is used within the utils library. This function should not be used outside of the main library.
static void closeAll ()
Close all open LoggerBuffer objects. Should only be called on a crash or exit of the game.
static void flushAll ()
Flush all open LoggerBuffer objects.
Private Member Functions
LoggerContextObject WithContext (LoggerContextObject *parent, std::string_view context)
Constructs a context with a parent. This is called by LoggerContextObject.WithContext.
void RecurseChangeContext (LoggerContextObject *ctx, std::string_view context, bool enable)
Recurses over all children contexts and disables/enables if they start with context.
Static Private Member Functions
static void emplace_safe (LoggerBuffer &buffer)
static void startConsumer ()
Private Attributes
friend Consumer
friend LoggerBuffer
friend LoggerContextObject
LoggerOptions options
The options associated with this logger.
std::unordered_set< std::string > disabledContexts
std::vector< LoggerContextObject * > contexts
All created contexts for this instance.
std::mutex contextMutex
The mutex for the contexts maps/sets.
std::string tag
const ModInfo modInfo
LoggerBuffer buffer
Static Private Attributes
static bool consumerStarted = false
static std::list< LoggerBuffer * > buffers
static std::mutex bufferMutex
Detailed Description
A buffer for logger data. Used for logging to file in a buffered fashion. Each LoggerBuffer exists to wrap around a single logger instance. Every time log is called on the instance, this buffer is updated (assuming options.toFile is true for the instance) Each buffer contains multiple messages that need to be written out, stored as an std::list.
Provides various options for loggers, including silencing them and logging to file.
Definition at line 88 of file logging.hpp.
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger (const ModInfo info, LoggerOptions options_) inline
Definition at line 93 of file logging.hpp.
                                                            : options(options_), tag("QuestHook[" + info.id + "|v" + info.version + "]"), modInfo(info), buffer(modInfo) {
             if (!init()) {
                 buffer.closed = true;
             }
             emplace_safe(buffer);
         }
References buffer, LoggerBuffer::closed, emplace_safe(), and init().
Referenced by get().
Logger() [2/2]
Logger::Logger (const ModInfo info) inline
Definition at line 99 of file logging.hpp.
                                    : options(LoggerOptions(false, false)), tag("QuestHook[" + info.id + "|v" + info.version + "]"), modInfo(info), buffer(modInfo) {
             if (!init()) {
                 buffer.closed = true;
             }
             emplace_safe(buffer);
         }
References buffer, LoggerBuffer::closed, emplace_safe(), and init().
~Logger()
Logger::~Logger () delete
Member Function Documentation
close()
void Logger::close ()
Closes the buffer for this logger instance, flushing as necessary. After this call, this logger will no longer log to a buffer, nor will it log to a file.
Definition at line 187 of file logging.cpp.
                    {
     Logger::bufferMutex.lock();
     buffer.flush();
     get_global().flush();
     buffer.closed = true;
     Logger::bufferMutex.unlock();
 }
References buffer, bufferMutex, LoggerBuffer::closed, LoggerBuffer::flush(), and get_global().
closeAll()
void Logger::closeAll () static
Close all open LoggerBuffer objects. Should only be called on a crash or exit of the game.
Definition at line 141 of file logging.cpp.
                       {
     __android_log_write(Logging::CRITICAL, Logger::get().tag.c_str(), "Closing all buffers!");
     Logger::bufferMutex.lock();
     for (auto* buffer : Logger::buffers) {
         buffer->flush();
         buffer->closed = true;
     }
     get_global().flush();
     get_global().closed = true;
     Logger::bufferMutex.unlock();
     __android_log_write(Logging::CRITICAL, Logger::get().tag.c_str(), "All buffers closed!");
 }
References buffer, bufferMutex, buffers, LoggerBuffer::closed, Logging::CRITICAL, LoggerBuffer::flush(), get(), get_global(), and tag.
Referenced by hook_shutdown_hook(), and safeAbort().
critical()
template<typename... TArgs> void Logger::critical (std::string_view fmt, TArgs... args) inline
Definition at line 115 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(Logging::CRITICAL, string_format(fmt, args...));
         }
References il2cpp_utils::args, Logging::CRITICAL, log(), options, LoggerOptions::silent, and string_format().
Referenced by LoggerContextObject::critical().
debug()
template<typename... TArgs> void Logger::debug (std::string_view fmt, TArgs... args) inline
Definition at line 143 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(Logging::DEBUG, string_format(fmt, args...));
         }
References il2cpp_utils::args, Logging::DEBUG, log(), options, LoggerOptions::silent, and string_format().
Referenced by LoggerContextObject::debug(), dump(), Instruction::findNth(), findUniquePattern(), Replicate(), and ROR().
disable()
constexpr void Logger::disable () inline constexpr
Call this to silence logs from this logger. Should improve performance slightly. Note that this call causes ALL calls to this particular logger to be silent, including from other mods. Should only be used in particular cases.
Definition at line 168 of file logging.hpp.
{
             options.silent = true;
         }
References options, and LoggerOptions::silent.
DisableContext()
void Logger::DisableContext (std::string_view context)
Disable logging for any contexts that start with the provided string. This is thread independent, and will silence across all threads.
Definition at line 257 of file logging.cpp.
{
     contextMutex.lock();
     disabledContexts.emplace(context.data());
     // We should also iterate over all disabledContexts and determine if any existing contexts need to be disabled.
     // Existing contexts could have parent contexts, though.
     for (auto* ctx : contexts) {
         // For each context, only check those without parents (top level, recurse down)
         if (ctx->parentContext == nullptr) {
             RecurseChangeContext(ctx, context, false);
         }
     }
     contextMutex.unlock();
 }
References contextMutex, contexts, disabledContexts, and RecurseChangeContext().
emplace_safe()
static void Logger::emplace_safe (LoggerBuffer & buffer) inline static private
Definition at line 220 of file logging.hpp.
{
             // Obtain lock
             std::scoped_lock<std::mutex> lock(bufferMutex);
             // Emplace, lock is released
             Logger::buffers.push_back(&buffer);
         }
References buffer, bufferMutex, and buffers.
Referenced by Logger().
enable()
constexpr void Logger::enable () inline constexpr
Call this to re-enable logs for this logger. Decreases performance slightly, but provides debug information. Note that this call causes ALL calls to this particular logger to be enabled again, including from other mods that want silence. Should only be used in particular cases.
Definition at line 174 of file logging.hpp.
{
             options.silent = false;
         }
References options, and LoggerOptions::silent.
Referenced by RecurseChangeContext().
EnableContext()
void Logger::EnableContext (std::string_view context)
Enables logging for the context. This function does nothing if DisableContext was not called with an exactly matching string before this call.
Definition at line 271 of file logging.cpp.
{
     contextMutex.lock();
     auto itr = disabledContexts.find(std::string(context));
     if (itr != disabledContexts.end()) {
         disabledContexts.erase(itr);
     }
     for (auto* ctx : contexts) {
         // For each context, only check those without parents (top level, recurse down)
         if (ctx->parentContext == nullptr) {
             RecurseChangeContext(ctx, context, true);
         }
     }
     contextMutex.unlock();
 }
References contextMutex, contexts, disabledContexts, and RecurseChangeContext().
error()
template<typename... TArgs> void Logger::error (std::string_view fmt, TArgs... args) inline
Definition at line 122 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(Logging::ERROR, string_format(fmt, args...));
         }
References il2cpp_utils::args, Logging::ERROR, log(), options, LoggerOptions::silent, and string_format().
Referenced by LoggerContextObject::error(), and Instruction::findNth().
flush()
void Logger::flush ()
Flushes the buffer for this logger instance.
Definition at line 178 of file logging.cpp.
                    {
     // Flush our buffer.
     // We do this by locking it and reading all of its messages to completion.
     Logger::bufferMutex.lock();
     buffer.flush();
     get_global().flush();
     Logger::bufferMutex.unlock();
 }
References buffer, bufferMutex, LoggerBuffer::flush(), and get_global().
flushAll()
void Logger::flushAll () static
Flush all open LoggerBuffer objects.
Definition at line 130 of file logging.cpp.
                       {
     __android_log_write(Logging::CRITICAL, Logger::get().tag.c_str(), "Flushing all buffers!");
     Logger::bufferMutex.lock();
     for (auto* buffer : Logger::buffers) {
         buffer->flush();
     }
     get_global().flush();
     Logger::bufferMutex.unlock();
     __android_log_write(Logging::CRITICAL, Logger::get().tag.c_str(), "All buffers flushed!");
 }
References buffer, bufferMutex, buffers, Logging::CRITICAL, LoggerBuffer::flush(), get(), get_global(), and tag.
get()
Logger & Logger::get () static
Returns the logger that is used within the utils library. This function should not be used outside of the main library.
Definition at line 59 of file logging.cpp.
                     {
     static auto utilsLogger = new Logger(ModInfo{"UtilsLogger", VERSION}, LoggerOptions(false, true));
     return *utilsLogger;
 }
References Logger(), and VERSION.
Referenced by AssemblyFunction::AssemblyFunction(), closeAll(), HookTracker::CombineHooks(), dump(), Configuration::ensureObject(), EvalSwitch(), ExtractAddress(), Instruction::findNth(), FindOrCreateInstruction(), findUniquePattern(), LoggerBuffer::flush(), flushAll(), il2cpp_utils::GetFieldValue(), il2cpp_functions::getFuncLogger(), getLibil2cppSize(), il2cpp_utils::getLogger(), Instruction::Instruction(), InstructionTree::PopulateChildren(), print(), ProcessRegisterDependencies(), Replicate(), ROR(), safeAbort(), and startConsumer().
GetDisabledContexts()
const std::unordered_set< std::string > Logger::GetDisabledContexts ()
Gets all disabled contexts on this instance.
Returns
The set of disabled context strings.
Definition at line 286 of file logging.cpp.
{
     return disabledContexts;
 }
References disabledContexts.
getOptions()
const LoggerOptions Logger::getOptions () const inline
Returns the current options for this logger.
Definition at line 178 of file logging.hpp.
{
             return options;
         }
References options.
info()
template<typename... TArgs> void Logger::info (std::string_view fmt, TArgs... args) inline
Definition at line 136 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(Logging::INFO, string_format(fmt, args...));
         }
References il2cpp_utils::args, Logging::INFO, log(), options, LoggerOptions::silent, and string_format().
Referenced by LoggerContextObject::info().
init()
bool Logger::init ()
Initialize this logger. Deletes existing file logs. This happens on default when this instance is constructed. This should also be called anytime the options field is modified.
Returns
True if the initialization was successful, false otherwise. If false is returned, you should set buffer.closed to true.
Definition at line 154 of file logging.cpp.
                   {
     // So, we want to take a look at our options.
     // If we have fileLog set to true, we want to clear the file pointed to by this log.
     // That means that we want to delete the existing file (because storing a bunch is pretty obnoxious)
     if (options.toFile) {
         if (fileexists(buffer.get_path())) {
             deletefile(buffer.get_path());
         }
         // Now, create the file and paths as necessary.
         if (!direxists(buffer.get_logDir())) {
             mkpath(buffer.get_logDir());
             __android_log_print(Logging::INFO, tag.c_str(), "Created logger buffer dir: %s", buffer.get_logDir().c_str());
         }
         std::ofstream str(buffer.get_path());
         if (!str.is_open()) {
             __android_log_print(Logging::CRITICAL, tag.c_str(), "Could not open logger buffer file: %s!", buffer.get_path().c_str());
             return false;
         } else {
             str.close();
         }
     }
     return true;
 }
References buffer, Logging::CRITICAL, deletefile(), direxists(), fileexists(), LoggerBuffer::get_logDir(), LoggerBuffer::get_path(), Logging::INFO, mkpath(), options, tag, and LoggerOptions::toFile.
Referenced by Logger().
log() [1/2]
void Logger::log (Logging::Level lvl, std::string str)
Definition at line 291 of file logging.cpp.
{
     if (options.silent) {
         return;
     }
     // Chunk string for logcat buffer
     if (str.length() > LOG_MAX_CHARS) {
         std::size_t i = 0;
         while (i < str.length()) {
             auto sub = str.substr(i, LOG_MAX_CHARS);
             auto newline = sub.find('\n');
             if (newline != std::string::npos) {
                 sub = sub.substr(0, newline);
                 i += newline + 1; // Skip actual newline character
             } else {
                 i += LOG_MAX_CHARS;
             }
             __android_log_write(lvl, tag.c_str(), sub.c_str());
         }
     } else {
         __android_log_write(lvl, tag.c_str(), str.c_str());
     }
     if (options.toFile) {
         // If we want to log to file, we want to write to a shared buffer.
         // This buffer should be consumed by a separate thread (started if we haven't yet started any consumer)
         // The overhead of this thread should be pretty minimal, all things considered, even if it handles every Logger instance.
         // The first thing we need to do is create our buffer, and add it to our buffers (lock while doing so)
         // Then, we need to start our thread if we haven't started it already
         // Then, we need to add our data to the buffer (lock while doing so)
         // The thread needs to consume from these buffers (locks while doing so)
         auto now = std::chrono::system_clock::now();
         auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()) % 1000;
         auto in_time = std::chrono::system_clock::to_time_t(now);
         std::tm bt = *std::localtime(&in_time);
         std::ostringstream oss;
         oss << std::put_time(&bt, "%m-%d %H:%M:%S.") << std::setfill('0') << std::setw(3) << ms.count();
         auto msg = oss.str() + " " + get_level(lvl) + " " + tag + ": " + str.c_str();
         // __android_log_print(Logging::DEBUG, tag.c_str(), "Logging message: %s to file!", msg.c_str());
         Logger::bufferMutex.lock();
         buffer.addMessage(msg);
         get_global().addMessage(msg);
         Logger::bufferMutex.unlock();
         startConsumer();
     }
 }
References LoggerBuffer::addMessage(), buffer, bufferMutex, get_global(), get_level(), LOG_MAX_CHARS, options, LoggerOptions::silent, startConsumer(), tag, and LoggerOptions::toFile.
Referenced by critical(), debug(), error(), info(), LoggerContextObject::log(), log(), print(), and warning().
log() [2/2]
template<typename... TArgs> void Logger::log (Logging::Level lvl, std::string_view fmt, TArgs... args) inline
Definition at line 108 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(lvl, string_format(fmt, args...));
         }
References il2cpp_utils::args, log(), options, LoggerOptions::silent, and string_format().
RecurseChangeContext()
void Logger::RecurseChangeContext (LoggerContextObject * ctx, std::string_view context, bool enable) private
Recurses over all children contexts and disables/enables if they start with context.
Definition at line 241 of file logging.cpp.
{
     if (!ctx) {
         // Failsafe
         return;
     }
     if (ctx->context.starts_with(context)) {
         ctx->enabled = enable;
         ctx->changeChildren(enable);
     } else {
         // For each child, if we didn't match, check to see if its context starts with the context to disable
         for (auto* child : ctx->childrenContexts) {
             RecurseChangeContext(child, context, enable);
         }
     }
 }
References LoggerContextObject::changeChildren(), LoggerContextObject::childrenContexts, LoggerContextObject::context, enable(), and LoggerContextObject::enabled.
Referenced by DisableContext(), and EnableContext().
startConsumer()
void Logger::startConsumer () static private
Definition at line 195 of file logging.cpp.
{
     if (!Logger::consumerStarted) {
         consumerStarted = true;
         __android_log_write(Logging::INFO, Logger::get().tag.c_str(), "Started consumer thread!");
         std::thread(Consumer()).detach();
     }
 }
References Consumer, consumerStarted, get(), Logging::INFO, and tag.
Referenced by log().
warning()
template<typename... TArgs> void Logger::warning (std::string_view fmt, TArgs... args) inline
Definition at line 129 of file logging.hpp.
{
             if (options.silent) {
                 return;
             }
             log(Logging::WARNING, string_format(fmt, args...));
         }
References il2cpp_utils::args, log(), options, LoggerOptions::silent, string_format(), and Logging::WARNING.
Referenced by Configuration::ensureObject(), findUniquePattern(), il2cpp_utils::GetFieldValue(), and LoggerContextObject::warning().
WithContext() [1/2]
LoggerContextObject Logger::WithContext (LoggerContextObject * parent, std::string_view context) private
Constructs a context with a parent. This is called by LoggerContextObject.WithContext.
Definition at line 217 of file logging.cpp.
{
     contextMutex.lock();
     for (auto item : disabledContexts) {
         if (context.starts_with(item)) {
             // Disable context
             if (parent) {
                 contextMutex.unlock();
                 return LoggerContextObject(parent, parent->context + options.contextSeparator + context.data(), false);
             } else {
                 contextMutex.unlock();
                 return LoggerContextObject(*this, context, false);
             }
         }
     }
     // If I am silent, my context objects are disabled.
     if (parent) {
         contextMutex.unlock();
         return LoggerContextObject(parent, parent->context + options.contextSeparator + context.data(), !options.silent);
     } else {
         contextMutex.unlock();
         return LoggerContextObject(*this, context, !options.silent);
     }
 }
References LoggerContextObject::context, contextMutex, LoggerOptions::contextSeparator, disabledContexts, LoggerContextObject, options, and LoggerOptions::silent.
WithContext() [2/2]
LoggerContextObject Logger::WithContext (std::string_view context)
Enters a logging context. Should be used for more specific logging information. Avoid entering contexts with names that contain % characters.
Parameters
context The context name to enter
Returns
LoggerContextObject that is used within the context.
Definition at line 203 of file logging.cpp.
{
     contextMutex.lock();
     for (auto item : disabledContexts) {
         if (context.starts_with(item)) {
             // Disable context
             contextMutex.unlock();
             return LoggerContextObject(*this, context, false);
         }
     }
     // If I am silent, my context objects are disabled.
     contextMutex.unlock();
     return LoggerContextObject(*this, context, !options.silent);
 }
References contextMutex, disabledContexts, LoggerContextObject, options, and LoggerOptions::silent.
Referenced by AssemblyFunction::AssemblyFunction(), HookTracker::CombineHooks(), EvalSwitch(), ExtractAddress(), FindOrCreateInstruction(), il2cpp_functions::getFuncLogger(), getLibil2cppSize(), il2cpp_utils::getLogger(), Instruction::Instruction(), InstructionTree::PopulateChildren(), ProcessRegisterDependencies(), safeAbort(), and LoggerContextObject::WithContext().
Field Documentation
buffer
LoggerBuffer Logger::buffer private
Definition at line 210 of file logging.hpp.
Referenced by close(), closeAll(), emplace_safe(), flush(), flushAll(), init(), log(), and Logger().
bufferMutex
std::mutex Logger::bufferMutex static private
Definition at line 213 of file logging.hpp.
Referenced by close(), closeAll(), emplace_safe(), flush(), flushAll(), log(), and Consumer::operator()().
buffers
std::list< LoggerBuffer * > Logger::buffers static private
Definition at line 212 of file logging.hpp.
Referenced by closeAll(), emplace_safe(), flushAll(), and Consumer::operator()().
Consumer
friend Logger::Consumer private
Definition at line 89 of file logging.hpp.
Referenced by startConsumer().
consumerStarted
bool Logger::consumerStarted = false static private
Definition at line 211 of file logging.hpp.
Referenced by startConsumer().
contextMutex
std::mutex Logger::contextMutex private
The mutex for the contexts maps/sets.
Definition at line 203 of file logging.hpp.
Referenced by DisableContext(), EnableContext(), LoggerContextObject::LoggerContextObject(), WithContext(), and LoggerContextObject::~LoggerContextObject().
contexts
std::vector<LoggerContextObject*> Logger::contexts private
All created contexts for this instance.
Definition at line 201 of file logging.hpp.
Referenced by DisableContext(), EnableContext(), LoggerContextObject::LoggerContextObject(), and LoggerContextObject::~LoggerContextObject().
disabledContexts
std::unordered_set<std::string> Logger::disabledContexts private
Definition at line 199 of file logging.hpp.
Referenced by DisableContext(), EnableContext(), GetDisabledContexts(), and WithContext().
LoggerBuffer
friend Logger::LoggerBuffer private
Definition at line 90 of file logging.hpp.
LoggerContextObject
friend Logger::LoggerContextObject private
Definition at line 91 of file logging.hpp.
Referenced by WithContext().
modInfo
const ModInfo Logger::modInfo private
Definition at line 206 of file logging.hpp.
options
LoggerOptions Logger::options private
The options associated with this logger.
Definition at line 197 of file logging.hpp.
Referenced by critical(), debug(), disable(), enable(), error(), getOptions(), info(), init(), log(), warning(), and WithContext().
tag
std::string Logger::tag private
Definition at line 205 of file logging.hpp.
Referenced by closeAll(), flushAll(), init(), log(), and startConsumer().
The documentation for this struct was generated from the following files:
shared/utils/logging.hpp
src/utils/logging.cpp