BeatSaber-Hooks: rapidjson::GenericStringBuffer< Encoding, Allocator > Class Template Reference
rapidjson::GenericStringBuffer< Encoding, Allocator > Class Template Reference
Represents an in-memory output stream.
#include <stringbuffer.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
GenericStringBuffer (Allocator *allocator=0, size_t capacity=kDefaultCapacity)
void Put (Ch c)
void PutUnsafe (Ch c)
void Flush ()
void Clear ()
void ShrinkToFit ()
void Reserve (size_t count)
Ch * Push (size_t count)
Ch * PushUnsafe (size_t count)
void Pop (size_t count)
const Ch * GetString () const
size_t GetSize () const
Get the size of string in bytes in the string buffer.
size_t GetLength () const
Get the length of string in Ch in the string buffer.
Data Fields
internal::Stack< Allocator > stack_
Static Public Attributes
static const size_t kDefaultCapacity = 256
Private Member Functions
GenericStringBuffer (const GenericStringBuffer &)
GenericStringBuffer & operator= (const GenericStringBuffer &)
Detailed Description
template<typename Encoding, typename Allocator = CrtAllocator>
class rapidjson::GenericStringBuffer< Encoding, Allocator >
Represents an in-memory output stream.
Template Parameters
Encoding Encoding of the stream.
Allocator type for allocating memory buffer.
Note
implements Stream concept
Definition at line 41 of file stringbuffer.h.
Member Typedef Documentation
Ch
template<typename Encoding , typename Allocator = CrtAllocator> typedef Encoding::Ch rapidjson::GenericStringBuffer< Encoding, Allocator >::Ch
Definition at line 43 of file stringbuffer.h.
Constructor & Destructor Documentation
GenericStringBuffer() [1/2]
template<typename Encoding , typename Allocator = CrtAllocator> rapidjson::GenericStringBuffer< Encoding, Allocator >::GenericStringBuffer (Allocator * allocator = 0, size_t capacity = kDefaultCapacity) inline
Definition at line 45 of file stringbuffer.h.
 : stack_(allocator, capacity) {}
GenericStringBuffer() [2/2]
template<typename Encoding , typename Allocator = CrtAllocator> rapidjson::GenericStringBuffer< Encoding, Allocator >::GenericStringBuffer (const GenericStringBuffer< Encoding, Allocator > &) private
Member Function Documentation
Clear()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::Clear () inline
Definition at line 60 of file stringbuffer.h.
 { stack_.Clear(); }
Referenced by rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorLocation(), main(), and TEST().
Flush()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::Flush () inline
Definition at line 58 of file stringbuffer.h.
 {}
GetLength()
template<typename Encoding , typename Allocator = CrtAllocator> size_t rapidjson::GenericStringBuffer< Encoding, Allocator >::GetLength () const inline
Get the length of string in Ch in the string buffer.
Definition at line 85 of file stringbuffer.h.
 { return stack_.GetSize() / sizeof(Ch); }
Referenced by TEST().
GetSize()
template<typename Encoding , typename Allocator = CrtAllocator> size_t rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize () const inline
Get the size of string in bytes in the string buffer.
Definition at line 82 of file stringbuffer.h.
 { return stack_.GetSize(); }
Referenced by rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorLocation(), and TEST().
GetString()
template<typename Encoding , typename Allocator = CrtAllocator> const Ch* rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString () const inline
Definition at line 73 of file stringbuffer.h.
{
         // Push and pop a null terminator. This is safe.
         *stack_.template Push<Ch>() = '\0';
         stack_.template Pop<Ch>(1);
         return stack_.template Bottom<Ch>();
     }
Referenced by rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorLocation(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), main(), TEST(), TEST_F(), TestTranscode(), and Configuration::Write().
operator=()
template<typename Encoding , typename Allocator = CrtAllocator> GenericStringBuffer& rapidjson::GenericStringBuffer< Encoding, Allocator >::operator= (const GenericStringBuffer< Encoding, Allocator > &) private
Pop()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::Pop (size_t count) inline
Definition at line 71 of file stringbuffer.h.
 { stack_.template Pop<Ch>(count); }
Referenced by TEST().
Push()
template<typename Encoding , typename Allocator = CrtAllocator> Ch* rapidjson::GenericStringBuffer< Encoding, Allocator >::Push (size_t count) inline
Definition at line 69 of file stringbuffer.h.
 { return stack_.template Push<Ch>(count); }
Referenced by rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorLocation(), and TEST().
PushUnsafe()
template<typename Encoding , typename Allocator = CrtAllocator> Ch* rapidjson::GenericStringBuffer< Encoding, Allocator >::PushUnsafe (size_t count) inline
Definition at line 70 of file stringbuffer.h.
 { return stack_.template PushUnsafe<Ch>(count); }
Put()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::Put (Ch c) inline
Definition at line 56 of file stringbuffer.h.
 { *stack_.template Push<Ch>() = c; }
Referenced by TEST(), and TEST_F().
PutUnsafe()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::PutUnsafe (Ch c) inline
Definition at line 57 of file stringbuffer.h.
 { *stack_.template PushUnsafe<Ch>() = c; }
Referenced by rapidjson::PutUnsafe().
Reserve()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::Reserve (size_t count) inline
Definition at line 68 of file stringbuffer.h.
 { stack_.template Reserve<Ch>(count); }
Referenced by rapidjson::PutReserve().
ShrinkToFit()
template<typename Encoding , typename Allocator = CrtAllocator> void rapidjson::GenericStringBuffer< Encoding, Allocator >::ShrinkToFit () inline
Definition at line 61 of file stringbuffer.h.
{
         // Push and pop a null terminator. This is safe.
         *stack_.template Push<Ch>() = '\0';
         stack_.ShrinkToFit();
         stack_.template Pop<Ch>(1);
     }
Referenced by TEST().
Field Documentation
kDefaultCapacity
template<typename Encoding , typename Allocator = CrtAllocator> const size_t rapidjson::GenericStringBuffer< Encoding, Allocator >::kDefaultCapacity = 256 static
Definition at line 87 of file stringbuffer.h.
stack_
template<typename Encoding , typename Allocator = CrtAllocator> internal::Stack<Allocator> rapidjson::GenericStringBuffer< Encoding, Allocator >::stack_ mutable
Definition at line 88 of file stringbuffer.h.
The documentation for this class was generated from the following files:
shared/rapidjson/include/rapidjson/fwd.h
shared/rapidjson/include/rapidjson/stringbuffer.h