BeatSaber-Hooks: JsonReader Class Reference
JsonReader Class Reference
Represents a JSON reader which implements Archiver concept.
#include <archiver.h>
Public Member Functions
JsonReader (const char *json)
Constructor.
~JsonReader ()
Destructor.
operator bool () const
JsonReader & StartObject ()
JsonReader & Member (const char *name)
bool HasMember (const char *name) const
JsonReader & EndObject ()
JsonReader & StartArray (size_t *size=0)
JsonReader & EndArray ()
JsonReader & operator& (bool &b)
JsonReader & operator& (unsigned &u)
JsonReader & operator& (int &i)
JsonReader & operator& (double &d)
JsonReader & operator& (std::string &s)
JsonReader & SetNull ()
Static Public Attributes
static const bool IsReader = true
static const bool IsWriter = !IsReader
Private Member Functions
JsonReader (const JsonReader &)
JsonReader & operator= (const JsonReader &)
void Next ()
Private Attributes
void * mDocument
DOM result of parsing.
void * mStack
Stack for iterating the DOM.
bool mError
Whether an error has occurred.
Detailed Description
Represents a JSON reader which implements Archiver concept.
Definition at line 56 of file archiver.h.
Constructor & Destructor Documentation
JsonReader() [1/2]
JsonReader::JsonReader (const char * json)
Constructor.
Parameters
json A non-const source json string for in-situ parsing.
Note
in-situ means the source JSON string will be modified after parsing.
Definition at line 31 of file archiver.cpp.
                                        : mDocument(), mStack(), mError(false) {
     mDocument = new Document;
     DOCUMENT->Parse(json);
     if (DOCUMENT->HasParseError())
         mError = true;
     else {
         mStack = new JsonReaderStack;
         STACK->push(JsonReaderStackItem(DOCUMENT, JsonReaderStackItem::BeforeStart));
     }
 }
References JsonReaderStackItem::BeforeStart, DOCUMENT, mDocument, mError, mStack, and STACK.
~JsonReader()
JsonReader::~JsonReader ()
Destructor.
Definition at line 42 of file archiver.cpp.
{
     delete DOCUMENT;
     delete STACK;
 }
References DOCUMENT, and STACK.
JsonReader() [2/2]
JsonReader::JsonReader (const JsonReader &) private
Member Function Documentation
EndArray()
JsonReader & JsonReader::EndArray ()
Definition at line 109 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsArray() && TOP.state == JsonReaderStackItem::Closed)
             Next();
         else
             mError = true;
     }
     return *this;
 }
References JsonReaderStackItem::Closed, CURRENT, mError, Next(), and TOP.
EndObject()
JsonReader & JsonReader::EndObject ()
Definition at line 58 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsObject() && TOP.state == JsonReaderStackItem::Started)
             Next();
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, Next(), JsonReaderStackItem::Started, and TOP.
HasMember()
bool JsonReader::HasMember (const char * name) const
Definition at line 83 of file archiver.cpp.
{
     if (!mError && CURRENT.IsObject() && TOP.state == JsonReaderStackItem::Started)
         return CURRENT.HasMember(name);
     return false;
 }
References CURRENT, mError, JsonReaderStackItem::Started, and TOP.
Member()
JsonReader & JsonReader::Member (const char * name)
Definition at line 68 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsObject() && TOP.state == JsonReaderStackItem::Started) {
             Value::ConstMemberIterator memberItr = CURRENT.FindMember(name);
             if (memberItr != CURRENT.MemberEnd())
                 STACK->push(JsonReaderStackItem(&memberItr->value, JsonReaderStackItem::BeforeStart));
             else
                 mError = true;
         }
         else
             mError = true;
     }
     return *this;
 }
References JsonReaderStackItem::BeforeStart, CURRENT, mError, STACK, JsonReaderStackItem::Started, and TOP.
Next()
void JsonReader::Next () private
Definition at line 185 of file archiver.cpp.
                       {
     if (!mError) {
         assert(!STACK->empty());
         STACK->pop();
         if (!STACK->empty() && CURRENT.IsArray()) {
             if (TOP.state == JsonReaderStackItem::Started) { // Otherwise means reading array item pass end
                 if (TOP.index < CURRENT.Size() - 1) {
                     const Value* value = &CURRENT[++TOP.index];
                     STACK->push(JsonReaderStackItem(value, JsonReaderStackItem::BeforeStart));
                 }
                 else
                     TOP.state = JsonReaderStackItem::Closed;
             }
             else
                 mError = true;
         }
     }
 }
References JsonReaderStackItem::BeforeStart, JsonReaderStackItem::Closed, CURRENT, mError, STACK, JsonReaderStackItem::Started, TOP, and rapidjson::value.
Referenced by EndArray(), EndObject(), and operator&().
operator bool()
JsonReader::operator bool () const inline
Definition at line 70 of file archiver.h.
 { return !mError; }
References mError.
operator&() [1/5]
JsonReader & JsonReader::operator& (bool & b)
Definition at line 119 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsBool()) {
             b = CURRENT.GetBool();
             Next();
         }
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, and Next().
operator&() [2/5]
JsonReader & JsonReader::operator& (double & d)
Definition at line 155 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsNumber()) {
             d = CURRENT.GetDouble();
             Next();
         }
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, and Next().
operator&() [3/5]
JsonReader & JsonReader::operator& (int & i)
Definition at line 143 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsInt()) {
             i = CURRENT.GetInt();
             Next();
         }
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, and Next().
operator&() [4/5]
JsonReader & JsonReader::operator& (std::string & s)
Definition at line 167 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsString()) {
             s = CURRENT.GetString();
             Next();
         }
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, and Next().
operator&() [5/5]
JsonReader & JsonReader::operator& (unsigned & u)
Definition at line 131 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsUint()) {
             u = CURRENT.GetUint();
             Next();
         }
         else
             mError = true;
     }
     return *this;
 }
References CURRENT, mError, and Next().
operator=()
JsonReader& JsonReader::operator= (const JsonReader &) private
SetNull()
JsonReader & JsonReader::SetNull ()
Definition at line 179 of file archiver.cpp.
{
     // This function is for JsonWriter only.
     mError = true;
     return *this;
 }
References mError.
StartArray()
JsonReader & JsonReader::StartArray (size_t * size = 0)
Definition at line 89 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsArray() && TOP.state == JsonReaderStackItem::BeforeStart) {
             TOP.state = JsonReaderStackItem::Started;
             if (size)
                 *size = CURRENT.Size();
             if (!CURRENT.Empty()) {
                 const Value* value = &CURRENT[TOP.index];
                 STACK->push(JsonReaderStackItem(value, JsonReaderStackItem::BeforeStart));
             }
             else
                 TOP.state = JsonReaderStackItem::Closed;
         }
         else
             mError = true;
     }
     return *this;
 }
References JsonReaderStackItem::BeforeStart, JsonReaderStackItem::Closed, CURRENT, mError, STACK, JsonReaderStackItem::Started, TOP, and rapidjson::value.
StartObject()
JsonReader & JsonReader::StartObject ()
Definition at line 48 of file archiver.cpp.
{
     if (!mError) {
         if (CURRENT.IsObject() && TOP.state == JsonReaderStackItem::BeforeStart)
             TOP.state = JsonReaderStackItem::Started;
         else
             mError = true;
     }
     return *this;
 }
References JsonReaderStackItem::BeforeStart, CURRENT, mError, JsonReaderStackItem::Started, and TOP.
Field Documentation
IsReader
const bool JsonReader::IsReader = true static
Definition at line 88 of file archiver.h.
IsWriter
const bool JsonReader::IsWriter = !IsReader static
Definition at line 89 of file archiver.h.
mDocument
void* JsonReader::mDocument private
DOM result of parsing.
Definition at line 98 of file archiver.h.
Referenced by JsonReader().
mError
bool JsonReader::mError private
Whether an error has occurred.
Definition at line 100 of file archiver.h.
Referenced by EndArray(), EndObject(), HasMember(), JsonReader(), Member(), Next(), operator bool(), operator&(), SetNull(), StartArray(), and StartObject().
mStack
void* JsonReader::mStack private
Stack for iterating the DOM.
Definition at line 99 of file archiver.h.
Referenced by JsonReader().
The documentation for this class was generated from the following files:
shared/rapidjson/example/archiver/archiver.h
shared/rapidjson/example/archiver/archiver.cpp