BeatSaber-Hooks: Dependent Class Reference
Dependent Class Reference
Public Member Functions
Dependent (const std::string &name, unsigned age, Education *education=0)
Dependent (const Dependent &rhs)
virtual ~Dependent ()
Dependent & operator= (const Dependent &rhs)
template<typename Writer >
void Serialize (Writer &writer) const
Public Member Functions inherited from Person
Person (const std::string &name, unsigned age)
Person (const Person &rhs)
virtual ~Person ()
Person & operator= (const Person &rhs)
Private Attributes
Education * education_
Additional Inherited Members
Protected Member Functions inherited from Person
template<typename Writer >
void Serialize (Writer &writer) const
Detailed Description
Definition at line 72 of file serialize.cpp.
Constructor & Destructor Documentation
Dependent() [1/2]
Dependent::Dependent (const std::string & name, unsigned age, Education * education = 0) inline
Definition at line 74 of file serialize.cpp.
 : Person(name, age), education_(education) {}
Dependent() [2/2]
Dependent::Dependent (const Dependent & rhs) inline
Definition at line 75 of file serialize.cpp.
 : Person(rhs), education_(0) { education_ = (rhs.education_ == 0) ? 0 : new Education(*rhs.education_); }
References education_.
~Dependent()
Dependent::~Dependent () virtual
Definition at line 106 of file serialize.cpp.
                       {
     delete education_;
 }
Member Function Documentation
operator=()
Dependent& Dependent::operator= (const Dependent & rhs) inline
Definition at line 78 of file serialize.cpp.
{
         if (this == &rhs)
             return *this;
         delete education_;
         education_ = (rhs.education_ == 0) ? 0 : new Education(*rhs.education_);
         return *this;
     }
References education_.
Serialize()
template<typename Writer > void Dependent::Serialize (Writer & writer) const inline
Definition at line 87 of file serialize.cpp.
{
         writer.StartObject();
         Person::Serialize(writer);
         writer.String("education");
         if (education_)
             education_->Serialize(writer);
         else
             writer.Null();
         writer.EndObject();
     }
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), Person::Serialize(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Field Documentation
education_
Education* Dependent::education_ private
Definition at line 103 of file serialize.cpp.
Referenced by Dependent(), and operator=().
The documentation for this class was generated from the following file:
shared/rapidjson/example/serialize/serialize.cpp