BeatSaber-Hooks: Employee Class Reference
Employee Class Reference
Public Member Functions
Employee (const std::string &name, unsigned age, bool married)
Employee (const Employee &rhs)
virtual ~Employee ()
Employee & operator= (const Employee &rhs)
void AddDependent (const Dependent &dependent)
template<typename Writer >
void Serialize (Writer &writer) const
Public Member Functions inherited from Person
Person (const std::string &name, unsigned age)
Person (const Person &rhs)
virtual ~Person ()
Person & operator= (const Person &rhs)
Private Attributes
std::vector< Dependent > dependents_
bool married_
Additional Inherited Members
Protected Member Functions inherited from Person
template<typename Writer >
void Serialize (Writer &writer) const
Detailed Description
Definition at line 110 of file serialize.cpp.
Constructor & Destructor Documentation
Employee() [1/2]
Employee::Employee (const std::string & name, unsigned age, bool married) inline
Definition at line 112 of file serialize.cpp.
 : Person(name, age), dependents_(), married_(married) {}
Employee() [2/2]
Employee::Employee (const Employee & rhs) inline
Definition at line 113 of file serialize.cpp.
 : Person(rhs), dependents_(rhs.dependents_), married_(rhs.married_) {}
~Employee()
Employee::~Employee () virtual
Definition at line 150 of file serialize.cpp.
                     {
 }
Member Function Documentation
AddDependent()
void Employee::AddDependent (const Dependent & dependent) inline
Definition at line 123 of file serialize.cpp.
{
         dependents_.push_back(dependent);
     }
operator=()
Employee& Employee::operator= (const Employee & rhs) inline
Definition at line 116 of file serialize.cpp.
{
         static_cast<Person&>(*this) = rhs;
         dependents_ = rhs.dependents_;
         married_ = rhs.married_;
         return *this;
     }
References dependents_, and married_.
Serialize()
template<typename Writer > void Employee::Serialize (Writer & writer) const inline
Definition at line 128 of file serialize.cpp.
{
         writer.StartObject();
         Person::Serialize(writer);
         writer.String("married");
         writer.Bool(married_);
         writer.String(("dependents"));
         writer.StartArray();
         for (std::vector<Dependent>::const_iterator dependentItr = dependents_.begin(); dependentItr != dependents_.end(); ++dependentItr)
             dependentItr->Serialize(writer);
         writer.EndArray();
         writer.EndObject();
     }
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Person::Serialize(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Field Documentation
dependents_
std::vector<Dependent> Employee::dependents_ private
Definition at line 146 of file serialize.cpp.
Referenced by operator=().
married_
bool Employee::married_ private
Definition at line 147 of file serialize.cpp.
Referenced by operator=().
The documentation for this class was generated from the following file:
shared/rapidjson/example/serialize/serialize.cpp