BeatSaber-Hooks: InstructionTree Class Reference
InstructionTree Class Reference
#include <instruction-parsing.hpp>
Public Member Functions
InstructionTree (const int32_t *inst)
void PopulateChildren (ParseState &parseState)
~InstructionTree ()
Data Fields
InstructionTree * noBranch
InstructionTree * branch
Additional Inherited Members
Private Types inherited from Instruction
enum ShiftType {
LSL , LSR , ASR , ROR ,
noShift
}
enum ExtendType {
UXTB , UXTH , UXTW , UXTX ,
SXTB , SXTH , SXTW , SXTX ,
noExtend
}
enum BranchType {
NOBRANCH , DIRCALL , INDCALL , ERET ,
DBGEXIT , RET , DIR , INDIR ,
EXCEPTION , RESET , UNKNOWN
}
Private Member Functions inherited from Instruction
Instruction (const int32_t *inst)
std::string toString () const
bool isPcRelAdr ()
bool isAddOrSubImm ()
bool isLoadOrStore ()
bool isLoad ()
bool isStore ()
bool isHint ()
bool isNOP ()
bool hasImmOffsetOnReg (uint_fast8_t reg)
template<class UnaryPredicate >
Instruction * findNth (int n, UnaryPredicate pred, int rets=0)
Instruction * findNthCall (int n, int rets=0)
Instruction * findNthDirectBranchWithoutLink (int n, int rets=0)
Instruction * findNthPcRelAdr (int n, int rets=0)
Instruction * findNthImmOffsetOnReg (int n, uint_fast8_t reg, int rets=0)
bool isBranch () const
bool isUnconditionalBranch () const
bool isReturn () const
bool isDirectBranch () const
bool isIndirectBranch () const
bool isCall () const
Static Private Member Functions inherited from Instruction
static bool extendIsUnsigned (ExtendType extend)
static uint_fast8_t extendGetLen (ExtendType extend)
Private Attributes inherited from Instruction
const int32_t * addr
int_fast8_t Rd = -2
int_fast8_t Rd2 = -1
int_fast8_t numSourceRegisters = -1
union {
int_fast8_t Rs [3] = { -1, -1, -1 }
int64_t result
};
std::optional< int64_t > imm
std::optional< const int32_t * > label
enum Instruction::ShiftType shiftType = noShift
enum Instruction::ExtendType extendType = noExtend
enum Instruction::BranchType branchType = NOBRANCH
bool parsed
bool valid = true
uint8_t size
Static Private Attributes inherited from Instruction
static const char *const branchTypeNames []
static const char *const branchTypeInfo []
Detailed Description
Definition at line 209 of file instruction-parsing.hpp.
Constructor & Destructor Documentation
InstructionTree()
InstructionTree::InstructionTree (const int32_t * inst)
Definition at line 1300 of file instruction-parsing.cpp.
                                                  : Instruction(pc) {
 }
~InstructionTree()
InstructionTree::~InstructionTree () inline
Definition at line 217 of file instruction-parsing.hpp.
{
Member Function Documentation
PopulateChildren()
void InstructionTree::PopulateChildren (ParseState & parseState)
Definition at line 1265 of file instruction-parsing.cpp.
{
     auto pc = this->addr;
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("PopulateChildren");
     logger.debug("InstructionTree: %p, %s", pc, this->toString().c_str());
     // If instruction was not fully parsed, stop.
     if (!parsed || !valid) return;
     if ((this->numSourceRegisters < 0) || (this->Rs[this->numSourceRegisters - 1] < 0)) {
         logger.error("The Instruction constructor did not properly parse this instruction's source registers! Please fix!");
     }
     // if instruction is return, stop parsing.
     if (isReturn()) return;
     // populate parseState.dependencyMap using this' dest and source registers
     ProcessRegisterDependencies(this, parseState.dependencyMap);
     // if instruction is direct branch, address to jump to is in "label"
     if (isDirectBranch()) {
         CRASH_UNLESS(label);
         const int32_t* addr = *label;
         // Note: these do not edit the dependency map so there is no need to take a backup of it ourselves
         branch = FindOrCreateInstruction(addr, parseState, "InstructionTree: recursing to branch location");
         if (isCall()) {
             parseState.functionCandidates.insert({addr, parseState.dependencyMap});  // the inserted depMap is a copy
         }
     } else {
         parseState.otherJumps.insert({pc, parseState.dependencyMap});
     }
     // unless instruction is unconditional branch, populate noBranch with next instruction in memory
     if (!isUnconditionalBranch()) {
         noBranch = FindOrCreateInstruction(pc + 1, parseState, "InstructionTree: recursing to next instruction");
     }
 }
References Instruction::addr, branch, LoggerContextObject::debug(), ParseState::dependencyMap, FindOrCreateInstruction(), ParseState::functionCandidates, Logger::get(), Instruction::isCall(), Instruction::isDirectBranch(), Instruction::isReturn(), Instruction::isUnconditionalBranch(), Instruction::label, noBranch, Instruction::numSourceRegisters, ParseState::otherJumps, Instruction::parsed, ProcessRegisterDependencies(), Instruction::Rs, Instruction::toString(), Instruction::valid, Logger::WithContext(), and LoggerContextObject::WithContext().
Field Documentation
branch
InstructionTree* InstructionTree::branch
Definition at line 212 of file instruction-parsing.hpp.
Referenced by PopulateChildren().
noBranch
InstructionTree* InstructionTree::noBranch
Definition at line 211 of file instruction-parsing.hpp.
Referenced by PopulateChildren().
The documentation for this class was generated from the following files:
shared/utils/instruction-parsing.hpp
src/utils/instruction-parsing.cpp