BeatSaber-Hooks: Modloader Class Reference
Modloader Class Reference
#include <modloader.hpp>
Static Public Member Functions
static const std::string getLibIl2CppPath ()
static const std::string getApplicationId ()
static bool getAllConstructed ()
static const ModloaderInfo getInfo ()
static const std::unordered_map< std::string, const Mod > getMods ()
static bool requireMod (const ModInfo &)
static bool requireMod (std::string_view id, std::string_view version)
static bool requireMod (std::string_view id)
Detailed Description
Definition at line 33 of file modloader.hpp.
Member Function Documentation
getAllConstructed()
static bool Modloader::getAllConstructed () static
getApplicationId()
static const std::string Modloader::getApplicationId () static
Referenced by HookTracker::CombineHooks(), LoggerBuffer::get_logDir(), Configuration::getConfigFilePath(), and getDataDir().
getInfo()
static const ModloaderInfo Modloader::getInfo () static
getLibIl2CppPath()
static const std::string Modloader::getLibIl2CppPath () static
Referenced by getLibil2cppSize(), getRealOffset(), and il2cpp_functions::Init().
getMods()
static const std::unordered_map<std::string, const Mod> Modloader::getMods () static
requireMod() [1/3]
static bool Modloader::requireMod (const ModInfo &) static
requireMod() [2/3]
static bool Modloader::requireMod (std::string_view id) static
requireMod() [3/3]
static bool Modloader::requireMod (std::string_view id, std::string_view version) static
The documentation for this class was generated from the following file:
extern/modloader/shared/modloader.hpp