BeatSaber-Hooks: LoggerContextObject Class Reference
LoggerContextObject Class Reference
#include <logging.hpp>
Public Member Functions
LoggerContextObject (Logger &l, std::string_view context_, bool enabled_)
Constructs a LoggerContextObject. Should only be called from Logger.WithContext or LoggerContextObject.WithContext.
LoggerContextObject (LoggerContextObject *const parent, std::string_view context_, bool enabled_)
Constructs a nested LoggerContextObject. Should only be called from Logger.WithContext or LoggerContextObject.WithContext.
bool operator== (const LoggerContextObject &other) const
Equality operator.
constexpr const LoggerContextObject * getParent ()
The parent context (or nullptr if there is no parent)
const std::list< LoggerContextObject * > getChildren ()
The children contexts (empty if there are no children)
LoggerContextObject (const LoggerContextObject &)=delete
LoggerContextObject (LoggerContextObject &&other)
Move constructor. Modifies the Logger's contexts collection.
~LoggerContextObject ()
Destructor. Modified the Logger's contexts collection.
void log (Logging::Level lvl, std::string str) const
template<typename T , typename... TArgs>
void log (Logging::Level lvl, std::string_view fmt, T first, TArgs... args) const
template<typename... TArgs>
void critical (std::string_view fmt, TArgs... args) const
template<typename... TArgs>
void error (std::string_view fmt, TArgs... args) const
template<typename... TArgs>
void warning (std::string_view fmt, TArgs... args) const
template<typename... TArgs>
void info (std::string_view fmt, TArgs... args) const
template<typename... TArgs>
void debug (std::string_view fmt, TArgs... args) const
LoggerContextObject WithContext (std::string_view ctx)
Enter a new context. This call forwards to logger.WithContext(this, ctx). Avoid entering contexts with names that contain % characters.
Data Fields
Logger & logger
The Logger reference.
const std::string context
The context of this LoggerContextObject.
Private Member Functions
void changeChildren (bool enable)
Iterates over all children and either enables or disables them.
Private Attributes
friend Logger
std::string tag
bool enabled = true
LoggerContextObject * parentContext = nullptr
std::list< LoggerContextObject * > childrenContexts
Detailed Description
Definition at line 229 of file logging.hpp.
Constructor & Destructor Documentation
LoggerContextObject() [1/4]
LoggerContextObject::LoggerContextObject (Logger & l, std::string_view context_, bool enabled_) inline
Constructs a LoggerContextObject. Should only be called from Logger.WithContext or LoggerContextObject.WithContext.
Parameters
l Logger instance to use
context_ The context for this object
enabled_ If it is enabled or not
Definition at line 250 of file logging.hpp.
                                                                            : enabled(enabled_), logger(l), context(context_.data()) {
         tag.append("(").append(context_.data()).append(") ");
         std::scoped_lock<std::mutex> lock(logger.contextMutex);
         logger.contexts.push_back(this);
     }
References Logger::contextMutex, Logger::contexts, logger, and tag.
LoggerContextObject() [2/4]
LoggerContextObject::LoggerContextObject (LoggerContextObject *const parent, std::string_view context_, bool enabled_) inline
Constructs a nested LoggerContextObject. Should only be called from Logger.WithContext or LoggerContextObject.WithContext.
Parameters
parent LoggerContextObject parent
context_ The context for this object
enabled_ If it is enabled or not
Definition at line 260 of file logging.hpp.
         : enabled(enabled_ && parent->enabled), parentContext(parent), logger(parent->logger), context(context_)
     {
         tag.append("(").append(context.data()).append(") ");
         parentContext->childrenContexts.push_back(this);
         std::scoped_lock<std::mutex> lock(logger.contextMutex);
         logger.contexts.push_back(this);
     }
References childrenContexts, context, Logger::contextMutex, Logger::contexts, logger, parentContext, and tag.
LoggerContextObject() [3/4]
LoggerContextObject::LoggerContextObject (const LoggerContextObject &) delete
LoggerContextObject() [4/4]
LoggerContextObject::LoggerContextObject (LoggerContextObject && other) inline
Move constructor. Modifies the Logger's contexts collection.
Definition at line 287 of file logging.hpp.
         : tag(std::move(other.tag)), enabled(std::move(other.enabled)), parentContext(other.parentContext), childrenContexts(std::move(other.childrenContexts)), logger(other.logger), context(std::move(other.context))
     {
         // Potential race condition if move is called, interrupted, and DisableContext is called (should not result in much issue, though)
         logger.contextMutex.try_lock();
         // We we move the context, we need to update the pointer in the contexts collection
         for (auto itr = logger.contexts.begin(); itr != logger.contexts.end(); ++itr) {
             if (*itr == &other) {
                 logger.contexts.erase(itr);
                 break;
             }
         }
         logger.contexts.push_back(this);
         logger.contextMutex.unlock();
     }
References Logger::contextMutex, Logger::contexts, and logger.
~LoggerContextObject()
LoggerContextObject::~LoggerContextObject () inline
Destructor. Modified the Logger's contexts collection.
Definition at line 303 of file logging.hpp.
{
         // We delete all of our children
         childrenContexts.clear();
         // Then we remove ourselves from our parent
         if (parentContext) {
             parentContext->childrenContexts.remove(this);
         }
         // Remove ourselves from logger.contexts
         logger.contextMutex.lock();
         for (auto itr = logger.contexts.begin(); itr != logger.contexts.end(); ++itr) {
             if (*itr == this) {
                 logger.contexts.erase(itr);
                 break;
             }
         }
         logger.contextMutex.unlock();
     }
References childrenContexts, Logger::contextMutex, Logger::contexts, logger, and parentContext.
Member Function Documentation
changeChildren()
void LoggerContextObject::changeChildren (bool enable) inline private
Iterates over all children and either enables or disables them.
Definition at line 236 of file logging.hpp.
{
         for (auto* item : childrenContexts) {
             item->enabled = enable;
         }
     }
References childrenContexts.
Referenced by Logger::RecurseChangeContext().
critical()
template<typename... TArgs> void LoggerContextObject::critical (std::string_view fmt, TArgs... args) const inline
Definition at line 333 of file logging.hpp.
{
         if (enabled) {
             logger.critical(tag + fmt.data(), args...);
         }
     }
References il2cpp_utils::args, Logger::critical(), enabled, logger, and tag.
Referenced by ProcessRegisterDependencies().
debug()
template<typename... TArgs> void LoggerContextObject::debug (std::string_view fmt, TArgs... args) const inline
Definition at line 357 of file logging.hpp.
{
         if (enabled) {
             logger.debug(tag + fmt.data(), args...);
         }
     }
References il2cpp_utils::args, Logger::debug(), enabled, logger, and tag.
Referenced by AssemblyFunction::AssemblyFunction(), FindOrCreateInstruction(), il2cpp_utils::LogField(), il2cpp_utils::LogFields(), il2cpp_utils::LogMethod(), il2cpp_utils::LogMethods(), il2cpp_utils::LogProperties(), il2cpp_utils::LogProperty(), and InstructionTree::PopulateChildren().
error()
template<typename... TArgs> void LoggerContextObject::error (std::string_view fmt, TArgs... args) const inline
Definition at line 339 of file logging.hpp.
{
         if (enabled) {
             logger.error(tag + fmt.data(), args...);
         }
     }
References il2cpp_utils::args, enabled, Logger::error(), logger, and tag.
Referenced by il2cpp_utils::createManual().
getChildren()
const std::list<LoggerContextObject*> LoggerContextObject::getChildren () inline
The children contexts (empty if there are no children)
Definition at line 281 of file logging.hpp.
{
         return childrenContexts;
     }
References childrenContexts.
getParent()
constexpr const LoggerContextObject* LoggerContextObject::getParent () inline constexpr
The parent context (or nullptr if there is no parent)
Definition at line 277 of file logging.hpp.
{
         return parentContext;
     }
References parentContext.
info()
template<typename... TArgs> void LoggerContextObject::info (std::string_view fmt, TArgs... args) const inline
Definition at line 351 of file logging.hpp.
{
         if (enabled) {
             logger.info(tag + fmt.data(), args...);
         }
     }
References il2cpp_utils::args, enabled, Logger::info(), logger, and tag.
Referenced by il2cpp_functions::Init(), il2cpp_utils::LogFields(), il2cpp_utils::LogMethods(), and il2cpp_utils::LogProperties().
log() [1/2]
void LoggerContextObject::log (Logging::Level lvl, std::string str) const inline
Definition at line 321 of file logging.hpp.
{
         if (enabled) {
             logger.log(lvl, tag + str);
         }
     }
References enabled, Logger::log(), logger, and tag.
log() [2/2]
template<typename T , typename... TArgs> void LoggerContextObject::log (Logging::Level lvl, std::string_view fmt, T first, TArgs... args) const inline
Definition at line 327 of file logging.hpp.
{
         if (enabled) {
             logger.log(lvl, tag + fmt.data(), first, args...);
         }
     }
References il2cpp_utils::args, enabled, Logger::log(), logger, and tag.
operator==()
bool LoggerContextObject::operator== (const LoggerContextObject & other) const inline
Equality operator.
Definition at line 269 of file logging.hpp.
{
         return tag == other.tag && enabled == other.enabled && parentContext == other.parentContext;
     }
References enabled, parentContext, and tag.
warning()
template<typename... TArgs> void LoggerContextObject::warning (std::string_view fmt, TArgs... args) const inline
Definition at line 345 of file logging.hpp.
{
         if (enabled) {
             logger.warning(tag + fmt.data(), args...);
         }
     }
References il2cpp_utils::args, enabled, logger, tag, and Logger::warning().
Referenced by il2cpp_utils::LogMethods().
WithContext()
LoggerContextObject LoggerContextObject::WithContext (std::string_view ctx) inline
Enter a new context. This call forwards to logger.WithContext(this, ctx). Avoid entering contexts with names that contain % characters.
Parameters
ctx The context name to enter
Returns
The LoggerContextObject in the context
Definition at line 366 of file logging.hpp.
{
         auto tmp = logger.WithContext(this, ctx);
         // Copy over enabled
         tmp.enabled = enabled;
         return tmp;
     }
References enabled, logger, and Logger::WithContext().
Referenced by AssemblyFunction::AssemblyFunction(), il2cpp_utils::AssertMatch(), il2cpp_utils::BuildGenericsMap(), il2cpp_utils::createcsstr(), il2cpp_utils::createManual(), EvalSwitch(), ExtractAddress(), find_GC_free(), find_GC_SetWriteBarrier(), il2cpp_utils::FindField(), il2cpp_utils::FindMethod(), il2cpp_utils::FindMethodUnsafe(), FindOrCreateInstruction(), il2cpp_utils::FindProperty(), il2cpp_utils::GenericsToStringHelper(), il2cpp_utils::GetClassFromName(), il2cpp_utils::GetFieldClass(), il2cpp_utils::GetParamClass(), il2cpp_utils::GetSystemType(), il2cpp_functions::Init(), Instruction::Instruction(), il2cpp_utils::IsConvertible(), il2cpp_utils::MakeGeneric(), il2cpp_utils::MakeGenericMethod(), il2cpp_utils::MakeGenericType(), il2cpp_utils::newcsstr(), il2cpp_utils::ParameterMatch(), InstructionTree::PopulateChildren(), ProcessRegisterDependencies(), and trace_GC_AllocFixed().
Field Documentation
childrenContexts
std::list<LoggerContextObject*> LoggerContextObject::childrenContexts private
Definition at line 243 of file logging.hpp.
Referenced by changeChildren(), getChildren(), LoggerContextObject(), Logger::RecurseChangeContext(), and ~LoggerContextObject().
context
const std::string LoggerContextObject::context
The context of this LoggerContextObject.
Definition at line 275 of file logging.hpp.
Referenced by il2cpp_utils::GenericsToStringHelper(), LoggerContextObject(), Logger::RecurseChangeContext(), and Logger::WithContext().
enabled
bool LoggerContextObject::enabled = true private
Definition at line 233 of file logging.hpp.
Referenced by critical(), debug(), error(), info(), log(), operator==(), Logger::RecurseChangeContext(), warning(), and WithContext().
Logger
friend LoggerContextObject::Logger private
Definition at line 230 of file logging.hpp.
logger
Logger& LoggerContextObject::logger
The Logger reference.
Definition at line 273 of file logging.hpp.
Referenced by critical(), debug(), error(), info(), log(), LoggerContextObject(), warning(), WithContext(), and ~LoggerContextObject().
parentContext
LoggerContextObject* LoggerContextObject::parentContext = nullptr private
Definition at line 242 of file logging.hpp.
Referenced by getParent(), LoggerContextObject(), operator==(), and ~LoggerContextObject().
tag
std::string LoggerContextObject::tag private
Definition at line 232 of file logging.hpp.
Referenced by critical(), debug(), error(), info(), log(), LoggerContextObject(), operator==(), and warning().
The documentation for this class was generated from the following file:
shared/utils/logging.hpp