BeatSaber-Hooks: Canvas Class Reference
Canvas Class Reference
Public Member Functions
Canvas ()
~Canvas ()
void Clear ()
void AddShape (Shape *shape)
void Print (std::ostream &os)
Private Attributes
std::vector< Shape * > shapes_
Friends
template<typename Archiver >
Archiver & operator& (Archiver &ar, Canvas &c)
Detailed Description
Definition at line 202 of file archivertest.cpp.
Constructor & Destructor Documentation
Canvas()
Canvas::Canvas () inline
Definition at line 204 of file archivertest.cpp.
 : shapes_() {}
~Canvas()
Canvas::~Canvas () inline
Definition at line 205 of file archivertest.cpp.
 { Clear(); }
References Clear().
Member Function Documentation
AddShape()
void Canvas::AddShape (Shape * shape) inline
Definition at line 212 of file archivertest.cpp.
 { shapes_.push_back(shape); }
References shapes_.
Referenced by test3().
Clear()
void Canvas::Clear () inline
Definition at line 207 of file archivertest.cpp.
                  {
         for (std::vector<Shape*>::iterator itr = shapes_.begin(); itr != shapes_.end(); ++itr)
             delete *itr;
     }
References shapes_.
Referenced by ~Canvas().
Print()
void Canvas::Print (std::ostream & os) inline
Definition at line 214 of file archivertest.cpp.
{
         for (std::vector<Shape*>::iterator itr = shapes_.begin(); itr != shapes_.end(); ++itr) {
             (*itr)->Print(os);
             std::cout << std::endl;
         }
     }
References shapes_.
Referenced by test3().
Friends And Related Function Documentation
operator&
template<typename Archiver > Archiver& operator& (Archiver & ar, Canvas & c) friend
Definition at line 245 of file archivertest.cpp.
{
     size_t shapeCount = c.shapes_.size();
     ar.StartArray(&shapeCount);
     if (ar.IsReader) {
         c.Clear();
         c.shapes_.resize(shapeCount);
     }
     for (size_t i = 0; i < shapeCount; i++)
         ar & c.shapes_[i];
     return ar.EndArray();
 }
Field Documentation
shapes_
std::vector<Shape*> Canvas::shapes_ private
Definition at line 225 of file archivertest.cpp.
Referenced by AddShape(), Clear(), and Print().
The documentation for this class was generated from the following file:
shared/rapidjson/example/archiver/archivertest.cpp