BeatSaber-Hooks: AssemblyFunction Class Reference
AssemblyFunction Class Reference
#include <instruction-parsing.hpp>
Public Member Functions
AssemblyFunction (const int32_t *inst)
std::string toString () const
Data Fields
InstructionTree * instructions
Private Attributes
ParseState parseState
Friends
std::ostream & operator<< (std::ostream &os, const AssemblyFunction &func)
Detailed Description
Definition at line 238 of file instruction-parsing.hpp.
Constructor & Destructor Documentation
AssemblyFunction()
AssemblyFunction::AssemblyFunction (const int32_t * inst)
Definition at line 1324 of file instruction-parsing.cpp.
                                                    : parseState() {
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("AssemblyFunction");
     logger.debug("Starting dependency map: %s", DepMapToString(parseState.dependencyMap).c_str());
     auto root = new InstructionTree(pc);
     parseState.frontier.push({root, std::move(parseState.dependencyMap)});
     while (!parseState.frontier.empty()) {
         auto p = parseState.frontier.top();
         parseState.frontier.pop();
         parseState.dependencyMap = std::move(p.second);
         p.first->PopulateChildren(parseState);
     }
 }
References LoggerContextObject::debug(), ParseState::dependencyMap, DepMapToString(), ParseState::frontier, Logger::get(), parseState, Logger::WithContext(), and LoggerContextObject::WithContext().
Member Function Documentation
toString()
std::string AssemblyFunction::toString () const
Definition at line 1318 of file instruction-parsing.cpp.
{
     std::ostringstream ss;
     ss << *this;
     return ss.str();
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const AssemblyFunction & func) friend
Definition at line 1303 of file instruction-parsing.cpp.
{
     os << std::hex << std::uppercase;
     os << "Function candidates: " << std::endl;
     for (auto p : func.parseState.functionCandidates) {
         os << "0x" << uintptr_t(p.first) << " (offset 0x" << asOffset((uintptr_t)p.first) << "): depMap "
             << DepMapToString(p.second) << std::endl;
     }
     os << "Other jumps: " << std::endl;
     for (auto p : func.parseState.otherJumps) {
         os << "0x" << uintptr_t(p.first) << " (offset 0x" << asOffset((uintptr_t)p.first) << "): depMap "
             << DepMapToString(p.second) << std::endl;
     }
     return os << std::nouppercase << std::dec;
 }
Field Documentation
instructions
InstructionTree* AssemblyFunction::instructions
Definition at line 240 of file instruction-parsing.hpp.
parseState
ParseState AssemblyFunction::parseState private
Definition at line 246 of file instruction-parsing.hpp.
Referenced by AssemblyFunction().
The documentation for this class was generated from the following files:
shared/utils/instruction-parsing.hpp
src/utils/instruction-parsing.cpp