BeatSaber-Hooks: src/config/config-utils.cpp File Reference
config-utils.cpp File Reference
#include <stddef.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "../../shared/config/config-utils.hpp"
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include "modloader/shared/modloader.hpp"
Macros
#define CONFIG_DEFINED_H
Functions
bool parsejsonfile (ConfigDocument &doc, std::string_view filename)
bool parsejson (ConfigDocument &doc, std::string_view js)
std::string getDataDir (const ModInfo &info)
Returns a path to the persistent data directory for the provided const ModInfo&.
std::string getDataDir (std::string_view id)
Returns a path to the persistent data directory for ID.
Variables
bool readJson = false
static std::optional< std::string > dataDir
Macro Definition Documentation
CONFIG_DEFINED_H
#define CONFIG_DEFINED_H
Definition at line 2 of file config-utils.cpp.
Function Documentation
getDataDir() [1/2]
std::string getDataDir (const ModInfo & info)
Returns a path to the persistent data directory for the provided const ModInfo&.
Parameters
info The const ModInfo& to find a path for.
Returns
The path to the directory.
Definition at line 92 of file config-utils.cpp.
{
     if (!dataDir) {
         dataDir = string_format(PERSISTENT_DIR, Modloader::getApplicationId().c_str());
         if (!direxists(*dataDir)) {
             mkpath(*dataDir);
         }
     }
     return *dataDir + info.id.c_str() + "/";
 }
References dataDir, direxists(), Modloader::getApplicationId(), info, mkpath(), PERSISTENT_DIR, and string_format().
getDataDir() [2/2]
std::string getDataDir (std::string_view id)
Returns a path to the persistent data directory for ID.
Parameters
id The id to find a path for.
Returns
The path to the directory.
Definition at line 102 of file config-utils.cpp.
{
     if (!dataDir) {
         dataDir = string_format(PERSISTENT_DIR, Modloader::getApplicationId().c_str());
         if (!direxists(*dataDir)) {
             mkpath(*dataDir);
         }
     }
     return *dataDir + id.data() + "/";
 }
References dataDir, direxists(), Modloader::getApplicationId(), mkpath(), PERSISTENT_DIR, and string_format().
parsejson()
bool parsejson (ConfigDocument & doc, std::string_view js)
Definition at line 70 of file config-utils.cpp.
{
     char temp[js.length() + 1];
     memcpy(temp, js.data(), js.length());
     temp[js.length()] = '\0';
     if (doc.ParseInsitu(temp).HasParseError()) {
         return false;
     }
     return true;
 }
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu().
parsejsonfile()
bool parsejsonfile (ConfigDocument & doc, std::string_view filename)
Definition at line 58 of file config-utils.cpp.
{
     if (!fileexists(filename.data())) {
         return false;
     }
     std::ifstream is;
     is.open(filename.data());
     IStreamWrapper wrapper {is};
     return !doc.ParseStream(wrapper).HasParseError();
 }
References fileexists(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
Referenced by Configuration::Reload().
Variable Documentation
dataDir
std::optional<std::string> dataDir static
Definition at line 91 of file config-utils.cpp.
Referenced by getDataDir().
readJson
bool readJson = false
Definition at line 18 of file config-utils.cpp.
Referenced by Configuration::Load(), and Configuration::Reload().