BeatSaber-Hooks: shared/config/config-utils.hpp File Reference
config-utils.hpp File Reference
#include <optional>
#include <stdio.h>
#include <stdlib.h>
#include "../utils/utils-functions.h"
#include "rapidjson-utils.hpp"
#include "modloader/shared/modloader.hpp"
#include <string>
#include <string_view>
Data Structures
class Configuration
Macros
#define PERSISTENT_DIR "/sdcard/ModData/%s/Mods/"
#define CONFIG_PATH_FORMAT "/sdcard/ModData/%s/Configs/"
Typedefs
typedef rapidjson::Document ConfigDocument
typedef rapidjson::Value ConfigValue
typedef enum ParseError ParseError_t
typedef enum WriteError WriteError_t
typedef enum JsonParseError JsonParseError_t
Enumerations
enum ParseError { PARSE_ERROR_FILE_DOES_NOT_EXIST = -1 }
enum WriteError { WRITE_ERROR_COULD_NOT_MAKE_FILE = -1 }
enum JsonParseError { JSON_PARSE_ERROR = -1 }
Functions
bool parsejsonfile (rapidjson::Document &doc, std::string_view filename)
bool parsejson (ConfigDocument &doc, std::string_view js)
std::string getDataDir (const ModInfo &info)
Returns a path to the persistent data directory for the provided const ModInfo&.
std::string getDataDir (std::string_view id)
Returns a path to the persistent data directory for ID.
Macro Definition Documentation
CONFIG_PATH_FORMAT
#define CONFIG_PATH_FORMAT "/sdcard/ModData/%s/Configs/"
Definition at line 23 of file config-utils.hpp.
PERSISTENT_DIR
#define PERSISTENT_DIR "/sdcard/ModData/%s/Mods/"
Definition at line 20 of file config-utils.hpp.
Typedef Documentation
ConfigDocument
typedef rapidjson::Document ConfigDocument
Definition at line 16 of file config-utils.hpp.
ConfigValue
typedef rapidjson::Value ConfigValue
Definition at line 17 of file config-utils.hpp.
JsonParseError_t
typedef enum JsonParseError JsonParseError_t
ParseError_t
typedef enum ParseError ParseError_t
WriteError_t
typedef enum WriteError WriteError_t
Enumeration Type Documentation
JsonParseError
enum JsonParseError
Enumerator
JSON_PARSE_ERROR
Definition at line 73 of file config-utils.hpp.
{
     JSON_PARSE_ERROR = -1
 } JsonParseError_t;
ParseError
enum ParseError
Enumerator
PARSE_ERROR_FILE_DOES_NOT_EXIST
Definition at line 63 of file config-utils.hpp.
{
     PARSE_ERROR_FILE_DOES_NOT_EXIST = -1
 } ParseError_t;
WriteError
enum WriteError
Enumerator
WRITE_ERROR_COULD_NOT_MAKE_FILE
Definition at line 68 of file config-utils.hpp.
{
     WRITE_ERROR_COULD_NOT_MAKE_FILE = -1
 } WriteError_t;
Function Documentation
getDataDir() [1/2]
std::string getDataDir (const ModInfo & info)
Returns a path to the persistent data directory for the provided const ModInfo&.
Parameters
info The const ModInfo& to find a path for.
Returns
The path to the directory.
Definition at line 92 of file config-utils.cpp.
{
     if (!dataDir) {
         dataDir = string_format(PERSISTENT_DIR, Modloader::getApplicationId().c_str());
         if (!direxists(*dataDir)) {
             mkpath(*dataDir);
         }
     }
     return *dataDir + info.id.c_str() + "/";
 }
References dataDir, direxists(), Modloader::getApplicationId(), info, mkpath(), PERSISTENT_DIR, and string_format().
getDataDir() [2/2]
std::string getDataDir (std::string_view id)
Returns a path to the persistent data directory for ID.
Parameters
id The id to find a path for.
Returns
The path to the directory.
Definition at line 102 of file config-utils.cpp.
{
     if (!dataDir) {
         dataDir = string_format(PERSISTENT_DIR, Modloader::getApplicationId().c_str());
         if (!direxists(*dataDir)) {
             mkpath(*dataDir);
         }
     }
     return *dataDir + id.data() + "/";
 }
References dataDir, direxists(), Modloader::getApplicationId(), mkpath(), PERSISTENT_DIR, and string_format().
parsejson()
bool parsejson (ConfigDocument & doc, std::string_view js)
Definition at line 70 of file config-utils.cpp.
{
     char temp[js.length() + 1];
     memcpy(temp, js.data(), js.length());
     temp[js.length()] = '\0';
     if (doc.ParseInsitu(temp).HasParseError()) {
         return false;
     }
     return true;
 }
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu().
parsejsonfile()
bool parsejsonfile (rapidjson::Document & doc, std::string_view filename)
Definition at line 58 of file config-utils.cpp.
{
     if (!fileexists(filename.data())) {
         return false;
     }
     std::ifstream is;
     is.open(filename.data());
     IStreamWrapper wrapper {is};
     return !doc.ParseStream(wrapper).HasParseError();
 }
References fileexists(), rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
Referenced by Configuration::Reload().