BeatSaber-Hooks: shared/rapidjson/test/unittest/filestreamtest.cpp File Reference
filestreamtest.cpp File Reference
#include "unittest.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/encodedstream.h"
Data Structures
class FileStreamTest
Functions
TEST_F (FileStreamTest, FileReadStream)
TEST_F (FileStreamTest, FileReadStream_Peek4)
TEST_F (FileStreamTest, FileWriteStream)
Function Documentation
TEST_F() [1/3]
TEST_F (FileStreamTest , FileReadStream)
Definition at line 90 of file filestreamtest.cpp.
{
     FILE *fp = fopen(filename_, "rb");
     ASSERT_TRUE(fp != 0);
     char buffer[65536];
     FileReadStream s(fp, buffer, sizeof(buffer));
     for (size_t i = 0; i < length_; i++) {
         EXPECT_EQ(json_[i], s.Peek());
         EXPECT_EQ(json_[i], s.Peek());  // 2nd time should be the same
         EXPECT_EQ(json_[i], s.Take());
     }
     EXPECT_EQ(length_, s.Tell());
     EXPECT_EQ('\0', s.Peek());
     fclose(fp);
 }
References rapidjson::FileReadStream::Peek(), rapidjson::FileReadStream::Take(), and rapidjson::FileReadStream::Tell().
TEST_F() [2/3]
TEST_F (FileStreamTest , FileReadStream_Peek4)
Definition at line 108 of file filestreamtest.cpp.
{
     FILE *fp = fopen(abcde_, "rb");
     ASSERT_TRUE(fp != 0);
     char buffer[4];
     FileReadStream s(fp, buffer, sizeof(buffer));
     const char* c = s.Peek4();
     for (int i = 0; i < 4; i++)
         EXPECT_EQ('a' + i, c[i]);
     EXPECT_EQ(0u, s.Tell());
     for (int i = 0; i < 5; i++) {
         EXPECT_EQ(static_cast<size_t>(i), s.Tell());
         EXPECT_EQ('a' + i, s.Peek());
         EXPECT_EQ('a' + i, s.Peek());
         EXPECT_EQ('a' + i, s.Take());
     }
     EXPECT_EQ(5u, s.Tell());
     EXPECT_EQ(0, s.Peek());
     EXPECT_EQ(0, s.Take());
     fclose(fp);
 }
References rapidjson::FileReadStream::Peek(), rapidjson::FileReadStream::Peek4(), rapidjson::FileReadStream::Take(), and rapidjson::FileReadStream::Tell().
TEST_F() [3/3]
TEST_F (FileStreamTest , FileWriteStream)
Definition at line 132 of file filestreamtest.cpp.
{
     char filename[L_tmpnam];
     FILE* fp = TempFile(filename);
     char buffer[65536];
     FileWriteStream os(fp, buffer, sizeof(buffer));
     for (size_t i = 0; i < length_; i++)
         os.Put(json_[i]);
     os.Flush();
     fclose(fp);
     // Read it back to verify
     fp = fopen(filename, "rb");
     FileReadStream is(fp, buffer, sizeof(buffer));
     for (size_t i = 0; i < length_; i++)
         EXPECT_EQ(json_[i], is.Take());
     EXPECT_EQ(length_, is.Tell());
     fclose(fp);
     //std::cout << filename << std::endl;
     remove(filename);
 }
References rapidjson::FileWriteStream::Flush(), rapidjson::FileWriteStream::Put(), rapidjson::FileReadStream::Take(), rapidjson::FileReadStream::Tell(), and TempFile().