BeatSaber-Hooks: shared/rapidjson/example/filterkeydom/filterkeydom.cpp File Reference
filterkeydom.cpp File Reference
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/error/en.h"
#include <stack>
Data Structures
class FilterKeyHandler< OutputHandler >
class FilterKeyReader< InputStream >
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 140 of file filterkeydom.cpp.
{
     if (argc != 2) {
         fprintf(stderr, "filterkeydom key < input.json > output.json\n");
         return 1;
     }
     // Prepare input stream.
     char readBuffer[65536];
     FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
     // Prepare Filter
     FilterKeyReader<FileReadStream> reader(is, argv[1], static_cast<SizeType>(strlen(argv[1])));
     // Populates the filtered events from reader
     Document document;
     document.Populate(reader);
     ParseResult pr = reader.GetParseResult();
     if (!pr) {
         fprintf(stderr, "\nError(%u): %s\n", static_cast<unsigned>(pr.Offset()), GetParseError_En(pr.Code()));
         return 1;
     }
     // Prepare JSON writer and output stream.
     char writeBuffer[65536];
     FileWriteStream os(stdout, writeBuffer, sizeof(writeBuffer));
     Writer<FileWriteStream> writer(os);
     // Write the document to standard output
     document.Accept(writer);
     return 0;
 }
References rapidjson::ParseResult::Code(), rapidjson::GetParseError_En(), FilterKeyReader< InputStream >::GetParseResult(), rapidjson::ParseResult::Offset(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Populate().