BeatSaber-Hooks: shared/rapidjson/example/filterkey/filterkey.cpp File Reference
filterkey.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/writer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/error/en.h"
#include <stack>
Data Structures
class FilterKeyHandler< OutputHandler >
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 108 of file filterkey.cpp.
{
     if (argc != 2) {
         fprintf(stderr, "filterkey key < input.json > output.json\n");
         return 1;
     }
     // Prepare JSON reader and input stream.
     Reader reader;
     char readBuffer[65536];
     FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
     // Prepare JSON writer and output stream.
     char writeBuffer[65536];
     FileWriteStream os(stdout, writeBuffer, sizeof(writeBuffer));
     Writer<FileWriteStream> writer(os);
     // Prepare Filter
     FilterKeyHandler<Writer<FileWriteStream> > filter(writer, argv[1], static_cast<SizeType>(strlen(argv[1])));
     // JSON reader parse from the input stream, filter handler filters the events, and forward to writer.
     // i.e. the events flow is: reader -> filter -> writer
     if (!reader.Parse(is, filter)) {
         fprintf(stderr, "\nError(%u): %s\n", static_cast<unsigned>(reader.GetErrorOffset()), GetParseError_En(reader.GetParseErrorCode()));
         return 1;
     }
     return 0;
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), rapidjson::GetParseError_En(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().