BeatSaber-Hooks: shared/utils/gc-alloc.hpp File Reference
gc-alloc.hpp File Reference
#include <stddef.h>
Functions
void * gc_alloc_specific (size_t sz)
Returns an allocated instance of the provided size that will not be written over by future GC allocations and holds references. You MUST use the gc_free_specific function defined here to destroy it. This function fallsback to calloc if no GC_Alloc or GC_Free implementations are found via xref/sigscan.
void gc_free_specific (void *ptr) noexcept
Deletes the provided allocated instance from the gc_alloc_specific function defined here. Other pointers will cause undefined behavior. This function will call GC_free if there is both a GC_Alloc and GC_Free implementation available, free otherwise.
void * gc_realloc_specific (void *ptr, size_t new_size)
Reallocation implementation is equivalent to: alloc + free.
Function Documentation
gc_alloc_specific()
void* gc_alloc_specific (size_t sz)
Returns an allocated instance of the provided size that will not be written over by future GC allocations and holds references. You MUST use the gc_free_specific function defined here to destroy it. This function fallsback to calloc if no GC_Alloc or GC_Free implementations are found via xref/sigscan.
Parameters
sz The size to allocate an instance of.
Returns
The allocated instance.
Definition at line 6 of file gc-alloc.cpp.
{
     // This function assumes il2cpp_functions will be called at a reasonable time, instead will warn you on allocating unsafe memory.
     if (il2cpp_functions::GarbageCollector_AllocateFixed && il2cpp_functions::GC_free) {
         // We should absolutely panic if we thought we had the allocation function, but it gave us null.
         auto* ptr = CRASH_UNLESS(il2cpp_functions::GarbageCollector_AllocateFixed(sz, nullptr));
         return ptr;
     } else {
         auto* ptr = calloc(1, sz);
         // We cannot use our logger because we allocate it using this function.
         __android_log_print(Logging::WARNING, "QuestHook[GC_Alloc]", "Allocation at: %p for size: %lu fallback to calloc!", ptr, sz);
         return ptr;
     }
 }
References il2cpp_functions::GarbageCollector_AllocateFixed, il2cpp_functions::GC_free, and Logging::WARNING.
Referenced by il2cpp_utils::AddNestedTypesToNametoClassHashTable(), il2cpp_utils::createManual(), and gc_realloc_specific().
gc_free_specific()
void gc_free_specific (void * ptr) noexcept
Deletes the provided allocated instance from the gc_alloc_specific function defined here. Other pointers will cause undefined behavior. This function will call GC_free if there is both a GC_Alloc and GC_Free implementation available, free otherwise.
Parameters
sz The pointer to free explicitly.
Returns
The allocated instance.
Definition at line 27 of file gc-alloc.cpp.
{
     if (il2cpp_functions::GarbageCollector_AllocateFixed && il2cpp_functions::GC_free) {
         il2cpp_functions::GC_free(ptr);
     }
     // TODO: Also check if a GC free would have been valid?
     else {
         free(ptr);
     }
 }
References il2cpp_functions::GarbageCollector_AllocateFixed, and il2cpp_functions::GC_free.
Referenced by gc_realloc_specific().
gc_realloc_specific()
void* gc_realloc_specific (void * ptr, size_t new_size)
Reallocation implementation is equivalent to: alloc + free.
Parameters
ptr The pointer to resize.
new_size The new size of the memory.
Returns
The resized instance.
Definition at line 20 of file gc-alloc.cpp.
{
     auto* nPtr = gc_alloc_specific(new_size);
     memcpy(nPtr, ptr, new_size);
     gc_free_specific(ptr);
     return nPtr;
 }
References gc_alloc_specific(), and gc_free_specific().