BeatSaber-Hooks: src/utils/hook-tracker.cpp File Reference
hook-tracker.cpp File Reference
#include "../../shared/utils/hook-tracker.hpp"
#include "shared/utils/instruction-parsing.hpp"
#include <dirent.h>
Macros
#define LIBS_FILE_PATH "/sdcard/Android/data/%s/files/libs"
#define MOD_TEMP_PATH_FMT "/data/data/%s/"
#define HOOKTRACKER_ORIG_SEARCH_COUNT 500
Functions
const void * __HOOKTRACKER_GET_HOOKS ()
const void * getOrigHelper (const void *const location, bool inTrampoline=false) noexcept
Macro Definition Documentation
HOOKTRACKER_ORIG_SEARCH_COUNT
#define HOOKTRACKER_ORIG_SEARCH_COUNT 500
Definition at line 136 of file hook-tracker.cpp.
LIBS_FILE_PATH
#define LIBS_FILE_PATH "/sdcard/Android/data/%s/files/libs"
Definition at line 69 of file hook-tracker.cpp.
MOD_TEMP_PATH_FMT
#define MOD_TEMP_PATH_FMT "/data/data/%s/"
Definition at line 72 of file hook-tracker.cpp.
Function Documentation
__HOOKTRACKER_GET_HOOKS()
const void* __HOOKTRACKER_GET_HOOKS ()
Definition at line 130 of file hook-tracker.cpp.
{
     return reinterpret_cast<const void*>(HookTracker::GetHooks());
 }
References HookTracker::GetHooks().
getOrigHelper()
const void* getOrigHelper (const void *const location, bool inTrampoline = false) noexcept
Definition at line 140 of file hook-tracker.cpp.
{
     // If we are a hook, we can't find our orig here, we must travel to our hook implementation.
     Instruction inst(reinterpret_cast<const int32_t*>(location));
     if (inst.isNOP()) {
         inst = Instruction(reinterpret_cast<const int32_t*>(location) + 1);
     }
     if (inst.isLoad() && inst.size == 8 && inst.label == inst.addr + 2) {
         // For hooks, label will always be 8 past address of function.
         // This label points to the trampoline.
         // However, this isn't necessarily all we need to do, since we could have MULTIPLE functions hooking this.
         // So, we will need to recurse here as well.
         return getOrigHelper(reinterpret_cast<const void*>(*inst.label), true);
     }
     if (!inTrampoline) {
         // If we are not in a trampoline and we are not hooked, we simply exit.
         return location;
     }
     // Look for all BLs in this function, if we find any, trace their remaining asm to see if they match the remaining instructions from our location
     // We shall assume for the sake of simplicity that the original function is going to be called within 100 instructions
     for (int i = 0; i < HOOKTRACKER_ORIG_SEARCH_COUNT; i++) {
         if (inst.branchType == Instruction::BranchType::INDCALL) {
             // Source register needs to be emulated/traced
             // It should be from a LDR from a static field
             // inst.Rs[0]
         }
     }
     // We can't find the orig function, but we know we are in a trampoline. Chances are the orig is not called or this function is too big.
     return location;
 }
References Instruction::addr, Instruction::branchType, HOOKTRACKER_ORIG_SEARCH_COUNT, Instruction::isLoad(), Instruction::isNOP(), Instruction::label, location, and Instruction::size.