BeatSaber-Hooks: src/utils/il2cpp-utils-methods.cpp File Reference
il2cpp-utils-methods.cpp File Reference
#include "../../shared/utils/il2cpp-utils-methods.hpp"
#include "../../shared/utils/hashing.hpp"
#include <sstream>
#include "../../shared/utils/typedefs.h"
Data Structures
struct std::hash< std::vector< T > >
Namespaces
il2cpp_utils
Typedefs
typedef std::pair< std::string, std::vector< const Il2CppType * > > il2cpp_utils::classesNamesTypesInnerPairType
Functions
template<class T >
void std::hash_combine (size_t &seed, T v)
template<class T >
std::size_t std::hash_seq (T const &seq) noexcept
const MethodInfo * il2cpp_utils::MakeGenericMethod (const MethodInfo *info, std::vector< Il2CppClass * > types) noexcept
const MethodInfo * il2cpp_utils::FindMethodUnsafe (const Il2CppClass *klass, std::string_view methodName, int argsCount) noexcept
const MethodInfo * il2cpp_utils::FindMethodUnsafe (std::string_view nameSpace, std::string_view className, std::string_view methodName, int argsCount) noexcept
const MethodInfo * il2cpp_utils::FindMethodUnsafe (Il2CppObject *instance, std::string_view methodName, int argsCount) noexcept
const MethodInfo * il2cpp_utils::FindMethod (FindMethodInfo &info) noexcept
void il2cpp_utils::LogMethods (LoggerContextObject &logger, Il2CppClass *klass, bool logParents)
void il2cpp_utils::LogMethod (LoggerContextObject &logger, const MethodInfo *method)
bool il2cpp_utils::IsConvertible (const Il2CppType *to, const Il2CppType *from, bool asArgs)
Variables
static std::unordered_map< std::pair< const Il2CppClass *, std::pair< std::string, decltype(MethodInfo::parameters_count)> >, const MethodInfo *, hash_pair_3 > il2cpp_utils::classesNamesToMethodsCache
static std::unordered_map< std::pair< const Il2CppClass *, classesNamesTypesInnerPairType >, const MethodInfo *, hash_pair_3 > il2cpp_utils::classesNamesTypesToMethodsCache
std::mutex il2cpp_utils::classNamesMethodsLock
std::mutex il2cpp_utils::classTypesMethodsLock
Function Documentation
hash_combine()
template<class T > void std::hash_combine (size_t & seed, T v)
Definition at line 8 of file il2cpp-utils-methods.cpp.
{
         seed ^= std::hash<T>{}(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
     }
References std::hash_combine().
Referenced by std::hash_combine(), and std::hash_seq().
hash_seq()
template<class T > std::size_t std::hash_seq (T const & seq) noexcept
Definition at line 14 of file il2cpp-utils-methods.cpp.
{
         std::size_t seed = seq.size();
         for(auto i: seq) {
             hash_combine(seed, i);
         }
         return seed;
     }
References std::hash_combine(), and std::hash_seq().
Referenced by std::hash_seq(), and std::hash< std::vector< T > >::operator()().