BeatSaber-Hooks: src/utils/il2cpp-functions.cpp File Reference
il2cpp-functions.cpp File Reference
#include <unistd.h>
#include "../../shared/utils/utils.h"
#include "../../shared/utils/il2cpp-functions.hpp"
#include "../../shared/utils/instruction-parsing.hpp"
#include "../../shared/utils/logging.hpp"
#include "modloader/shared/modloader.hpp"
Functions
static bool find_GC_free (const int32_t *Runtime_Shutdown)
static bool find_GC_SetWriteBarrier (const int32_t *set_wbarrier_field)
void * __wrapper_gc_malloc_uncollectable (size_t sz, [[maybe_unused]] void *desc)
static bool trace_GC_AllocFixed (Instruction *DomainGetCurrent)
static bool find_GC_AllocFixed (Instruction *DomainGetCurrent)
void hook_shutdown_hook ()
Variables
void *(* wrapped_gc_malloc_uncollectable)(size_t sz, long long type)
void(* shutdown_hook)() = NULL
Function Documentation
__wrapper_gc_malloc_uncollectable()
void* __wrapper_gc_malloc_uncollectable (size_t sz, [[maybe_unused] ] void * desc)
Definition at line 414 of file il2cpp-functions.cpp.
{
     // 2 determined from ghidra dump of caller
     return wrapped_gc_malloc_uncollectable(sz, 2);
 }
References wrapped_gc_malloc_uncollectable.
Referenced by find_GC_AllocFixed().
find_GC_AllocFixed()
static bool find_GC_AllocFixed (Instruction * DomainGetCurrent) static
Definition at line 430 of file il2cpp-functions.cpp.
{
     if (!trace_GC_AllocFixed(DomainGetCurrent)) {
         bool multipleMatches;
         auto sigMatch = findUniquePatternInLibil2cpp(multipleMatches, "f5 0f 1d f8 f4 4f 01 a9 fd 7b 02 a9"
             "fd 83 00 91 ?? ?? ?? ?? ?? ?? ?? ?? 1f 00 20 f1 f3 03 01 2a", "GC_Malloc_Uncollectable");
         if (sigMatch && !multipleMatches) {
             // We need to make a wrapper method instead and set that.
             wrapped_gc_malloc_uncollectable = (decltype(wrapped_gc_malloc_uncollectable))sigMatch;
             il2cpp_functions::GarbageCollector_AllocateFixed = &__wrapper_gc_malloc_uncollectable;
         } else {
             return false;
         }
     }
     return true;
 }
References __wrapper_gc_malloc_uncollectable(), findUniquePatternInLibil2cpp(), il2cpp_functions::GarbageCollector_AllocateFixed, trace_GC_AllocFixed(), and wrapped_gc_malloc_uncollectable.
Referenced by il2cpp_functions::Init().
find_GC_free()
static bool find_GC_free (const int32_t * Runtime_Shutdown) static
Definition at line 379 of file il2cpp-functions.cpp.
{
     bool multipleMatches;
     auto sigMatch = findUniquePatternInLibil2cpp(multipleMatches, "f8 5f bc a9 f6 57 01 a9 f4 4f 02 a9 "
         "fd 7b 03 a9 fd c3 00 91 a0 08 00 b4 f3 03 00 aa ?? ?? ?? ?? 69 82 56 d3 4a ?? ?? 91 4b 0d 09 8b 49 55 40 f9 "
         "0a 9c 9c 52 0a 04 a0 72 00 cc 74 92 68 fe 56 d3 6c 01 0a 8b 0a 03 84 52", "GC_free");
     if (sigMatch && !multipleMatches) {
         il2cpp_functions::GC_free = (decltype(il2cpp_functions::GC_free))sigMatch;
     } else {
         static auto logger = il2cpp_functions::getFuncLogger().WithContext("find_GC_free");
         // xref tracing __WILL__ fail if Runtime_Shutdown is hooked by __ANY__ lib/mod, such as another bs-hook's file logger.
         Instruction Runtime_Shutdown_inst(Runtime_Shutdown);
         auto blr = RET_0_UNLESS(logger, Runtime_Shutdown_inst.findNth(1, std::mem_fn(&Instruction::isIndirectBranch)));
         auto j2GC_FF = RET_0_UNLESS(logger, blr->findNthCall(5));  // BL(R)
         if (blr != &Runtime_Shutdown_inst) delete blr;
         Instruction GC_FreeFixed(RET_0_UNLESS(logger, j2GC_FF->label));
         il2cpp_functions::GC_free = (decltype(il2cpp_functions::GC_free))RET_0_UNLESS(logger, GC_FreeFixed.label);
         if (j2GC_FF != blr) delete j2GC_FF;
     }
     return true;
 }
References Instruction::findNth(), findUniquePatternInLibil2cpp(), il2cpp_functions::GC_free, il2cpp_functions::getFuncLogger(), Instruction::isIndirectBranch(), Instruction::label, RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by il2cpp_functions::Init().
find_GC_SetWriteBarrier()
static bool find_GC_SetWriteBarrier (const int32_t * set_wbarrier_field) static
Definition at line 400 of file il2cpp-functions.cpp.
{
     if (!set_wbarrier_field) {
         return false;
     }
     static auto logger = il2cpp_functions::getFuncLogger().WithContext("find_GC_SetWriteBarrier");
     Instruction gc_wbarrier_start(set_wbarrier_field);
     auto* swb = RET_0_UNLESS(logger, gc_wbarrier_start.findNthDirectBranchWithoutLink(1));
     il2cpp_functions::GarbageCollector_SetWriteBarrier = (decltype(il2cpp_functions::GarbageCollector_SetWriteBarrier))RET_0_UNLESS(logger, swb->label);
     if (swb != &gc_wbarrier_start) delete swb;
     return true;
 }
References Instruction::findNthDirectBranchWithoutLink(), il2cpp_functions::GarbageCollector_SetWriteBarrier, il2cpp_functions::getFuncLogger(), RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by il2cpp_functions::Init().
hook_shutdown_hook()
void hook_shutdown_hook ()
Definition at line 454 of file il2cpp-functions.cpp.
{
     Logger::closeAll();
     shutdown_hook();
 }
References Logger::closeAll(), and shutdown_hook.
trace_GC_AllocFixed()
static bool trace_GC_AllocFixed (Instruction * DomainGetCurrent) static
Definition at line 419 of file il2cpp-functions.cpp.
{
     static auto logger = il2cpp_functions::getFuncLogger().WithContext("trace_GC_AllocFixed");
     // Domain::GetCurrent has a single bl to GarbageCollector::AllocateFixed
     // MetadataCache::InitializeGCSafe is 3rd bl after first b.ne, which is the 6th b(.lt, .ne), t(bz, nz), c(bz, nz)
     Instruction domainGetCurrentImpl(RET_0_UNLESS(logger, DomainGetCurrent->label));
     auto* gcAlloc = RET_0_UNLESS(logger, domainGetCurrentImpl.findNthCall(1));
     il2cpp_functions::GarbageCollector_AllocateFixed = (decltype(il2cpp_functions::GarbageCollector_AllocateFixed))RET_0_UNLESS(logger, gcAlloc->label);
     if (gcAlloc != &domainGetCurrentImpl) delete gcAlloc;
     return true;
 }
References Instruction::findNthCall(), il2cpp_functions::GarbageCollector_AllocateFixed, il2cpp_functions::getFuncLogger(), Instruction::label, RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by find_GC_AllocFixed().
Variable Documentation
shutdown_hook
void(* shutdown_hook) () () = NULL
Definition at line 454 of file il2cpp-functions.cpp.
Referenced by hook_shutdown_hook().
wrapped_gc_malloc_uncollectable
void*(* wrapped_gc_malloc_uncollectable) (size_t sz, long long type) (size_t sz, long long type)
Definition at line 412 of file il2cpp-functions.cpp.
Referenced by __wrapper_gc_malloc_uncollectable(), and find_GC_AllocFixed().