BeatSaber-Hooks: shared/inline-hook/inlineHook.h File Reference
inlineHook.h File Reference
#include <stdio.h>
Enumerations
enum ele7en_status {
ELE7EN_ERROR_UNKNOWN = -1 , ELE7EN_OK = 0 , ELE7EN_ERROR_NOT_INITIALIZED , ELE7EN_ERROR_NOT_EXECUTABLE ,
ELE7EN_ERROR_NOT_REGISTERED , ELE7EN_ERROR_NOT_HOOKED , ELE7EN_ERROR_ALREADY_REGISTERED , ELE7EN_ERROR_ALREADY_HOOKED ,
ELE7EN_ERROR_SO_NOT_FOUND , ELE7EN_ERROR_FUNCTION_NOT_FOUND
}
Functions
enum ele7en_status registerInlineHook (uint32_t target_addr, uint32_t new_addr, uint32_t **proto_addr)
enum ele7en_status inlineUnHook (uint32_t target_addr)
void inlineUnHookAll ()
enum ele7en_status inlineHook (uint32_t target_addr)
void inlineHookAll ()
Enumeration Type Documentation
ele7en_status
enum ele7en_status
Enumerator
ELE7EN_ERROR_UNKNOWN
ELE7EN_OK
ELE7EN_ERROR_NOT_INITIALIZED
ELE7EN_ERROR_NOT_EXECUTABLE
ELE7EN_ERROR_NOT_REGISTERED
ELE7EN_ERROR_NOT_HOOKED
ELE7EN_ERROR_ALREADY_REGISTERED
ELE7EN_ERROR_ALREADY_HOOKED
ELE7EN_ERROR_SO_NOT_FOUND
ELE7EN_ERROR_FUNCTION_NOT_FOUND
Definition at line 10 of file inlineHook.h.
                    {
     ELE7EN_ERROR_UNKNOWN = -1,
     ELE7EN_OK = 0,
     ELE7EN_ERROR_NOT_INITIALIZED,
     ELE7EN_ERROR_NOT_EXECUTABLE,
     ELE7EN_ERROR_NOT_REGISTERED,
     ELE7EN_ERROR_NOT_HOOKED,
     ELE7EN_ERROR_ALREADY_REGISTERED,
     ELE7EN_ERROR_ALREADY_HOOKED,
     ELE7EN_ERROR_SO_NOT_FOUND,
     ELE7EN_ERROR_FUNCTION_NOT_FOUND
 };
Function Documentation
inlineHook()
enum ele7en_status inlineHook (uint32_t target_addr)
Definition at line 343 of file inlineHook.c.
 {
     int i;
     struct inlineHookItem *item;
     item = NULL;
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].target_addr == target_addr) {
             item = &info.item[i];
             break;
         }
     }
     if (item == NULL) {
         return ELE7EN_ERROR_NOT_REGISTERED;
     }
     if (item->status == REGISTERED) {
         pid_t pid;
         pid = freeze(item, ACTION_ENABLE);
         doInlineHook(item);
         unFreeze(pid);
         return ELE7EN_OK;
     }
     else if (item->status == HOOKED) {
         return ELE7EN_ERROR_ALREADY_HOOKED;
     }
     else {
         return ELE7EN_ERROR_UNKNOWN;
     }
 }
inlineHookAll()
void inlineHookAll ()
Definition at line 411 of file inlineHook.c.
 {
     pid_t pid;
     int i;
     pid = freeze(NULL, ACTION_ENABLE);
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].status == REGISTERED) {
             doInlineHook(&info.item[i]);
         }
     }
     unFreeze(pid);
 }
References ACTION_ENABLE, doInlineHook(), freeze(), info, inlineHookInfo::item, REGISTERED, inlineHookInfo::size, inlineHookItem::status, and unFreeze().
inlineUnHook()
enum ele7en_status inlineUnHook (uint32_t target_addr)
Definition at line 292 of file inlineHook.c.
 {
     int i;
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].target_addr == target_addr && info.item[i].status == HOOKED) {
             pid_t pid;
             pid = freeze(&info.item[i], ACTION_DISABLE);
             doInlineUnHook(&info.item[i], i);
             unFreeze(pid);
             return ELE7EN_OK;
         }
     }
     return ELE7EN_ERROR_NOT_HOOKED;
 }
inlineUnHookAll()
void inlineUnHookAll ()
Definition at line 326 of file inlineHook.c.
 {
     pid_t pid;
     int i;
     pid = freeze(NULL, ACTION_DISABLE);
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].status == HOOKED) {
             doInlineUnHook(&info.item[i], i);
             --i;
         }
     }
     unFreeze(pid);
 }
References ACTION_DISABLE, doInlineUnHook(), freeze(), HOOKED, info, inlineHookInfo::item, inlineHookInfo::size, inlineHookItem::status, and unFreeze().
registerInlineHook()
enum ele7en_status registerInlineHook (uint32_t target_addr, uint32_t new_addr, uint32_t ** proto_addr)
Definition at line 246 of file inlineHook.c.
 {
     struct inlineHookItem *item;
     if (!isExecutableAddr(target_addr) || !isExecutableAddr(new_addr)) {
         return ELE7EN_ERROR_NOT_EXECUTABLE;
     }
     item = findInlineHookItem(target_addr);
     if (item != NULL) {
         if (item->status == REGISTERED) {
             return ELE7EN_ERROR_ALREADY_REGISTERED;
         }
         else if (item->status == HOOKED) {
             return ELE7EN_ERROR_ALREADY_HOOKED;
         }
         else {
             return ELE7EN_ERROR_UNKNOWN;
         }
     }
     item = addInlineHookItem();
     item->target_addr = target_addr;
     item->new_addr = new_addr;
     item->proto_addr = proto_addr;
     item->length = TEST_BIT0(item->target_addr) ? 12 : 8;
     // TODO: Allocate this in a place where GC doesn't ruin it
     item->orig_instructions = malloc(item->length);
     memcpy(item->orig_instructions, (void *) CLEAR_BIT0(item->target_addr), item->length);
     item->trampoline_instructions = mmap(NULL, PAGE_SIZE, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_ANONYMOUS | MAP_PRIVATE, 0, 0);
     relocateInstruction(item->target_addr, item->orig_instructions, item->length, item->trampoline_instructions, item->orig_boundaries, item->trampoline_boundaries, &item->count);
     item->status = REGISTERED;
     return ELE7EN_OK;
 }