BeatSaber-Hooks: src/inline-hook/inlineHook.c File Reference
inlineHook.c File Reference
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <dirent.h>
#include <signal.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <sys/ptrace.h>
#include "relocate.h"
#include "inlineHook.h"
Data Structures
struct inlineHookItem
struct inlineHookInfo
Macros
#define PAGE_SIZE 4096
#define PAGE_START(addr) (~(PAGE_SIZE - 1) & (addr))
#define SET_BIT0(addr) (addr | 1)
#define CLEAR_BIT0(addr) (addr & 0xFFFFFFFE)
#define TEST_BIT0(addr) (addr & 1)
#define ACTION_ENABLE 0
#define ACTION_DISABLE 1
Enumerations
enum hook_status { REGISTERED , HOOKED }
Functions
static int getAllTids (pid_t exclude_tid, pid_t *tids)
static bool doProcessThreadPC (struct inlineHookItem *item, struct pt_regs *regs, int action)
static void processThreadPC (pid_t tid, struct inlineHookItem *item, int action)
static pid_t freeze (struct inlineHookItem *item, int action)
static void unFreeze (pid_t pid)
static bool isExecutableAddr (uint32_t addr)
static struct inlineHookItem * findInlineHookItem (uint32_t target_addr)
static struct inlineHookItem * addInlineHookItem ()
static void deleteInlineHookItem (int pos)
enum ele7en_status registerInlineHook (uint32_t target_addr, uint32_t new_addr, uint32_t **proto_addr)
static void doInlineUnHook (struct inlineHookItem *item, int pos)
enum ele7en_status inlineUnHook (uint32_t target_addr)
void inlineUnHookAll ()
static void doInlineHook (struct inlineHookItem *item)
enum ele7en_status inlineHook (uint32_t target_addr)
void inlineHookAll ()
Variables
static struct inlineHookInfo info = {0}
Macro Definition Documentation
ACTION_DISABLE
#define ACTION_DISABLE 1
Definition at line 33 of file inlineHook.c.
ACTION_ENABLE
#define ACTION_ENABLE 0
Definition at line 32 of file inlineHook.c.
CLEAR_BIT0
#define CLEAR_BIT0 (addr) (addr & 0xFFFFFFFE)
Definition at line 29 of file inlineHook.c.
PAGE_SIZE
#define PAGE_SIZE 4096
Definition at line 24 of file inlineHook.c.
PAGE_START
#define PAGE_START (addr) (~(PAGE_SIZE - 1) & (addr))
Definition at line 27 of file inlineHook.c.
SET_BIT0
#define SET_BIT0 (addr) (addr | 1)
Definition at line 28 of file inlineHook.c.
TEST_BIT0
#define TEST_BIT0 (addr) (addr & 1)
Definition at line 30 of file inlineHook.c.
Enumeration Type Documentation
hook_status
enum hook_status
Enumerator
REGISTERED
HOOKED
Definition at line 35 of file inlineHook.c.
                  {
     REGISTERED,
     HOOKED,
 };
Function Documentation
addInlineHookItem()
static struct inlineHookItem* addInlineHookItem () static
Definition at line 233 of file inlineHook.c.
{
     struct inlineHookItem *item;
     if (info.size >= 1024) {
         return NULL;
     }
     item = &info.item[info.size];
     ++info.size;
     return item;
 }
References info, inlineHookInfo::item, and inlineHookInfo::size.
deleteInlineHookItem()
static void deleteInlineHookItem (int pos) static
Definition at line 246 of file inlineHook.c.
 {
     info.item[pos] = info.item[info.size - 1];
     --info.size;
 }
References info, inlineHookInfo::item, and inlineHookInfo::size.
Referenced by doInlineUnHook().
doInlineHook()
static void doInlineHook (struct inlineHookItem * item) static
Definition at line 343 of file inlineHook.c.
 {
     mprotect((void *) PAGE_START(CLEAR_BIT0(item->target_addr)), PAGE_SIZE * 2, PROT_READ | PROT_WRITE | PROT_EXEC);
     if (item->proto_addr != NULL) {
         *(item->proto_addr) = TEST_BIT0(item->target_addr) ? (uint32_t *) SET_BIT0((uint32_t) item->trampoline_instructions) : item->trampoline_instructions;
     }
     if (TEST_BIT0(item->target_addr)) {
         int i;
         i = 0;
         if (CLEAR_BIT0(item->target_addr) % 4 != 0) {
             ((uint16_t *) CLEAR_BIT0(item->target_addr))[i++] = 0xBF00;  // NOP
         }
         ((uint16_t *) CLEAR_BIT0(item->target_addr))[i++] = 0xF8DF;
         ((uint16_t *) CLEAR_BIT0(item->target_addr))[i++] = 0xF000; // LDR.W PC, [PC]
         ((uint16_t *) CLEAR_BIT0(item->target_addr))[i++] = item->new_addr & 0xFFFF;
         ((uint16_t *) CLEAR_BIT0(item->target_addr))[i++] = item->new_addr >> 16;
     }
     else {
         ((uint32_t *) (item->target_addr))[0] = 0xe51ff004; // LDR PC, [PC, #-4]
         ((uint32_t *) (item->target_addr))[1] = item->new_addr;
     }
     mprotect((void *) PAGE_START(CLEAR_BIT0(item->target_addr)), PAGE_SIZE * 2, PROT_READ | PROT_EXEC);
     item->status = HOOKED;
     cacheflush(CLEAR_BIT0(item->target_addr), CLEAR_BIT0(item->target_addr) + item->length, 0);
 }
References CLEAR_BIT0, HOOKED, inlineHookItem::length, inlineHookItem::new_addr, PAGE_SIZE, PAGE_START, inlineHookItem::proto_addr, SET_BIT0, inlineHookItem::status, inlineHookItem::target_addr, TEST_BIT0, and inlineHookItem::trampoline_instructions.
Referenced by inlineHookAll().
doInlineUnHook()
static void doInlineUnHook (struct inlineHookItem * item, int pos) static
Definition at line 292 of file inlineHook.c.
 {
     mprotect((void *) PAGE_START(CLEAR_BIT0(item->target_addr)), PAGE_SIZE * 2, PROT_READ | PROT_WRITE | PROT_EXEC);
     memcpy((void *) CLEAR_BIT0(item->target_addr), item->orig_instructions, item->length);
     mprotect((void *) PAGE_START(CLEAR_BIT0(item->target_addr)), PAGE_SIZE * 2, PROT_READ | PROT_EXEC);
     munmap(item->trampoline_instructions, PAGE_SIZE);
     free(item->orig_instructions);
     deleteInlineHookItem(pos);
     cacheflush(CLEAR_BIT0(item->target_addr), CLEAR_BIT0(item->target_addr) + item->length, 0);
 }
References CLEAR_BIT0, deleteInlineHookItem(), inlineHookItem::length, inlineHookItem::orig_instructions, PAGE_SIZE, PAGE_START, inlineHookItem::target_addr, and inlineHookItem::trampoline_instructions.
Referenced by inlineUnHookAll().
doProcessThreadPC()
static bool doProcessThreadPC (struct inlineHookItem * item, struct pt_regs * regs, int action) static
Definition at line 92 of file inlineHook.c.
 {
     int offset;
     int i;
     switch (action)
     {
         case ACTION_ENABLE:
             offset = regs->ARM_pc - CLEAR_BIT0(item->target_addr);
             for (i = 0; i < item->count; ++i) {
                 if (offset == item->orig_boundaries[i]) {
                     regs->ARM_pc = (uint32_t) item->trampoline_instructions + item->trampoline_boundaries[i];
                     return true;
                 }
             }
             break;
         case ACTION_DISABLE:
             offset = regs->ARM_pc - (int) item->trampoline_instructions;
             for (i = 0; i < item->count; ++i) {
                 if (offset == item->trampoline_boundaries[i]) {
                     regs->ARM_pc = CLEAR_BIT0(item->target_addr) + item->orig_boundaries[i];
                     return true;
                 }
             }
             break;
     }
     return false;
 }
References ACTION_DISABLE, ACTION_ENABLE, CLEAR_BIT0, inlineHookItem::count, inlineHookItem::orig_boundaries, inlineHookItem::target_addr, inlineHookItem::trampoline_boundaries, and inlineHookItem::trampoline_instructions.
Referenced by processThreadPC().
findInlineHookItem()
static struct inlineHookItem* findInlineHookItem (uint32_t target_addr) static
Definition at line 220 of file inlineHook.c.
 {
     int i;
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].target_addr == target_addr) {
             return &info.item[i];
         }
     }
     return NULL;
 }
References info, inlineHookInfo::item, inlineHookInfo::size, and inlineHookItem::target_addr.
freeze()
static pid_t freeze (struct inlineHookItem * item, int action) static
Definition at line 144 of file inlineHook.c.
 {
     int count;
     pid_t tids[1024];
     pid_t pid;
     pid = -1;
     count = getAllTids(gettid(), tids);
     if (count > 0) {
         pid = fork();
         if (pid == 0) {
             int i;
             for (i = 0; i < count; ++i) {
                 if (ptrace(PTRACE_ATTACH, tids[i], NULL, NULL) == 0) {
                     waitpid(tids[i], NULL, WUNTRACED);
                     processThreadPC(tids[i], item, action);
                 }
             }
             raise(SIGSTOP);
             for (i = 0; i < count; ++i) {
                 ptrace(PTRACE_DETACH, tids[i], NULL, NULL);
             }
             raise(SIGKILL);
         }
         else if (pid > 0) {
             waitpid(pid, NULL, WUNTRACED);
         }
     }
     return pid;
 }
References getAllTids(), and processThreadPC().
Referenced by inlineHookAll(), and inlineUnHookAll().
getAllTids()
static int getAllTids (pid_t exclude_tid, pid_t * tids) static
Definition at line 61 of file inlineHook.c.
 {
     char dir_path[32];
     DIR *dir;
     int i;
     struct dirent *entry;
     pid_t tid;
     if (exclude_tid < 0) {
         snprintf(dir_path, sizeof(dir_path), "/proc/self/task");
     }
     else {
         snprintf(dir_path, sizeof(dir_path), "/proc/%d/task", exclude_tid);
     }
     dir = opendir(dir_path);
     if (dir == NULL) {
         return 0;
     }
     i = 0;
     while((entry = readdir(dir)) != NULL) {
         tid = atoi(entry->d_name);
         if (tid != 0 && tid != exclude_tid) {
             tids[i++] = tid;
         }
     }
     closedir(dir);
     return i;
 }
Referenced by freeze().
inlineHook()
enum ele7en_status inlineHook (uint32_t target_addr)
Definition at line 343 of file inlineHook.c.
 {
     int i;
     struct inlineHookItem *item;
     item = NULL;
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].target_addr == target_addr) {
             item = &info.item[i];
             break;
         }
     }
     if (item == NULL) {
         return ELE7EN_ERROR_NOT_REGISTERED;
     }
     if (item->status == REGISTERED) {
         pid_t pid;
         pid = freeze(item, ACTION_ENABLE);
         doInlineHook(item);
         unFreeze(pid);
         return ELE7EN_OK;
     }
     else if (item->status == HOOKED) {
         return ELE7EN_ERROR_ALREADY_HOOKED;
     }
     else {
         return ELE7EN_ERROR_UNKNOWN;
     }
 }
inlineHookAll()
void inlineHookAll ()
Definition at line 411 of file inlineHook.c.
 {
     pid_t pid;
     int i;
     pid = freeze(NULL, ACTION_ENABLE);
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].status == REGISTERED) {
             doInlineHook(&info.item[i]);
         }
     }
     unFreeze(pid);
 }
References ACTION_ENABLE, doInlineHook(), freeze(), info, inlineHookInfo::item, REGISTERED, inlineHookInfo::size, inlineHookItem::status, and unFreeze().
inlineUnHook()
enum ele7en_status inlineUnHook (uint32_t target_addr)
Definition at line 292 of file inlineHook.c.
 {
     int i;
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].target_addr == target_addr && info.item[i].status == HOOKED) {
             pid_t pid;
             pid = freeze(&info.item[i], ACTION_DISABLE);
             doInlineUnHook(&info.item[i], i);
             unFreeze(pid);
             return ELE7EN_OK;
         }
     }
     return ELE7EN_ERROR_NOT_HOOKED;
 }
inlineUnHookAll()
void inlineUnHookAll ()
Definition at line 326 of file inlineHook.c.
 {
     pid_t pid;
     int i;
     pid = freeze(NULL, ACTION_DISABLE);
     for (i = 0; i < info.size; ++i) {
         if (info.item[i].status == HOOKED) {
             doInlineUnHook(&info.item[i], i);
             --i;
         }
     }
     unFreeze(pid);
 }
References ACTION_DISABLE, doInlineUnHook(), freeze(), HOOKED, info, inlineHookInfo::item, inlineHookInfo::size, inlineHookItem::status, and unFreeze().
isExecutableAddr()
static bool isExecutableAddr (uint32_t addr) static
Definition at line 192 of file inlineHook.c.
 {
     FILE *fp;
     char line[1024];
     uint32_t start;
     uint32_t end;
     fp = fopen("/proc/self/maps", "r");
     if (fp == NULL) {
         return false;
     }
     while (fgets(line, sizeof(line), fp)) {
         if (strstr(line, "r-xp") || strstr(line, "rwxp")) {
             start = strtoul(strtok(line, "-"), NULL, 16);
             end = strtoul(strtok(NULL, " "), NULL, 16);
             if (addr >= start && addr <= end) {
                 fclose(fp);
                 return true;
             }
         }
     }
     fclose(fp);
     return false;
 }
processThreadPC()
static void processThreadPC (pid_t tid, struct inlineHookItem * item, int action) static
Definition at line 122 of file inlineHook.c.
 {
     struct pt_regs regs;
     if (ptrace(PTRACE_GETREGS, tid, NULL, &regs) == 0) {
         if (item == NULL) {
             int pos;
             for (pos = 0; pos < info.size; ++pos) {
                 if (doProcessThreadPC(&info.item[pos], &regs, action) == true) {
                     break;
                 }
             }
         }
         else {
             doProcessThreadPC(item, &regs, action);
         }
         ptrace(PTRACE_SETREGS, tid, NULL, &regs);
     }
 }
References doProcessThreadPC(), info, inlineHookInfo::item, and inlineHookInfo::size.
Referenced by freeze().
registerInlineHook()
enum ele7en_status registerInlineHook (uint32_t target_addr, uint32_t new_addr, uint32_t ** proto_addr)
Definition at line 246 of file inlineHook.c.
 {
     struct inlineHookItem *item;
     if (!isExecutableAddr(target_addr) || !isExecutableAddr(new_addr)) {
         return ELE7EN_ERROR_NOT_EXECUTABLE;
     }
     item = findInlineHookItem(target_addr);
     if (item != NULL) {
         if (item->status == REGISTERED) {
             return ELE7EN_ERROR_ALREADY_REGISTERED;
         }
         else if (item->status == HOOKED) {
             return ELE7EN_ERROR_ALREADY_HOOKED;
         }
         else {
             return ELE7EN_ERROR_UNKNOWN;
         }
     }
     item = addInlineHookItem();
     item->target_addr = target_addr;
     item->new_addr = new_addr;
     item->proto_addr = proto_addr;
     item->length = TEST_BIT0(item->target_addr) ? 12 : 8;
     // TODO: Allocate this in a place where GC doesn't ruin it
     item->orig_instructions = malloc(item->length);
     memcpy(item->orig_instructions, (void *) CLEAR_BIT0(item->target_addr), item->length);
     item->trampoline_instructions = mmap(NULL, PAGE_SIZE, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_ANONYMOUS | MAP_PRIVATE, 0, 0);
     relocateInstruction(item->target_addr, item->orig_instructions, item->length, item->trampoline_instructions, item->orig_boundaries, item->trampoline_boundaries, &item->count);
     item->status = REGISTERED;
     return ELE7EN_OK;
 }
unFreeze()
static void unFreeze (pid_t pid) static
Definition at line 182 of file inlineHook.c.
 {
     if (pid < 0) {
         return;
     }
     kill(pid, SIGCONT);
     wait(NULL);
 }
Referenced by inlineHookAll(), and inlineUnHookAll().
Variable Documentation
info
struct inlineHookInfo info = {0} static
Definition at line 1 of file inlineHook.c.
Referenced by HookTracker::AddHook(), addInlineHookItem(), deleteInlineHookItem(), direxists(), findInlineHookItem(), il2cpp_utils::FindMethod(), Configuration::getConfigFilePath(), getDataDir(), inlineHookAll(), inlineUnHookAll(), il2cpp_utils::MakeGenericMethod(), processThreadPC(), HookTracker::RemoveHook(), and il2cpp_utils::RunGenericMethod().