BeatSaber-Hooks: shared/utils/instruction-parsing.hpp File Reference
instruction-parsing.hpp File Reference
#include <array>
#include <bitset>
#include <optional>
#include <stack>
#include <unordered_map>
#include "logging.hpp"
#include "utils.h"
#include <cassert>
Data Structures
class Register
class Instruction
struct RegisterSet
struct PSTATE
struct ProgramState
class InstructionTree
struct ParseState
class AssemblyFunction
Macros
#define BRANCH_ENUM(DO)
#define MAKE_ENUM(VAR, STR) VAR,
#define MAKE_NAMES(VAR, STR) #VAR,
#define MAKE_STRINGS(VAR, STR) STR,
#define ONES(N) ((1ull << (N)) - 1ull)
Functions
template<class T >
T trunc (T bits, int N)
template<class To , class From >
To ZeroExtend (From bits, [[maybe_unused]] int M)
template<class To , class From >
To SignExtend (From bits, int M)
template<class To , class From >
To Replicate (From bits, int M, int N=sizeof(To) *CHAR_BIT)
template<class T >
int HighestSetBit (T x, int N)
template<class T >
T LSL (T x, int N, unsigned shift)
template<class T >
T LSR (T x, int N, unsigned shift)
template<class T >
T ASR (T x, int N, unsigned shift)
template<class T >
T ROR (T x, int N, unsigned shift)
template<class T >
T bits (T x, int high, int low)
decltype(Instruction::result) ExtractAddress (Instruction *instWithResultAdr, Instruction *instWithImmOffset)
decltype(Instruction::result) ExtractAddress (const int32_t *addr, int pcRelN, int offsetN)
template<typename TRet , typename ... TFuncArgs, typename ... TArgs>
decltype(Instruction::result) ExtractAddress (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
decltype(Instruction::result) ExtractAddressFixed (const int32_t *inst, int idxOfInstWithResultAdr, int idxOfInstWithImmOffset)
template<typename TRet , typename ... TFuncArgs, typename ... TArgs>
decltype(Instruction::result) ExtractAddressFixed (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
Instruction * EvalSwitch (const uint32_t *switchTable, int switchCaseValue)
Instruction * EvalSwitch (const int32_t *inst, int pcRelN, int offsetN, int switchCaseValue)
template<typename TRet , typename ... TFuncArgs, typename ... TArgs>
Instruction * EvalSwitch (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
Macro Definition Documentation
BRANCH_ENUM
#define BRANCH_ENUM (DO)
Value:
        DO(NOBRANCH,  "") \
        DO(DIRCALL,   "Direct Branch with link") \
        DO(INDCALL,   "Indirect Branch with link") \
        DO(ERET,      "Exception return (indirect)") \
        DO(DBGEXIT,   "Exit from Debug state") \
        DO(RET,       "Indirect branch with function return hint") \
        DO(DIR,       "Direct branch") \
        DO(INDIR,     "Indirect branch") \
        DO(EXCEPTION, "Exception entry") \
        DO(RESET,     "Reset") \
        DO(UNKNOWN,   "Other")
Definition at line 62 of file instruction-parsing.hpp.
MAKE_ENUM
#define MAKE_ENUM (VAR, STR) VAR,
Definition at line 76 of file instruction-parsing.hpp.
MAKE_NAMES
#define MAKE_NAMES (VAR, STR) #VAR,
MAKE_STRINGS
#define MAKE_STRINGS (VAR, STR) STR,
ONES
#define ONES (N) ((1ull << (N)) - 1ull)
Definition at line 249 of file instruction-parsing.hpp.
Function Documentation
ASR()
template<class T > T ASR (T x, int N, unsigned shift)
Definition at line 320 of file instruction-parsing.hpp.
{
References trunc().
bits()
template<class T > T bits (T x, int high, int low)
Definition at line 340 of file instruction-parsing.hpp.
{
References trunc().
Referenced by Instruction::Instruction(), Replicate(), SignExtend(), trunc(), and ZeroExtend().
EvalSwitch() [1/3]
Instruction* EvalSwitch (const int32_t * inst, int pcRelN, int offsetN, int switchCaseValue)
Definition at line 80 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("EvalSwitch");
     auto switchTable = (const uint32_t*)ExtractAddress(inst, pcRelN, offsetN);
     RET_0_UNLESS(logger, switchTable);
     return EvalSwitch(switchTable, switchCaseValue);
 }
References EvalSwitch(), ExtractAddress(), Logger::get(), RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
EvalSwitch() [2/3]
Instruction* EvalSwitch (const uint32_t * switchTable, int switchCaseValue)
Definition at line 71 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("EvalSwitch");
     auto stOffset = SignExtend<int64_t>(switchTable[switchCaseValue - 1], 32);
     auto jmpAddr = (int64_t)switchTable + stOffset;
     logger.debug("jmp offset from switch table: %lX (-%lX); jmp: %lX (offset %lX)",
         stOffset, -stOffset, jmpAddr, asOffset(jmpAddr));
     return new Instruction((const int32_t*)jmpAddr);
 }
References Logger::get(), Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by EvalSwitch(), and il2cpp_functions::Init().
EvalSwitch() [3/3]
template<typename TRet , typename ... TFuncArgs, typename ... TArgs> Instruction* EvalSwitch (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
Definition at line 375 of file instruction-parsing.hpp.
{
References il2cpp_utils::args, and EvalSwitch().
ExtractAddress() [1/3]
decltype(Instruction::result) ExtractAddress (const int32_t * addr, int pcRelN, int offsetN)
Definition at line 52 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("ExtractAddress");
     Instruction funcInst(addr);
     auto instAdrp = funcInst.findNthPcRelAdr(pcRelN);
     RET_0_UNLESS(logger, instAdrp);
     auto instOff = instAdrp->findNthImmOffsetOnReg(offsetN, instAdrp->Rd);
     RET_0_UNLESS(logger, instOff);
     logger.debug("adrp idx: %lu, offset instruction idx: %lu", instAdrp->addr - funcInst.addr, instOff->addr - funcInst.addr);
     logger.debug("instAdrp: %s", instAdrp->toString().c_str());
     logger.debug("instOff:  %s", instOff->toString().c_str());
     return ExtractAddress(instAdrp, instOff);
 }
References Instruction::addr, ExtractAddress(), Instruction::findNthPcRelAdr(), Logger::get(), RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
ExtractAddress() [2/3]
template<typename TRet , typename ... TFuncArgs, typename ... TArgs> decltype(Instruction::result) ExtractAddress (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
Definition at line 353 of file instruction-parsing.hpp.
References il2cpp_utils::args, and ExtractAddress().
ExtractAddress() [3/3]
decltype(Instruction::result) ExtractAddress (Instruction * instWithResultAdr, Instruction * instWithImmOffset)
Definition at line 41 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("ExtractAddress");
     RET_0_UNLESS(logger, instWithImmOffset->imm);
     auto jmpOff = instWithResultAdr->result;
     auto offset = *(instWithImmOffset->imm);
     auto jmp = jmpOff + offset;
     logger.debug("offset: %lX, jmp: %lX (offset %lX)", offset, jmp, asOffset(jmp));
     return jmp;
 }
References Logger::get(), Instruction::imm, Instruction::result, RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by EvalSwitch(), ExtractAddress(), ExtractAddressFixed(), and il2cpp_functions::Init().
ExtractAddressFixed() [1/2]
decltype(Instruction::result) ExtractAddressFixed (const int32_t * inst, int idxOfInstWithResultAdr, int idxOfInstWithImmOffset)
Definition at line 65 of file instruction-parsing.cpp.
{
     auto instWithResultAdr = Instruction(&inst[idxOfInstWithResultAdr]);
     auto instWithImmOffset = Instruction(&inst[idxOfInstWithImmOffset]);
     return ExtractAddress(&instWithResultAdr, &instWithImmOffset);
 }
References ExtractAddress().
Referenced by ExtractAddressFixed().
ExtractAddressFixed() [2/2]
template<typename TRet , typename ... TFuncArgs, typename ... TArgs> decltype(Instruction::result) ExtractAddressFixed (function_ptr_t< TRet, TFuncArgs... > func, TArgs... args)
Definition at line 363 of file instruction-parsing.hpp.
References il2cpp_utils::args, and ExtractAddressFixed().
HighestSetBit()
template<class T > int HighestSetBit (T x, int N)
Definition at line 298 of file instruction-parsing.hpp.
{
     for (int i = N - 1; i >= 0; i--) {
         if (x & (1 << i)) return i;
Referenced by DecodeBitMasks(), and Instruction::Instruction().
LSL()
template<class T > T LSL (T x, int N, unsigned shift)
Definition at line 308 of file instruction-parsing.hpp.
{
References trunc().
Referenced by ROR().
LSR()
template<class T > T LSR (T x, int N, unsigned shift)
Definition at line 314 of file instruction-parsing.hpp.
{
References trunc().
Referenced by ROR().
Replicate()
template<class To , class From > To Replicate (From bits, int M, int N = sizeof(To) * CHAR_BIT)
Definition at line 278 of file instruction-parsing.hpp.
{
     CRASH_UNLESS(N % M == 0);
     To replicatedBits = bits;
     auto repSize = M;
     while (repSize * 2 <= N) {
         replicatedBits |= (replicatedBits << repSize);
         repSize *= 2;
     }
     // The overlap should all match since N % M == 0 means that N - M*a % M == 0
     replicatedBits |= (replicatedBits << (N - repSize));
     if (N != M) {
         Logger::get().debug("Replicate %s * %i = %s", std::bitset<sizeof(From)*CHAR_BIT>(bits).to_string().c_str(), N / M,
             std::bitset<sizeof(To)*CHAR_BIT>(replicatedBits).to_string().c_str());
References bits(), Logger::debug(), and Logger::get().
ROR()
template<class T > T ROR (T x, int N, unsigned shift)
Definition at line 327 of file instruction-parsing.hpp.
{
     shift %= N;
     T ret = LSR(x, N, shift) | LSL(x, N, N - shift);
     if ((ret == 0) && (x != 0)) {
         Logger::get().debug("%s ROR %i (-%i) returned %s!", std::bitset<sizeof(T)*CHAR_BIT>(x).to_string().c_str(), shift, N - shift,
             std::bitset<sizeof(T)*CHAR_BIT>(ret).to_string().c_str());
         SAFE_ABORT();
References Logger::debug(), Logger::get(), LSL(), LSR(), and T.
Referenced by DecodeBitMasks().
SignExtend()
template<class To , class From > To SignExtend (From bits, int M)
Definition at line 268 of file instruction-parsing.hpp.
{
     static_assert(std::is_signed_v<To>);
     constexpr int N = sizeof(To) * CHAR_BIT;
     assert(N >= M);
References bits().
trunc()
template<class T > T trunc (T bits, int N)
Definition at line 253 of file instruction-parsing.hpp.
{
     if (N == sizeof(T)*CHAR_BIT) return bits;
References bits(), ONES, and T.
Referenced by ASR(), bits(), DecodeBitMasks(), LSL(), and LSR().
ZeroExtend()
template<class To , class From > To ZeroExtend (From bits, [[maybe_unused] ] int M)
Definition at line 261 of file instruction-parsing.hpp.
{
References bits().