BeatSaber-Hooks: src/utils/instruction-parsing.cpp File Reference
instruction-parsing.cpp File Reference
#include "../../shared/utils/instruction-parsing.hpp"
#include "../../shared/utils/utils.h"
#include <functional>
#include <new>
#include <sstream>
#include "../../shared/utils/logging.hpp"
Functions
std::optional< std::pair< uint64_t, uint64_t > > DecodeBitMasks (unsigned N, unsigned imms, unsigned immr, unsigned regSize, bool logical)
decltype(Instruction::result) ExtractAddress (Instruction *instWithResultAdr, Instruction *instWithImmOffset)
decltype(Instruction::result) ExtractAddress (const int32_t *addr, int pcRelN, int offsetN)
decltype(Instruction::result) ExtractAddressFixed (const int32_t *inst, int idxOfInstWithResultAdr, int idxOfInstWithImmOffset)
Instruction * EvalSwitch (const uint32_t *switchTable, int switchCaseValue)
Instruction * EvalSwitch (const int32_t *inst, int pcRelN, int offsetN, int switchCaseValue)
std::ostream & operator<< (std::ostream &os, const Register &regName)
std::ostream & operator<< (std::ostream &os, const Instruction &inst)
InstructionTree * FindOrCreateInstruction (const int32_t *pc, ParseState &parseState, const char *msg)
void ProcessRegisterDependencies (Instruction *inst, uint_fast8_t Rd, decltype(ParseState::dependencyMap)&depMap)
void ProcessRegisterDependencies (Instruction *inst, decltype(ParseState::dependencyMap)&depMap)
bool OnlySelfDeps (uint_fast8_t reg, decltype(ParseState::dependencyMap)&depMap)
std::string DepMapToString (decltype(ParseState::dependencyMap)&depMap)
std::ostream & operator<< (std::ostream &os, const AssemblyFunction &func)
Variables
static const char * unalloc = "UNALLOCATED"
static const char * pcRelAddr = "PC-rel. addressing"
static const char * ldSt = "Loads and Stores"
static const char * addSubImm = "Add/subtract (immediate)"
static const char * nopSt = "NOP"
static const char * hintSt = "HINT"
static const auto & SP = Register::SP
static const auto & RZR = Register::RZR
static const auto & RLINK = Register::RLINK
Function Documentation
DecodeBitMasks()
std::optional<std::pair<uint64_t, uint64_t> > DecodeBitMasks (unsigned N, unsigned imms, unsigned immr, unsigned regSize, bool logical)
Definition at line 17 of file instruction-parsing.cpp.
{
     auto len = HighestSetBit((N << 6) | trunc(~imms, 6), 7);
     if (len < 1) return std::nullopt;
     unsigned size = 1 << len;
     assert(regSize >= size);
     unsigned levels = size - 1;  // a real bitmask of the rightmost "size" bits
     unsigned R = immr & levels;
     unsigned S = imms & levels;
     // For logical immediates an all-ones value of S is reserved since it would generate a useless all-ones result
     if (logical && (S == levels)) return std::nullopt;
     auto diff = S - R;  // "6-bit subtract with borrow"
     unsigned d = trunc(diff, len);
     uint64_t welem = ONES(S + 1);  // # of sig bits = size
     uint64_t telem = ONES(d + 1);  // # of sig bits = size
     welem = ROR(welem, size, R);
     // Replicate the patterns to fill regSize
     auto wmask = Replicate<uint64_t>(welem, size, regSize);
     auto tmask = Replicate<uint64_t>(telem, size, regSize);
     return std::pair{wmask, tmask};
 }
References HighestSetBit(), ONES, il2cpp_utils::R, ROR(), and trunc().
Referenced by Instruction::Instruction().
DepMapToString()
std::string DepMapToString (decltype(ParseState::dependencyMap)& depMap)
Definition at line 1230 of file instruction-parsing.cpp.
{
     std::ostringstream ss;
     ss << "{self deps: [";
     for (uint_fast8_t i = 0; i < depMap.max_size(); i++) {
         if ((i != 0) && ((i % 8) == 0)) {
             ss << "|";
         }
         if (depMap[i].none()) {
             ss << " ";
         } else if (OnlySelfDeps(i, depMap)) {
             ss << "O";  // a loop
         } else {
             ss << ">";  // deps are listed on right
         }
     }
     ss << "]; ";
     bool first = true;
     for (uint_fast8_t i = 0; i < depMap.max_size(); i++) {
         if (!OnlySelfDeps(i, depMap) && depMap[i].any()) {
             if (!first) ss << "; ";
             ss << Register(i, true) << " deps: ";
             bool innerFirst = true;
             for (uint_fast8_t dep = 0; dep < depMap[i].size(); dep++) {
                 if (!depMap[i][dep]) continue;
                 if (!innerFirst) ss << ", ";
                 ss << Register(dep, true);
                 innerFirst = false;
             }
             first = false;
         }
     }
     ss << "}" << std::flush;
     return ss.str();
 }
References OnlySelfDeps().
Referenced by AssemblyFunction::AssemblyFunction().
EvalSwitch() [1/2]
Instruction* EvalSwitch (const int32_t * inst, int pcRelN, int offsetN, int switchCaseValue)
Definition at line 80 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("EvalSwitch");
     auto switchTable = (const uint32_t*)ExtractAddress(inst, pcRelN, offsetN);
     RET_0_UNLESS(logger, switchTable);
     return EvalSwitch(switchTable, switchCaseValue);
 }
References EvalSwitch(), ExtractAddress(), Logger::get(), RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
EvalSwitch() [2/2]
Instruction* EvalSwitch (const uint32_t * switchTable, int switchCaseValue)
Definition at line 71 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("EvalSwitch");
     auto stOffset = SignExtend<int64_t>(switchTable[switchCaseValue - 1], 32);
     auto jmpAddr = (int64_t)switchTable + stOffset;
     logger.debug("jmp offset from switch table: %lX (-%lX); jmp: %lX (offset %lX)",
         stOffset, -stOffset, jmpAddr, asOffset(jmpAddr));
     return new Instruction((const int32_t*)jmpAddr);
 }
References Logger::get(), Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by EvalSwitch(), and il2cpp_functions::Init().
ExtractAddress() [1/2]
decltype(Instruction::result) ExtractAddress (const int32_t * addr, int pcRelN, int offsetN)
Definition at line 52 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("ExtractAddress");
     Instruction funcInst(addr);
     auto instAdrp = funcInst.findNthPcRelAdr(pcRelN);
     RET_0_UNLESS(logger, instAdrp);
     auto instOff = instAdrp->findNthImmOffsetOnReg(offsetN, instAdrp->Rd);
     RET_0_UNLESS(logger, instOff);
     logger.debug("adrp idx: %lu, offset instruction idx: %lu", instAdrp->addr - funcInst.addr, instOff->addr - funcInst.addr);
     logger.debug("instAdrp: %s", instAdrp->toString().c_str());
     logger.debug("instOff:  %s", instOff->toString().c_str());
     return ExtractAddress(instAdrp, instOff);
 }
References Instruction::addr, ExtractAddress(), Instruction::findNthPcRelAdr(), Logger::get(), RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
ExtractAddress() [2/2]
decltype(Instruction::result) ExtractAddress (Instruction * instWithResultAdr, Instruction * instWithImmOffset)
Definition at line 41 of file instruction-parsing.cpp.
{
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("ExtractAddress");
     RET_0_UNLESS(logger, instWithImmOffset->imm);
     auto jmpOff = instWithResultAdr->result;
     auto offset = *(instWithImmOffset->imm);
     auto jmp = jmpOff + offset;
     logger.debug("offset: %lX, jmp: %lX (offset %lX)", offset, jmp, asOffset(jmp));
     return jmp;
 }
References Logger::get(), Instruction::imm, Instruction::result, RET_0_UNLESS, Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by EvalSwitch(), ExtractAddress(), ExtractAddressFixed(), and il2cpp_functions::Init().
ExtractAddressFixed()
decltype(Instruction::result) ExtractAddressFixed (const int32_t * inst, int idxOfInstWithResultAdr, int idxOfInstWithImmOffset)
Definition at line 65 of file instruction-parsing.cpp.
{
     auto instWithResultAdr = Instruction(&inst[idxOfInstWithResultAdr]);
     auto instWithImmOffset = Instruction(&inst[idxOfInstWithImmOffset]);
     return ExtractAddress(&instWithResultAdr, &instWithImmOffset);
 }
References ExtractAddress().
Referenced by ExtractAddressFixed().
FindOrCreateInstruction()
InstructionTree* FindOrCreateInstruction (const int32_t * pc, ParseState & parseState, const char * msg)
Definition at line 1190 of file instruction-parsing.cpp.
{
     auto p = parseState.codeToInstTree.find(pc);
     static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("FindOrCreateInstruction");
     if (p != parseState.codeToInstTree.end()) {
         logger.debug("not recursing: InstructionTree for %p (offset %lX) already exists", pc, asOffset((uintptr_t)pc));
         return p->second;
     } else {
         logger.debug("%s (pc %p, offset %lX)", msg, pc, asOffset((uintptr_t)pc));
         auto inst = new (std::nothrow) InstructionTree(pc);
         parseState.frontier.push({inst, parseState.dependencyMap});  // the inserted depMap is a copy
         parseState.codeToInstTree[pc] = inst;
         return inst;
     }
 }
References ParseState::codeToInstTree, LoggerContextObject::debug(), ParseState::dependencyMap, ParseState::frontier, Logger::get(), Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by InstructionTree::PopulateChildren().
OnlySelfDeps()
bool OnlySelfDeps (uint_fast8_t reg, decltype(ParseState::dependencyMap)& depMap)
Definition at line 1225 of file instruction-parsing.cpp.
{
     auto deps = depMap[reg];
     return ((deps.count() == 1) && deps[reg]);
 }
Referenced by DepMapToString().
operator<<() [1/3]
std::ostream& operator<< (std::ostream & os, const AssemblyFunction & func)
Definition at line 1303 of file instruction-parsing.cpp.
{
     os << std::hex << std::uppercase;
     os << "Function candidates: " << std::endl;
     for (auto p : func.parseState.functionCandidates) {
         os << "0x" << uintptr_t(p.first) << " (offset 0x" << asOffset((uintptr_t)p.first) << "): depMap "
             << DepMapToString(p.second) << std::endl;
     }
     os << "Other jumps: " << std::endl;
     for (auto p : func.parseState.otherJumps) {
         os << "0x" << uintptr_t(p.first) << " (offset 0x" << asOffset((uintptr_t)p.first) << "): depMap "
             << DepMapToString(p.second) << std::endl;
     }
     return os << std::nouppercase << std::dec;
 }
operator<<() [2/3]
std::ostream& operator<< (std::ostream & os, const Instruction & inst)
Definition at line 115 of file instruction-parsing.cpp.
{
     os << std::showbase;
     if (inst.parseLevel <= 0) return os << "Unparsable";
     os << '"' << inst.kind[inst.parseLevel - 1] << '"';
     if (inst.valid) {
         if (inst.Rd >= 0) os << ", destination register: " << Register(inst.Rd, inst.RdCanBeSP);
         if (inst.Rd2 >= 0) os << ", destination register 2: " << Register(inst.Rd2, inst.RdCanBeSP);
         if (inst.imm) os << ", imm: " << std::hex << *inst.imm;
         if (inst.label) os << ", label: " << std::hex << asOffset(*inst.label) << " (" << *inst.label << ")";
         if (inst.branchType != Instruction::NOBRANCH) {
             os << ", branch type: " << Instruction::branchTypeInfo[inst.branchType];
         }
         if (inst.numSourceRegisters == 0) {
             if (inst.Rd >= 0) os << ", result: " << std::hex << inst.result;
         } else if (inst.numSourceRegisters > 0) {
             os << ", source registers: ";
             for (int j = 0; j < inst.numSourceRegisters; j++) {
                 if (j != 0) os << ", ";
                 os << Register(inst.Rs[j], j ? false : inst.Rs0CanBeSP);
             }
         }
     } else {
         os << ", marked invalid!";
     }
     return os << std::noshowbase;
 }
operator<<() [3/3]
std::ostream& operator<< (std::ostream & os, const Register & regName)
Definition at line 90 of file instruction-parsing.cpp.
{
     auto reg = regName.num;
     if (reg == SP || reg == RZR) {
         if (regName.r31_is_sp) {
             os << "SP";
         } else {
             os << "XZR";
         }
     } else if (reg == RLINK) {
         os << "R30 (link register)";
     } else if (reg == 29) {
         os << "R29 (frame ptr)";
     } else {
         os << "R" << std::dec << +reg;
         if (reg < 0 || reg >= 32) os << " (invalid register!)";
     }
     return os;
 }
ProcessRegisterDependencies() [1/2]
void ProcessRegisterDependencies (Instruction * inst, decltype(ParseState::dependencyMap)& depMap)
Definition at line 1220 of file instruction-parsing.cpp.
{
     if (inst->Rd >= 0) ProcessRegisterDependencies(inst, inst->Rd, depMap);
     if (inst->Rd2 >= 0) ProcessRegisterDependencies(inst, inst->Rd2, depMap);
 }
References ProcessRegisterDependencies(), Instruction::Rd, and Instruction::Rd2.
ProcessRegisterDependencies() [2/2]
void ProcessRegisterDependencies (Instruction * inst, uint_fast8_t Rd, decltype(ParseState::dependencyMap)& depMap)
Definition at line 1205 of file instruction-parsing.cpp.
{
     auto newDeps = decltype(ParseState::dependencyMap)::value_type();  // storage for the dependencies of a single register
     for (uint_fast8_t i = 0; i < inst->numSourceRegisters; i++) {
         auto Rs = inst->Rs[i];
         if ((Rs < 0) || ((size_t)Rs >= depMap.max_size())) {
             static auto logger = Logger::get().WithContext("instruction-parsing").WithContext("ProcessRegisterDependencies");
             logger.critical("Instruction is wrong! numSourceRegisters = %i but Rs[%i] = %i\n%s", inst->numSourceRegisters, i, Rs,
                 inst->toString().c_str());
             SAFE_ABORT();
         }
         newDeps |= depMap[Rs];
     }
     depMap[Rd] = std::move(newDeps);
 }
References LoggerContextObject::critical(), ParseState::dependencyMap, Logger::get(), Instruction::numSourceRegisters, Instruction::Rs, Instruction::toString(), Logger::WithContext(), and LoggerContextObject::WithContext().
Referenced by InstructionTree::PopulateChildren(), and ProcessRegisterDependencies().
Variable Documentation
addSubImm
const char* addSubImm = "Add/subtract (immediate)" static
Definition at line 11 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction(), and Instruction::isAddOrSubImm().
hintSt
const char* hintSt = "HINT" static
Definition at line 13 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction(), and Instruction::isHint().
ldSt
const char* ldSt = "Loads and Stores" static
Definition at line 10 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction(), and Instruction::isLoadOrStore().
nopSt
const char* nopSt = "NOP" static
Definition at line 12 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction(), and Instruction::isNOP().
pcRelAddr
const char* pcRelAddr = "PC-rel. addressing" static
Definition at line 9 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction(), and Instruction::isPcRelAdr().
RLINK
const auto& RLINK = Register::RLINK static
Definition at line 89 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction().
RZR
const auto& RZR = Register::RZR static
Definition at line 88 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction().
SP
const auto& SP = Register::SP static
Definition at line 87 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction().
unalloc
const char* unalloc = "UNALLOCATED" static
Definition at line 8 of file instruction-parsing.cpp.
Referenced by Instruction::Instruction().