BeatSaber-Hooks: shared/rapidjson/test/unittest/istreamwrappertest.cpp File Reference
istreamwrappertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/istreamwrapper.h"
#include "rapidjson/encodedstream.h"
#include "rapidjson/document.h"
#include <sstream>
#include <fstream>
Functions
template<typename StringStreamType >
static void TestStringStream ()
TEST (IStreamWrapper, istringstream)
TEST (IStreamWrapper, stringstream)
TEST (IStreamWrapper, wistringstream)
TEST (IStreamWrapper, wstringstream)
template<typename FileStreamType >
static bool Open (FileStreamType &fs, const char *filename)
TEST (IStreamWrapper, ifstream)
TEST (IStreamWrapper, fstream)
Function Documentation
Open()
template<typename FileStreamType > static bool Open (FileStreamType & fs, const char * filename) static
Definition at line 106 of file istreamwrappertest.cpp.
{
     const char *paths[] = {
         "encodings",
         "bin/encodings",
         "../bin/encodings",
         "../../bin/encodings",
         "../../../bin/encodings"
     };
     char buffer[1024];
     for (size_t i = 0; i < sizeof(paths) / sizeof(paths[0]); i++) {
         sprintf(buffer, "%s/%s", paths[i], filename);
         fs.open(buffer, ios_base::in | ios_base::binary);
         if (fs.is_open())
             return true;
     }
     return false;
 }
Referenced by EncodedStreamTest::ReadFile(), TEST(), EncodedStreamTest::TestAutoUTFInputStream(), and EncodedStreamTest::TestEncodedInputStream().
TEST() [1/6]
TEST (IStreamWrapper , fstream)
Definition at line 135 of file istreamwrappertest.cpp.
{
     fstream fs;
     ASSERT_TRUE(Open(fs, "utf8bom.json"));
     IStreamWrapper isw(fs);
     EncodedInputStream<UTF8<>, IStreamWrapper> eis(isw);
     Document d;
     EXPECT_TRUE(!d.ParseStream(eis).HasParseError());
     EXPECT_TRUE(d.IsObject());
     EXPECT_EQ(5u, d.MemberCount());
 }
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), Open(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
TEST() [2/6]
TEST (IStreamWrapper , ifstream)
Definition at line 124 of file istreamwrappertest.cpp.
{
     ifstream ifs;
     ASSERT_TRUE(Open(ifs, "utf8bom.json"));
     IStreamWrapper isw(ifs);
     EncodedInputStream<UTF8<>, IStreamWrapper> eis(isw);
     Document d;
     EXPECT_TRUE(!d.ParseStream(eis).HasParseError());
     EXPECT_TRUE(d.IsObject());
     EXPECT_EQ(5u, d.MemberCount());
 }
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), Open(), and rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
TEST() [3/6]
TEST (IStreamWrapper , istringstream)
Definition at line 89 of file istreamwrappertest.cpp.
{
     TestStringStream<istringstream>();
 }
TEST() [4/6]
TEST (IStreamWrapper , stringstream)
Definition at line 93 of file istreamwrappertest.cpp.
{
     TestStringStream<stringstream>();
 }
TEST() [5/6]
TEST (IStreamWrapper , wistringstream)
Definition at line 97 of file istreamwrappertest.cpp.
{
     TestStringStream<wistringstream>();
 }
TEST() [6/6]
TEST (IStreamWrapper , wstringstream)
Definition at line 101 of file istreamwrappertest.cpp.
{
     TestStringStream<wstringstream>();
 }
TestStringStream()
template<typename StringStreamType > static void TestStringStream () static
Definition at line 32 of file istreamwrappertest.cpp.
{
     typedef typename StringStreamType::char_type Ch;
     {
         StringStreamType iss;
         BasicIStreamWrapper<StringStreamType> is(iss);
         EXPECT_EQ(0u, is.Tell());
         if (sizeof(Ch) == 1) {
             EXPECT_EQ(0, is.Peek4());
             EXPECT_EQ(0u, is.Tell());
         }
         EXPECT_EQ(0, is.Peek());
         EXPECT_EQ(0, is.Take());
         EXPECT_EQ(0u, is.Tell());
     }
     {
         Ch s[] = { 'A', 'B', 'C', '\0' };
         StringStreamType iss(s);
         BasicIStreamWrapper<StringStreamType> is(iss);
         EXPECT_EQ(0u, is.Tell());
         if (sizeof(Ch) == 1) {
             EXPECT_EQ(0, is.Peek4()); // less than 4 bytes
         }
         for (int i = 0; i < 3; i++) {
             EXPECT_EQ(static_cast<size_t>(i), is.Tell());
             EXPECT_EQ('A' + i, is.Peek());
             EXPECT_EQ('A' + i, is.Peek());
             EXPECT_EQ('A' + i, is.Take());
         }
         EXPECT_EQ(3u, is.Tell());
         EXPECT_EQ(0, is.Peek());
         EXPECT_EQ(0, is.Take());
     }
     {
         Ch s[] = { 'A', 'B', 'C', 'D', 'E', '\0' };
         StringStreamType iss(s);
         BasicIStreamWrapper<StringStreamType> is(iss);
         if (sizeof(Ch) == 1) {
             const Ch* c = is.Peek4();
             for (int i = 0; i < 4; i++)
                 EXPECT_EQ('A' + i, c[i]);
             EXPECT_EQ(0u, is.Tell());
         }
         for (int i = 0; i < 5; i++) {
             EXPECT_EQ(static_cast<size_t>(i), is.Tell());
             EXPECT_EQ('A' + i, is.Peek());
             EXPECT_EQ('A' + i, is.Peek());
             EXPECT_EQ('A' + i, is.Take());
         }
         EXPECT_EQ(5u, is.Tell());
         EXPECT_EQ(0, is.Peek());
         EXPECT_EQ(0, is.Take());
     }
 }
References rapidjson::BasicIStreamWrapper< StreamType >::Peek(), rapidjson::BasicIStreamWrapper< StreamType >::Peek4(), rapidjson::BasicIStreamWrapper< StreamType >::Take(), and rapidjson::BasicIStreamWrapper< StreamType >::Tell().