BeatSaber-Hooks: shared/rapidjson/test/unittest/itoatest.cpp File Reference
itoatest.cpp File Reference
#include "unittest.h"
#include "rapidjson/internal/itoa.h"
Data Structures
struct Traits< T >
struct Traits< uint32_t >
struct Traits< int32_t >
struct Traits< uint64_t >
struct Traits< int64_t >
Functions
template<typename T >
static void VerifyValue (T value, void(*f)(T, char *), char *(*g)(T, char *))
template<typename T >
static void Verify (void(*f)(T, char *), char *(*g)(T, char *))
static void u32toa_naive (uint32_t value, char *buffer)
static void i32toa_naive (int32_t value, char *buffer)
static void u64toa_naive (uint64_t value, char *buffer)
static void i64toa_naive (int64_t value, char *buffer)
TEST (itoa, u32toa)
TEST (itoa, i32toa)
TEST (itoa, u64toa)
TEST (itoa, i64toa)
Function Documentation
i32toa_naive()
static void i32toa_naive (int32_t value, char * buffer) static
Definition at line 109 of file itoatest.cpp.
{
     uint32_t u = static_cast<uint32_t>(value);
     if (value < 0) {
         *buffer++ = '-';
         u = ~u + 1;
     }
     u32toa_naive(u, buffer);
 }
References u32toa_naive(), and rapidjson::value.
Referenced by TEST().
i64toa_naive()
static void i64toa_naive (int64_t value, char * buffer) static
Definition at line 133 of file itoatest.cpp.
{
     uint64_t u = static_cast<uint64_t>(value);
     if (value < 0) {
         *buffer++ = '-';
         u = ~u + 1;
     }
     u64toa_naive(u, buffer);
 }
References u64toa_naive(), and rapidjson::value.
Referenced by TEST().
TEST() [1/4]
TEST (itoa , i32toa)
Definition at line 146 of file itoatest.cpp.
                    {
     Verify(i32toa_naive, i32toa);
 }
References rapidjson::internal::i32toa(), i32toa_naive(), and Verify().
TEST() [2/4]
TEST (itoa , i64toa)
Definition at line 154 of file itoatest.cpp.
                    {
     Verify(i64toa_naive, i64toa);
 }
References rapidjson::internal::i64toa(), i64toa_naive(), and Verify().
TEST() [3/4]
TEST (itoa , u32toa)
Definition at line 142 of file itoatest.cpp.
                    {
     Verify(u32toa_naive, u32toa);
 }
References rapidjson::internal::u32toa(), u32toa_naive(), and Verify().
TEST() [4/4]
TEST (itoa , u64toa)
Definition at line 150 of file itoatest.cpp.
                    {
     Verify(u64toa_naive, u64toa);
 }
References rapidjson::internal::u64toa(), u64toa_naive(), and Verify().
u32toa_naive()
static void u32toa_naive (uint32_t value, char * buffer) static
Definition at line 94 of file itoatest.cpp.
{
     char temp[10];
     char *p = temp;
     do {
         *p++ = static_cast<char>(char(value % 10) + '0');
         value /= 10;
     } while (value > 0);
     do {
         *buffer++ = *--p;
     } while (p != temp);
     *buffer = '\0';
 }
References rapidjson::value.
Referenced by i32toa_naive(), and TEST().
u64toa_naive()
static void u64toa_naive (uint64_t value, char * buffer) static
Definition at line 118 of file itoatest.cpp.
{
     char temp[20];
     char *p = temp;
     do {
         *p++ = static_cast<char>(char(value % 10) + '0');
         value /= 10;
     } while (value > 0);
     do {
         *buffer++ = *--p;
     } while (p != temp);
     *buffer = '\0';
 }
References rapidjson::value.
Referenced by i64toa_naive(), and TEST().
Verify()
template<typename T > static void Verify (void(*)(T, char *) f, char *(*)(T, char *) g) static
Definition at line 70 of file itoatest.cpp.
{
     // Boundary cases
     VerifyValue<T>(0, f, g);
     VerifyValue<T>((std::numeric_limits<T>::min)(), f, g);
     VerifyValue<T>((std::numeric_limits<T>::max)(), f, g);
     // 2^n - 1, 2^n, 10^n - 1, 10^n until overflow
     for (int power = 2; power <= 10; power += 8) {
         T i = 1, last;
         do {
             VerifyValue<T>(i - 1, f, g);
             VerifyValue<T>(i, f, g);
             if ((std::numeric_limits<T>::min)() < 0) {
                 VerifyValue<T>(Traits<T>::Negate(i), f, g);
                 VerifyValue<T>(Traits<T>::Negate(i + 1), f, g);
             }
             last = i;
             if (i > static_cast<T>((std::numeric_limits<T>::max)() / static_cast<T>(power)))
                 break;
             i *= static_cast<T>(power);
         } while (last < i);
     }
 }
References T.
Referenced by TEST().
VerifyValue()
template<typename T > static void VerifyValue (T value, void(*)(T, char *) f, char *(*)(T, char *) g) static
Definition at line 58 of file itoatest.cpp.
{
     char buffer1[Traits<T>::kBufferSize];
     char buffer2[Traits<T>::kBufferSize];
     f(value, buffer1);
     *g(value, buffer2) = '\0';
     EXPECT_STREQ(buffer1, buffer2);
 }
References rapidjson::value.