BeatSaber-Hooks: shared/rapidjson/example/jsonx/jsonx.cpp File Reference
jsonx.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/stringbuffer.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/error/en.h"
#include <cstdio>
Data Structures
class JsonxWriter< OutputStream >
Functions
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 189 of file jsonx.cpp.
{
     // Prepare JSON reader and input stream.
     Reader reader;
     char readBuffer[65536];
     FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
     // Prepare JSON writer and output stream.
     char writeBuffer[65536];
     FileWriteStream os(stdout, writeBuffer, sizeof(writeBuffer));
     JsonxWriter<FileWriteStream> writer(os);
     // JSON reader parse from the input stream and let writer generate the output.
     if (!reader.Parse(is, writer)) {
         fprintf(stderr, "\nError(%u): %s\n", static_cast<unsigned>(reader.GetErrorOffset()), GetParseError_En(reader.GetParseErrorCode()));
         return 1;
     }
     return 0;
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), rapidjson::GetParseError_En(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().