BeatSaber-Hooks: shared/rapidjson/test/unittest/jsoncheckertest.cpp File Reference
jsoncheckertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/document.h"
Data Structures
struct NoOpHandler
Functions
static char * ReadFile (const char *filename, size_t &length)
TEST (JsonChecker, Reader)
Function Documentation
ReadFile()
static char* ReadFile (const char * filename, size_t & length) static
Definition at line 21 of file jsoncheckertest.cpp.
{
     const char *paths[] = {
         "jsonchecker",
         "bin/jsonchecker",
         "../bin/jsonchecker",
         "../../bin/jsonchecker",
         "../../../bin/jsonchecker"
     };
     char buffer[1024];
     FILE *fp = 0;
     for (size_t i = 0; i < sizeof(paths) / sizeof(paths[0]); i++) {
         sprintf(buffer, "%s/%s", paths[i], filename);
         fp = fopen(buffer, "rb");
         if (fp)
             break;
     }
     if (!fp)
         return 0;
     fseek(fp, 0, SEEK_END);
     length = static_cast<size_t>(ftell(fp));
     fseek(fp, 0, SEEK_SET);
     char* json = static_cast<char*>(malloc(length + 1));
     size_t readLength = fread(json, 1, length, fp);
     json[readLength] = '\0';
     fclose(fp);
     return json;
 }
References json.
Referenced by TEST().
TEST()
TEST (JsonChecker , Reader)
Definition at line 69 of file jsoncheckertest.cpp.
{
     char filename[256];
     // jsonchecker/failXX.json
     for (int i = 1; i <= 33; i++) {
         if (i == 1) // fail1.json is valid in rapidjson, which has no limitation on type of root element (RFC 7159).
             continue;
         if (i == 18)    // fail18.json is valid in rapidjson, which has no limitation on depth of nesting.
             continue;
         sprintf(filename, "fail%d.json", i);
         size_t length;
         char* json = ReadFile(filename, length);
         if (!json) {
             printf("jsonchecker file %s not found", filename);
             ADD_FAILURE();
             continue;
         }
         // Test stack-based parsing.
         GenericDocument<UTF8<>, CrtAllocator> document; // Use Crt allocator to check exception-safety (no memory leak)
         document.Parse(json);
         EXPECT_TRUE(document.HasParseError()) << filename;
         // Test iterative parsing.
         document.Parse<kParseIterativeFlag>(json);
         EXPECT_TRUE(document.HasParseError()) << filename;
         // Test iterative pull-parsing.
         Reader reader;
         StringStream ss(json);
         NoOpHandler h;
         reader.IterativeParseInit();
         while (!reader.IterativeParseComplete()) {
             if (!reader.IterativeParseNext<kParseDefaultFlags>(ss, h))
                 break;
         }
         EXPECT_TRUE(reader.HasParseError()) << filename;
         free(json);
     }
     // passX.json
     for (int i = 1; i <= 3; i++) {
         sprintf(filename, "pass%d.json", i);
         size_t length;
         char* json = ReadFile(filename, length);
         if (!json) {
             printf("jsonchecker file %s not found", filename);
             continue;
         }
         // Test stack-based parsing.
         GenericDocument<UTF8<>, CrtAllocator> document; // Use Crt allocator to check exception-safety (no memory leak)
         document.Parse(json);
         EXPECT_FALSE(document.HasParseError()) << filename;
         // Test iterative parsing.
         document.Parse<kParseIterativeFlag>(json);
         EXPECT_FALSE(document.HasParseError()) << filename;
         // Test iterative pull-parsing.
         Reader reader;
         StringStream ss(json);
         NoOpHandler h;
         reader.IterativeParseInit();
         while (!reader.IterativeParseComplete()) {
             if (!reader.IterativeParseNext<kParseDefaultFlags>(ss, h))
                 break;
         }
         EXPECT_FALSE(reader.HasParseError()) << filename;
         free(json);
     }
 }
References rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), json, rapidjson::kParseDefaultFlags, rapidjson::kParseIterativeFlag, rapidjson::GenericDocument< Encoding, Allocator, StackAllocator >::Parse(), and ReadFile().