BeatSaber-Hooks: src/utils/logging.cpp File Reference
logging.cpp File Reference
#include "../../shared/utils/logging.hpp"
#include "modloader/shared/modloader.hpp"
#include <string_view>
#include <string>
#include <memory>
#include "../../shared/utils/utils-functions.h"
#include "../../shared/utils/utils.h"
#include <fstream>
#include <chrono>
#include <ctime>
#include <iomanip>
#include <sstream>
Data Structures
class Consumer
Macros
#define VERSION "0.0.0"
#define LOG_MAX_CHARS 1000
Functions
const char * get_level (Logging::Level level)
LoggerBuffer & get_global ()
Variables
bool createdGlobal = false
Macro Definition Documentation
LOG_MAX_CHARS
#define LOG_MAX_CHARS 1000
Definition at line 290 of file logging.cpp.
VERSION
#define VERSION "0.0.0"
Definition at line 19 of file logging.cpp.
Function Documentation
get_global()
LoggerBuffer& get_global ()
Definition at line 46 of file logging.cpp.
{
     static LoggerBuffer g(ModInfo{"GlobalLog", VERSION});
     if (!createdGlobal) {
         if (fileexists(g.get_path())) {
             deletefile(g.get_path());
         }
         __android_log_print(Logging::INFO, "QuestHook[Logging]", "Created get_global() log at path: %s", g.get_path().c_str());
         createdGlobal = true;
     }
     return g;
 }
References createdGlobal, deletefile(), fileexists(), Logging::INFO, and VERSION.
Referenced by Logger::close(), Logger::closeAll(), Logger::flush(), Logger::flushAll(), Logger::log(), and Consumer::operator()().
get_level()
const char* get_level (Logging::Level level)
Definition at line 26 of file logging.cpp.
{
     switch (level)
     {
     case Logging::Level::CRITICAL:
         return "CRITICAL";
     case Logging::Level::ERROR:
         return "ERROR";
     case Logging::Level::WARNING:
         return "WARNING";
     case Logging::Level::INFO:
         return "INFO";
     case Logging::Level::DEBUG:
         return "DEBUG";
     default:
         return "UNKNOWN";
     }
 }
References Logging::CRITICAL, Logging::DEBUG, Logging::ERROR, Logging::INFO, and Logging::WARNING.
Referenced by Logger::log().
Variable Documentation
createdGlobal
bool createdGlobal = false
Definition at line 44 of file logging.cpp.
Referenced by get_global().