BeatSaber-Hooks: shared/rapidjson/example/messagereader/messagereader.cpp File Reference
messagereader.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/error/en.h"
#include <iostream>
#include <string>
#include <map>
Data Structures
struct MessageHandler
Typedefs
typedef map< string, string > MessageMap
Functions
static void ParseMessages (const char *json, MessageMap &messages)
int main ()
Typedef Documentation
MessageMap
typedef map<string, string> MessageMap
Definition at line 13 of file messagereader.cpp.
Function Documentation
main()
int main ()
Definition at line 89 of file messagereader.cpp.
            {
     MessageMap messages;
     const char* json1 = "{ \"greeting\" : \"Hello!\", \"farewell\" : \"bye-bye!\" }";
     cout << json1 << endl;
     ParseMessages(json1, messages);
     for (MessageMap::const_iterator itr = messages.begin(); itr != messages.end(); ++itr)
         cout << itr->first << ": " << itr->second << endl;
     cout << endl << "Parse a JSON with invalid schema." << endl;
     const char* json2 = "{ \"greeting\" : \"Hello!\", \"farewell\" : \"bye-bye!\", \"foo\" : {} }";
     cout << json2 << endl;
     ParseMessages(json2, messages);
     return 0;
 }
References ParseMessages().
ParseMessages()
static void ParseMessages (const char * json, MessageMap & messages) static
Definition at line 75 of file messagereader.cpp.
{
     Reader reader;
     MessageHandler handler;
     StringStream ss(json);
     if (reader.Parse(ss, handler))
         messages.swap(handler.messages_);   // Only change it if success.
     else {
         ParseErrorCode e = reader.GetParseErrorCode();
         size_t o = reader.GetErrorOffset();
         cout << "Error: " << GetParseError_En(e) << endl;;
         cout << " at offset " << o << " near '" << string(json).substr(o, 10) << "...'" << endl;
     }
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), rapidjson::GetParseError_En(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), MessageHandler::messages_, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
Referenced by main().