BeatSaber-Hooks: doj Namespace Reference
doj Namespace Reference
Namespaces
anonymous_namespace{alphanum.hpp}
Data Structures
struct alphanum_less
Functions
template<typename lT , typename rT >
int alphanum_comp (const lT &left, const rT &right)
template<>
int alphanum_comp< std::string > (const std::string &l, const std::string &r)
int alphanum_comp (char *l, char *r)
int alphanum_comp (const char *l, const char *r)
int alphanum_comp (char *l, const char *r)
int alphanum_comp (const char *l, char *r)
int alphanum_comp (const std::string &l, char *r)
int alphanum_comp (char *l, const std::string &r)
int alphanum_comp (const std::string &l, const char *r)
int alphanum_comp (const char *l, const std::string &r)
Function Documentation
alphanum_comp() [1/9]
int doj::alphanum_comp (char * l, char * r)
Compare l and r with the same semantics as strcmp(), but with the "Alphanum Algorithm" which produces more human-friendly results.
Returns
negative if l<r, 0 if l==r, positive if l>r.
Definition at line 215 of file alphanum.hpp.
   {
     assert(l);
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<char*,char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [2/9]
int doj::alphanum_comp (char * l, const char * r)
Definition at line 235 of file alphanum.hpp.
   {
     assert(l);
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<char*,const char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [3/9]
int doj::alphanum_comp (char * l, const std::string & r)
Definition at line 264 of file alphanum.hpp.
   {
     assert(l);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<char*,std::string> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r.c_str());
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [4/9]
int doj::alphanum_comp (const char * l, char * r)
Definition at line 245 of file alphanum.hpp.
   {
     assert(l);
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<const char*,char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [5/9]
int doj::alphanum_comp (const char * l, const char * r)
Definition at line 225 of file alphanum.hpp.
   {
     assert(l);
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<const char*,const char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [6/9]
int doj::alphanum_comp (const char * l, const std::string & r)
Definition at line 282 of file alphanum.hpp.
   {
     assert(l);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<const char*,std::string> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l, r.c_str());
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [7/9]
template<typename lT , typename rT > int doj::alphanum_comp (const lT & left, const rT & right)
Compare left and right with the same semantics as strcmp(), but with the "Alphanum Algorithm" which produces more human-friendly results. The classes lT and rT must implement "std::ostream operator<< (std::ostream&, const Ty&)".
Returns
negative if left<right, 0 if left==right, positive if left>right.
Definition at line 176 of file alphanum.hpp.
   {
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<" << typeid(left).name() << "," << typeid(right).name() << "> " << left << "," << right << std::endl;
 #endif
     std::ostringstream l; l << left;
     std::ostringstream r; r << right;
     return alphanum_impl(l.str().c_str(), r.str().c_str());
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
Referenced by doj::alphanum_less< Ty >::operator()().
alphanum_comp() [8/9]
int doj::alphanum_comp (const std::string & l, char * r)
Definition at line 255 of file alphanum.hpp.
   {
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<std::string,char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l.c_str(), r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp() [9/9]
int doj::alphanum_comp (const std::string & l, const char * r)
Definition at line 273 of file alphanum.hpp.
   {
     assert(r);
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<std::string,const char*> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l.c_str(), r);
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().
alphanum_comp< std::string >()
template<> int doj::alphanum_comp< std::string > (const std::string & l, const std::string & r)
Compare l and r with the same semantics as strcmp(), but with the "Alphanum Algorithm" which produces more human-friendly results.
Returns
negative if l<r, 0 if l==r, positive if l>r.
Definition at line 194 of file alphanum.hpp.
   {
 #ifdef DOJDEBUG
     std::clog << "alphanum_comp<std::string,std::string> " << l << "," << r << std::endl;
 #endif
     return alphanum_impl(l.c_str(), r.c_str());
   }
References doj::anonymous_namespace{alphanum.hpp}::alphanum_impl().