BeatSaber-Hooks: il2cpp_utils Namespace Reference
il2cpp_utils Namespace Reference
Namespaces
array_utils
il2cpp_type_check
Data Structures
struct hash_pair
struct hash_pair_3
struct FindMethodInfo
struct __InternalCSStr
struct WrapperInstance
The wrapper for an invokable delegate with a context.
struct WrapperStatic
The wrapper for an invokable delegate without an existing context.
Typedefs
typedef std::pair< std::string, std::vector< const Il2CppType * > > classesNamesTypesInnerPairType
Enumerations
enum class CreationType { Temporary , Manual }
How to create an il2cpp object.
enum class StringType { Temporary , Manual }
Functions
LoggerContextObject & getLogger ()
Il2CppClass * GetClassFromName (std::string_view name_space, std::string_view type_name)
Il2CppClass * MakeGeneric (const Il2CppClass *klass, std::vector< const Il2CppClass * > args)
Il2CppClass * MakeGeneric (const Il2CppClass *klass, const Il2CppType **types, uint32_t numTypes)
std::string GenericClassStandardName (Il2CppGenericClass *genClass)
void LogClass (LoggerContextObject &logger, Il2CppClass *klass, bool logParents) noexcept
void BuildGenericsMap ()
void LogClasses (LoggerContextObject &logger, std::string_view classPrefix, bool logParents) noexcept
void AddTypeToNametoClassHashTable (const Il2CppImage *img, TypeDefinitionIndex index)
void AddNestedTypesToNametoClassHashTable (const Il2CppImage *img, const Il2CppTypeDefinition *typeDefinition)
void AddNestedTypesToNametoClassHashTable (Il2CppNameToTypeDefinitionIndexHashTable *hashTable, const char *namespaze, const std::string &parentName, Il2CppClass *klass)
std::string ExceptionToString (Il2CppException *exp) noexcept
FieldInfo * FindField (Il2CppClass *klass, std::string_view fieldName)
Il2CppClass * GetFieldClass (FieldInfo *field)
void LogField (LoggerContextObject &logger, FieldInfo *field)
void LogFields (LoggerContextObject &logger, Il2CppClass *klass, bool logParents)
const MethodInfo * MakeGenericMethod (const MethodInfo *info, std::vector< Il2CppClass * > types) noexcept
const MethodInfo * FindMethodUnsafe (const Il2CppClass *klass, std::string_view methodName, int argsCount) noexcept
const MethodInfo * FindMethodUnsafe (std::string_view nameSpace, std::string_view className, std::string_view methodName, int argsCount) noexcept
const MethodInfo * FindMethodUnsafe (Il2CppObject *instance, std::string_view methodName, int argsCount) noexcept
const MethodInfo * FindMethod (FindMethodInfo &info) noexcept
void LogMethods (LoggerContextObject &logger, Il2CppClass *klass, bool logParents)
void LogMethod (LoggerContextObject &logger, const MethodInfo *method)
bool IsConvertible (const Il2CppType *to, const Il2CppType *from, bool asArgs)
const PropertyInfo * FindProperty (Il2CppClass *klass, std::string_view propName)
const PropertyInfo * FindProperty (std::string_view nameSpace, std::string_view className, std::string_view propertyName)
void LogProperty (LoggerContextObject &logger, const PropertyInfo *prop)
void LogProperties (LoggerContextObject &logger, Il2CppClass *klass, bool logParents)
std::vector< const Il2CppType * > ClassVecToTypes (std::vector< const Il2CppClass * > seq)
const Il2CppType * MakeRef (const Il2CppType *type)
const Il2CppType * UnRef (const Il2CppType *type)
bool ParameterMatch (const MethodInfo *method, std::vector< Il2CppClass * > genTypes, std::vector< const Il2CppType * > argTypes)
bool ParameterMatch (const MethodInfo *method, std::vector< const Il2CppType * > argTypes)
const char * TypeGetSimpleName (const Il2CppType *type)
bool IsInterface (const Il2CppClass *klass)
std::vector< Il2CppClass * > ClassesFrom (std::vector< Il2CppClass * > classes)
std::vector< Il2CppClass * > ClassesFrom (std::vector< std::string_view > strings)
std::vector< const Il2CppType * > TypesFrom (std::vector< const Il2CppType * > types)
std::vector< const Il2CppType * > TypesFrom (std::vector< const Il2CppClass * > classes)
std::vector< const Il2CppType * > TypesFrom (std::vector< std::string_view > strings)
Il2CppClass * GetParamClass (const MethodInfo *method, int paramIdx)
Il2CppReflectionType * MakeGenericType (Il2CppReflectionType *gt, Il2CppArray *types)
Il2CppReflectionType * GetSystemType (const Il2CppType *typ)
Il2CppReflectionType * GetSystemType (const Il2CppClass *klass)
Il2CppReflectionType * GetSystemType (std::string_view nameSpace, std::string_view className)
void GenericsToStringHelper (Il2CppGenericClass *genClass, std::ostream &os)
std::string ClassStandardName (const Il2CppClass *klass, bool generics)
Il2CppObject * createManual (const Il2CppClass *klass) noexcept
Manually creates an instance of the provided Il2CppClass*. The created instance's type initializer will NOT execute on another thread! Be warned!
void * __AllocateUnsafe (std::size_t size)
Il2CppString * createcsstr (std::string_view inp, StringType type)
bool Match (const Il2CppObject *source, const Il2CppClass *klass) noexcept
bool AssertMatch (const Il2CppObject *source, Il2CppClass *klass)
void ClearDelegates ()
Clears all allocated delegates. THIS SHOULD NOT BE CALLED UNLESS YOU ARE CERTAIN ALL ALLOCATED DELEGATES NO LONGER EXIST IN IL2CPP!
void ClearDelegate (void *delegate)
Clears the specified delegate.
void AddAllocatedDelegate (void *delegate)
Adds the allocated Delegate* to the set of mapped delegates.
template<class TOut >
::std::optional< TOut > FromIl2CppObject (Il2CppObject *obj)
template<class T >
bool FromIl2CppObject (Il2CppObject *obj, T &out)
void LogClasses (LoggerContextObject &logger, ::std::string_view classPrefix, bool logParents=false) noexcept
Il2CppReflectionType * GetSystemType (::std::string_view nameSpace, ::std::string_view className)
template<class T >
void a_lack_of_no_arg_class_for ([[maybe_unused]]::std::string_view s)
template<typename T >
Il2CppClass * ExtractClass (T &&arg)
template<class T , bool ResultRequired = false>
Il2CppClass * NoArgClass ()
template<typename T >
const Il2CppType * ExtractType (T &&arg)
template<class T >
const Il2CppType * ExtractIndependentType ()
auto ExtractTypes ()
template<typename T , typename... TArgs>
::std::vector< const Il2CppType * > ExtractTypes (T &&arg, TArgs &&... args)
void AddNestedTypesToNametoClassHashTable (Il2CppNameToTypeDefinitionIndexHashTable *hashTable, const char *namespaze, const ::std::string &parentName, Il2CppClass *klass)
template<typename ParentT >
bool AssignableFrom (Il2CppClass *subOrInstanceKlass)
This method allows you to check if the parameter is a child or instance of the parent class. E.g (B extends A)
template<class U , class T >
U * cast (T *inst)
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may crash. See try_cast for a version that does not.
template<typename U , typename T >
U & cast_ref (T &inst)
Performs an il2cpp type checked cast from T to U, reference version. See cast for more documentation.
template<typename U , typename T >
std::optional< U * > try_cast (T *inst)
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
FieldInfo * FindField (Il2CppClass *klass, ::std::string_view fieldName)
template<class... TArgs>
FieldInfo * FindField (::std::string_view nameSpace, ::std::string_view className, TArgs &&... params)
template<class T , class... TArgs>
::std::enable_if_t<!::std::is_convertible_v< T, ::std::string_view >, FieldInfo * > FindField (T &&instance, TArgs &&... params)
template<typename TOut = Il2CppObject*>
::std::optional< TOut > GetFieldValue (Il2CppObject *instance, FieldInfo *field)
template<typename TOut = Il2CppObject*, typename T >
::std::optional< TOut > GetFieldValue (T &&classOrInstance, ::std::string_view fieldName)
template<typename TOut = Il2CppObject*>
::std::optional< TOut > GetFieldValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view fieldName)
template<class TArg >
bool SetFieldValue (Il2CppObject *instance, FieldInfo *field, TArg &&value)
template<class T , class TArg >
bool SetFieldValue (T &classOrInstance, ::std::string_view fieldName, TArg &&value)
template<class TArg >
bool SetFieldValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view fieldName, TArg &&value)
template<typename... TArgs>
Il2CppObject * CreateFieldValue (FieldInfo *field, TArgs &&...args)
template<typename... TArgs>
Il2CppObject * CreateFieldValueUnsafe (FieldInfo *field, TArgs &&...args)
::std::vector< Il2CppClass * > ClassesFrom (::std::vector< Il2CppClass * > classes)
::std::vector< Il2CppClass * > ClassesFrom (::std::vector<::std::string_view > strings)
template<class T >
Il2CppObject * ToIl2CppObject (T &&arg)
template<class T >
void * ExtractValue (T &&arg)
auto ExtractValues ()
template<class T , class... TArgs>
::std::vector< void * > ExtractValues (T &&arg, TArgs &&...args)
const MethodInfo * MakeGenericMethod (const MethodInfo *info, ::std::vector< Il2CppClass * > types) noexcept
Instantiates a generic MethodInfo* from the provided Il2CppClasses.
const MethodInfo * FindMethodUnsafe (const Il2CppClass *klass, ::std::string_view methodName, int argsCount) noexcept
const MethodInfo * FindMethodUnsafe (Il2CppObject *instance, ::std::string_view methodName, int argsCount) noexcept
const MethodInfo * FindMethodUnsafe (::std::string_view nameSpace, ::std::string_view className, ::std::string_view methodName, int argsCount) noexcept
template<typename... TArgs, ::std::enable_if_t<(... &&!::std::is_convertible_v< TArgs, FindMethodInfo >), int > = 0>
const MethodInfo * FindMethod (TArgs &&... args) noexcept
bool ParameterMatch (const MethodInfo *method, ::std::vector< const Il2CppType * > argTypes)
bool ParameterMatch (const MethodInfo *method, ::std::vector< Il2CppClass * > genTypes, ::std::vector< const Il2CppType * > argTypes)
template<class TOut = Il2CppObject*, bool checkTypes = true, class T , class... TArgs>
::std::optional< TOut > RunMethod (T &&instance, const MethodInfo *method, TArgs &&...params)
template<class TOut = Il2CppObject*, bool checkTypes = true, class... TArgs>
::std::optional< TOut > RunStaticMethod (const MethodInfo *method, TArgs &&...params)
template<class TOut = Il2CppObject*, class T , class... TArgs>
::std::optional< TOut > RunMethodUnsafe (T &&instance, const MethodInfo *method, TArgs &&...params)
template<class TOut = Il2CppObject*, class... TArgs>
::std::optional< TOut > RunStaticMethodUnsafe (const MethodInfo *method, TArgs &&...params)
template<class TOut = Il2CppObject*, bool checkTypes = true, class T , class... TArgs>
::std::enable_if_t<!::std::is_convertible_v< T, ::std::string_view >, ::std::optional< TOut > > RunMethod (T &&classOrInstance, ::std::string_view methodName, TArgs &&...params)
template<class TOut = Il2CppObject*, bool checkTypes = true, class... TArgs>
::std::optional< TOut > RunMethod (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, TArgs &&...params)
template<class TOut = Il2CppObject*, class T , class... TArgs>
::std::optional< TOut > RunGenericMethod (T &&instance, const MethodInfo *info, ::std::vector< Il2CppClass * > genTypes, TArgs &&...params) noexcept
Instantiates a generic MethodInfo* from the provided Il2CppClasses and invokes it.
This method will not crash.
template<class TOut = Il2CppObject*, class T , class... TArgs>
::std::optional< TOut > RunGenericMethod (T &&classOrInstance, ::std::string_view methodName, ::std::vector< Il2CppClass * > genTypes, TArgs &&...params) noexcept
template<class TOut = Il2CppObject*, class... TArgs>
::std::optional< TOut > RunGenericMethod (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, ::std::vector< Il2CppClass * > genTypes, TArgs &&...params) noexcept
template<class TOut = Il2CppObject*, class T , class... TArgs>
::std::enable_if_t<::std::is_base_of_v< Il2CppClass, T >||::std::is_base_of_v< Il2CppObject, T >, ::std::optional< TOut > > RunMethodUnsafe (T *classOrInstance, ::std::string_view methodName, TArgs &&...params)
template<class TOut = Il2CppObject*, class... TArgs>
::std::optional< TOut > RunMethodUnsafe (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, TArgs &&...params)
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs>
::std::optional< TOut > New (Il2CppClass *klass, TArgs &&...args)
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs>
::std::optional< TOut > NewUnsafe (const Il2CppClass *klass, TArgs &&...args)
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs>
::std::enable_if_t<(... &&((!::std::is_same_v< const Il2CppClass *, TArgs >||!::std::is_same_v< Il2CppClass *, TArgs >) &&!::std::is_convertible_v< TArgs, ::std::string_view >)), ::std::optional< TOut > > New (TArgs &&...args)
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs>
::std::optional< TOut > New (::std::string_view nameSpace, ::std::string_view className, TArgs &&...args)
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs>
::std::optional< TOut > NewUnsafe (::std::string_view nameSpace, ::std::string_view className, TArgs *...args)
const PropertyInfo * FindProperty (Il2CppClass *klass, ::std::string_view propertyName)
const PropertyInfo * FindProperty (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propertyName)
template<class T >
const PropertyInfo * FindProperty (T &&instance, ::std::string_view propertyName)
template<class TOut = Il2CppObject*, bool checkTypes = true, class T >
::std::optional< TOut > GetPropertyValue (T &&classOrInstance, const PropertyInfo *prop)
template<typename TOut = Il2CppObject*, bool checkTypes = true, typename T >
::std::optional< TOut > GetPropertyValue (T &&classOrInstance, ::std::string_view propName)
template<typename TOut = Il2CppObject*, bool checkTypes = true>
::std::optional< TOut > GetPropertyValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propName)
template<bool checkTypes = true, class T , class TArg >
bool SetPropertyValue (T &classOrInstance, const PropertyInfo *prop, TArg &&value)
template<bool checkTypes = true, class T , class TArg >
bool SetPropertyValue (T &classOrInstance, ::std::string_view propName, TArg &&value)
template<bool checkTypes = true, class TArg >
bool SetPropertyValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propName, TArg &&value)
::std::vector< const Il2CppType * > ClassVecToTypes (::std::vector< const Il2CppClass * > seq)
::std::vector< const Il2CppType * > TypesFrom (::std::vector< const Il2CppType * > types)
::std::vector< const Il2CppType * > TypesFrom (::std::vector< const Il2CppClass * > classes)
::std::vector< const Il2CppType * > TypesFrom (::std::vector<::std::string_view > strings)
template<CreationType creationType = CreationType::Temporary>
Il2CppString * newcsstr (std::u16string_view inp)
Create a new csstr from a UTF16 string view.
template<CreationType creationType = CreationType::Temporary>
Il2CppString * newcsstr (std::string_view inp)
Create a new csstr from a UTF8 string view.
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*, typename R , typename... TArgs>
T MakeDelegate (const Il2CppClass *delegateClass, TObj obj, function_ptr_t< R, TArgs... > callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppClass*.
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*>
T MakeDelegate (const Il2CppClass *delegateClass, TObj obj, void *callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppClass*. Assumes the callback has no parameters and a void return.
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*, typename R , typename... TArgs>
T MakeDelegate (const Il2CppType *actionType, TObj obj, function_ptr_t< R, TArgs... > callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppType* PLEASE!!! use the FieldInfo*, MethodInfo*, or Il2CppClass* versions instead if you can.
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*>
T MakeDelegate (const Il2CppType *delegateType, TObj obj, void *callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppType* and void* callback. Assumes the callback has no parameters and a void return.
template<typename T = MulticastDelegate*, typename T1 , typename T2 >
T MakeDelegate (const MethodInfo *method, int paramIdx, T1 &&arg1, T2 &&arg2)
Creates a delegate fit to be passed in the given parameter position to the given method.
template<typename T = MulticastDelegate*, typename T1 , typename T2 >
T MakeDelegate (FieldInfo *field, T1 &&arg1, T2 &&arg2)
Creates a delegate fit to be assigned to the given field.
template<class I , class R , class... TArgs>
R __attribute__ ((noinline)) invoker_func_instance(WrapperInstance< I
The invoker function for a delegate that has a non-trivial context.
template<typename T = MulticastDelegate*, class I , class R , class... TArgs>
T MakeDelegate (const Il2CppClass *delegateClass, I &instance, std::function< R(I *, TArgs...)> f)
Makes a delegate wrapping a context function (such as a context lambda).
template<typename T = MulticastDelegate*, class R , class... TArgs>
T MakeDelegate (const Il2CppClass *delegateClass, std::function< R(TArgs...)> f)
Makes a delegate wrapping a context function (such as a context lambda).
template<typename T = MulticastDelegate*, class I , class R , class... TArgs>
T MakeDelegate (const Il2CppClass *delegateClass, I &instance, R(I::*memberFunc)(TArgs...))
Makes a delegate wrapping the provided instance method.
template<typename... TArgs>
Il2CppObject * CreateParam (const MethodInfo *method, int paramIdx, TArgs &&...args)
template<typename... TArgs>
Il2CppObject * CreateParamUnsafe (const MethodInfo *method, int paramIdx, TArgs &&...args)
template<typename T >
Array< T > * vectorToArray (::std::vector< T > &vec)
Converts a vector to an Array*.
Il2CppString * createcsstr (::std::string_view inp, StringType type=StringType::Temporary)
Creates a new C# string and registers it with GC. Copies the input string.
bool AssertMatch (const Il2CppObject *source, const Il2CppClass *klass)
template<class To , class From >
auto down_cast (From *in) noexcept
template<typename... TArgs>
Il2CppObject * RuntimeInvoke (const MethodInfo *method, Il2CppObject *reference, Il2CppException **exc, TArgs *...args)
template<typename T = void, typename... TArgs>
void ExtractClassesNoArgs (::std::vector< const Il2CppClass * > &vec)
template<typename... TArgs>
::std::vector< const Il2CppClass * > ExtractFromFunctionNoArgs ()
template<typename T = MulticastDelegate*, typename Ret , typename... TArgs>
T MakeFunc (function_ptr_t< Ret, TArgs... > lambda)
Creates and returns a C# System.Func<TArgs..., Ret> from the provided function_ptr_t. Note that this function assumes AOT code exists for a System.Func with the provided generic arguments.
template<typename T = MulticastDelegate*, typename... TArgs>
T MakeAction (function_ptr_t< void, TArgs... > lambda)
Creates and returns a C# System.Action<TArgs...> from the provided function_ptr_t. Note that this function assumes AOT code exists for a System.Action with the provided generic arguments.
Variables
static std::unordered_map< std::pair< std::string, std::string >, Il2CppClass *, hash_pair > namesToClassesCache
static std::mutex nameHashLock
static int indent = -1
static int maxIndent
std::unordered_set< Il2CppClass * > loggedClasses
static std::unordered_map< Il2CppClass *, std::map< std::string, Il2CppGenericClass *, doj::alphanum_less< std::string > > > classToGenericClassMap
static std::unordered_map< std::pair< const Il2CppClass *, std::string >, FieldInfo *, hash_pair > classesNamesToFieldsCache
static std::mutex nameFieldLock
static std::unordered_map< std::pair< const Il2CppClass *, std::pair< std::string, decltype(MethodInfo::parameters_count)> >, const MethodInfo *, hash_pair_3 > classesNamesToMethodsCache
static std::unordered_map< std::pair< const Il2CppClass *, classesNamesTypesInnerPairType >, const MethodInfo *, hash_pair_3 > classesNamesTypesToMethodsCache
std::mutex classNamesMethodsLock
std::mutex classTypesMethodsLock
static std::unordered_map< std::pair< const Il2CppClass *, std::string >, const PropertyInfo *, hash_pair > classesNamesToPropertiesCache
static std::mutex classPropertiesLock
static std::unordered_map< Il2CppClass *, const char * > typeMap
static std::mutex typeLock
std::unordered_set< void * > delegates
R R
R TArgs * instance
R TArgs TArgs args
Typedef Documentation
classesNamesTypesInnerPairType
typedef std::pair<std::string, std::vector<const Il2CppType*> > il2cpp_utils::classesNamesTypesInnerPairType
Definition at line 32 of file il2cpp-utils-methods.cpp.
Enumeration Type Documentation
CreationType
enum il2cpp_utils::CreationType strong
How to create an il2cpp object.
Enumerator
Temporary
Created object is a C# object, it may be GC'd.
Manual
Created object is manual, it must be freed explicitly (via delete).
Definition at line 23 of file il2cpp-utils-methods.hpp.
{
         Temporary,
         Manual
     };
StringType
enum il2cpp_utils::StringType strong
Enumerator
Temporary
Manual
Definition at line 379 of file il2cpp-utils.hpp.
{
         Temporary,  // string is normal C# object, may be GC'd
         Manual,     // string is owned by C++, must be manually freed (use this for string constants as well)
     };
Function Documentation
__AllocateUnsafe()
void* il2cpp_utils::__AllocateUnsafe (std::size_t size)
Definition at line 247 of file il2cpp-utils.cpp.
{
         il2cpp_functions::Init();
         // Because we want to allocate this object using C# GC, we will do a bit of a hack here.
         // Essentially, we take advantage of the instance size of System.Object, and then IMMEDIATELY revert it.
         // If we fail for ANY REASON in here, VERY BAD THINGS can happen.
         static auto* objKlass = CRASH_UNLESS(GetClassFromName("System", "Object"));
         // Ideally, we make this atomic, but because we aren't using locks anywhere, we hope for the best...
         // TODO: Acquire object class special lock
         auto origSize = objKlass->instance_size;
         objKlass->instance_size = static_cast<decltype(origSize)>(size);
         auto* instance = il2cpp_functions::object_new(objKlass);
         objKlass->instance_size = origSize;
         return instance;
     }
References GetClassFromName(), il2cpp_functions::Init(), instance, and il2cpp_functions::object_new.
Referenced by MakeDelegate().
__attribute__()
template<class I , class R , class... TArgs> R il2cpp_utils::__attribute__ ((noinline))
The invoker function for a delegate that has a non-trivial context.
Template Parameters
I The wrapped instance type.
R The return type of the function.
TArgs The argument types of the function.
Parameters
instance The wrapped instance of this context function.
args The arguments to pass to this function.
Returns
The return from the wrapped function.
References args, and instance.
a_lack_of_no_arg_class_for()
template<class T > void il2cpp_utils::a_lack_of_no_arg_class_for ([[maybe_unused] ]::std::string_view s)
Definition at line 70 of file il2cpp-utils-classes.hpp.
 {};
AddAllocatedDelegate()
void il2cpp_utils::AddAllocatedDelegate (void * delegate)
Adds the allocated Delegate* to the set of mapped delegates.
Parameters
delegate The Delegate* to add
Remarks
See ClearDelegates() and ClearDelegate(Delegate* delegate)
Definition at line 307 of file il2cpp-utils.cpp.
{
         delegates.insert(delegate);
     }
References delegates.
Referenced by MakeDelegate().
AddNestedTypesToNametoClassHashTable() [1/3]
void il2cpp_utils::AddNestedTypesToNametoClassHashTable (const Il2CppImage * img, const Il2CppTypeDefinition * typeDefinition)
Definition at line 249 of file il2cpp-utils-classes.cpp.
{
         il2cpp_functions::Init();
         for (int i = 0; i < typeDefinition->nested_type_count; ++i) {
             Il2CppClass *klass = il2cpp_functions::MetadataCache_GetNestedTypeFromIndex(typeDefinition->nestedTypesStart + i);
             AddNestedTypesToNametoClassHashTable(img->nameToClassHashTable, il2cpp_functions::MetadataCache_GetStringFromIndex(typeDefinition->namespaceIndex), il2cpp_functions::MetadataCache_GetStringFromIndex(typeDefinition->nameIndex), klass);
         }
     }
References il2cpp_functions::Init(), il2cpp_functions::MetadataCache_GetNestedTypeFromIndex(), and il2cpp_functions::MetadataCache_GetStringFromIndex().
Referenced by AddNestedTypesToNametoClassHashTable(), and AddTypeToNametoClassHashTable().
AddNestedTypesToNametoClassHashTable() [2/3]
void il2cpp_utils::AddNestedTypesToNametoClassHashTable (Il2CppNameToTypeDefinitionIndexHashTable * hashTable, const char * namespaze, const ::std::string & parentName, Il2CppClass * klass)
AddNestedTypesToNametoClassHashTable() [3/3]
void il2cpp_utils::AddNestedTypesToNametoClassHashTable (Il2CppNameToTypeDefinitionIndexHashTable * hashTable, const char * namespaze, const std::string & parentName, Il2CppClass * klass)
Definition at line 257 of file il2cpp-utils-classes.cpp.
{
         il2cpp_functions::Init();
         std::string name = parentName + "/" + klass->name;
         char *pName = (char*)gc_alloc_specific(name.size() + 1 * sizeof(char));
         strcpy(pName, name.c_str());
         hashTable->insert(std::make_pair(std::make_pair(namespaze, (const char*)pName), il2cpp_functions::MetadataCache_GetIndexForTypeDefinition(klass)));
         void *iter = NULL;
         while (Il2CppClass *nestedClass = il2cpp_functions::class_get_nested_types(klass, &iter))
             AddNestedTypesToNametoClassHashTable(hashTable, namespaze, name, nestedClass);
     }
References AddNestedTypesToNametoClassHashTable(), il2cpp_functions::class_get_nested_types, gc_alloc_specific(), il2cpp_functions::Init(), and il2cpp_functions::MetadataCache_GetIndexForTypeDefinition().
AddTypeToNametoClassHashTable()
void il2cpp_utils::AddTypeToNametoClassHashTable (const Il2CppImage * img, TypeDefinitionIndex index)
Definition at line 236 of file il2cpp-utils-classes.cpp.
{
         il2cpp_functions::Init();
         const Il2CppTypeDefinition* typeDefinition = il2cpp_functions::MetadataCache_GetTypeDefinitionFromIndex(index);
         // don't add nested types
         if (typeDefinition->declaringTypeIndex != kTypeIndexInvalid)
             return;
         if (img != il2cpp_functions::get_corlib())
             AddNestedTypesToNametoClassHashTable(img, typeDefinition);
         img->nameToClassHashTable->insert(std::make_pair(std::make_pair(il2cpp_functions::MetadataCache_GetStringFromIndex(typeDefinition->namespaceIndex), il2cpp_functions::MetadataCache_GetStringFromIndex(typeDefinition->nameIndex)), index));
     }
References AddNestedTypesToNametoClassHashTable(), il2cpp_functions::get_corlib, il2cpp_functions::Init(), il2cpp_functions::MetadataCache_GetStringFromIndex(), and il2cpp_functions::MetadataCache_GetTypeDefinitionFromIndex().
Referenced by LogClasses().
AssertMatch() [1/2]
bool il2cpp_utils::AssertMatch (const Il2CppObject * source, const Il2CppClass * klass)
AssertMatch() [2/2]
bool il2cpp_utils::AssertMatch (const Il2CppObject * source, Il2CppClass * klass)
Definition at line 278 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("AssertMatch");
         il2cpp_functions::Init();
         if (!Match(source, klass)) {
             logger.critical("source with class '%s' does not match class '%s'!",
                 ClassStandardName(source->klass).c_str(), ClassStandardName(klass).c_str());
             SAFE_ABORT();
         }
         return true;
     }
References ClassStandardName(), getLogger(), il2cpp_functions::Init(), Match(), rapidjson::source, and LoggerContextObject::WithContext().
AssignableFrom()
template<typename ParentT > bool il2cpp_utils::AssignableFrom (Il2CppClass * subOrInstanceKlass)
This method allows you to check if the parameter is a child or instance of the parent class. E.g (B extends A)
Template Parameters
ParentT The parent class (left hand assignment)
Parameters
subOrInstanceKlass the instance class (right hand assignment)
A a;
if (a is B b) {
}
Returns
Returns true if subOrInstanceKlass is a child or instance of ParentT. For more information, check https://docs.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=net-5.0
Definition at line 164 of file il2cpp-utils-classes.hpp.
{
         il2cpp_functions::Init();
         RET_DEFAULT_UNLESS(getLogger(), subOrInstanceKlass);
         auto* parentK = RET_DEFAULT_UNLESS(getLogger(), classof(ParentT));
         return il2cpp_functions::class_is_assignable_from(parentK, subOrInstanceKlass);
     }
References il2cpp_functions::class_is_assignable_from, classof, getLogger(), il2cpp_functions::Init(), and RET_DEFAULT_UNLESS.
BuildGenericsMap()
void il2cpp_utils::BuildGenericsMap ()
Definition at line 146 of file il2cpp-utils-classes.cpp.
{
         static auto logger = getLogger().WithContext("BuildGenericsMap");
         il2cpp_functions::Init();
         auto* metadataReg = RET_V_UNLESS(logger, *il2cpp_functions::s_Il2CppMetadataRegistrationPtr);
         logger.debug("metadataReg: %p, offset = %lX", metadataReg, ((uintptr_t)metadataReg) - getRealOffset(0));
         int uncached_class_count = 0;
         for (int i=0; i < metadataReg->genericClassesCount; i++) {
             Il2CppGenericClass* genClass = metadataReg->genericClasses[i];
             if (!genClass) continue;
             if (!(genClass->cached_class)) {
                 uncached_class_count++;
             }
             std::string genClassName = GenericClassStandardName(genClass);
             auto* typeDefClass = il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex(genClass->typeDefinitionIndex);
             if (!typeDefClass) continue;
             classToGenericClassMap[typeDefClass][genClassName.c_str()] = genClass;
         }
         logger.debug("uncached_class_count: %i (%f proportion of total)", uncached_class_count, uncached_class_count * 1.0 / metadataReg->genericClassesCount);
     }
References classToGenericClassMap, GenericClassStandardName(), getLogger(), getRealOffset(), il2cpp_functions::Init(), il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex, RET_V_UNLESS, il2cpp_functions::s_Il2CppMetadataRegistrationPtr, and LoggerContextObject::WithContext().
Referenced by LogClasses().
cast()
template<class U , class T > U* il2cpp_utils::cast (T * inst)
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may crash. See try_cast for a version that does not.
Template Parameters
T The type to cast from.
U The type to cast to.
Returns
A U* of the cast value.
Definition at line 179 of file il2cpp-utils-classes.hpp.
{
         // TODO: Assumes T* is (at least) an Il2CppClass**, this means it assumes klass as first field.
         auto* k1 = CRASH_UNLESS(classof(U*));
         auto* k2 = *reinterpret_cast<Il2CppClass**>(CRASH_UNLESS(inst));
         CRASH_UNLESS(k2);
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return reinterpret_cast<U*>(inst);
         }
         SAFE_ABORT();
         return nullptr;
     }
References il2cpp_functions::class_is_assignable_from, and classof.
Referenced by cast_ref().
cast_ref()
template<typename U , typename T > U& il2cpp_utils::cast_ref (T & inst)
Performs an il2cpp type checked cast from T to U, reference version. See cast for more documentation.
Template Parameters
T The type to cast from.
U The type to cast to.
Returns
A U& of the cast value.
Definition at line 195 of file il2cpp-utils-classes.hpp.
{
         return *cast(std::addressof(inst));
     }
References cast().
ClassesFrom() [1/4]
std::vector< Il2CppClass * > il2cpp_utils::ClassesFrom (::std::vector< Il2CppClass * > classes)
ClassesFrom() [2/4]
std::vector< Il2CppClass * > il2cpp_utils::ClassesFrom (::std::vector<::std::string_view > strings)
ClassesFrom() [3/4]
std::vector<Il2CppClass*> il2cpp_utils::ClassesFrom (std::vector< Il2CppClass * > classes)
Definition at line 118 of file il2cpp-utils.cpp.
 { return classes; }
Referenced by il2cpp_utils::FindMethodInfo::FindMethodInfo().
ClassesFrom() [4/4]
std::vector<Il2CppClass*> il2cpp_utils::ClassesFrom (std::vector< std::string_view > strings)
Definition at line 119 of file il2cpp-utils.cpp.
{
         std::vector<Il2CppClass*> classes;
         for (size_t i = 0; i < strings.size() - 1; i += 2) {
             classes.push_back(GetClassFromName(strings[i].data(), strings[i+1].data()));
         }
         return classes;
     }
References GetClassFromName().
ClassStandardName()
std::string il2cpp_utils::ClassStandardName (const Il2CppClass * klass, bool generics)
Definition at line 201 of file il2cpp-utils.cpp.
{
         il2cpp_functions::Init();
         std::stringstream ss;
         const char* namespaze = il2cpp_functions::class_get_namespace(klass);
         auto* declaring = il2cpp_functions::class_get_declaring_type(klass);
         bool hasNamespace = (namespaze && namespaze[0] != '\0');
         if (!hasNamespace && declaring) {
             ss << ClassStandardName(declaring) << "/";
         } else {
             ss << namespaze << "::";
         }
         ss << il2cpp_functions::class_get_name(klass);
         if (generics) {
             il2cpp_functions::class_is_generic(klass);
             auto* genClass = klass->generic_class;
             if (genClass) {
                 GenericsToStringHelper(genClass, ss);
             }
         }
         return ss.str();
     }
References il2cpp_functions::class_get_declaring_type, il2cpp_functions::class_get_name, il2cpp_functions::class_get_namespace, il2cpp_functions::class_is_generic, GenericsToStringHelper(), and il2cpp_functions::Init().
Referenced by AssertMatch(), FindField(), FindMethod(), FindMethodUnsafe(), FindProperty(), GenericClassStandardName(), LogClass(), LogClasses(), LogFields(), LogMethods(), LogProperties(), and MakeGeneric().
ClassVecToTypes() [1/2]
::std::vector<const Il2CppType*> il2cpp_utils::ClassVecToTypes (::std::vector< const Il2CppClass * > seq)
ClassVecToTypes() [2/2]
std::vector<const Il2CppType*> il2cpp_utils::ClassVecToTypes (std::vector< const Il2CppClass * > seq)
Definition at line 17 of file il2cpp-utils.cpp.
{
         il2cpp_functions::Init();
         std::vector<const Il2CppType*> types(seq.size());
         std::transform(seq.begin(), seq.end(), types.begin(), il2cpp_functions::class_get_type_const);
         return types;
     }
References il2cpp_functions::class_get_type_const, and il2cpp_functions::Init().
Referenced by TypesFrom().
ClearDelegate()
void il2cpp_utils::ClearDelegate (void * delegate)
Clears the specified delegate.
Parameters
delegate The Delegate* to clear the allocated MethodInfo* from, if it exists
Definition at line 299 of file il2cpp-utils.cpp.
{
         auto itr = delegates.find(delegate);
         if (itr != delegates.end()) {
             free(reinterpret_cast<Delegate*>(*itr)->original_method_info);
             delegates.erase(itr);
         }
     }
References delegates, and Delegate::original_method_info.
ClearDelegates()
void il2cpp_utils::ClearDelegates ()
Clears all allocated delegates. THIS SHOULD NOT BE CALLED UNLESS YOU ARE CERTAIN ALL ALLOCATED DELEGATES NO LONGER EXIST IN IL2CPP!
Definition at line 292 of file il2cpp-utils.cpp.
{
         for (auto itr : delegates) {
             free(reinterpret_cast<Delegate*>(itr)->original_method_info);
         }
         delegates.clear();
     }
References delegates.
createcsstr() [1/2]
Il2CppString* il2cpp_utils::createcsstr (::std::string_view inp, StringType type = StringType::Temporary)
Creates a new C# string and registers it with GC. Copies the input string.
Parameters
inp String view to create the string from.
type The type of string to create
Returns
Created string
createcsstr() [2/2]
Il2CppString* il2cpp_utils::createcsstr (std::string_view inp, StringType type)
Definition at line 262 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("createcsstr");
         il2cpp_functions::Init();
         switch (type) {
             case StringType::Manual: {
                 return newcsstr<CreationType::Manual>(inp);
             }
             default:
                 return newcsstr<CreationType::Temporary>(inp);
         }
     }
References getLogger(), il2cpp_functions::Init(), Manual, and LoggerContextObject::WithContext().
CreateFieldValue()
template<typename... TArgs> Il2CppObject* il2cpp_utils::CreateFieldValue (FieldInfo * field, TArgs &&... args)
Definition at line 139 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetFieldClass(field));
         return il2cpp_utils::New(klass, args...);
     }
References args, GetFieldClass(), getLogger(), New(), and RET_0_UNLESS.
CreateFieldValueUnsafe()
template<typename... TArgs> Il2CppObject* il2cpp_utils::CreateFieldValueUnsafe (FieldInfo * field, TArgs &&... args)
Definition at line 146 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetFieldClass(field));
         return il2cpp_utils::NewUnsafe(klass, args...);
     }
References args, GetFieldClass(), getLogger(), NewUnsafe(), and RET_0_UNLESS.
createManual()
Il2CppObject * il2cpp_utils::createManual (const Il2CppClass * klass) noexcept
Manually creates an instance of the provided Il2CppClass*. The created instance's type initializer will NOT execute on another thread! Be warned!
Parameters
klass The Il2CppClass* to create an instance of.
Returns
The created instance, or nullptr if it failed for any reason.
Definition at line 224 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("createManual");
         if (!klass->initialized) {
             logger.error("Cannot create an object that does not have an initialized class: %p", klass);
             return nullptr;
         }
         // Allocate GC Specific object
         auto* obj = reinterpret_cast<Il2CppObject*>(gc_alloc_specific(klass->instance_size));
         obj->klass = const_cast<Il2CppClass*>(klass);
         // Call cctor, we don't bother making a new thread for the type initializer. BE WARNED!
         if (klass->has_cctor && !klass->cctor_finished && !klass->cctor_started) {
             obj->klass->cctor_started = true;
             auto* m = RET_0_UNLESS(logger, FindMethodUnsafe(klass, ".cctor", 0));
             RET_0_UNLESS(logger, il2cpp_utils::RunStaticMethodUnsafe(m));
             obj->klass->cctor_finished = true;
         }
         // This really has the weirdest syntax ever, I swear...
         // First param is unused, second param is dereferenced and is set to third param.
         // Second param is write barrier'd
         // This takes advantage of the fact that the first field of an Il2CppObject is a klass.
         return obj;
     }
References LoggerContextObject::error(), FindMethodUnsafe(), gc_alloc_specific(), getLogger(), RET_0_UNLESS, RunStaticMethodUnsafe(), and LoggerContextObject::WithContext().
Referenced by New(), and NewUnsafe().
CreateParam()
template<typename... TArgs> Il2CppObject* il2cpp_utils::CreateParam (const MethodInfo * method, int paramIdx, TArgs &&... args)
Definition at line 348 of file il2cpp-utils.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetParamClass(method, paramIdx));
         return il2cpp_utils::New(klass, args...);
     }
References args, getLogger(), GetParamClass(), New(), and RET_0_UNLESS.
CreateParamUnsafe()
template<typename... TArgs> Il2CppObject* il2cpp_utils::CreateParamUnsafe (const MethodInfo * method, int paramIdx, TArgs &&... args)
Definition at line 355 of file il2cpp-utils.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetParamClass(method, paramIdx));
         return il2cpp_utils::NewUnsafe(klass, args...);
     }
References args, getLogger(), GetParamClass(), NewUnsafe(), and RET_0_UNLESS.
down_cast()
template<class To , class From > auto il2cpp_utils::down_cast (From * in) noexcept
Definition at line 400 of file il2cpp-utils.hpp.
{
         static_assert(::std::is_nothrow_convertible_v<To*, From*>);
         return static_cast<To*>(in);
     }
ExceptionToString()
std::string il2cpp_utils::ExceptionToString (Il2CppException * exp) noexcept
Definition at line 11 of file il2cpp-utils-exceptions.cpp.
{
         il2cpp_functions::Init();
         char msg[EXCEPTION_MESSAGE_SIZE];
         il2cpp_functions::format_exception(exp, msg, EXCEPTION_MESSAGE_SIZE);
         // auto exception_message = csstrtostr(exp->message);
         // return to_utf8(exception_message);
         return msg;
     }
References EXCEPTION_MESSAGE_SIZE, il2cpp_functions::format_exception, and il2cpp_functions::Init().
Referenced by MakeGenericType(), and RunMethod().
ExtractClass()
template<typename T > Il2CppClass* il2cpp_utils::ExtractClass (T && arg)
Definition at line 73 of file il2cpp-utils-classes.hpp.
{
         using Dt = ::std::decay_t<T>;
         using arg_class = il2cpp_type_check::il2cpp_arg_class<Dt>;
         static auto& logger = getLogger();
         Il2CppClass* klass = arg_class::get(arg);
         if (!klass) {
             logger.error("Failed to determine class! Tips: instead of nullptr, pass the Il2CppType* or Il2CppClass* of the argument instead!");
         }
         return klass;
     }
References getLogger().
Referenced by FindField(), il2cpp_utils::FindMethodInfo::FindMethodInfo(), FindProperty(), RunMethod(), and ToIl2CppObject().
ExtractClassesNoArgs()
template<typename T = void, typename... TArgs> void il2cpp_utils::ExtractClassesNoArgs (::std::vector< const Il2CppClass * > & vec)
Definition at line 415 of file il2cpp-utils.hpp.
{
         vec.push_back(classof(T));
         if constexpr (sizeof...(TArgs) != 0) {
             ExtractClassesNoArgs<TArgs...>(vec);
         }
     }
References classof, and T.
Referenced by ExtractFromFunctionNoArgs().
ExtractFromFunctionNoArgs()
template<typename... TArgs> ::std::vector<const Il2CppClass*> il2cpp_utils::ExtractFromFunctionNoArgs ()
Definition at line 423 of file il2cpp-utils.hpp.
{
         ::std::vector<const Il2CppClass*> vec(sizeof...(TArgs));
         ExtractClassesNoArgs<TArgs...>(vec);
         return vec;
     }
References ExtractClassesNoArgs().
Referenced by MakeAction(), and MakeFunc().
ExtractIndependentType()
template<class T > const Il2CppType* il2cpp_utils::ExtractIndependentType ()
Definition at line 117 of file il2cpp-utils-classes.hpp.
{
         static auto& logger = getLogger();
         if constexpr (std::is_reference_v<T>) {
             auto* klass = RET_0_UNLESS(logger, NoArgClass<std::remove_reference_t<T>>());
             return &klass->this_arg;
         } else {
             auto* klass = RET_0_UNLESS(logger, NoArgClass<T>());
             il2cpp_functions::Init();
             return il2cpp_functions::class_get_type(klass);
         }
     }
References il2cpp_functions::class_get_type, getLogger(), il2cpp_functions::Init(), NoArgClass(), and RET_0_UNLESS.
ExtractType()
template<typename T > const Il2CppType* il2cpp_utils::ExtractType (T && arg)
Definition at line 107 of file il2cpp-utils-classes.hpp.
{
         static auto& logger = getLogger();
         const Il2CppType* typ = il2cpp_type_check::il2cpp_arg_type<T>::get(arg);
         if (!typ)
             logger.error("ExtractType: failed to determine type! Tips: instead of nullptr, pass the Il2CppType* or Il2CppClass* of the argument instead!");
         return typ;
     }
References getLogger().
Referenced by ExtractTypes(), RunMethod(), and SetFieldValue().
ExtractTypes() [1/2]
auto il2cpp_utils::ExtractTypes () inline
Definition at line 129 of file il2cpp-utils-classes.hpp.
{
         return ::std::vector<const Il2CppType*>();
     }
Referenced by ExtractTypes(), RunGenericMethod(), and RunMethod().
ExtractTypes() [2/2]
template<typename T , typename... TArgs> ::std::vector<const Il2CppType*> il2cpp_utils::ExtractTypes (T && arg, TArgs &&... args)
Definition at line 134 of file il2cpp-utils-classes.hpp.
{
         auto* tFirst = ExtractType(arg);
         auto tOthers = ExtractTypes(args...);
         if (tFirst) tOthers.insert(tOthers.begin(), tFirst);
         return tOthers;
     }
References args, ExtractType(), and ExtractTypes().
ExtractValue()
template<class T > void* il2cpp_utils::ExtractValue (T && arg)
Definition at line 114 of file il2cpp-utils-methods.hpp.
{
         il2cpp_functions::Init();
         using Dt = ::std::decay_t<T>;
         if constexpr (::std::is_same_v<Dt, Il2CppType*> || ::std::is_same_v<Dt, Il2CppClass*>) {
             return nullptr;
         } else if constexpr (::std::is_pointer_v<Dt>) {
             if constexpr (::std::is_base_of_v<Il2CppObject, ::std::remove_pointer_t<Dt>>) {
                 if (arg) {
                     auto* klass = il2cpp_functions::object_get_class(arg);
                     if (klass && klass->valuetype) {
                         // Arg is an Il2CppObject* of a value type. It needs to be unboxed.
                         return il2cpp_functions::object_unbox(arg);
                     }
                 }
             }
             return arg;
         } else {
             return const_cast<Dt*>(&arg);
         }
     }
References il2cpp_functions::Init(), il2cpp_functions::object_get_class, and il2cpp_functions::object_unbox.
Referenced by ExtractValues(), RunMethod(), and SetFieldValue().
ExtractValues() [1/2]
auto il2cpp_utils::ExtractValues () inline
Definition at line 136 of file il2cpp-utils-methods.hpp.
{
         return ::std::vector<void*>();
     }
Referenced by ExtractValues(), and RunMethod().
ExtractValues() [2/2]
template<class T , class... TArgs> ::std::vector<void*> il2cpp_utils::ExtractValues (T && arg, TArgs &&... args)
Definition at line 141 of file il2cpp-utils-methods.hpp.
{
         auto* firstVal = ExtractValue(arg);
         auto otherVals = ExtractValues(args...);
         otherVals.insert(otherVals.begin(), firstVal);  // inserts at front
         return otherVals;
     }
References args, ExtractValue(), and ExtractValues().
FindField() [1/4]
template<class... TArgs> FieldInfo* il2cpp_utils::FindField (::std::string_view nameSpace, ::std::string_view className, TArgs &&... params)
Definition at line 33 of file il2cpp-utils-fields.hpp.
{
         return FindField(GetClassFromName(nameSpace, className), params...);
     }
References FindField(), and GetClassFromName().
FindField() [2/4]
FieldInfo* il2cpp_utils::FindField (Il2CppClass * klass, ::std::string_view fieldName)
FindField() [3/4]
FieldInfo* il2cpp_utils::FindField (Il2CppClass * klass, std::string_view fieldName)
Definition at line 11 of file il2cpp-utils-fields.cpp.
{
         static auto logger = getLogger().WithContext("FindField");
         il2cpp_functions::Init();
         RET_0_UNLESS(logger, klass);
         // Check Cache
         auto key = std::pair<Il2CppClass*, std::string>(klass, fieldName);
         nameFieldLock.lock();
         auto itr = classesNamesToFieldsCache.find(key);
         if (itr != classesNamesToFieldsCache.end()) {
             nameFieldLock.unlock();
             return itr->second;
         }
         nameFieldLock.unlock();
         auto field = il2cpp_functions::class_get_field_from_name(klass, fieldName.data());
         if (!field) {
             logger.error("could not find field %s in class '%s'!", fieldName.data(), ClassStandardName(klass).c_str());
             LogFields(logger, klass);
             if (klass->parent != klass) field = FindField(klass->parent, fieldName);
         }
         nameFieldLock.lock();
         classesNamesToFieldsCache.emplace(key, field);
         nameFieldLock.unlock();
         return field;
     }
References il2cpp_functions::class_get_field_from_name, classesNamesToFieldsCache, ClassStandardName(), getLogger(), il2cpp_functions::Init(), LogFields(), nameFieldLock, RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by FindField(), GetFieldValue(), and SetFieldValue().
FindField() [4/4]
template<class T , class... TArgs> ::std::enable_if_t<!::std::is_convertible_v<T, ::std::string_view>, FieldInfo*> il2cpp_utils::FindField (T && instance, TArgs &&... params)
Definition at line 44 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         auto* klass = RET_0_UNLESS(logger, ExtractClass(instance));
         return FindField(klass, params...);
     }
References ExtractClass(), FindField(), getLogger(), il2cpp_functions::Init(), instance, and RET_0_UNLESS.
FindMethod() [1/2]
const MethodInfo * il2cpp_utils::FindMethod (FindMethodInfo & info) noexcept
Definition at line 146 of file il2cpp-utils-methods.cpp.
     {
         static auto logger = getLogger().WithContext("FindMethod");
         il2cpp_functions::Init();
         auto* klass = info.klass;
         RET_DEFAULT_UNLESS(logger, klass);
         // TODO: make cache work for generics (stratify by generics count?) and differing return types?
         // Check Cache
         auto innerPair = classesNamesTypesInnerPairType(info.name, info.argTypes);
         auto key = std::pair<Il2CppClass*, classesNamesTypesInnerPairType>(klass, innerPair);
         classTypesMethodsLock.lock();
         auto itr = classesNamesTypesToMethodsCache.find(key);
         if (itr != classesNamesTypesToMethodsCache.end()) {
             classTypesMethodsLock.unlock();
             return itr->second;
         }
         classTypesMethodsLock.unlock();
         void* myIter = nullptr;
         const MethodInfo* methodInfo = nullptr;  // basic match
         bool multipleBasicMatches = false;
         const MethodInfo* returnMatch = nullptr;
         bool multipleReturnMatches = false;
         const MethodInfo* perfectMatch = nullptr;
         bool multiplePerfectMatches = false;
         // Does NOT automatically recurse through klass's parents
         while (const MethodInfo* current = il2cpp_functions::class_get_methods(info.klass, &myIter)) {
             if ((info.name == current->name) && ParameterMatch(current, info.genTypes, info.argTypes)) {
                 if (info.returnType) {
                     auto* returnClass = il2cpp_functions::class_from_il2cpp_type(current->return_type);
                     if (info.returnType == returnClass) {
                         if (perfectMatch) {
                             multiplePerfectMatches = true;
                             logger.error("Multiple perfect matches???");
                         }
                         else perfectMatch = current;
                     }
                     if (il2cpp_functions::class_is_assignable_from(info.returnType, returnClass)) {
                         if (returnMatch) {
                             logger.debug("Multiple return type matches.");
                             multipleReturnMatches = true;
                         }
                         else returnMatch = current;
                     }
                 }
                 if (methodInfo)
                     multipleBasicMatches = true;
                 else
                     methodInfo = current;
             }
         }
         if (!methodInfo && klass->parent && klass->parent != klass) {
             info.klass = klass->parent;
             methodInfo = FindMethod(info);
             info.klass = klass;
         }
         if (!multiplePerfectMatches && perfectMatch) {
             // It's important that these kinds of matches aren't added to the general cache
             return perfectMatch;
         } else if (!multipleReturnMatches && returnMatch) {
             return returnMatch;
         } else if (!methodInfo || multipleBasicMatches) {
             std::stringstream ss;
             ss << ((multipleBasicMatches) ? "found multiple matches for" : "could not find");
             ss << " method " << info.name << "(";
             bool first = true;
             for (auto t : info.argTypes) {
                 if (!first) ss << ", ";
                 first = false;
                 ss << TypeGetSimpleName(t);
             }
             ss << ") in class '" << ClassStandardName(klass) << "'!";
             logger.error("%s", ss.str().c_str());
             LogMethods(logger, klass);
             RET_DEFAULT_UNLESS(logger, !methodInfo || multipleBasicMatches);
         }
         classTypesMethodsLock.lock();
         classesNamesTypesToMethodsCache.emplace(key, methodInfo);
         classTypesMethodsLock.unlock();
         return methodInfo;
     }
References il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::class_get_methods, il2cpp_functions::class_is_assignable_from, classesNamesTypesToMethodsCache, ClassStandardName(), classTypesMethodsLock, getLogger(), info, il2cpp_functions::Init(), LogMethods(), ParameterMatch(), RET_DEFAULT_UNLESS, TypeGetSimpleName(), and LoggerContextObject::WithContext().
Referenced by FindMethod(), RunGenericMethod(), and RunMethod().
FindMethod() [2/2]
template<typename... TArgs, ::std::enable_if_t<(... &&!::std::is_convertible_v< TArgs, FindMethodInfo >), int > = 0> const MethodInfo* il2cpp_utils::FindMethod (TArgs &&... args) noexcept
Definition at line 263 of file il2cpp-utils-methods.hpp.
{
         auto info = FindMethodInfo(args...);
         return FindMethod(info);
     }
References args, FindMethod(), and info.
FindMethodUnsafe() [1/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (::std::string_view nameSpace, ::std::string_view className, ::std::string_view methodName, int argsCount) noexcept
FindMethodUnsafe() [2/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (const Il2CppClass * klass, ::std::string_view methodName, int argsCount) noexcept
FindMethodUnsafe() [3/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (const Il2CppClass * klass, std::string_view methodName, int argsCount) noexcept
Definition at line 92 of file il2cpp-utils-methods.cpp.
     {
         il2cpp_functions::Init();
         static auto logger = getLogger().WithContext("FindMethodUnsafe");
         RET_DEFAULT_UNLESS(logger, klass);
         // Check Cache
         auto innerPair = std::pair<std::string, decltype(MethodInfo::parameters_count)>(methodName, argsCount);
         auto key = std::pair<const Il2CppClass*, decltype(innerPair)>(klass, innerPair);
         classNamesMethodsLock.lock();
         auto itr = classesNamesToMethodsCache.find(key);
         if (itr != classesNamesToMethodsCache.end()) {
             classNamesMethodsLock.unlock();
             return itr->second;
         }
         classNamesMethodsLock.unlock();
         // Recurses through klass's parents
         auto methodInfo = il2cpp_functions::class_get_method_from_name(klass, methodName.data(), argsCount);
         if (!methodInfo) {
             logger.error("could not find method %s with %i parameters in class '%s'!", methodName.data(), argsCount, ClassStandardName(klass).c_str());
             LogMethods(logger, const_cast<Il2CppClass*>(klass), true);
             RET_DEFAULT_UNLESS(logger, methodInfo);
         }
         classNamesMethodsLock.lock();
         classesNamesToMethodsCache.emplace(key, methodInfo);
         classNamesMethodsLock.unlock();
         return methodInfo;
     }
References il2cpp_functions::class_get_method_from_name, classesNamesToMethodsCache, classNamesMethodsLock, ClassStandardName(), getLogger(), il2cpp_functions::Init(), LogMethods(), RET_DEFAULT_UNLESS, and LoggerContextObject::WithContext().
Referenced by Array< T >::Contains(), Array< T >::CopyTo(), createManual(), FindMethodUnsafe(), Array< T >::GetEnumerator(), Array< T >::IndexOf(), MakeDelegate(), MakeGenericType(), RunMethod(), and RunMethodUnsafe().
FindMethodUnsafe() [4/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (Il2CppObject * instance, ::std::string_view methodName, int argsCount) noexcept
FindMethodUnsafe() [5/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (Il2CppObject * instance, std::string_view methodName, int argsCount) noexcept
Definition at line 134 of file il2cpp-utils-methods.cpp.
     {
         static auto logger = getLogger().WithContext("FindMethodUnsafe");
         il2cpp_functions::Init();
         auto klass = RET_DEFAULT_UNLESS(logger, il2cpp_functions::object_get_class(instance));
         return FindMethodUnsafe(klass, methodName, argsCount);
     }
References FindMethodUnsafe(), getLogger(), il2cpp_functions::Init(), instance, il2cpp_functions::object_get_class, RET_DEFAULT_UNLESS, and LoggerContextObject::WithContext().
FindMethodUnsafe() [6/6]
const MethodInfo* il2cpp_utils::FindMethodUnsafe (std::string_view nameSpace, std::string_view className, std::string_view methodName, int argsCount) noexcept
Definition at line 125 of file il2cpp-utils-methods.cpp.
     {
         return FindMethodUnsafe(GetClassFromName(nameSpace, className), methodName, argsCount);
     }
References FindMethodUnsafe(), and GetClassFromName().
FindProperty() [1/5]
const PropertyInfo* il2cpp_utils::FindProperty (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propertyName)
FindProperty() [2/5]
const PropertyInfo* il2cpp_utils::FindProperty (Il2CppClass * klass, ::std::string_view propertyName)
FindProperty() [3/5]
const PropertyInfo* il2cpp_utils::FindProperty (Il2CppClass * klass, std::string_view propName)
Definition at line 11 of file il2cpp-utils-properties.cpp.
{
         static auto logger = getLogger().WithContext("FindProperty");
         il2cpp_functions::Init();
         RET_0_UNLESS(logger, klass);
         // Check Cache
         auto key = std::pair<Il2CppClass*, std::string>(klass, propName);
         classPropertiesLock.lock();
         auto itr = classesNamesToPropertiesCache.find(key);
         if (itr != classesNamesToPropertiesCache.end()) {
             classPropertiesLock.unlock();
             return itr->second;
         }
         classPropertiesLock.unlock();
         auto prop = il2cpp_functions::class_get_property_from_name(klass, propName.data());
         if (!prop) {
             logger.error("could not find property %s in class '%s'!", propName.data(), ClassStandardName(klass).c_str());
             LogProperties(logger, klass);
             if (klass->parent != klass) prop = FindProperty(klass->parent, propName);
         }
         classPropertiesLock.lock();
         classesNamesToPropertiesCache.emplace(key, prop);
         classPropertiesLock.unlock();
         return prop;
     }
References il2cpp_functions::class_get_property_from_name, classesNamesToPropertiesCache, classPropertiesLock, ClassStandardName(), getLogger(), il2cpp_functions::Init(), LogProperties(), RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by FindProperty(), GetPropertyValue(), and SetPropertyValue().
FindProperty() [4/5]
const PropertyInfo* il2cpp_utils::FindProperty (std::string_view nameSpace, std::string_view className, std::string_view propertyName)
Definition at line 37 of file il2cpp-utils-properties.cpp.
{
         return FindProperty(GetClassFromName(nameSpace, className), propertyName);
     }
References FindProperty(), and GetClassFromName().
FindProperty() [5/5]
template<class T > const PropertyInfo* il2cpp_utils::FindProperty (T && instance, ::std::string_view propertyName)
Definition at line 26 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, ExtractClass(instance));
         return FindProperty(klass, propertyName);
     }
References ExtractClass(), FindProperty(), getLogger(), instance, and RET_0_UNLESS.
FromIl2CppObject() [1/2]
template<class TOut > ::std::optional<TOut> il2cpp_utils::FromIl2CppObject (Il2CppObject * obj)
Definition at line 14 of file il2cpp-utils-classes.hpp.
{
         il2cpp_functions::Init();
         // using Dt = ::std::decay_t<TOut>;
         void* val = obj;
         // nullptr (which runtime_invoke returns for "void" return type!) is different from nullopt (a runtime_invoke error!)
         if (obj && il2cpp_functions::class_is_valuetype(il2cpp_functions::object_get_class(obj))) {
             static auto& logger = getLogger();
             val = RET_NULLOPT_UNLESS(logger, il2cpp_functions::object_unbox(obj));
         }
         if constexpr (::std::is_pointer_v<TOut>) {
             return static_cast<TOut>(val);
         } else {
             return *static_cast<TOut*>(val);
         }
     }
References il2cpp_functions::class_is_valuetype, getLogger(), il2cpp_functions::Init(), il2cpp_functions::object_get_class, il2cpp_functions::object_unbox, and RET_NULLOPT_UNLESS.
Referenced by SetFieldValue().
FromIl2CppObject() [2/2]
template<class T > bool il2cpp_utils::FromIl2CppObject (Il2CppObject * obj, T & out)
Definition at line 32 of file il2cpp-utils-classes.hpp.
{
         using Dt = ::std::decay_t<T>;
         if (auto ret = FromIl2CppObject<Dt>(obj)) {
             if constexpr (::std::is_pointer_v<Dt>) {
                 // if they asked for the output in a pointer, we shouldn't change the pointer itself
                 *out = *(*ret);
             } else {
                 out = *ret;
             }
             return true;
         }
         return false;
     }
GenericClassStandardName()
std::string il2cpp_utils::GenericClassStandardName (Il2CppGenericClass * genClass)
Definition at line 16 of file il2cpp-utils-classes.cpp.
{
         if (genClass->cached_class) {
             return ClassStandardName(genClass->cached_class);
         }
         if (genClass->typeDefinitionIndex != kTypeDefinitionIndexInvalid) {
             il2cpp_functions::Init();
             auto* klass = il2cpp_functions::GenericClass_GetClass(genClass);
             return ClassStandardName(klass);
         }
         return "?";
     }
References ClassStandardName(), il2cpp_functions::GenericClass_GetClass, and il2cpp_functions::Init().
Referenced by BuildGenericsMap().
GenericsToStringHelper()
void il2cpp_utils::GenericsToStringHelper (Il2CppGenericClass * genClass, std::ostream & os)
Definition at line 179 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("GenericsToStringHelper");
         auto genContext = &genClass->context;
         auto* genInst = genContext->class_inst;
         if (!genInst) {
             genInst = genContext->method_inst;
             if (genInst) logger.warning("Missing class_inst! Trying method_inst?");
         }
         if (genInst) {
             os << "<";
             for (size_t i = 0; i < genInst->type_argc; i++) {
                 auto typ = genInst->type_argv[i];
                 if (i > 0) os << ", ";
                 const char* typName = TypeGetSimpleName(typ);
                 os << typName;
             }
             os << ">";
         } else {
             logger.warning("context->class_inst missing for genClass!");
         }
     }
References LoggerContextObject::context, getLogger(), TypeGetSimpleName(), and LoggerContextObject::WithContext().
Referenced by ClassStandardName().
GetClassFromName()
Il2CppClass * il2cpp_utils::GetClassFromName (std::string_view name_space, std::string_view type_name)
Definition at line 16 of file il2cpp-type-check.cpp.
{
         il2cpp_functions::Init();
         static auto logger = getLogger().WithContext("GetClassFromName");
         // TODO: avoid creating std::string at any point except new pair insertion via P0919
         // Check cache
         auto key = std::pair<std::string, std::string>(name_space, type_name);
         nameHashLock.lock();
         auto itr = namesToClassesCache.find(key);
         if (itr != namesToClassesCache.end()) {
             nameHashLock.unlock();
             return itr->second;
         }
         nameHashLock.unlock();
         auto dom = RET_0_UNLESS(logger, il2cpp_functions::domain_get());
         size_t assemb_count;
         const Il2CppAssembly** allAssemb = il2cpp_functions::domain_get_assemblies(dom, &assemb_count);
         for (size_t i = 0; i < assemb_count; i++) {
             auto assemb = allAssemb[i];
             auto img = il2cpp_functions::assembly_get_image(assemb);
             if (!img) {
                 logger.error("Assembly with name: %s has a null image!", assemb->aname.name);
                 continue;
             }
             auto klass = il2cpp_functions::class_from_name(img, name_space.data(), type_name.data());
             if (klass) {
                 nameHashLock.lock();
                 namesToClassesCache.emplace(key, klass);
                 nameHashLock.unlock();
                 return klass;
             }
         }
         logger.error("Could not find class with namepace: %s and name: %s",
             name_space.data(), type_name.data());
         return nullptr;
     }
References il2cpp_functions::assembly_get_image, il2cpp_functions::class_from_name, il2cpp_functions::domain_get, il2cpp_functions::domain_get_assemblies, getLogger(), il2cpp_functions::Init(), nameHashLock, namesToClassesCache, RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by __AllocateUnsafe(), ClassesFrom(), FindField(), FindMethodUnsafe(), FindProperty(), GetFieldValue(), GetPropertyValue(), GetSystemType(), MakeAction(), MakeDelegate(), MakeFunc(), New(), NewUnsafe(), RunGenericMethod(), RunMethod(), RunMethodUnsafe(), SetFieldValue(), SetPropertyValue(), and TypesFrom().
GetFieldClass()
Il2CppClass * il2cpp_utils::GetFieldClass (FieldInfo * field)
Definition at line 37 of file il2cpp-utils-fields.cpp.
{
         static auto logger = getLogger().WithContext("GetFieldClass");
         auto type = RET_0_UNLESS(logger, il2cpp_functions::field_get_type(field));
         return il2cpp_functions::class_from_il2cpp_type(type);
     }
References il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::field_get_type, getLogger(), RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by CreateFieldValue(), and CreateFieldValueUnsafe().
GetFieldValue() [1/3]
template<typename TOut = Il2CppObject*> ::std::optional<TOut> il2cpp_utils::GetFieldValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view fieldName)
Definition at line 88 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_NULLOPT_UNLESS(logger, GetClassFromName(nameSpace, className));
         return GetFieldValue<TOut>(klass, fieldName);
     }
References GetClassFromName(), getLogger(), and RET_NULLOPT_UNLESS.
GetFieldValue() [2/3]
template<typename TOut = Il2CppObject*> ::std::optional<TOut> il2cpp_utils::GetFieldValue (Il2CppObject * instance, FieldInfo * field)
Definition at line 55 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         RET_NULLOPT_UNLESS(logger, field);
         // Check that the TOut requested by the user matches the field.
         auto* outType = ExtractIndependentType<TOut>();
         if (outType && !IsConvertible(outType, field->type, false)) {
             Logger::get().warning("User requested TOut %s does not match the field's type, %s!",
                 TypeGetSimpleName(outType), TypeGetSimpleName(field->type));
         }
         TOut out;
         if (instance) {
             il2cpp_functions::field_get_value(instance, field, &out);
         } else { // Fallback to perform a static field set
             il2cpp_functions::field_static_get_value(field, &out);
         }
         return out;
     }
References il2cpp_functions::field_get_value, il2cpp_functions::field_static_get_value, Logger::get(), getLogger(), il2cpp_functions::Init(), instance, IsConvertible(), RET_NULLOPT_UNLESS, TypeGetSimpleName(), and Logger::warning().
GetFieldValue() [3/3]
template<typename TOut = Il2CppObject*, typename T > ::std::optional<TOut> il2cpp_utils::GetFieldValue (T && classOrInstance, ::std::string_view fieldName)
Definition at line 79 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* field = RET_NULLOPT_UNLESS(logger, FindField(classOrInstance, fieldName));
         Il2CppObject* obj = ToIl2CppObject(classOrInstance);  // null is allowed (for T = Il2CppType* or Il2CppClass*)
         return GetFieldValue<TOut>(obj, field);
     }
References FindField(), getLogger(), RET_NULLOPT_UNLESS, and ToIl2CppObject().
getLogger()
LoggerContextObject & il2cpp_utils::getLogger ()
Definition at line 7 of file il2cpp-type-check.cpp.
{
         static auto logger = Logger::get().WithContext("il2cpp_utils");
         return logger;
     }
References Logger::get(), and Logger::WithContext().
Referenced by AssertMatch(), AssignableFrom(), BuildGenericsMap(), createcsstr(), CreateFieldValue(), CreateFieldValueUnsafe(), createManual(), CreateParam(), CreateParamUnsafe(), ExtractClass(), ExtractIndependentType(), ExtractType(), FindField(), FindMethod(), FindMethodUnsafe(), FindProperty(), FromIl2CppObject(), GenericsToStringHelper(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T *, typename std::enable_if_t< has_get< il2cpp_no_arg_class< T > > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< Il2CppType * >::get(), GetClassFromName(), GetFieldClass(), GetFieldValue(), GetParamClass(), GetPropertyValue(), GetSystemType(), IsConvertible(), MakeAction(), MakeDelegate(), MakeFunc(), MakeGeneric(), MakeGenericMethod(), MakeGenericType(), New(), newcsstr(), NewUnsafe(), NoArgClass(), ParameterMatch(), RunGenericMethod(), RunMethod(), RunMethodUnsafe(), SetFieldValue(), SetPropertyValue(), ToIl2CppObject(), and vectorToArray().
GetParamClass()
Il2CppClass * il2cpp_utils::GetParamClass (const MethodInfo * method, int paramIdx)
Definition at line 138 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("GetParamClass");
         auto type = RET_0_UNLESS(logger, il2cpp_functions::method_get_param(method, paramIdx));
         return il2cpp_functions::class_from_il2cpp_type(type);
     }
References il2cpp_functions::class_from_il2cpp_type, getLogger(), il2cpp_functions::method_get_param, RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by CreateParam(), and CreateParamUnsafe().
GetPropertyValue() [1/3]
template<typename TOut = Il2CppObject*, bool checkTypes = true> ::std::optional<TOut> il2cpp_utils::GetPropertyValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propName)
Definition at line 54 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetClassFromName(nameSpace, className));
         return GetPropertyValue<TOut, checkTypes>(klass, propName);
     }
References GetClassFromName(), getLogger(), and RET_0_UNLESS.
GetPropertyValue() [2/3]
template<typename TOut = Il2CppObject*, bool checkTypes = true, typename T > ::std::optional<TOut> il2cpp_utils::GetPropertyValue (T && classOrInstance, ::std::string_view propName)
Definition at line 46 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         auto* prop = RET_NULLOPT_UNLESS(logger, FindProperty(classOrInstance, propName));
         return GetPropertyValue<TOut, checkTypes>(classOrInstance, prop);
     }
References FindProperty(), getLogger(), and RET_NULLOPT_UNLESS.
GetPropertyValue() [3/3]
template<class TOut = Il2CppObject*, bool checkTypes = true, class T > ::std::optional<TOut> il2cpp_utils::GetPropertyValue (T && classOrInstance, const PropertyInfo * prop)
Definition at line 35 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         RET_NULLOPT_UNLESS(logger, prop);
         auto* getter = RET_NULLOPT_UNLESS(logger, il2cpp_functions::property_get_get_method(prop));
         return RunMethod<TOut, checkTypes>(classOrInstance, getter);
     }
References getLogger(), il2cpp_functions::Init(), il2cpp_functions::property_get_get_method, and RET_NULLOPT_UNLESS.
Referenced by newcsstr().
GetSystemType() [1/4]
Il2CppReflectionType* il2cpp_utils::GetSystemType (::std::string_view nameSpace, ::std::string_view className)
GetSystemType() [2/4]
Il2CppReflectionType * il2cpp_utils::GetSystemType (const Il2CppClass * klass)
Definition at line 166 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("GetSystemType");
         il2cpp_functions::Init();
         RET_0_UNLESS(logger, klass);
         auto* typ = il2cpp_functions::class_get_type_const(klass);
         return GetSystemType(typ);
     }
References il2cpp_functions::class_get_type_const, getLogger(), GetSystemType(), il2cpp_functions::Init(), RET_0_UNLESS, and LoggerContextObject::WithContext().
GetSystemType() [3/4]
Il2CppReflectionType * il2cpp_utils::GetSystemType (const Il2CppType * typ)
Definition at line 161 of file il2cpp-utils.cpp.
{
         il2cpp_functions::Init();
         return reinterpret_cast<Il2CppReflectionType*>(il2cpp_functions::type_get_object(typ));
     }
References il2cpp_functions::Init(), and il2cpp_functions::type_get_object.
Referenced by GetSystemType(), MakeGeneric(), and MakeGenericMethod().
GetSystemType() [4/4]
Il2CppReflectionType* il2cpp_utils::GetSystemType (std::string_view nameSpace, std::string_view className)
Definition at line 175 of file il2cpp-utils.cpp.
{
         return GetSystemType(il2cpp_utils::GetClassFromName(nameSpace, className));
     }
References GetClassFromName(), and GetSystemType().
IsConvertible()
bool il2cpp_utils::IsConvertible (const Il2CppType * to, const Il2CppType * from, bool asArgs)
Definition at line 291 of file il2cpp-utils-methods.cpp.
{
         static auto logger = getLogger().WithContext("IsConvertible");
         RET_0_UNLESS(logger, to);
         RET_0_UNLESS(logger, from);
         if (asArgs) {
             if (to->byref) {
                 if (!from->byref) {
                     logger.debug("to (%s, %p) is ref/out while from (%s, %p) is not. Not convertible.",
                         TypeGetSimpleName(to), to, TypeGetSimpleName(from), from);
                     return false;
                 }
             }
         }
         il2cpp_functions::Init();
         auto classTo = il2cpp_functions::class_from_il2cpp_type(to);
         auto classFrom = il2cpp_functions::class_from_il2cpp_type(from);
         bool ret = (to->type == IL2CPP_TYPE_MVAR) || il2cpp_functions::class_is_assignable_from(classTo, classFrom);
         if (!ret) {
             if (il2cpp_functions::class_is_enum(classTo)) {
                 ret = IsConvertible(il2cpp_functions::class_enum_basetype(classTo), from, asArgs);
             }
         }
         return ret;
     }
References il2cpp_functions::class_enum_basetype, il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::class_is_assignable_from, il2cpp_functions::class_is_enum, getLogger(), il2cpp_functions::Init(), RET_0_UNLESS, TypeGetSimpleName(), and LoggerContextObject::WithContext().
Referenced by GetFieldValue(), ParameterMatch(), RunMethod(), and SetFieldValue().
IsInterface()
bool il2cpp_utils::IsInterface (const Il2CppClass * klass)
Definition at line 112 of file il2cpp-utils.cpp.
{
         return (klass->flags & TYPE_ATTRIBUTE_INTERFACE) ||
             (klass->byval_arg.type == IL2CPP_TYPE_VAR) ||
             (klass->byval_arg.type == IL2CPP_TYPE_MVAR);
     }
LogClass()
void il2cpp_utils::LogClass (LoggerContextObject & logger, Il2CppClass * klass, bool logParents) noexcept
Definition at line 28 of file il2cpp-utils-classes.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, klass);
         if (loggedClasses.count(klass)) {
             logger.debug("Already logged %p!", klass);
             return;
         }
         loggedClasses.insert(klass);
         RET_V_UNLESS(logger, klass->klass == klass);  // otherwise, klass is likely NOT an Il2CppClass*!
         RET_V_UNLESS(logger, klass->name);  // ditto
         indent++;
         // Note: il2cpp stops at GenericMetadata::MaximumRuntimeGenericDepth (which is 8)
         maxIndent = std::max(indent, maxIndent);
         bool methodInit = false;
         if (klass->name) {
             // Note: unless vm/Class.cpp is wrong, Class::Init always returns true
             il2cpp_functions::Class_Init(klass);
             if (klass->initialized_and_no_error) {
                 methodInit = true;
             }
         }
         logger.debug("%i ======================CLASS INFO FOR CLASS: %s======================", indent, ClassStandardName(klass).c_str());
         void* myIter = nullptr;
         if (!methodInit) {
             // log results of Class::Init
             logger.warning("klass->initialized: %i, init_pending: %i, has_initialization_error: %i, initializationExceptionGCHandle: %Xll",
                     klass->initialized, klass->init_pending, klass->has_initialization_error, klass->initializationExceptionGCHandle);
             auto* m1 = il2cpp_functions::class_get_methods(klass, &myIter);  // attempt again to initialize the method data
             if (klass->method_count && !klass->methods) {
                 logger.error("Class::Init and class_get_methods failed to initialize klass->methods! class_get_methods returned: %p",
                     m1);
                 if (m1) LogMethod(logger, m1);
             }
         }
         logger.debug("Pointer: %p", klass);
         logger.debug("Type Token: %i", il2cpp_functions::class_get_type_token(klass));
         auto typeDefIdx = klass->generic_class ? klass->generic_class->typeDefinitionIndex : il2cpp_functions::MetadataCache_GetIndexForTypeDefinition(klass);
         logger.debug("TypeDefinitionIndex: %i", typeDefIdx);
         // Repair the typeDefinition value if it was null but we found one
         if (!klass->typeDefinition && typeDefIdx > 0) klass->typeDefinition = il2cpp_functions::MetadataCache_GetTypeDefinitionFromIndex(typeDefIdx);
         logger.debug("Type definition: %p", klass->typeDefinition);
         logger.debug("Assembly Name: %s", il2cpp_functions::class_get_assemblyname(klass));
         auto* typ = il2cpp_functions::class_get_type(klass);
         if (typ) {
             logger.debug("Type name: %s", il2cpp_functions::type_get_name(typ));
             if (auto* reflName = il2cpp_functions::Type_GetName(typ, IL2CPP_TYPE_NAME_FORMAT_REFLECTION)) {
                 logger.debug("Type reflection name: %s", reflName);
                 il2cpp_functions::free(reflName);
             }
             logger.debug("Fully qualifed type name: %s", il2cpp_functions::type_get_assembly_qualified_name(typ));
         }
         logger.debug("Rank: %i", il2cpp_functions::class_get_rank(klass));
         logger.debug("Flags: 0x%.8X", il2cpp_functions::class_get_flags(klass));
         logger.debug("Event Count: %i", klass->event_count);
         logger.debug("Method Count: %i", klass->method_count);
         logger.debug("Is Generic: %i", il2cpp_functions::class_is_generic(klass));
         logger.debug("Is Abstract: %i", il2cpp_functions::class_is_abstract(klass));
         // Some methods, such as GenericClass::GetClass, may not initialize all fields in Il2CppClass, and thus not meet all implicit contracts defined by the comments in Il2CppClass's struct definition.
         // But unless we're blind, the only method that sets is_generic on non-methods is MetadataCache::FromTypeDefinition. That method also contains the only assignment of genericContainerIndex.
         // Therefore, this code makes only the following assumptions:
         // 1. If is_generic is set, then genericContainerIndex was also intentionally set (even if it's 0) and is not -1 (invalid)
         // 2. Even if is_generic wasn't set, a positive genericContainerIndex was intentionally set that way and is a valid index.
         if (klass->is_generic || klass->genericContainerIndex > 0) {
             auto* genContainer = il2cpp_functions::MetadataCache_GetGenericContainerFromIndex(klass->genericContainerIndex);
             logger.debug("genContainer: idx %i, ownerIndex: %i, is_method: %i", klass->genericContainerIndex, genContainer->ownerIndex, genContainer->is_method);
             if (genContainer->ownerIndex != typeDefIdx) {
                 logger.error("genContainer ownerIndex mismatch!");
             }
             for (int i = 0; i < genContainer->type_argc; i++) {
                 auto genParamIdx = genContainer->genericParameterStart + i;
                 auto* genParam = il2cpp_functions::MetadataCache_GetGenericParameterFromIndex(genParamIdx);
                 if (genParam) {
                     logger.debug("genParam #%i, idx %i: ownerIdx %i, name %s, num %i, flags (see "
                         "IL2CPP_GENERIC_PARAMETER_ATTRIBUTE_X in il2cpp-tabledefs.h) 0x%.2X", i, genParamIdx, genParam->ownerIndex,
                         il2cpp_functions::MetadataCache_GetStringFromIndex(genParam->nameIndex), genParam->num, genParam->flags);
                 } else {
                     logger.warning("genParam %i, idx %i: null", i, genParamIdx);
                 }
             }
         } else {
             logger.debug("genericContainerIndex: %i", klass->genericContainerIndex);
         }
         logger.debug("%i =========METHODS=========", indent);
         LogMethods(logger, klass);
         logger.debug("%i =======END METHODS=======", indent);
         auto* declaring = il2cpp_functions::class_get_declaring_type(klass);
         logger.debug("declaring type: %p (%s)", declaring, declaring ? ClassStandardName(declaring).c_str() : "");
         if (declaring && logParents) LogClass(logger, declaring, logParents);
         auto* element = il2cpp_functions::class_get_element_class(klass);
         logger.debug("element class: %p ('%s', self = %p)", element, element ? ClassStandardName(element).c_str() : "", klass);
         if (element && element != klass && logParents) LogClass(logger, element, logParents);
         logger.debug("%i =======PROPERTIES=======", indent);
         LogProperties(logger, klass);
         logger.debug("%i =====END PROPERTIES=====", indent);
         logger.debug("%i =========FIELDS=========", indent);
         LogFields(logger, klass);
         logger.debug("%i =======END FIELDS=======", indent);
         auto* parent = il2cpp_functions::class_get_parent(klass);
         logger.debug("parent: %p (%s)", parent, parent ? ClassStandardName(parent).c_str() : "");
         if (parent && logParents) LogClass(logger, parent, logParents);
         logger.debug("%i, ==================================================================================", indent);
         indent--;
     }
References il2cpp_functions::class_get_assemblyname, il2cpp_functions::class_get_declaring_type, il2cpp_functions::class_get_element_class, il2cpp_functions::class_get_flags, il2cpp_functions::class_get_methods, il2cpp_functions::class_get_parent, il2cpp_functions::class_get_rank, il2cpp_functions::class_get_type, il2cpp_functions::class_get_type_token, il2cpp_functions::Class_Init, il2cpp_functions::class_is_abstract, il2cpp_functions::class_is_generic, ClassStandardName(), il2cpp_functions::free, indent, il2cpp_functions::Init(), LogFields(), loggedClasses, LogMethod(), LogMethods(), LogProperties(), maxIndent, il2cpp_functions::MetadataCache_GetGenericContainerFromIndex(), il2cpp_functions::MetadataCache_GetGenericParameterFromIndex(), il2cpp_functions::MetadataCache_GetIndexForTypeDefinition(), il2cpp_functions::MetadataCache_GetStringFromIndex(), il2cpp_functions::MetadataCache_GetTypeDefinitionFromIndex(), RET_V_UNLESS, il2cpp_functions::type_get_assembly_qualified_name, il2cpp_functions::type_get_name, and il2cpp_functions::Type_GetName().
Referenced by LogClasses().
LogClasses() [1/2]
void il2cpp_utils::LogClasses (LoggerContextObject & logger, ::std::string_view classPrefix, bool logParents = false) noexcept
LogClasses() [2/2]
void il2cpp_utils::LogClasses (LoggerContextObject & logger, std::string_view classPrefix, bool logParents) noexcept
Definition at line 169 of file il2cpp-utils-classes.cpp.
{
         il2cpp_functions::Init();
         BuildGenericsMap();
         // Begin prefix matching
         std::map<std::string, Il2CppClass*, doj::alphanum_less<std::string>> matches;
         // Get il2cpp domain
         auto* dom = il2cpp_functions::domain_get();
         // Get all il2cpp assemblies
         size_t size;
         auto** assembs = il2cpp_functions::domain_get_assemblies(dom, &size);
         for (size_t i = 0; i < size; ++i) {
             // Get image for each assembly
             if (!assembs[i]) {
                 logger.warning("Assembly %zu was null! Skipping.", i);
                 continue;
             }
             logger.debug("Scanning assembly \"%s\"", assembs[i]->aname.name);
             auto* img = il2cpp_functions::assembly_get_image(assembs[i]);
             if (!img) {
                 logger.warning("Assembly's image was null! Skipping.");
                 continue;
             }
             if (img->nameToClassHashTable == nullptr) {
                 logger.debug("Assembly's nameToClassHashTable is empty. Populating it instead.");
                 img->nameToClassHashTable = new Il2CppNameToTypeDefinitionIndexHashTable();
                 for (uint32_t index = 0; index < img->typeCount; index++) {
                     TypeDefinitionIndex typeIndex = img->typeStart + index;
                     AddTypeToNametoClassHashTable(img, typeIndex);
                 }
                 for (uint32_t index = 0; index < img->exportedTypeCount; index++) {
                     auto typeIndex = il2cpp_functions::MetadataCache_GetExportedTypeFromIndex(img->exportedTypeStart + index);
                     if (typeIndex != kTypeIndexInvalid)
                         AddTypeToNametoClassHashTable(img, typeIndex);
                 }
             }
             for (auto itr = img->nameToClassHashTable->begin(); itr != img->nameToClassHashTable->end(); ++itr) {
                 // ->first is a KeyWrapper(pair(namespaceName, className))
                 // ->second is TypeDefinitionIndex
                 if (strncmp(classPrefix.data(), itr->first.key.second, classPrefix.length()) == 0) {
                     // Starts with!
                     // Convert TypeDefinitionIndex --> class
                     auto klazz = il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex(itr->second);
                     matches[ClassStandardName(klazz)] = klazz;
                 }
             }
         }
         usleep(1000);  // 0.001s
         logger.debug("LogClasses:");
         for ( const auto &pair : matches ) {
             LogClass(logger, pair.second, logParents);
             indent = -1;
             for ( const auto &genPair : classToGenericClassMap[pair.second] ) {
                 logger.debug("%s", genPair.first.c_str());
             }
             usleep(1000);  // 0.001s
         }
         logger.debug("LogClasses(\"%s\") is complete.", classPrefix.data());
         logger.debug("maxIndent: %i", maxIndent);
     }
References AddTypeToNametoClassHashTable(), il2cpp_functions::assembly_get_image, BuildGenericsMap(), ClassStandardName(), classToGenericClassMap, il2cpp_functions::domain_get, il2cpp_functions::domain_get_assemblies, indent, il2cpp_functions::Init(), LogClass(), maxIndent, il2cpp_functions::MetadataCache_GetExportedTypeFromIndex(), and il2cpp_functions::MetadataCache_GetTypeInfoFromTypeDefinitionIndex.
LogField()
void il2cpp_utils::LogField (LoggerContextObject & logger, FieldInfo * field)
Definition at line 43 of file il2cpp-utils-fields.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, field);
         auto flags = il2cpp_functions::field_get_flags(field);
         const char* flagStr = (flags & FIELD_ATTRIBUTE_STATIC) ? "static " : "";
         auto* type = il2cpp_functions::field_get_type(field);
         auto typeStr = TypeGetSimpleName(type);
         auto name = il2cpp_functions::field_get_name(field);
         name = name ? name : "__noname__";
         auto offset = il2cpp_functions::field_get_offset(field);
         logger.debug("%s%s %s; // 0x%lx, flags: 0x%.4X", flagStr, typeStr, name, offset, flags);
     }
References LoggerContextObject::debug(), il2cpp_functions::field_get_flags, il2cpp_functions::field_get_name, il2cpp_functions::field_get_offset, il2cpp_functions::field_get_type, il2cpp_functions::Init(), RET_V_UNLESS, and TypeGetSimpleName().
Referenced by LogFields().
LogFields()
void il2cpp_utils::LogFields (LoggerContextObject & logger, Il2CppClass * klass, bool logParents)
Definition at line 58 of file il2cpp-utils-fields.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, klass);
         void* myIter = nullptr;
         FieldInfo* field;
         if (klass->name) il2cpp_functions::Class_Init(klass);
         if (logParents) logger.info("class name: %s", ClassStandardName(klass).c_str());
         logger.debug("field_count: %i", klass->field_count);
         while ((field = il2cpp_functions::class_get_fields(klass, &myIter))) {
             LogField(logger, field);
         }
         usleep(100);
         if (logParents && klass->parent && klass->parent != klass) {
             LogFields(logger, klass->parent, logParents);
         }
     }
References il2cpp_functions::class_get_fields, il2cpp_functions::Class_Init, ClassStandardName(), LoggerContextObject::debug(), LoggerContextObject::info(), il2cpp_functions::Init(), LogField(), and RET_V_UNLESS.
Referenced by FindField(), and LogClass().
LogMethod()
void il2cpp_utils::LogMethod (LoggerContextObject & logger, const MethodInfo * method)
Definition at line 259 of file il2cpp-utils-methods.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, method);
         auto flags = il2cpp_functions::method_get_flags(method, nullptr);
         std::stringstream flagStream;
         if (flags & METHOD_ATTRIBUTE_STATIC) flagStream << "static ";
         if (flags & METHOD_ATTRIBUTE_VIRTUAL) flagStream << "virtual ";
         if (flags & METHOD_ATTRIBUTE_ABSTRACT) flagStream << "abstract ";
         const auto& flagStrRef = flagStream.str();
         const char* flagStr = flagStrRef.c_str();
         auto* retType = il2cpp_functions::method_get_return_type(method);
         auto retTypeStr = TypeGetSimpleName(retType);
         auto methodName = il2cpp_functions::method_get_name(method);
         methodName = methodName ? methodName : "__noname__";
         std::stringstream paramStream;
         for (size_t i = 0; i < il2cpp_functions::method_get_param_count(method); i++) {
             if (i > 0) paramStream << ", ";
             auto* argType = il2cpp_functions::method_get_param(method, i);
             if (il2cpp_functions::type_is_byref(argType)) {
                 paramStream << "out/ref ";
             }
             paramStream << TypeGetSimpleName(argType) << " ";
             auto name = il2cpp_functions::method_get_param_name(method, i);
             paramStream << (name ? name : "__noname__");
         }
         const auto& paramStrRef = paramStream.str();
         const char* paramStr = paramStrRef.c_str();
         // TODO: add <T> after methodName
         logger.debug("%s%s %s(%s);", flagStr, retTypeStr, methodName, paramStr);
     }
References LoggerContextObject::debug(), il2cpp_functions::Init(), il2cpp_functions::method_get_flags, il2cpp_functions::method_get_name, il2cpp_functions::method_get_param, il2cpp_functions::method_get_param_count, il2cpp_functions::method_get_param_name, il2cpp_functions::method_get_return_type, RET_V_UNLESS, il2cpp_functions::type_is_byref, and TypeGetSimpleName().
Referenced by LogClass(), and LogMethods().
LogMethods()
void il2cpp_utils::LogMethods (LoggerContextObject & logger, Il2CppClass * klass, bool logParents)
Definition at line 231 of file il2cpp-utils-methods.cpp.
{
         RET_V_UNLESS(logger, klass);
         if (klass->name) {
             il2cpp_functions::Init();
             il2cpp_functions::Class_Init(klass);
         }
         if (klass->method_count && !(klass->methods)) {
             logger.warning("Class is valid and claims to have methods but ->methods is null! class name: %s", ClassStandardName(klass).c_str());
             return;
         }
         if (logParents) logger.info("class name: %s", ClassStandardName(klass).c_str());
         logger.debug("method_count: %i", klass->method_count);
         for (int i = 0; i < klass->method_count; i++) {
             if (klass->methods[i]) {
                 logger.debug("Method %i:", i);
                 LogMethod(logger, klass->methods[i]);
             } else {
                 logger.warning("Method: %i Does not exist!", i);
             }
         }
         usleep(100);  // 0.0001s
         if (logParents && klass->parent && (klass->parent != klass)) {
             LogMethods(logger, klass->parent, logParents);
         }
     }
References il2cpp_functions::Class_Init, ClassStandardName(), LoggerContextObject::debug(), LoggerContextObject::info(), il2cpp_functions::Init(), LogMethod(), RET_V_UNLESS, and LoggerContextObject::warning().
Referenced by FindMethod(), FindMethodUnsafe(), and LogClass().
LogProperties()
void il2cpp_utils::LogProperties (LoggerContextObject & logger, Il2CppClass * klass, bool logParents)
Definition at line 64 of file il2cpp-utils-properties.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, klass);
         void* myIter = nullptr;
         const PropertyInfo* prop;
         if (klass->name) il2cpp_functions::Class_Init(klass);
         if (logParents) logger.info("class name: %s", ClassStandardName(klass).c_str());
         logger.debug("property_count: %i", klass->property_count);
         while ((prop = il2cpp_functions::class_get_properties(klass, &myIter))) {
             LogProperty(logger, prop);
         }
         usleep(100);
         if (logParents && klass->parent && klass->parent != klass) {
             LogProperties(logger, klass->parent, logParents);
         }
     }
References il2cpp_functions::class_get_properties, il2cpp_functions::Class_Init, ClassStandardName(), LoggerContextObject::debug(), LoggerContextObject::info(), il2cpp_functions::Init(), LogProperty(), and RET_V_UNLESS.
Referenced by FindProperty(), and LogClass().
LogProperty()
void il2cpp_utils::LogProperty (LoggerContextObject & logger, const PropertyInfo * prop)
Definition at line 41 of file il2cpp-utils-properties.cpp.
{
         il2cpp_functions::Init();
         RET_V_UNLESS(logger, prop);
         auto flags = il2cpp_functions::property_get_flags(prop);
         const char* flagStr = (flags & FIELD_ATTRIBUTE_STATIC) ? "static " : "";
         auto name = il2cpp_functions::property_get_name(prop);
         name = name ? name : "__noname__";
         auto* getter = il2cpp_functions::property_get_get_method(prop);
         auto getterName = getter ? il2cpp_functions::method_get_name(getter) : "";
         auto* setter = il2cpp_functions::property_get_set_method(prop);
         auto setterName = setter ? il2cpp_functions::method_get_name(setter) : "";
         const Il2CppType* type = nullptr;
         if (getter) {
             type = il2cpp_functions::method_get_return_type(getter);
         } else if (setter) {
             type = il2cpp_functions::method_get_param(setter, 0);
         }
         auto typeStr = type ? TypeGetSimpleName(type) : "?type?";
         logger.debug("%s%s %s { %s; %s; }; // flags: 0x%.4X", flagStr, typeStr, name, getterName, setterName, flags);
     }
References LoggerContextObject::debug(), il2cpp_functions::Init(), il2cpp_functions::method_get_name, il2cpp_functions::method_get_param, il2cpp_functions::method_get_return_type, il2cpp_functions::property_get_flags, il2cpp_functions::property_get_get_method, il2cpp_functions::property_get_name, il2cpp_functions::property_get_set_method, RET_V_UNLESS, and TypeGetSimpleName().
Referenced by LogProperties().
MakeAction()
template<typename T = MulticastDelegate*, typename... TArgs> T il2cpp_utils::MakeAction (function_ptr_t< void, TArgs... > lambda)
Creates and returns a C# System.Action<TArgs...> from the provided function_ptr_t. Note that this function assumes AOT code exists for a System.Action with the provided generic arguments.
Template Parameters
TArgs The arguments of the function
Returns
The created System.Action<TArgs...>. Null if it could not be created.
Definition at line 454 of file il2cpp-utils.hpp.
{
         static_assert(sizeof...(TArgs) <= 16, "Cannot create an Action`<T1, T2, ..., TN> where N is > 16!");
         static auto& logger = getLogger();
         if constexpr (sizeof...(TArgs) != 0) {
             // Get generic class with matching number of args
             static auto* genericClass = il2cpp_utils::GetClassFromName("System", "Action`" + ::std::to_string(sizeof...(TArgs)));
             // Extract all parameter types and return types
             static auto genericClasses = ExtractFromFunctionNoArgs<TArgs...>();
             // Instantiate the Func` type
             auto* instantiatedFunc = RET_DEFAULT_UNLESS(logger, il2cpp_utils::MakeGeneric(genericClass, genericClasses));
             // Create the action from the instantiated Func` type
             return il2cpp_utils::MakeDelegate<T>(instantiatedFunc, static_cast<Il2CppObject*>(nullptr), lambda);
         } else {
             static auto* klass = il2cpp_utils::GetClassFromName("System", "Action");
             return il2cpp_utils::MakeDelegate<T>(klass, static_cast<Il2CppObject*>(nullptr), lambda);
         }
     }
References ExtractFromFunctionNoArgs(), GetClassFromName(), getLogger(), MakeGeneric(), and RET_DEFAULT_UNLESS.
MakeDelegate() [1/9]
template<typename T = MulticastDelegate*, class I , class R , class... TArgs> T il2cpp_utils::MakeDelegate (const Il2CppClass * delegateClass, I & instance, R(I::*)(TArgs...) memberFunc) inline
Makes a delegate wrapping the provided instance method.
Template Parameters
T The type to return.
I The instance object.
R The return type of the delegate.
TArgs The arguments of the delegate.
Parameters
delegateClass The Il2CppClass* of the delegate to create.
instance The (move constructible) instance reference to provide to the delegate. This instance is moved and will no longer be valid.
memberFunc A pointer to the member function on the provided instance to invoke for this delegate.
Returns
The created delegate.
Definition at line 342 of file il2cpp-utils.hpp.
{
         return MakeDelegate<T>(delegateClass, instance, std::function<R(I*, TArgs...)>(memberFunc));
     }
References instance, and R.
MakeDelegate() [2/9]
template<typename T = MulticastDelegate*, class I , class R , class... TArgs> T il2cpp_utils::MakeDelegate (const Il2CppClass * delegateClass, I & instance, std::function< R(I *, TArgs...)> f)
Makes a delegate wrapping a context function (such as a context lambda).
Template Parameters
T The type to return.
I The instance object to provide to this delegate.
R The return type of the delegate.
TArgs The arguments of the delegate.
Parameters
delegateClass The Il2CppClass* of the delegate to create.
instance The (move constructible) instance reference to provide to the delegate. This instance is moved and will no longer be valid.
f The function to invoke with the delegate.
Returns
The created delegate.
Definition at line 307 of file il2cpp-utils.hpp.
{
         auto* wrapperInstance = reinterpret_cast<WrapperInstance<I, R, TArgs...>*>(__AllocateUnsafe(sizeof(WrapperInstance<I, R, TArgs...>)));
         wrapperInstance->rawInstance = std::move(instance);
         wrapperInstance->wrappedFunc = f;
         return MakeDelegate<T>(delegateClass, wrapperInstance, &invoker_func_instance<I, R, TArgs...>);
     }
References __AllocateUnsafe(), instance, and R.
MakeDelegate() [3/9]
template<typename T = MulticastDelegate*, class R , class... TArgs> T il2cpp_utils::MakeDelegate (const Il2CppClass * delegateClass, std::function< R(TArgs...)> f)
Makes a delegate wrapping a context function (such as a context lambda).
Template Parameters
T The type to return.
I The instance object to provide to this delegate.
R The return type of the delegate.
TArgs The arguments of the delegate.
Parameters
delegateClass The Il2CppClass* of the delegate to create.
instance The (move constructible) instance reference to provide to the delegate. This instance is moved and will no longer be valid.
f The function to invoke with the delegate.
Returns
The created delegate.
Definition at line 325 of file il2cpp-utils.hpp.
{
         auto* wrapperInstance = reinterpret_cast<WrapperStatic<R, TArgs...>*>(__AllocateUnsafe(sizeof(WrapperStatic<R, TArgs...>)));
         wrapperInstance->wrappedFunc = f;
         wrapperInstance->klass = GetClassFromName("System", "Object");
         return MakeDelegate<T>(delegateClass, wrapperInstance, &invoker_func_static<R, TArgs...>);
     }
References __AllocateUnsafe(), GetClassFromName(), and R.
MakeDelegate() [4/9]
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*, typename R , typename... TArgs> T il2cpp_utils::MakeDelegate (const Il2CppClass * delegateClass, TObj obj, function_ptr_t< R, TArgs... > callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppClass*.
Template Parameters
T The type to return
TObj The type of the target object
Parameters
delegateClass The delegate Il2CppClass* to use
obj The target instance
callback The callback function_ptr_t
Returns
The created delegate
Definition at line 132 of file il2cpp-utils.hpp.
{
         static_assert(std::is_pointer_v<TObj>, "TObj must be a pointer!");
         static_assert(std::is_pointer_v<T>, "T must be a pointer!");
         static auto& logger = getLogger();
         /*
         * TODO: call PlatformInvoke::MarshalFunctionPointerToDelegate directly instead of copying code from it,
         * or at least use a cache like utils::NativeDelegateMethodCache::GetNativeDelegate(nativeFunctionPointer);
         */
         // Lets cache this method. Well formed delegates have only one Invoke method, so ignore param count.
         auto* invoke = il2cpp_utils::FindMethodUnsafe(delegateClass, "Invoke", -1);
         auto* method = reinterpret_cast<MethodInfo*>(calloc(1, sizeof(MethodInfo)));
         // Add the allocated delegate so we can free it later.
         method->methodPointer = (Il2CppMethodPointer)callback;
         method->invoker_method = NULL;
         method->parameters_count = invoke->parameters_count;
         method->slot = kInvalidIl2CppMethodSlot;
         method->is_marshaled_from_native = true;  // "a fake MethodInfo wrapping a native function pointer"
         // In the event that a function is static, this will behave as normal
         if (obj == nullptr) method->flags |= METHOD_ATTRIBUTE_STATIC;
         // TODO: figure out why passing method directly doesn't work
         // TODO: auto-free MethodInfo* after Delegate instance is GC'd
         // TODO: This is horrible
         auto* delegate = RET_DEFAULT_UNLESS(logger, il2cpp_utils::NewUnsafe<T>(delegateClass, obj, &method));
         auto* asDelegate = reinterpret_cast<Delegate*>(delegate);
         AddAllocatedDelegate(asDelegate);
         if ((void*)asDelegate->method_ptr != (void*)callback) {
             logger.error("Created Delegate's method_ptr (%p) is incorrect (should be %p)!", asDelegate->method_ptr, callback);
             return nullptr;
         }
         return delegate;
     }
References AddAllocatedDelegate(), FindMethodUnsafe(), getLogger(), and RET_DEFAULT_UNLESS.
Referenced by MakeDelegate().
MakeDelegate() [5/9]
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*> T il2cpp_utils::MakeDelegate (const Il2CppClass * delegateClass, TObj obj, void * callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppClass*. Assumes the callback has no parameters and a void return.
Template Parameters
T The type to return
TObj The type of the target object
Parameters
delegateClass The delegate Il2CppClass* to use
obj The target instance
callback The callback function_ptr_t
Returns
The created delegate
Definition at line 174 of file il2cpp-utils.hpp.
{
         auto tmp = reinterpret_cast<function_ptr_t<void>>(callback);
         return MakeDelegate(delegateClass, obj, tmp);
     }
References MakeDelegate().
MakeDelegate() [6/9]
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*, typename R , typename... TArgs> T il2cpp_utils::MakeDelegate (const Il2CppType * actionType, TObj obj, function_ptr_t< R, TArgs... > callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppType* PLEASE!!! use the FieldInfo*, MethodInfo*, or Il2CppClass* versions instead if you can.
Template Parameters
T The type to return
TObj The type of the target object
Parameters
delegateType The delegate Il2CppType* to use
obj The target instance
callback The callback function_ptr_t
Returns
The created delegate
Definition at line 188 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         Il2CppClass* delegateClass = il2cpp_functions::class_from_il2cpp_type(actionType);
         return MakeDelegate(delegateClass, obj, callback);
     }
References il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::Init(), and MakeDelegate().
MakeDelegate() [7/9]
template<typename T = MulticastDelegate*, typename TObj = Il2CppObject*> T il2cpp_utils::MakeDelegate (const Il2CppType * delegateType, TObj obj, void * callback)
Creates a delegate of return type T, with target TObj, using the provided Il2CppType* and void* callback. Assumes the callback has no parameters and a void return.
Template Parameters
T The type to return
TObj The type of the target object
Parameters
delegateType The delegate Il2CppType* to use
obj The target instance
callback The callback function
Returns
The created delegate
Definition at line 203 of file il2cpp-utils.hpp.
{
         auto tmp = reinterpret_cast<function_ptr_t<void>>(callback);
         return MakeDelegate(delegateType, obj, tmp);
     }
References MakeDelegate().
MakeDelegate() [8/9]
template<typename T = MulticastDelegate*, typename T1 , typename T2 > T il2cpp_utils::MakeDelegate (const MethodInfo * method, int paramIdx, T1 && arg1, T2 && arg2)
Creates a delegate fit to be passed in the given parameter position to the given method.
Template Parameters
T The type to return
T1 The type to forward to another call of MakeDelegate
T2 The type to forward to another call of MakeDelegate
Parameters
method The MethodInfo* to grab the parameter from
paramIdx The parameter to grab the type from
arg1 Forwarded to another MakeDelegate
arg2 Forwarded to another MakeDelegate
Returns
The created delegate
Definition at line 218 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         static auto& logger = getLogger();
         auto* delegateType = RET_0_UNLESS(logger, il2cpp_functions::method_get_param(method, paramIdx));
         return MakeDelegate<T>(delegateType, arg1, arg2);
     }
References getLogger(), il2cpp_functions::Init(), il2cpp_functions::method_get_param, and RET_0_UNLESS.
MakeDelegate() [9/9]
template<typename T = MulticastDelegate*, typename T1 , typename T2 > T il2cpp_utils::MakeDelegate (FieldInfo * field, T1 && arg1, T2 && arg2)
Creates a delegate fit to be assigned to the given field.
Template Parameters
T The type to return
T1 The type to forward to another call of MakeDelegate
T2 The type to forward to another call of MakeDelegate
Parameters
field The FieldInfo* to grab the parameter from
arg1 Forwarded to another MakeDelegate
arg2 Forwarded to another MakeDelegate
Returns
The created delegate
Definition at line 234 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         static auto& logger = getLogger();
         auto* delegateType = RET_0_UNLESS(logger, il2cpp_functions::field_get_type(field));
         return MakeDelegate<T>(delegateType, arg1, arg2);
     }
References il2cpp_functions::field_get_type, getLogger(), il2cpp_functions::Init(), and RET_0_UNLESS.
MakeFunc()
template<typename T = MulticastDelegate*, typename Ret , typename... TArgs> T il2cpp_utils::MakeFunc (function_ptr_t< Ret, TArgs... > lambda)
Creates and returns a C# System.Func<TArgs..., Ret> from the provided function_ptr_t. Note that this function assumes AOT code exists for a System.Func with the provided generic arguments.
Template Parameters
Ret The return type of the function
TArgs The arguments of the function
Returns
The created System.Func<TArgs..., Ret>. Null if it could not be created.
Definition at line 435 of file il2cpp-utils.hpp.
{
         static_assert(sizeof...(TArgs) + 1 <= 16, "Cannot create a Func`<T1, T2, ..., TN> where N is > 16!");
         static_assert(!std::is_same_v<Ret, void>, "Function used in ::il2cpp_utils::MakeFunc must have a non-void return!");
         static auto& logger = getLogger();
         // Get generic class with matching number of args
         static auto* genericClass = il2cpp_utils::GetClassFromName("System", "Func`" + ::std::to_string(sizeof...(TArgs) + 1));
         // Extract all parameter types and return types
         static auto genericClasses = ExtractFromFunctionNoArgs<Ret, TArgs...>();
         // Instantiate the Func` type
         auto* instantiatedFunc = RET_DEFAULT_UNLESS(logger, il2cpp_utils::MakeGeneric(genericClass, genericClasses));
         // Create the action from the instantiated Func` type
         return il2cpp_utils::MakeDelegate<T>(instantiatedFunc, static_cast<Il2CppObject*>(nullptr), lambda);
     }
References ExtractFromFunctionNoArgs(), GetClassFromName(), getLogger(), MakeGeneric(), and RET_DEFAULT_UNLESS.
MakeGeneric() [1/2]
Il2CppClass * il2cpp_utils::MakeGeneric (const Il2CppClass * klass, const Il2CppType ** types, uint32_t numTypes)
Definition at line 85 of file il2cpp-type-check.cpp.
{
         il2cpp_functions::Init();
         static auto logger = getLogger().WithContext("GetClassFromName");
         auto typ = RET_0_UNLESS(logger, il2cpp_functions::defaults->systemtype_class);
         auto klassType = RET_0_UNLESS(logger, GetSystemType(klass));
         // Call Type.MakeGenericType on it
         auto arr = il2cpp_functions::array_new_specific(typ, numTypes);
         if (!arr) {
             logger.error("Failed to make new array with length: %u", numTypes);
             return nullptr;
         }
         for (size_t i = 0; i < numTypes; i++) {
             const Il2CppType* arg = types[i];
             auto* o = GetSystemType(arg);
             if (!o) {
                 logger.error("Failed to get system type for %s", il2cpp_functions::type_get_name(arg));
                 return nullptr;
             }
             il2cpp_array_set(arr, void*, i, reinterpret_cast<void*>(o));
         }
         auto* reflection_type = RET_0_UNLESS(logger, MakeGenericType(reinterpret_cast<Il2CppReflectionType*>(klassType), arr));
         auto* ret = RET_0_UNLESS(logger, il2cpp_functions::class_from_system_type(reflection_type));
         logger.debug("Returning '%s'", ClassStandardName(ret).c_str());
         return ret;
     }
References il2cpp_functions::array_new_specific, il2cpp_functions::class_from_system_type, ClassStandardName(), il2cpp_functions::defaults, getLogger(), GetSystemType(), il2cpp_array_set, il2cpp_functions::Init(), MakeGenericType(), RET_0_UNLESS, il2cpp_functions::type_get_name, and LoggerContextObject::WithContext().
MakeGeneric() [2/2]
Il2CppClass * il2cpp_utils::MakeGeneric (const Il2CppClass * klass, std::vector< const Il2CppClass * > args)
Definition at line 54 of file il2cpp-type-check.cpp.
{
         il2cpp_functions::Init();
         static auto logger = getLogger().WithContext("MakeGeneric");
         auto typ = RET_0_UNLESS(logger, il2cpp_functions::defaults->systemtype_class);
         auto klassType = RET_0_UNLESS(logger, GetSystemType(klass));
         // Call Type.MakeGenericType on it
         auto arr = il2cpp_functions::array_new_specific(typ, args.size());
         if (!arr) {
             logger.error("Failed to make new array with length: %zu", args.size());
             return nullptr;
         }
         int i = 0;
         for (auto arg : args) {
             auto* o = GetSystemType(arg);
             if (!o) {
                 logger.error("Failed to get type for %s", il2cpp_functions::class_get_name_const(arg));
                 return nullptr;
             }
             il2cpp_array_set(arr, void*, i, reinterpret_cast<void*>(o));
             i++;
         }
         auto* reflection_type = RET_0_UNLESS(logger, MakeGenericType(reinterpret_cast<Il2CppReflectionType*>(klassType), arr));
         auto* ret = RET_0_UNLESS(logger, il2cpp_functions::class_from_system_type(reflection_type));
         logger.debug("Returning '%s'", ClassStandardName(ret).c_str());
         return ret;
     }
References args, il2cpp_functions::array_new_specific, il2cpp_functions::class_from_system_type, il2cpp_functions::class_get_name_const, ClassStandardName(), il2cpp_functions::defaults, getLogger(), GetSystemType(), il2cpp_array_set, il2cpp_functions::Init(), MakeGenericType(), RET_0_UNLESS, and LoggerContextObject::WithContext().
Referenced by il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< T, typename std::enable_if_t< std::is_base_of_v< NestedType, T > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< S< TArgs... >, typename std::enable_if_t< has_get< il2cpp_gen_struct_no_arg_class< S > > > >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< S< TArgs... > * >::get(), MakeAction(), and MakeFunc().
MakeGenericMethod() [1/2]
const MethodInfo* il2cpp_utils::MakeGenericMethod (const MethodInfo * info, ::std::vector< Il2CppClass * > types) noexcept
Instantiates a generic MethodInfo* from the provided Il2CppClasses.
Returns
MethodInfo* for RunMethod calls, will be nullptr on failure
MakeGenericMethod() [2/2]
const MethodInfo* il2cpp_utils::MakeGenericMethod (const MethodInfo * info, std::vector< Il2CppClass * > types) noexcept
Definition at line 40 of file il2cpp-utils-methods.cpp.
     {
         static auto logger = getLogger().WithContext("MakeGenericMethod");
         il2cpp_functions::Init();
         // Ensure it exists and is generic
         THROW_OR_RET_NULL(logger, info);
         THROW_OR_RET_NULL(logger, il2cpp_functions::method_is_generic(info));
         static auto* typeClass = THROW_OR_RET_NULL(logger, il2cpp_functions::defaults->systemtype_class);
         // Create the Il2CppReflectionMethod* from the MethodInfo* using the MethodInfo's type
         auto* infoObj = il2cpp_functions::method_get_object(info, nullptr);
         if (!infoObj) {
             logger.error("Failed to get MonoMethod from MethodInfo: %p", info);
             THROW_OR_RET_NULL(logger, infoObj);
         }
         // Populate generic parameters into array
         auto* arr = reinterpret_cast<Array<Il2CppReflectionType*>*>(il2cpp_functions::array_new(typeClass, types.size()));
         if (!arr) {
             logger.error("Failed to create array of length: %u", types.size());
             THROW_OR_RET_NULL(logger, arr);
         }
         int i = 0;
         for (auto* klass : types) {
             auto* typeObj = GetSystemType(klass);
             if (!typeObj) {
                 logger.error("Failed to get type object from class: %s", il2cpp_functions::class_get_name_const(klass));
                 THROW_OR_RET_NULL(logger, typeObj);
             }
             arr->values[i] = typeObj;
             i++;
         }
         // Call instance function on infoObj to MakeGeneric
         // Does not need to perform type checking, since if this does not match, it will fail more miserably.
         auto res = il2cpp_utils::RunMethod<Il2CppReflectionMethod*, false>(infoObj, "MakeGenericMethod", arr);
         const auto* returnedInfoObj = RET_0_UNLESS(logger, res);
         if (!returnedInfoObj) {
             logger.error("Failed to get Il2CppReflectionMethod from MakeGenericMethod!");
             THROW_OR_RET_NULL(logger, returnedInfoObj);
         }
         // Get MethodInfo* back from generic instantiated method
         const auto* inflatedInfo = il2cpp_functions::method_get_from_reflection(returnedInfoObj);
         if (!inflatedInfo) {
             logger.error("Got null MethodInfo* from Il2CppReflectionMethod: %p", returnedInfoObj);
             THROW_OR_RET_NULL(logger, inflatedInfo);
         }
         // Return method to be invoked by caller
         return inflatedInfo;
     }
References il2cpp_functions::array_new, il2cpp_functions::class_get_name_const, il2cpp_functions::defaults, getLogger(), GetSystemType(), info, il2cpp_functions::Init(), il2cpp_functions::method_get_from_reflection, il2cpp_functions::method_get_object, il2cpp_functions::method_is_generic, RET_0_UNLESS, THROW_OR_RET_NULL, and LoggerContextObject::WithContext().
Referenced by RunGenericMethod().
MakeGenericType()
Il2CppReflectionType * il2cpp_utils::MakeGenericType (Il2CppReflectionType * gt, Il2CppArray * types)
Definition at line 144 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("MakeGenericType");
         il2cpp_functions::Init();
         auto runtimeType = RET_0_UNLESS(logger, il2cpp_functions::defaults->runtimetype_class);
         auto makeGenericMethod = RET_0_UNLESS(logger, FindMethodUnsafe(runtimeType, "MakeGenericType", 2));
         Il2CppException* exp = nullptr;
         void* params[] = {reinterpret_cast<void*>(gt), reinterpret_cast<void*>(types)};
         auto genericType = il2cpp_functions::runtime_invoke(makeGenericMethod, nullptr, params, &exp);
         if (exp) {
             logger.error("il2cpp_utils: MakeGenericType: Failed with exception: %s", ExceptionToString(exp).c_str());
             return nullptr;
         }
         return reinterpret_cast<Il2CppReflectionType*>(genericType);
     }
References il2cpp_functions::defaults, ExceptionToString(), FindMethodUnsafe(), getLogger(), il2cpp_functions::Init(), RET_0_UNLESS, il2cpp_functions::runtime_invoke, and LoggerContextObject::WithContext().
Referenced by MakeGeneric().
MakeRef()
const Il2CppType * il2cpp_utils::MakeRef (const Il2CppType * type)
Definition at line 25 of file il2cpp-utils.cpp.
{
         if (type->byref) return type;
         il2cpp_functions::Init();
         // could use Class::GetByrefType instead of &->this_arg but it does the same thing
         return &il2cpp_functions::class_from_il2cpp_type(type)->this_arg;
     }
References il2cpp_functions::class_from_il2cpp_type, and il2cpp_functions::Init().
Match()
bool il2cpp_utils::Match (const Il2CppObject * source, const Il2CppClass * klass) noexcept
Definition at line 274 of file il2cpp-utils.cpp.
{
         return (source->klass == klass);
     }
References rapidjson::source.
Referenced by AssertMatch(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match().
New() [1/3]
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs> ::std::optional<TOut> il2cpp_utils::New (::std::string_view nameSpace, ::std::string_view className, TArgs &&... args)
Definition at line 506 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetClassFromName(nameSpace, className));
         return New<TOut, creationType>(klass, args...);
     }
References args, GetClassFromName(), getLogger(), and RET_0_UNLESS.
New() [2/3]
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs> ::std::optional<TOut> il2cpp_utils::New (Il2CppClass * klass, TArgs &&... args)
Definition at line 454 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         Il2CppObject* obj;
         if constexpr (creationType == CreationType::Temporary) {
             // object_new call
             obj = RET_NULLOPT_UNLESS(logger, il2cpp_functions::object_new(klass));
         } else {
             obj = RET_NULLOPT_UNLESS(logger, createManual(klass));
         }
         // runtime_invoke constructor with right type(s) of arguments, return null if constructor errors
         RET_NULLOPT_UNLESS(logger, RunMethod(obj, ".ctor", args...));
         return FromIl2CppObject<TOut>(obj);
     }
References args, createManual(), getLogger(), il2cpp_functions::Init(), il2cpp_functions::object_new, RET_NULLOPT_UNLESS, RunMethod(), and Temporary.
Referenced by CreateFieldValue(), CreateParam(), and Array< T >::New().
New() [3/3]
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs> ::std::enable_if_t<(... && ((!::std::is_same_v<const Il2CppClass*, TArgs> || !::std::is_same_v<Il2CppClass*, TArgs>) && !::std::is_convertible_v<TArgs, ::std::string_view>)), ::std::optional<TOut> > il2cpp_utils::New (TArgs &&... args)
Definition at line 497 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_NULLOPT_UNLESS(logger, (NoArgClass<TOut, true>()));
         return New<TOut, creationType>(klass, args...);
     }
References args, getLogger(), and RET_NULLOPT_UNLESS.
newcsstr() [1/2]
template<CreationType creationType = CreationType::Temporary> Il2CppString* il2cpp_utils::newcsstr (std::string_view inp)
Create a new csstr from a UTF8 string view.
Template Parameters
creationType The creation type for the string.
Parameters
inp The input string to create.
Returns
The returned string.
Definition at line 99 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         if constexpr (creationType == CreationType::Manual) {
             // TODO: Perhaps manually call createManual instead
             auto len = inp.length();
             auto mallocSize = sizeof(Il2CppString) + sizeof(Il2CppChar) * (len + 1);
             // String never has any references anyways, malloc is safe here because the string gets copied over anyways.
             auto* str = reinterpret_cast<__InternalCSStr*>(malloc(mallocSize));
             str->object.klass = il2cpp_functions::defaults->string_class;
             str->object.monitor = nullptr;
             str->length = len;
             for (size_t i = 0; i < len; i++) {
                 str->chars[i] = inp[i];
             }
             str->chars[len] = '\0';
             return reinterpret_cast<Il2CppString*>(str);
         } else {
             static auto logger = getLogger().WithContext("newcsstr");
             static auto enc = RET_0_UNLESS(logger, GetPropertyValue("System.Text", "Encoding", "ASCII"));
             // Create new string, created from the literal char*, not to be confused with a copy of this data
             auto* obj = RET_0_UNLESS(logger, RunMethod<Il2CppString*>("System", "String", "CreateStringFromEncoding", (uint8_t*)inp.data(), (int)inp.length(), enc));
             return reinterpret_cast<Il2CppString*>(obj);
         }
     }
References il2cpp_functions::defaults, getLogger(), GetPropertyValue(), il2cpp_functions::Init(), Manual, il2cpp_utils::__InternalCSStr::object, RET_0_UNLESS, and LoggerContextObject::WithContext().
newcsstr() [2/2]
template<CreationType creationType = CreationType::Temporary> Il2CppString* il2cpp_utils::newcsstr (std::u16string_view inp)
Create a new csstr from a UTF16 string view.
Template Parameters
creationType The creation type for the string.
Parameters
inp The input string to create.
Returns
The returned string.
Definition at line 74 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         if constexpr (creationType == CreationType::Manual) {
             auto len = inp.length();
             auto mallocSize = sizeof(Il2CppString) + sizeof(Il2CppChar) * (len + 1);
             // String never has any references anyways, malloc is safe here because the string gets copied over anyways.
             auto* str = reinterpret_cast<__InternalCSStr*>(malloc(mallocSize));
             str->object.klass = il2cpp_functions::defaults->string_class;
             str->object.monitor = nullptr;
             str->length = len;
             for (size_t i = 0; i < len; i++) {
                 str->chars[i] = inp[i];
             }
             str->chars[len] = '\0';
             return reinterpret_cast<Il2CppString*>(str);
         } else {
             return il2cpp_functions::string_new_utf16(reinterpret_cast<const Il2CppChar*>(inp.data()), inp.length());
         }
     }
References il2cpp_functions::defaults, il2cpp_functions::Init(), Manual, il2cpp_utils::__InternalCSStr::object, and il2cpp_functions::string_new_utf16.
NewUnsafe() [1/2]
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs> ::std::optional<TOut> il2cpp_utils::NewUnsafe (::std::string_view nameSpace, ::std::string_view className, TArgs *... args)
Definition at line 515 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetClassFromName(nameSpace, className));
         return NewUnsafe<TOut, creationType>(klass, args...);
     }
References args, GetClassFromName(), getLogger(), and RET_0_UNLESS.
NewUnsafe() [2/2]
template<typename TOut = Il2CppObject*, CreationType creationType = CreationType::Temporary, typename... TArgs> ::std::optional<TOut> il2cpp_utils::NewUnsafe (const Il2CppClass * klass, TArgs &&... args)
Definition at line 473 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         Il2CppObject* obj;
         if constexpr (creationType == CreationType::Temporary) {
             // object_new call
             obj = RET_NULLOPT_UNLESS(logger, il2cpp_functions::object_new(klass));
         } else {
             obj = RET_NULLOPT_UNLESS(logger, createManual(klass));
         }
         // runtime_invoke constructor with right number of args, return null if constructor errors
         RET_NULLOPT_UNLESS(logger, RunMethodUnsafe(obj, ".ctor", args...));
         return FromIl2CppObject<TOut>(obj);
     }
References args, createManual(), getLogger(), il2cpp_functions::Init(), il2cpp_functions::object_new, RET_NULLOPT_UNLESS, RunMethodUnsafe(), and Temporary.
Referenced by CreateFieldValueUnsafe(), and CreateParamUnsafe().
NoArgClass()
template<class T , bool ResultRequired = false> Il2CppClass* il2cpp_utils::NoArgClass ()
Definition at line 85 of file il2cpp-utils-classes.hpp.
{
         // TODO: change ifndef HAS_CODEGEN to 'if compile warnings are not errors'?
         static auto& logger = getLogger();
         #ifndef HAS_CODEGEN
         using arg_class = il2cpp_type_check::il2cpp_no_arg_class<T>;
         if constexpr (!has_get<arg_class>) {
             if constexpr (ResultRequired) {
                 static_assert(false_t<arg_class>, "il2cpp-type-check.hpp could not deduce what C# type your type represents");
             } else {
                 a_lack_of_no_arg_class_for<T>("please tell il2cpp-type-check.hpp what C# type your type represents");
                 THROW_OR_RET_NULL(logger, false);
             }
         } else
         #endif
         if constexpr (ResultRequired) {
             return THROW_OR_RET_NULL(logger, il2cpp_type_check::il2cpp_no_arg_class<T>::get());
         } else {
             return il2cpp_type_check::il2cpp_no_arg_class<T>::get();
         }
     }
References getLogger(), and THROW_OR_RET_NULL.
Referenced by ExtractIndependentType().
ParameterMatch() [1/4]
bool il2cpp_utils::ParameterMatch (const MethodInfo * method, ::std::vector< const Il2CppType * > argTypes)
ParameterMatch() [2/4]
bool il2cpp_utils::ParameterMatch (const MethodInfo * method, ::std::vector< Il2CppClass * > genTypes, ::std::vector< const Il2CppType * > argTypes)
ParameterMatch() [3/4]
bool il2cpp_utils::ParameterMatch (const MethodInfo * method, std::vector< const Il2CppType * > argTypes)
Definition at line 73 of file il2cpp-utils.cpp.
{
         return ParameterMatch(method, {}, argTypes);
     }
References ParameterMatch().
ParameterMatch() [4/4]
bool il2cpp_utils::ParameterMatch (const MethodInfo * method, std::vector< Il2CppClass * > genTypes, std::vector< const Il2CppType * > argTypes)
Definition at line 38 of file il2cpp-utils.cpp.
{
         static auto logger = getLogger().WithContext("ParameterMatch");
         il2cpp_functions::Init();
         if (method->parameters_count != argTypes.size()) {
             return false;
         }
         auto genCount = (method->is_generic && !method->is_inflated) ? method->genericContainer->type_argc : 0;
         if ((size_t)genCount != genTypes.size()) {
             logger.warning("Potential method match had wrong number of generics %i (expected %i)",
                 genCount, genTypes.size());
             return false;
         }
         // TODO: supply boolStrictMatch and use type_equals instead of IsConvertible if supplied?
         for (decltype(method->parameters_count) i = 0; i < method->parameters_count; i++) {
             auto* paramType = method->parameters[i].parameter_type;
             if (paramType->type == IL2CPP_TYPE_MVAR) {
                 auto genIdx = paramType->data.genericParameterIndex - method->genericContainer->genericParameterStart;
                 if (genIdx < 0) {
                     logger.warning("Extracted invalid genIdx %i from parameter %i", genIdx, i);
                 } else if (genIdx >= genCount) {
                     logger.warning("ParameterMatch was not supplied enough genTypes to determine type of parameter %i "
                         "(had %i, needed %i)!", i, genCount, genIdx);
                 } else {
                     auto* klass = genTypes.at(genIdx);
                     paramType = (paramType->byref) ? &klass->this_arg : &klass->byval_arg;
                 }
             }
             // TODO: just because two parameter lists match doesn't necessarily mean this is the best match...
             if (!(IsConvertible(paramType, argTypes.at(i)))) {
                 return false;
             }
         }
         return true;
     }
References getLogger(), il2cpp_functions::Init(), IsConvertible(), and LoggerContextObject::WithContext().
Referenced by FindMethod(), ParameterMatch(), and RunMethod().
RunGenericMethod() [1/3]
template<class TOut = Il2CppObject*, class... TArgs> ::std::optional<TOut> il2cpp_utils::RunGenericMethod (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, ::std::vector< Il2CppClass * > genTypes, TArgs &&... params) noexcept
Definition at line 420 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_NULLOPT_UNLESS(logger, GetClassFromName(nameSpace, klassName));
         return RunGenericMethod<TOut>(klass, methodName, genTypes, params...);
     }
References GetClassFromName(), getLogger(), and RET_NULLOPT_UNLESS.
RunGenericMethod() [2/3]
template<class TOut = Il2CppObject*, class T , class... TArgs> ::std::optional<TOut> il2cpp_utils::RunGenericMethod (T && classOrInstance, ::std::string_view methodName, ::std::vector< Il2CppClass * > genTypes, TArgs &&... params) noexcept
Definition at line 406 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto types = ExtractTypes(params...);
         if (types.size() != sizeof...(TArgs)) {
             logger.warning("ExtractTypes for method %s failed!", methodName.data());
             return ::std::nullopt;
         }
         auto* info = RET_NULLOPT_UNLESS(logger, FindMethod(classOrInstance, NoArgClass<TOut>(), methodName, genTypes, types));
         return RunGenericMethod<TOut>(classOrInstance, info, genTypes, params...);
     }
References ExtractTypes(), FindMethod(), getLogger(), info, and RET_NULLOPT_UNLESS.
RunGenericMethod() [3/3]
template<class TOut = Il2CppObject*, class T , class... TArgs> ::std::optional<TOut> il2cpp_utils::RunGenericMethod (T && instance, const MethodInfo * info, ::std::vector< Il2CppClass * > genTypes, TArgs &&... params) noexcept
Instantiates a generic MethodInfo* from the provided Il2CppClasses and invokes it.
This method will not crash.
Template Parameters
TOut The return type of the method to invoke
T Instance type
TArgs Parameters to RunMethod
Parameters
instance Instance to RunMethod, or null/class
info Generic MethodInfo* to invoke
genTypes Types to instantiate the generic MethodInfo* with
params Parameters to RunMethod
Definition at line 399 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* createdMethod = RET_NULLOPT_UNLESS(logger, MakeGenericMethod(info, genTypes));
         return RunMethod<TOut, false>(instance, createdMethod, params...);
     }
References getLogger(), info, instance, MakeGenericMethod(), and RET_NULLOPT_UNLESS.
RunMethod() [1/3]
template<class TOut = Il2CppObject*, bool checkTypes = true, class... TArgs> ::std::optional<TOut> il2cpp_utils::RunMethod (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, TArgs &&... params)
Definition at line 383 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_NULLOPT_UNLESS(logger, GetClassFromName(nameSpace, klassName));
         return RunMethod<TOut, checkTypes>(klass, methodName, params...);
     }
References GetClassFromName(), getLogger(), and RET_NULLOPT_UNLESS.
RunMethod() [2/3]
template<class TOut = Il2CppObject*, bool checkTypes = true, class T , class... TArgs> ::std::enable_if_t<!::std::is_convertible_v<T, ::std::string_view>, ::std::optional<TOut> > il2cpp_utils::RunMethod (T && classOrInstance, ::std::string_view methodName, TArgs &&... params)
Definition at line 354 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         if constexpr (checkTypes) {
             auto types = ExtractTypes(params...);
             if (types.size() != sizeof...(TArgs)) {
                 logger.warning("ExtractTypes for method %s failed!", methodName.data());
                 return ::std::nullopt;
             }
             auto* method = RET_NULLOPT_UNLESS(logger, FindMethod(classOrInstance, NoArgClass<TOut>(), methodName, types));
             return RunMethod<TOut, true>(classOrInstance, method, params...);
         }
         // TODO: We should probably change how FindMethod is called/isn't called
         // At the moment, however, if you call RunMethod with checkTypes = false, it will perform an FindMethodUnsafe instead
         // But it will return nullptr if there are multiple matches
         else {
             if constexpr (std::is_same_v<T, Il2CppClass*>) {
                 auto* method = RET_NULLOPT_UNLESS(logger, FindMethodUnsafe(classOrInstance, methodName, sizeof...(TArgs)));
                 return RunMethod<TOut, false>(classOrInstance, method, params...);
             } else {
                 auto* klass = RET_NULLOPT_UNLESS(logger, ExtractClass(classOrInstance));
                 auto* method = RET_NULLOPT_UNLESS(logger, FindMethodUnsafe(klass, methodName, sizeof...(TArgs)));
                 return RunMethod<TOut, false>(classOrInstance, method, params...);
             }
         }
     }
References ExtractClass(), ExtractTypes(), FindMethod(), FindMethodUnsafe(), getLogger(), and RET_NULLOPT_UNLESS.
RunMethod() [3/3]
template<class TOut = Il2CppObject*, bool checkTypes = true, class T , class... TArgs> ::std::optional<TOut> il2cpp_utils::RunMethod (T && instance, const MethodInfo * method, TArgs &&... params)
Definition at line 287 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         RET_NULLOPT_UNLESS(logger, method);
         if constexpr (checkTypes && sizeof...(TArgs) > 0) {
             auto typeVec = ExtractTypes(params...);
             RET_NULLOPT_UNLESS(logger, typeVec.size() == sizeof...(TArgs));
             RET_NULLOPT_UNLESS(logger, ParameterMatch(method, typeVec));
         }
         void* inst = ExtractValue(instance);  // null is allowed (for T = Il2CppType* or Il2CppClass*)
         Il2CppException* exp = nullptr;
         auto invokeParamsVec = ExtractValues(params...);
         il2cpp_functions::Init();
         auto* ret = il2cpp_functions::runtime_invoke(method, inst, invokeParamsVec.data(), &exp);
         // Check if the TOut that the user requested makes sense given the Il2CppObject* we actually got
         if constexpr (checkTypes) {
             if (ret) {
                 // By using this instead of ExtractType, we avoid unboxing because the ultimate type in that case would depend on the
                 // method in the first place
                 auto* outType = ExtractIndependentType<TOut>();
                 if (outType) {
                     auto* retType = ExtractType(ret);
                     if (!IsConvertible(outType, retType, false)) {
                         logger.warning("User requested TOut %s does not match the method's return object of type %s!",
                             TypeGetSimpleName(outType), TypeGetSimpleName(retType));
                     }
                 }
             }
         }
         if (exp) {
             logger.error("%s: Failed with exception: %s", il2cpp_functions::method_get_name(method),
                 il2cpp_utils::ExceptionToString(exp).c_str());
             return ::std::nullopt;
         }
         return FromIl2CppObject<TOut>(ret);
     }
References ExceptionToString(), ExtractType(), ExtractTypes(), ExtractValue(), ExtractValues(), getLogger(), il2cpp_functions::Init(), instance, IsConvertible(), il2cpp_functions::method_get_name, ParameterMatch(), RET_NULLOPT_UNLESS, il2cpp_functions::runtime_invoke, and TypeGetSimpleName().
Referenced by New().
RunMethodUnsafe() [1/3]
template<class TOut = Il2CppObject*, class... TArgs> ::std::optional<TOut> il2cpp_utils::RunMethodUnsafe (::std::string_view nameSpace, ::std::string_view klassName, ::std::string_view methodName, TArgs &&... params)
Definition at line 445 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_NULLOPT_UNLESS(logger, GetClassFromName(nameSpace, klassName));
         return RunMethodUnsafe<TOut>(klass, methodName, params...);
     }
References GetClassFromName(), getLogger(), and RET_NULLOPT_UNLESS.
RunMethodUnsafe() [2/3]
template<class TOut = Il2CppObject*, class T , class... TArgs> ::std::optional<TOut> il2cpp_utils::RunMethodUnsafe (T && instance, const MethodInfo * method, TArgs &&... params)
Definition at line 336 of file il2cpp-utils-methods.hpp.
{
         return RunMethod<TOut, false>(instance, method, params...);
     }
References instance.
Referenced by Array< T >::CopyTo(), Array< T >::GetEnumerator(), and NewUnsafe().
RunMethodUnsafe() [3/3]
template<class TOut = Il2CppObject*, class T , class... TArgs> ::std::enable_if_t<::std::is_base_of_v<Il2CppClass, T> || ::std::is_base_of_v<Il2CppObject, T>, ::std::optional<TOut> > il2cpp_utils::RunMethodUnsafe (T * classOrInstance, ::std::string_view methodName, TArgs &&... params)
Definition at line 434 of file il2cpp-utils-methods.hpp.
{
         static auto& logger = getLogger();
         RET_NULLOPT_UNLESS(logger, classOrInstance);
         auto* method = RET_NULLOPT_UNLESS(logger, FindMethodUnsafe(classOrInstance, methodName, sizeof...(TArgs)));
         return RunMethod<TOut, false>(classOrInstance, method, params...);
     }
References FindMethodUnsafe(), getLogger(), and RET_NULLOPT_UNLESS.
RunStaticMethod()
template<class TOut = Il2CppObject*, bool checkTypes = true, class... TArgs> ::std::optional<TOut> il2cpp_utils::RunStaticMethod (const MethodInfo * method, TArgs &&... params)
Definition at line 330 of file il2cpp-utils-methods.hpp.
{
         return RunMethod<TOut, checkTypes>(static_cast<Il2CppClass*>(nullptr), method, params...);
     }
RunStaticMethodUnsafe()
template<class TOut = Il2CppObject*, class... TArgs> ::std::optional<TOut> il2cpp_utils::RunStaticMethodUnsafe (const MethodInfo * method, TArgs &&... params)
Definition at line 342 of file il2cpp-utils-methods.hpp.
{
         return RunMethod<TOut, false>(static_cast<Il2CppClass*>(nullptr), method, params...);
     }
Referenced by createManual().
RuntimeInvoke()
template<typename... TArgs> Il2CppObject* il2cpp_utils::RuntimeInvoke (const MethodInfo * method, Il2CppObject * reference, Il2CppException ** exc, TArgs *... args)
Definition at line 407 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         void* invokeParams[] = {reinterpret_cast<void*>(args)...};
         return il2cpp_functions::runtime_invoke(method, reference, invokeParams, exc);
     }
References args, il2cpp_functions::Init(), and il2cpp_functions::runtime_invoke.
SetFieldValue() [1/3]
template<class TArg > bool il2cpp_utils::SetFieldValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view fieldName, TArg && value)
Definition at line 131 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetClassFromName(nameSpace, className));
         return SetFieldValue(klass, fieldName, value);
     }
References GetClassFromName(), getLogger(), RET_0_UNLESS, SetFieldValue(), and rapidjson::value.
SetFieldValue() [2/3]
template<class TArg > bool il2cpp_utils::SetFieldValue (Il2CppObject * instance, FieldInfo * field, TArg && value)
Definition at line 98 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         RET_0_UNLESS(logger, field);
         // Ensure supplied value matches field's type
         auto* typ = ExtractType(value);
         RET_0_UNLESS(logger, IsConvertible(field->type, typ));
         void* val = ExtractValue(value);
         if (instance) {
             il2cpp_functions::field_set_value(instance, field, val);
         } else { // Fallback to perform a static field set
             il2cpp_functions::field_static_set_value(field, val);
         }
         return true;
     }
References ExtractType(), ExtractValue(), il2cpp_functions::field_set_value, il2cpp_functions::field_static_set_value, getLogger(), il2cpp_functions::Init(), instance, IsConvertible(), RET_0_UNLESS, and rapidjson::value.
Referenced by SetFieldValue().
SetFieldValue() [3/3]
template<class T , class TArg > bool il2cpp_utils::SetFieldValue (T & classOrInstance, ::std::string_view fieldName, TArg && value)
Definition at line 119 of file il2cpp-utils-fields.hpp.
{
         static auto& logger = getLogger();
         auto* field = RET_0_UNLESS(logger, FindField(classOrInstance, fieldName));
         Il2CppObject* obj = ToIl2CppObject(classOrInstance);  // null is allowed (for T = Il2CppType* or Il2CppClass*)
         RET_0_UNLESS(logger, SetFieldValue(obj, field, value));
         if (obj) RET_0_UNLESS(logger, FromIl2CppObject(obj, classOrInstance));
         return true;
     }
References FindField(), FromIl2CppObject(), getLogger(), RET_0_UNLESS, SetFieldValue(), ToIl2CppObject(), and rapidjson::value.
SetPropertyValue() [1/3]
template<bool checkTypes = true, class TArg > bool il2cpp_utils::SetPropertyValue (::std::string_view nameSpace, ::std::string_view className, ::std::string_view propName, TArg && value)
Definition at line 85 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, GetClassFromName(nameSpace, className));
         return SetPropertyValue<checkTypes>(klass, propName, value);
     }
References GetClassFromName(), getLogger(), RET_0_UNLESS, and rapidjson::value.
SetPropertyValue() [2/3]
template<bool checkTypes = true, class T , class TArg > bool il2cpp_utils::SetPropertyValue (T & classOrInstance, ::std::string_view propName, TArg && value)
Definition at line 76 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         auto* prop = RET_0_UNLESS(logger, FindProperty(classOrInstance, propName));
         return SetPropertyValue<checkTypes>(classOrInstance, prop, value);
     }
References FindProperty(), getLogger(), RET_0_UNLESS, and rapidjson::value.
SetPropertyValue() [3/3]
template<bool checkTypes = true, class T , class TArg > bool il2cpp_utils::SetPropertyValue (T & classOrInstance, const PropertyInfo * prop, TArg && value)
Definition at line 64 of file il2cpp-utils-properties.hpp.
{
         static auto& logger = getLogger();
         il2cpp_functions::Init();
         RET_0_UNLESS(logger, prop);
         auto* setter = RET_0_UNLESS(logger, il2cpp_functions::property_get_set_method(prop));
         return (bool)RunMethod<Il2CppObject*, checkTypes>(classOrInstance, setter, value);
     }
References getLogger(), il2cpp_functions::Init(), il2cpp_functions::property_get_set_method, RET_0_UNLESS, and rapidjson::value.
ToIl2CppObject()
template<class T > Il2CppObject* il2cpp_utils::ToIl2CppObject (T && arg)
Definition at line 101 of file il2cpp-utils-methods.hpp.
{
         il2cpp_functions::Init();
         using Dt = ::std::decay_t<T>;
         if constexpr (::std::is_same_v<Dt, Il2CppType*> || ::std::is_same_v<Dt, Il2CppClass*>) {
             return nullptr;
         }
         static auto& logger = getLogger();
         auto* klass = RET_0_UNLESS(logger, ExtractClass(arg));
         return il2cpp_functions::value_box(klass, &arg);
     }
References ExtractClass(), getLogger(), il2cpp_functions::Init(), RET_0_UNLESS, and il2cpp_functions::value_box.
Referenced by GetFieldValue(), and SetFieldValue().
try_cast()
template<typename U , typename T > std::optional<U*> il2cpp_utils::try_cast (T * inst)
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
Template Parameters
T The type to cast from.
U The type to cast to.
Returns
A U* of the cast value, if successful.
Definition at line 205 of file il2cpp-utils-classes.hpp.
{
         auto* k1 = classof(U*);
         if (!k1 || !inst) {
             return std::nullopt;
         }
         // TODO: Assumes T* is (at least) an Il2CppClass**, this means it assumes klass as first field.
         auto* k2 = *reinterpret_cast<Il2CppClass**>(inst);
         if (!k2) {
             return std::nullopt;
         }
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return reinterpret_cast<U*>(inst);
         }
         return std::nullopt;
     }
References il2cpp_functions::class_is_assignable_from, and classof.
TypeGetSimpleName()
const char * il2cpp_utils::TypeGetSimpleName (const Il2CppType * type)
Definition at line 81 of file il2cpp-utils.cpp.
{
         il2cpp_functions::Init();
         typeLock.lock();
         if (typeMap.empty()) {
             typeMap[il2cpp_functions::defaults->boolean_class] = "bool";
             typeMap[il2cpp_functions::defaults->byte_class] = "byte";
             typeMap[il2cpp_functions::defaults->sbyte_class] = "sbyte";
             typeMap[il2cpp_functions::defaults->char_class] = "char";
             typeMap[il2cpp_functions::defaults->single_class] = "float";
             typeMap[il2cpp_functions::defaults->double_class] = "double";
             typeMap[il2cpp_functions::defaults->int16_class] = "short";
             typeMap[il2cpp_functions::defaults->uint16_class] = "ushort";
             typeMap[il2cpp_functions::defaults->int32_class] = "int";
             typeMap[il2cpp_functions::defaults->uint32_class] = "uint";
             typeMap[il2cpp_functions::defaults->int64_class] = "long";
             typeMap[il2cpp_functions::defaults->uint64_class] = "ulong";
             typeMap[il2cpp_functions::defaults->object_class] = "object";
             typeMap[il2cpp_functions::defaults->string_class] = "string";
             typeMap[il2cpp_functions::defaults->void_class] = "void";
         }
         auto p = typeMap.find(il2cpp_functions::class_from_il2cpp_type(type));
         if (p != typeMap.end()) {
             typeLock.unlock();
             return p->second;
         } else {
             typeLock.unlock();
             return il2cpp_functions::type_get_name(type);
         }
     }
References il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::defaults, il2cpp_functions::Init(), il2cpp_functions::type_get_name, typeLock, and typeMap.
Referenced by FindMethod(), GenericsToStringHelper(), GetFieldValue(), IsConvertible(), LogField(), LogMethod(), LogProperty(), and RunMethod().
TypesFrom() [1/6]
::std::vector<const Il2CppType*> il2cpp_utils::TypesFrom (::std::vector< const Il2CppClass * > classes)
TypesFrom() [2/6]
::std::vector<const Il2CppType*> il2cpp_utils::TypesFrom (::std::vector< const Il2CppType * > types)
TypesFrom() [3/6]
::std::vector<const Il2CppType*> il2cpp_utils::TypesFrom (::std::vector<::std::string_view > strings)
TypesFrom() [4/6]
std::vector< const Il2CppType * > il2cpp_utils::TypesFrom (std::vector< const Il2CppClass * > classes)
Definition at line 127 of file il2cpp-utils.cpp.
 { return ClassVecToTypes(classes); }
References ClassVecToTypes().
TypesFrom() [5/6]
std::vector< const Il2CppType * > il2cpp_utils::TypesFrom (std::vector< const Il2CppType * > types)
Definition at line 126 of file il2cpp-utils.cpp.
 { return types; }
Referenced by il2cpp_utils::FindMethodInfo::FindMethodInfo().
TypesFrom() [6/6]
std::vector< const Il2CppType * > il2cpp_utils::TypesFrom (std::vector< std::string_view > strings)
Definition at line 128 of file il2cpp-utils.cpp.
{
         std::vector<const Il2CppType*> types;
         il2cpp_functions::Init();
         for (size_t i = 0; i < strings.size() - 1; i += 2) {
             auto clazz = GetClassFromName(strings[i].data(), strings[i+1].data());
             types.push_back(il2cpp_functions::class_get_type(clazz));
         }
         return types;
     }
References il2cpp_functions::class_get_type, GetClassFromName(), and il2cpp_functions::Init().
UnRef()
const Il2CppType * il2cpp_utils::UnRef (const Il2CppType * type)
Definition at line 32 of file il2cpp-utils.cpp.
{
         if (!type->byref) return type;
         il2cpp_functions::Init();
         return il2cpp_functions::class_get_type(il2cpp_functions::class_from_il2cpp_type(type));
     }
References il2cpp_functions::class_from_il2cpp_type, il2cpp_functions::class_get_type, and il2cpp_functions::Init().
vectorToArray()
template<typename T > Array<T>* il2cpp_utils::vectorToArray (::std::vector< T > & vec)
Converts a vector to an Array*.
Template Parameters
T Inner type of the vector and array
Parameters
vec Vector to create the Array from
Returns
The created Array<T>*
Definition at line 366 of file il2cpp-utils.hpp.
{
         il2cpp_functions::Init();
         static auto& logger = getLogger();
         Array<T>* arr = reinterpret_cast<Array<T>*>(RET_0_UNLESS(logger, il2cpp_functions::array_new(il2cpp_type_check::il2cpp_no_arg_class<T>::get(), vec.size())));
         for (size_t i = 0; i < vec.size(); i++) {
             arr->values[i] = vec[i];
         }
         return arr;
     }
References il2cpp_functions::array_new, getLogger(), il2cpp_functions::Init(), and RET_0_UNLESS.
Variable Documentation
args
R TArgs TArgs il2cpp_utils::args
Initial value:
{
        if constexpr (std::is_same_v<R, void>) {
            instance->wrappedFunc(&instance->rawInstance, args...);
        } else {
            return instance->wrappedFunc(&instance->rawInstance, args...);
        }
    }
    template<class R, class... TArgs>
    R __attribute__((noinline)) invoker_func_static(WrapperStatic<R, TArgs...>* instance, TArgs... args) {
        if constexpr (std::is_same_v<R, void>) {
            instance->wrappedFunc(args...);
        } else {
            return instance->wrappedFunc(args...);
        }
    }
    void* __AllocateUnsafe(std::size_t size)
Definition at line 267 of file il2cpp-utils.hpp.
Referenced by __attribute__(), HookTracker::AddHook(), CreateFieldValue(), CreateFieldValueUnsafe(), CreateParam(), CreateParamUnsafe(), Logger::critical(), LoggerContextObject::critical(), Logger::debug(), LoggerContextObject::debug(), Logger::error(), LoggerContextObject::error(), EvalSwitch(), ExtractAddress(), ExtractAddressFixed(), ExtractTypes(), ExtractValues(), FindMethod(), Logger::info(), LoggerContextObject::info(), LoggerContextObject::log(), Logger::log(), MakeGeneric(), New(), Array< T >::New(), NewUnsafe(), HookTracker::RemoveHook(), requires(), RuntimeInvoke(), string_format(), string_vformat(), Logger::warning(), and LoggerContextObject::warning().
classesNamesToFieldsCache
std::unordered_map<std::pair<const Il2CppClass*, std::string>, FieldInfo*, hash_pair> il2cpp_utils::classesNamesToFieldsCache static
Definition at line 8 of file il2cpp-utils-fields.cpp.
Referenced by FindField().
classesNamesToMethodsCache
std::unordered_map<std::pair<const Il2CppClass*, std::pair<std::string, decltype(MethodInfo::parameters_count)> >, const MethodInfo*, hash_pair_3> il2cpp_utils::classesNamesToMethodsCache static
Definition at line 31 of file il2cpp-utils-methods.cpp.
Referenced by FindMethodUnsafe().
classesNamesToPropertiesCache
std::unordered_map<std::pair<const Il2CppClass*, std::string>, const PropertyInfo*, hash_pair> il2cpp_utils::classesNamesToPropertiesCache static
Definition at line 8 of file il2cpp-utils-properties.cpp.
Referenced by FindProperty().
classesNamesTypesToMethodsCache
std::unordered_map<std::pair<const Il2CppClass*, classesNamesTypesInnerPairType>, const MethodInfo*, hash_pair_3> il2cpp_utils::classesNamesTypesToMethodsCache static
Definition at line 33 of file il2cpp-utils-methods.cpp.
Referenced by FindMethod().
classNamesMethodsLock
std::mutex il2cpp_utils::classNamesMethodsLock
Definition at line 34 of file il2cpp-utils-methods.cpp.
Referenced by FindMethodUnsafe().
classPropertiesLock
std::mutex il2cpp_utils::classPropertiesLock static
Definition at line 9 of file il2cpp-utils-properties.cpp.
Referenced by FindProperty().
classToGenericClassMap
std::unordered_map<Il2CppClass*, std::map<std::string, Il2CppGenericClass*, doj::alphanum_less<std::string> > > il2cpp_utils::classToGenericClassMap static
Definition at line 145 of file il2cpp-utils-classes.cpp.
Referenced by BuildGenericsMap(), and LogClasses().
classTypesMethodsLock
std::mutex il2cpp_utils::classTypesMethodsLock
Definition at line 35 of file il2cpp-utils-methods.cpp.
Referenced by FindMethod().
delegates
std::unordered_set<void*> il2cpp_utils::delegates
Definition at line 290 of file il2cpp-utils.cpp.
Referenced by AddAllocatedDelegate(), ClearDelegate(), and ClearDelegates().
indent
int il2cpp_utils::indent = -1 static
Definition at line 12 of file il2cpp-utils-classes.cpp.
Referenced by analyzeBytes(), LogClass(), and LogClasses().
instance
R TArgs* il2cpp_utils::instance
Definition at line 267 of file il2cpp-utils.hpp.
Referenced by __AllocateUnsafe(), __attribute__(), FindField(), FindMethodUnsafe(), FindProperty(), GetFieldValue(), MakeDelegate(), SafePtr< T >::SafePointerWrapper::New(), requires(), RunGenericMethod(), RunMethod(), RunMethodUnsafe(), and SetFieldValue().
loggedClasses
std::unordered_set<Il2CppClass*> il2cpp_utils::loggedClasses
Definition at line 14 of file il2cpp-utils-classes.cpp.
Referenced by LogClass().
maxIndent
int il2cpp_utils::maxIndent static
Definition at line 13 of file il2cpp-utils-classes.cpp.
Referenced by LogClass(), and LogClasses().
nameFieldLock
std::mutex il2cpp_utils::nameFieldLock static
Definition at line 9 of file il2cpp-utils-fields.cpp.
Referenced by FindField().
nameHashLock
std::mutex il2cpp_utils::nameHashLock static
Definition at line 14 of file il2cpp-type-check.cpp.
Referenced by GetClassFromName().
namesToClassesCache
std::unordered_map<std::pair<std::string, std::string>, Il2CppClass*, hash_pair> il2cpp_utils::namesToClassesCache static
Definition at line 13 of file il2cpp-type-check.cpp.
Referenced by GetClassFromName().
R
R il2cpp_utils::R
Definition at line 267 of file il2cpp-utils.hpp.
Referenced by DecodeBitMasks(), and MakeDelegate().
typeLock
std::mutex il2cpp_utils::typeLock static
Definition at line 78 of file il2cpp-utils.cpp.
Referenced by TypeGetSimpleName().
typeMap
std::unordered_map<Il2CppClass*, const char*> il2cpp_utils::typeMap static
Definition at line 77 of file il2cpp-utils.cpp.
Referenced by TypeGetSimpleName().