BeatSaber-Hooks: shared/rapidjson/test/unittest/ostreamwrappertest.cpp File Reference
ostreamwrappertest.cpp File Reference
#include "unittest.h"
#include "rapidjson/ostreamwrapper.h"
#include "rapidjson/encodedstream.h"
#include "rapidjson/document.h"
#include <sstream>
#include <fstream>
Functions
template<typename StringStreamType >
static void TestStringStream ()
TEST (OStreamWrapper, ostringstream)
TEST (OStreamWrapper, stringstream)
TEST (OStreamWrapper, wostringstream)
TEST (OStreamWrapper, wstringstream)
TEST (OStreamWrapper, cout)
template<typename FileStreamType >
static void TestFileStream ()
TEST (OStreamWrapper, ofstream)
TEST (OStreamWrapper, fstream)
Function Documentation
TEST() [1/7]
TEST (OStreamWrapper , cout)
Definition at line 56 of file ostreamwrappertest.cpp.
{
     OStreamWrapper os(cout);
     const char* s = "Hello World!\n";
     while (*s)
         os.Put(*s++);
     os.Flush();
 }
References OStreamWrapper::Flush(), and OStreamWrapper::Put().
TEST() [2/7]
TEST (OStreamWrapper , fstream)
Definition at line 90 of file ostreamwrappertest.cpp.
{
     TestFileStream<fstream>();
 }
TEST() [3/7]
TEST (OStreamWrapper , ofstream)
Definition at line 86 of file ostreamwrappertest.cpp.
{
     TestFileStream<ofstream>();
 }
TEST() [4/7]
TEST (OStreamWrapper , ostringstream)
Definition at line 40 of file ostreamwrappertest.cpp.
{
     TestStringStream<ostringstream>();
 }
TEST() [5/7]
TEST (OStreamWrapper , stringstream)
Definition at line 44 of file ostreamwrappertest.cpp.
{
     TestStringStream<stringstream>();
 }
TEST() [6/7]
TEST (OStreamWrapper , wostringstream)
Definition at line 48 of file ostreamwrappertest.cpp.
{
     TestStringStream<wostringstream>();
 }
TEST() [7/7]
TEST (OStreamWrapper , wstringstream)
Definition at line 52 of file ostreamwrappertest.cpp.
{
     TestStringStream<wstringstream>();
 }
TestFileStream()
template<typename FileStreamType > static void TestFileStream () static
Definition at line 65 of file ostreamwrappertest.cpp.
{
     char filename[L_tmpnam];
     FILE* fp = TempFile(filename);
     fclose(fp);
     const char* s = "Hello World!\n";
     {
         FileStreamType ofs(filename, ios::out | ios::binary);
         BasicOStreamWrapper<FileStreamType> osw(ofs);
         for (const char* p = s; *p; p++)
             osw.Put(*p);
         osw.Flush();
     }
     fp = fopen(filename, "r");
     ASSERT_TRUE( fp != NULL );
     for (const char* p = s; *p; p++)
         EXPECT_EQ(*p, static_cast<char>(fgetc(fp)));
     fclose(fp);
 }
References rapidjson::BasicOStreamWrapper< StreamType >::Flush(), rapidjson::BasicOStreamWrapper< StreamType >::Put(), and TempFile().
TestStringStream()
template<typename StringStreamType > static void TestStringStream () static
Definition at line 27 of file ostreamwrappertest.cpp.
{
     typedef typename StringStreamType::char_type Ch;
     Ch s[] = { 'A', 'B', 'C', '\0' };
     StringStreamType oss(s);
     BasicOStreamWrapper<StringStreamType> os(oss);
     for (size_t i = 0; i < 3; i++)
         os.Put(s[i]);
     os.Flush();
     for (size_t i = 0; i < 3; i++)
         EXPECT_EQ(s[i], oss.str()[i]);
 }
References rapidjson::BasicOStreamWrapper< StreamType >::Flush(), and rapidjson::BasicOStreamWrapper< StreamType >::Put().