BeatSaber-Hooks: shared/rapidjson/test/perftest/schematest.cpp File Reference
schematest.cpp File Reference
#include "perftest.h"
#include "rapidjson/schema.h"
#include <ctime>
#include <string>
#include <vector>
Data Structures
class Schema
struct Schema::TestSuite
Macros
#define ARRAY_SIZE(a) sizeof(a) / sizeof(a[0])
Functions
template<typename Allocator >
static RAPIDJSON_DIAG_PUSH char * ReadFile (const char *filename, Allocator &allocator)
TEST_F (Schema, TestSuite)
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (a) sizeof(a) / sizeof(a[0])
Definition at line 10 of file schematest.cpp.
Function Documentation
ReadFile()
template<typename Allocator > static RAPIDJSON_DIAG_PUSH char* ReadFile (const char * filename, Allocator & allocator) static
Definition at line 20 of file schematest.cpp.
{
     const char *paths[] = {
         "",
         "bin/",
         "../bin/",
         "../../bin/",
         "../../../bin/"
     };
     char buffer[1024];
     FILE *fp = 0;
     for (size_t i = 0; i < sizeof(paths) / sizeof(paths[0]); i++) {
         sprintf(buffer, "%s%s", paths[i], filename);
         fp = fopen(buffer, "rb");
         if (fp)
             break;
     }
     if (!fp)
         return 0;
     fseek(fp, 0, SEEK_END);
     size_t length = static_cast<size_t>(ftell(fp));
     fseek(fp, 0, SEEK_SET);
     char* json = reinterpret_cast<char*>(allocator.Malloc(length + 1));
     size_t readLength = fread(json, 1, length, fp);
     json[readLength] = '\0';
     fclose(fp);
     return json;
 }
References json.
Referenced by EncodedStreamTest::CompareBufferFile(), EncodedStreamTest::CompareFile(), Schema::SetUp(), EncodedStreamTest::SetUp(), EncodedStreamTest::TestAutoUTFInputStream(), and EncodedStreamTest::TestEncodedInputStream().
TEST_F()
TEST_F (Schema , TestSuite)
Definition at line 198 of file schematest.cpp.
{
     char validatorBuffer[65536];
     MemoryPoolAllocator<> validatorAllocator(validatorBuffer, sizeof(validatorBuffer));
     const int trialCount = 100000;
     int testCount = 0;
     clock_t start = clock();
     for (int i = 0; i < trialCount; i++) {
         for (TestSuiteList::const_iterator itr = testSuites.begin(); itr != testSuites.end(); ++itr) {
             const TestSuite& ts = **itr;
             GenericSchemaValidator<SchemaDocument, BaseReaderHandler<UTF8<> >, MemoryPoolAllocator<> >  validator(*ts.schema, &validatorAllocator);
             for (DocumentList::const_iterator testItr = ts.tests.begin(); testItr != ts.tests.end(); ++testItr) {
                 validator.Reset();
                 (*testItr)->Accept(validator);
                 testCount++;
             }
             validatorAllocator.Clear();
         }
     }
     clock_t end = clock();
     double duration = double(end - start) / CLOCKS_PER_SEC;
     printf("%d trials in %f s -> %f trials per sec\n", trialCount, duration, trialCount / duration);
     printf("%d tests per trial\n", testCount / trialCount);
 }
References rapidjson::MemoryPoolAllocator< BaseAllocator >::Clear(), and rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().