BeatSaber-Hooks: shared/rapidjson/example/pretty/pretty.cpp File Reference
pretty.cpp File Reference
#include "rapidjson/reader.h"
#include "rapidjson/prettywriter.h"
#include "rapidjson/filereadstream.h"
#include "rapidjson/filewritestream.h"
#include "rapidjson/error/en.h"
Functions
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 12 of file pretty.cpp.
{
     // Prepare reader and input stream.
     Reader reader;
     char readBuffer[65536];
     FileReadStream is(stdin, readBuffer, sizeof(readBuffer));
     // Prepare writer and output stream.
     char writeBuffer[65536];
     FileWriteStream os(stdout, writeBuffer, sizeof(writeBuffer));
     PrettyWriter<FileWriteStream> writer(os);
     // JSON reader parse from the input stream and let writer generate the output.
     if (!reader.Parse<kParseValidateEncodingFlag>(is, writer)) {
         fprintf(stderr, "\nError(%u): %s\n", static_cast<unsigned>(reader.GetErrorOffset()), GetParseError_En(reader.GetParseErrorCode()));
         return 1;
     }
     return 0;
 }
References rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), rapidjson::GetParseError_En(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), rapidjson::kParseValidateEncodingFlag, and rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().