BeatSaber-Hooks: shared/rapidjson/example/serialize/serialize.cpp File Reference
serialize.cpp File Reference
#include "rapidjson/prettywriter.h"
#include <cstdio>
#include <string>
#include <vector>
Data Structures
class Person
class Education
class Dependent
class Employee
Functions
int main (int, char *[])
Function Documentation
main()
int main (int , char * [])
Definition at line 153 of file serialize.cpp.
{
     std::vector<Employee> employees;
     employees.push_back(Employee("Milo YIP", 34, true));
     employees.back().AddDependent(Dependent("Lua YIP", 3, new Education("Happy Kindergarten", 3.5)));
     employees.back().AddDependent(Dependent("Mio YIP", 1));
     employees.push_back(Employee("Percy TSE", 30, false));
     StringBuffer sb;
     PrettyWriter<StringBuffer> writer(sb);
     writer.StartArray();
     for (std::vector<Employee>::const_iterator employeeItr = employees.begin(); employeeItr != employees.end(); ++employeeItr)
         employeeItr->Serialize(writer);
     writer.EndArray();
     puts(sb.GetString());
     return 0;
 }
References rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray().