BeatSaber-Hooks: shared/rapidjson/example/simplepullreader/simplepullreader.cpp File Reference
simplepullreader.cpp File Reference
#include "rapidjson/reader.h"
#include <iostream>
#include <sstream>
Data Structures
struct MyHandler
Functions
template<typename T >
std::string stringify (T x)
int main ()
Function Documentation
main()
int main ()
Definition at line 40 of file simplepullreader.cpp.
            {
     const char json[] = " { \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] } ";
     MyHandler handler;
     Reader reader;
     StringStream ss(json);
     reader.IterativeParseInit();
     while (!reader.IterativeParseComplete()) {
         reader.IterativeParseNext<kParseDefaultFlags>(ss, handler);
         cout << handler.type << handler.data << endl;
     }
     return 0;
 }
References MyHandler::data, rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), rapidjson::kParseDefaultFlags, and MyHandler::type.
stringify()
template<typename T > std::string stringify (T x)
Definition at line 9 of file simplepullreader.cpp.
{
     std::stringstream ss;
     ss << x;
     return ss.str();
 }
Referenced by MyHandler::Double(), MyHandler::EndArray(), MyHandler::EndObject(), MyHandler::Int(), MyHandler::Int64(), MyHandler::Uint(), and MyHandler::Uint64().