BeatSaber-Hooks: shared/rapidjson/example/simplewriter/simplewriter.cpp File Reference
simplewriter.cpp File Reference
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 8 of file simplewriter.cpp.
            {
     StringBuffer s;
     Writer<StringBuffer> writer(s);
     writer.StartObject();               // Between StartObject()/EndObject(),
     writer.Key("hello");                // output a key,
     writer.String("world");             // follow by a value.
     writer.Key("t");
     writer.Bool(true);
     writer.Key("f");
     writer.Bool(false);
     writer.Key("n");
     writer.Null();
     writer.Key("i");
     writer.Uint(123);
     writer.Key("pi");
     writer.Double(3.1416);
     writer.Key("a");
     writer.StartArray();                // Between StartArray()/EndArray(),
     for (unsigned i = 0; i < 4; i++)
         writer.Uint(i);                 // all values are elements of the array.
     writer.EndArray();
     writer.EndObject();
     // {"hello":"world","t":true,"f":false,"n":null,"i":123,"pi":3.1416,"a":[0,1,2,3]}
     cout << s.GetString() << endl;
     return 0;
 }
References rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint().