BeatSaber-Hooks: ParseState Struct Reference
ParseState Struct Reference
#include <instruction-parsing.hpp>
Public Member Functions
ParseState ()
Data Fields
std::array< std::bitset< Register::TOTAL_NUMBER >, Register::TOTAL_NUMBER > dependencyMap
std::unordered_map< const int32_t *, InstructionTree * > codeToInstTree
std::unordered_map< const int32_t *, decltype(dependencyMap)> functionCandidates
std::unordered_map< const int32_t *, decltype(dependencyMap)> otherJumps
std::stack< std::pair< InstructionTree *, decltype(dependencyMap)> > frontier
Detailed Description
Definition at line 223 of file instruction-parsing.hpp.
Constructor & Destructor Documentation
ParseState()
ParseState::ParseState () inline
Definition at line 231 of file instruction-parsing.hpp.
                  {
         for (uint_fast8_t i = 0; i < dependencyMap.size(); i++) {
References dependencyMap.
Field Documentation
codeToInstTree
std::unordered_map<const int32_t*, InstructionTree*> ParseState::codeToInstTree
Definition at line 226 of file instruction-parsing.hpp.
Referenced by FindOrCreateInstruction().
dependencyMap
std::array<std::bitset<Register::TOTAL_NUMBER>, Register::TOTAL_NUMBER> ParseState::dependencyMap
Definition at line 225 of file instruction-parsing.hpp.
Referenced by AssemblyFunction::AssemblyFunction(), FindOrCreateInstruction(), ParseState(), InstructionTree::PopulateChildren(), and ProcessRegisterDependencies().
frontier
std::stack<std::pair<InstructionTree*, decltype(dependencyMap)> > ParseState::frontier
Definition at line 229 of file instruction-parsing.hpp.
Referenced by AssemblyFunction::AssemblyFunction(), and FindOrCreateInstruction().
functionCandidates
std::unordered_map<const int32_t*, decltype(dependencyMap)> ParseState::functionCandidates
Definition at line 227 of file instruction-parsing.hpp.
Referenced by InstructionTree::PopulateChildren().
otherJumps
std::unordered_map<const int32_t*, decltype(dependencyMap)> ParseState::otherJumps
Definition at line 228 of file instruction-parsing.hpp.
Referenced by InstructionTree::PopulateChildren().
The documentation for this struct was generated from the following file:
shared/utils/instruction-parsing.hpp