BeatSaber-Hooks: Array< T > Struct Template Reference
Array< T > Struct Template Reference
#include <typedefs-array.hpp>
Public Member Functions
ALIGN_TYPE (8) T values[IL2CPP_ZERO_LEN_ARRAY]
il2cpp_array_size_t Length () const
T & operator[] (size_t i)
const T & operator[] (size_t i) const
T & get (size_t i)
Get a given index, performs bound checking and throws std::runtime_error on failure.
const T & get (size_t i) const
Get a given index, performs bound checking and throws std::runtime_error on failure.
std::optional< WrapperRef< T > > try_get (size_t i)
Tries to get a given index, performs bound checking and returns a std::nullopt on failure.
std::optional< WrapperRef< const T > > try_get (size_t i) const
Tries to get a given index, performs bound checking and returns a std::nullopt on failure.
Il2CppObject * GetEnumerator ()
bool Contains (T item)
void CopyTo (::Array< T > *array, int arrayIndex)
int IndexOf (T item)
void copy_to (std::vector< T > &vec) const
Copies the array to the provided vector reference of same type.
std::span< T > ref_to ()
Provides a reference span of the held data within this array. The span should NOT outlive this instance.
const std::span< T > ref_to () const
Provides a reference span of the held data within this array. The span should NOT outlive this instance.
Static Public Member Functions
static Array< T > * New (std::initializer_list< T > vals)
static Array< T > * NewLength (il2cpp_array_size_t size)
template<typename... TArgs>
static Array< T > * New (TArgs &&... args)
Detailed Description
template<class T>
struct Array< T >
Definition at line 104 of file typedefs-array.hpp.
Member Function Documentation
ALIGN_TYPE()
template<class T > Array< T >::ALIGN_TYPE (8)
Contains()
template<class T > bool Array< T >::Contains (T item) inline
Definition at line 190 of file typedefs-array.hpp.
{
         // TODO: find a better way around the existence of 2 methods with this name (the 2nd not being generic at all)
         static auto* method = CRASH_UNLESS(il2cpp_utils::FindMethodUnsafe(
             this, "System.Collections.Generic.ICollection`1.Contains", 1));
         return CRASH_UNLESS(il2cpp_utils::RunMethodUnsafe<bool>(this, method, item));
     }
References il2cpp_utils::FindMethodUnsafe().
copy_to()
template<class T > void Array< T >::copy_to (std::vector< T > & vec) const inline
Copies the array to the provided vector reference of same type.
Parameters
vec The vector to copy to.
Definition at line 207 of file typedefs-array.hpp.
{
         vec.assign(values, values + Length());
     }
CopyTo()
template<class T > void Array< T >::CopyTo (::Array< T > * array, int arrayIndex) inline
Definition at line 196 of file typedefs-array.hpp.
{
         static auto* method = CRASH_UNLESS(il2cpp_utils::FindMethodUnsafe(
             this, "System.Collections.Generic.ICollection`1.CopyTo", 2));
         CRASH_UNLESS(il2cpp_utils::RunMethodUnsafe(this, method, array, arrayIndex));
     }
References il2cpp_utils::FindMethodUnsafe(), and il2cpp_utils::RunMethodUnsafe().
get() [1/2]
template<class T > T& Array< T >::get (size_t i) inline
Get a given index, performs bound checking and throws std::runtime_error on failure.
Parameters
i The index to get.
Returns
The reference to the item.
Definition at line 126 of file typedefs-array.hpp.
                      {
         THROW_UNLESS(i < Length() && i >= 0);
         return values[i];
     }
get() [2/2]
template<class T > const T& Array< T >::get (size_t i) const inline
Get a given index, performs bound checking and throws std::runtime_error on failure.
Parameters
i The index to get.
Returns
The const reference to the item.
Definition at line 133 of file typedefs-array.hpp.
{
         THROW_UNLESS(i < Length() && i >= 0);
         return values[i];
     }
GetEnumerator()
template<class T > Il2CppObject* Array< T >::GetEnumerator () inline
Definition at line 178 of file typedefs-array.hpp.
{
   #endif
         static auto* method = CRASH_UNLESS(il2cpp_utils::FindMethodUnsafe(
             this, "System.Collections.Generic.IEnumerable`1.GetEnumerator", 0));
       #ifdef HAS_CODEGEN
         return CRASH_UNLESS(il2cpp_utils::RunMethodUnsafe<System::Collections::Generic::IEnumerator_1<T>*>(
       #else
         return CRASH_UNLESS(il2cpp_utils::RunMethodUnsafe(
       #endif
             this, method));
     }
References il2cpp_utils::FindMethodUnsafe(), and il2cpp_utils::RunMethodUnsafe().
IndexOf()
template<class T > int Array< T >::IndexOf (T item) inline
Definition at line 201 of file typedefs-array.hpp.
{
         static auto* method = CRASH_UNLESS(il2cpp_utils::FindMethodUnsafe(this, "System.Collections.Generic.IList`1.IndexOf", 1));
         return CRASH_UNLESS(il2cpp_utils::RunMethodUnsafe<int>(this, method, item));
     }
References il2cpp_utils::FindMethodUnsafe().
Length()
template<class T > il2cpp_array_size_t Array< T >::Length () const inline
Definition at line 110 of file typedefs-array.hpp.
{
         if (bounds) {
             return bounds->length;
         }
         return max_length;
     }
New() [1/2]
template<class T > static Array<T>* Array< T >::New (std::initializer_list< T > vals) inline static
Definition at line 156 of file typedefs-array.hpp.
{
         il2cpp_functions::Init();
         auto* arr = reinterpret_cast<Array<T>*>(il2cpp_functions::array_new(
             il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get(), vals.size()));
         memcpy(arr->values, vals.begin(), sizeof(T)*vals.size());
         return arr;
     }
References il2cpp_functions::array_new, il2cpp_functions::Init(), and T.
New() [2/2]
template<class T > template<typename... TArgs> static Array<T>* Array< T >::New (TArgs &&... args) inline static
Definition at line 171 of file typedefs-array.hpp.
{
         return New({args...});
     }
References il2cpp_utils::args, and il2cpp_utils::New().
NewLength()
template<class T > static Array<T>* Array< T >::NewLength (il2cpp_array_size_t size) inline static
Definition at line 164 of file typedefs-array.hpp.
{
         il2cpp_functions::Init();
         return reinterpret_cast<Array<T>*>(il2cpp_functions::array_new(
             il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class<T>::get(), size));
     }
References il2cpp_functions::array_new, and il2cpp_functions::Init().
operator[]() [1/2]
template<class T > T& Array< T >::operator[] (size_t i) inline
Definition at line 116 of file typedefs-array.hpp.
{
         return values[i];
     }
operator[]() [2/2]
template<class T > const T& Array< T >::operator[] (size_t i) const inline
Definition at line 119 of file typedefs-array.hpp.
{
         return values[i];
     }
ref_to() [1/2]
template<class T > std::span<T> Array< T >::ref_to () inline
Provides a reference span of the held data within this array. The span should NOT outlive this instance.
Returns
The created span.
Definition at line 212 of file typedefs-array.hpp.
{
         return std::span(values, Length());
     }
ref_to() [2/2]
template<class T > const std::span<T> Array< T >::ref_to () const inline
Provides a reference span of the held data within this array. The span should NOT outlive this instance.
Returns
The created span.
Definition at line 217 of file typedefs-array.hpp.
{
         return std::span(const_cast<T*>(values), Length());
     }
References T.
try_get() [1/2]
template<class T > std::optional<WrapperRef<T> > Array< T >::try_get (size_t i) inline
Tries to get a given index, performs bound checking and returns a std::nullopt on failure.
Parameters
i The index to get.
Returns
The WrapperRef<T> to the item, mostly considered to be a T&.
Definition at line 140 of file typedefs-array.hpp.
{
         if (i >= Length() || i < 0) {
             return std::nullopt;
         }
         return WrapperRef(values[i]);
     }
try_get() [2/2]
template<class T > std::optional<WrapperRef<const T> > Array< T >::try_get (size_t i) const inline
Tries to get a given index, performs bound checking and returns a std::nullopt on failure.
Parameters
i The index to get.
Returns
The WrapperRef<const T> to the item, mostly considered to be a const T&.
Definition at line 149 of file typedefs-array.hpp.
{
         if (i >= Length() || i < 0) {
             return std::nullopt;
         }
         return WrapperRef(values[i]);
     }
The documentation for this struct was generated from the following file:
shared/utils/typedefs-array.hpp