BeatSaber-Hooks: Counter Struct Reference
Counter Struct Reference
A thread-safe, static type that holds a mapping from addresses to reference counts.
#include <typedefs-wrappers.hpp>
Static Public Member Functions
static void add (void *addr)
Adds to the reference count of an address. If the address does not exist, initializes a new entry for it to 1.
static void remove (void *addr)
Decreases the reference count of an address. If the address has 1 or fewer references, erases it.
static size_t get (void *addr)
Gets the reference count of an address, or 0 if no such address exists.
Static Private Attributes
static std::unordered_map< void *, size_t > addrRefCount
static std::shared_mutex mutex
Detailed Description
A thread-safe, static type that holds a mapping from addresses to reference counts.
Definition at line 30 of file typedefs-wrappers.hpp.
Member Function Documentation
add()
static void Counter::add (void * addr) inline static
Adds to the reference count of an address. If the address does not exist, initializes a new entry for it to 1.
Parameters
addr The address to add.
Definition at line 33 of file typedefs-wrappers.hpp.
{
         std::unique_lock lock(mutex);
         auto itr = addrRefCount.find(addr);
         if (itr != addrRefCount.end()) {
             ++itr->second;
         } else {
             addrRefCount.emplace(addr, 1);
         }
     }
References addrRefCount, and mutex.
Referenced by CountPointer< T >::CountPointer(), and CountPointer< T >::emplace().
get()
static size_t Counter::get (void * addr) inline static
Gets the reference count of an address, or 0 if no such address exists.
Parameters
addr The address to get the count of.
Returns
The reference count of the provided address.
Definition at line 56 of file typedefs-wrappers.hpp.
{
         std::shared_lock lock(mutex);
         auto itr = addrRefCount.find(addr);
         if (itr != addrRefCount.end()) {
             return itr->second;
         } else {
             return 0;
         }
     }
References addrRefCount, and mutex.
Referenced by CountPointer< T >::count().
remove()
static void Counter::remove (void * addr) inline static
Decreases the reference count of an address. If the address has 1 or fewer references, erases it.
Parameters
addr The address to decrease.
Definition at line 44 of file typedefs-wrappers.hpp.
{
         std::unique_lock lock(mutex);
         auto itr = addrRefCount.find(addr);
         if (itr != addrRefCount.end() && itr->second > 1) {
             --itr->second;
         } else {
             addrRefCount.erase(itr);
         }
     }
References addrRefCount, and mutex.
Referenced by CountPointer< T >::emplace(), and CountPointer< T >::~CountPointer().
Field Documentation
addrRefCount
std::unordered_map< void *, size_t > Counter::addrRefCount static private
Definition at line 66 of file typedefs-wrappers.hpp.
Referenced by add(), get(), and remove().
mutex
std::shared_mutex Counter::mutex static private
Definition at line 67 of file typedefs-wrappers.hpp.
Referenced by add(), get(), and remove().
The documentation for this struct was generated from the following files:
shared/utils/typedefs-wrappers.hpp
src/utils/typedefs-wrapper.cpp