BeatSaber-Hooks: gnu_string Struct Reference
gnu_string Struct Reference
#include <il2cpp-functions.hpp>
Public Member Functions
const char * _M_data () const
const _Rep * _M_rep () const
const char * c_str () const
int length () const
Data Fields
const char * _M_p
const char padding [9]
Detailed Description
Definition at line 27 of file il2cpp-functions.hpp.
Member Function Documentation
_M_data()
const char* gnu_string::_M_data () const inline
Definition at line 32 of file il2cpp-functions.hpp.
{
         return _M_p;
     }
References _M_p.
Referenced by _M_rep().
_M_rep()
const _Rep* gnu_string::_M_rep () const inline
Definition at line 36 of file il2cpp-functions.hpp.
{
         return &((reinterpret_cast<const _Rep *>(_M_data()))[-1]);
     }
References _M_data().
Referenced by length().
c_str()
const char* gnu_string::c_str () const inline
Definition at line 40 of file il2cpp-functions.hpp.
{
         return _M_p;
     }
References _M_p.
length()
int gnu_string::length () const inline
Definition at line 44 of file il2cpp-functions.hpp.
{
         return _M_rep()->_M_length;
     }
References _Rep::_M_length, and _M_rep().
Field Documentation
_M_p
const char* gnu_string::_M_p
Definition at line 28 of file il2cpp-functions.hpp.
Referenced by _M_data(), and c_str().
padding
const char gnu_string::padding[9]
Definition at line 30 of file il2cpp-functions.hpp.
The documentation for this struct was generated from the following file:
shared/utils/il2cpp-functions.hpp