BeatSaber-Hooks: il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T > Struct Template Reference
il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T > Struct Template Reference
#include <il2cpp-type-check.hpp>
Static Public Member Functions
static Il2CppClass * get ([[maybe_unused]] T arg)
Detailed Description
template<typename T>
struct il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T >
Definition at line 133 of file il2cpp-type-check.hpp.
Member Function Documentation
get()
template<typename T > static Il2CppClass* il2cpp_utils::il2cpp_type_check::il2cpp_arg_class< T >::get ([[maybe_unused] ] T arg) inline static
Definition at line 134 of file il2cpp-type-check.hpp.
{
                 if constexpr (has_get<il2cpp_no_arg_class<T>>) {
                     return il2cpp_no_arg_class<T>::get();
                 }
                 return nullptr;
             }
Referenced by il2cpp_utils::il2cpp_type_check::il2cpp_arg_type< const T & >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_type< T && >::get(), il2cpp_utils::il2cpp_type_check::il2cpp_arg_type< T & >::get(), and il2cpp_utils::il2cpp_type_check::il2cpp_arg_type< T * >::get().
The documentation for this struct was generated from the following file:
shared/utils/il2cpp-type-check.hpp