BeatSaber-Hooks: HookTracker Struct Reference
HookTracker Struct Reference
#include <hook-tracker.hpp>
Static Public Member Functions
static void AddHook (HookInfo info) noexcept
Adds a HookInfo to be tracked.
template<typename... TArgs>
static void AddHook (TArgs &&... args) noexcept
Calls AddHook.
static void RemoveHook (HookInfo info) noexcept
Stops tracking the provided HookInfo.
template<typename... TArgs>
static void RemoveHook (TArgs &&... args) noexcept
Calls RemoveHook.
static void RemoveHooks () noexcept
Stop tracking all hooks.
static void RemoveHooks (const void *const location) noexcept
Stop tracking all hooks at a certain offset.
static void CombineHooks () noexcept
Combines all HookTrackers from all bs-hook libraries together.
static bool IsHooked (const void *const location) noexcept
Checks to see if there are any hooks installed at the offset provided. Returns true if at least one hook is installed, false otherwise.
static const std::list< HookInfo > GetHooks (const void *const location) noexcept
Returns any hooks that access this location, or an empty list if there are none.
static const std::unordered_map< const void *, std::list< HookInfo > > * GetHooks () noexcept
Returns all hooks.
template<typename T >
static const void * GetOrig (T location) noexcept
Returns the original location of a function that may or may not be hooked. If the function is not hooked, it returns the input. If the function is hooked, it returns the first installed hook's original location.
static const void * InstructionGetOrig (const void *const location) noexcept
Returns the original location of a function that may or may not be hooked, but confirms it with instruction parsing. If the function is not hooked, it returns the input. If the function is hooked (instruction check), it returns the first installed hooks original location. Note that this should only be called on functions that don't have matching instructions to hook installations, otherwise it may trace too far.
static bool InstructionIsHooked (const void *const location) noexcept
Checks to see if there is a hook installed (via instruction parsing) at the offset provided. Returns true if the first instructions at this location match the instructions created by a hook, implying a hook has been installed. Note that this should only be called on functions that don't have matching instructions to hook installations, otherwise it may false positive.
Static Private Member Functions
static const void * GetOrigInternal (const void *const) noexcept
Static Private Attributes
static std::unordered_map< const void *, std::list< HookInfo > > hooks
Detailed Description
Definition at line 20 of file hook-tracker.hpp.
Member Function Documentation
AddHook() [1/2]
void HookTracker::AddHook (HookInfo info) static noexcept
Adds a HookInfo to be tracked.
Parameters
info The HookInfo to track.
Definition at line 6 of file hook-tracker.cpp.
{
     auto itr = hooks.find(info.destination);
     if (itr == hooks.end()) {
         hooks.emplace(info.destination, std::list<HookInfo>()).first->second.emplace_back(info);
     } else {
         itr->second.emplace_back(info);
     }
 }
References info.
Referenced by AddHook().
AddHook() [2/2]
template<typename... TArgs> static void HookTracker::AddHook (TArgs &&... args) inline static noexcept
Calls AddHook.
Definition at line 26 of file hook-tracker.hpp.
{
         AddHook(HookInfo(std::forward<TArgs>(args)...));
     }
References AddHook(), and il2cpp_utils::args.
CombineHooks()
void HookTracker::CombineHooks () static noexcept
Combines all HookTrackers from all bs-hook libraries together.
Definition at line 76 of file hook-tracker.cpp.
{
     static auto logger = Logger::get().WithContext("HookTracker");
     auto libsFolder = string_format(LIBS_FILE_PATH, Modloader::getApplicationId().c_str());
     auto tmpPath = string_format(MOD_TEMP_PATH_FMT, Modloader::getApplicationId().c_str());
     DIR* dir = opendir(libsFolder.c_str());
     if (dir == nullptr) {
         logger.warning("Failed to open libs folder! At path: %s", libsFolder.c_str());
         return;
     }
     struct dirent* dp;
     while ((dp = readdir(dir)) != NULL) {
         if (std::string(dp->d_name).starts_with("libbeatsaber-hook")) {
             // Find and combine
             auto path = tmpPath + dp->d_name;
             auto* image = dlopen(path.c_str(), RTLD_LAZY | RTLD_LOCAL);
             auto* err = dlerror();
             if (image == nullptr || err != nullptr) {
                 logger.warning("Failed to dlopen: %s! %s", path.c_str(), err);
                 continue;
             }
             // Open the library, look for a function called: __HOOKTRACKER_GET_HOOKS
             auto* getter = dlsym(image, "__HOOKTRACKER_GET_HOOKS");
             if (getter == nullptr) {
                 logger.warning("Failed to find symbol: %s", "__HOOKTRACKER_GET_HOOKS");
                 continue;
             }
             // Of course, if the function returns something that is of a different HookInfo type, for example, this may cause all sorts of pain.
             auto otherHooks = *reinterpret_cast<const std::unordered_map<const void*, std::list<HookInfo>>*(*)()>(getter)();
             for (auto itr : otherHooks) {
                 // For each void*, find our match
                 auto match = hooks.find(itr.first);
                 if (match == hooks.end()) {
                     hooks.insert({itr.first, itr.second});
                 } else {
                     // Add only unique items
                     for (auto item : itr.second) {
                         bool unique = true;
                         for (auto& existing : match->second) {
                             if (existing == item) {
                                 unique = false;
                                 break;
                             }
                         }
                         if (unique) {
                             match->second.push_back(item);
                         }
                     }
                 }
             }
             dlclose(image);
         }
     }
 }
References Logger::get(), Modloader::getApplicationId(), hooks, LIBS_FILE_PATH, MOD_TEMP_PATH_FMT, string_format(), and Logger::WithContext().
GetHooks() [1/2]
const std::unordered_map< const void *, std::list< HookInfo > > * HookTracker::GetHooks () static noexcept
Returns all hooks.
Returns
The installed hooks.
Definition at line 55 of file hook-tracker.cpp.
{
     return &hooks;
 }
References hooks.
Referenced by __HOOKTRACKER_GET_HOOKS().
GetHooks() [2/2]
const std::list< HookInfo > HookTracker::GetHooks (const void *const location) static noexcept
Returns any hooks that access this location, or an empty list if there are none.
Parameters
location The offset to check for.
Returns
An std::list<HookInfo> of hooks.
Definition at line 46 of file hook-tracker.cpp.
{
     CombineHooks();
     auto itr = hooks.find(location);
     if (itr != hooks.end()) {
         return itr->second;
     }
     return std::list<HookInfo>();
 }
References location.
GetOrig()
template<typename T > static const void* HookTracker::GetOrig (T location) inline static noexcept
Returns the original location of a function that may or may not be hooked. If the function is not hooked, it returns the input. If the function is hooked, it returns the first installed hook's original location.
Parameters
location The offset to get the original function for.
Returns
The returned address.
Definition at line 62 of file hook-tracker.hpp.
{
         return GetOrigInternal(reinterpret_cast<void*>(location));
     }
References GetOrigInternal(), and location.
Referenced by il2cpp_functions::Init().
GetOrigInternal()
const void * HookTracker::GetOrigInternal (const void * const location) static private noexcept
Definition at line 59 of file hook-tracker.cpp.
{
     CombineHooks();
     auto itr = hooks.find(location);
     if (itr != hooks.end() && itr->second.size() > 0) {
         return itr->second.front().orig;
     }
     return location;
 }
References location.
Referenced by GetOrig().
InstructionGetOrig()
const void * HookTracker::InstructionGetOrig (const void *const location) static noexcept
Returns the original location of a function that may or may not be hooked, but confirms it with instruction parsing. If the function is not hooked, it returns the input. If the function is hooked (instruction check), it returns the first installed hooks original location. Note that this should only be called on functions that don't have matching instructions to hook installations, otherwise it may trace too far.
Parameters
location The offset to get the original function for.
Returns
The returned address.
Definition at line 171 of file hook-tracker.cpp.
{
     Instruction inst(reinterpret_cast<const int32_t*>(location));
     if (inst.isNOP()) {
         inst = Instruction(reinterpret_cast<const int32_t*>(location) + 1);
     }
     if (inst.isLoad() && inst.size == 8 && inst.label == inst.addr + 2) {
         // For hooks, label will always be 8 past address of function.
         // This label points to the trampoline.
         // However, this isn't necessarily all we need to do, since we could have MULTIPLE functions hooking this.
         // So, we will need to recurse here as well.
         return HookTracker::InstructionGetOrig(*reinterpret_cast<const void* const*>(*inst.label));
     }
     // If we aren't any of these things, we exit out.
     return location;
 }
References Instruction::addr, Instruction::isLoad(), Instruction::isNOP(), Instruction::label, location, and Instruction::size.
InstructionIsHooked()
bool HookTracker::InstructionIsHooked (const void *const location) static noexcept
Checks to see if there is a hook installed (via instruction parsing) at the offset provided. Returns true if the first instructions at this location match the instructions created by a hook, implying a hook has been installed. Note that this should only be called on functions that don't have matching instructions to hook installations, otherwise it may false positive.
Parameters
location The offset to check for.
Returns
Whether there exists an instruction hook acting on this location.
Definition at line 187 of file hook-tracker.cpp.
{
     // First actual instruction should be an LDR (literal) PC + 0x8
     Instruction inst(reinterpret_cast<const int32_t*>(location));
     if (inst.isNOP()) {
         inst = Instruction(reinterpret_cast<const int32_t*>(location) + 1);
     }
     return inst.isLoad() && inst.size == 8 && inst.label == inst.addr + 2;
     // // The third instruction should be a BR x17
     // Instruction instr(reinterpret_cast<const int32_t *>(location) + 2);
     // return instr.isIndirectBranch() && instr.numSourceRegisters == 1 && instr.Rs[0] == 17;
 }
References Instruction::addr, Instruction::isLoad(), Instruction::isNOP(), Instruction::label, location, and Instruction::size.
IsHooked()
bool HookTracker::IsHooked (const void *const location) static noexcept
Checks to see if there are any hooks installed at the offset provided. Returns true if at least one hook is installed, false otherwise.
Parameters
location The offset to check for.
Returns
Whether there exists at least one hook acting on this location.
Definition at line 37 of file hook-tracker.cpp.
{
     CombineHooks();
     auto itr = hooks.find(location);
     if (itr != hooks.end()) {
         return itr->second.size() > 0;
     }
     return false;
 }
References location.
RemoveHook() [1/2]
void HookTracker::RemoveHook (HookInfo info) static noexcept
Stops tracking the provided HookInfo.
Parameters
info The HookInfo to stop tracking.
Definition at line 15 of file hook-tracker.cpp.
{
     auto itr = hooks.find(info.destination);
     if (itr != hooks.end()) {
         for (auto& item : itr->second) {
             if (item == info) {
                 itr->second.remove(item);
             }
         }
     }
 }
References info.
Referenced by RemoveHook().
RemoveHook() [2/2]
template<typename... TArgs> static void HookTracker::RemoveHook (TArgs &&... args) inline static noexcept
Calls RemoveHook.
Definition at line 34 of file hook-tracker.hpp.
{
         RemoveHook(HookInfo(std::forward<TArgs>(args)...));
     }
References il2cpp_utils::args, and RemoveHook().
RemoveHooks() [1/2]
void HookTracker::RemoveHooks () static noexcept
Stop tracking all hooks.
Definition at line 26 of file hook-tracker.cpp.
{
     hooks.clear();
 }
References hooks.
RemoveHooks() [2/2]
void HookTracker::RemoveHooks (const void *const location) static noexcept
Stop tracking all hooks at a certain offset.
Parameters
location The offset to check for any installed hooks.
Definition at line 30 of file hook-tracker.cpp.
{
     auto itr = hooks.find(location);
     if (itr != hooks.end()) {
         hooks.erase(itr);
     }
 }
References location.
Field Documentation
hooks
std::unordered_map< const void *, std::list< HookInfo > > HookTracker::hooks static private
Definition at line 79 of file hook-tracker.hpp.
Referenced by CombineHooks(), GetHooks(), and RemoveHooks().
The documentation for this struct was generated from the following files:
shared/utils/hook-tracker.hpp
src/utils/hook-tracker.cpp