BeatSaber-Hooks: CountPointer< T > Struct Template Reference
CountPointer< T > Struct Template Reference
Represents a smart pointer that has a reference count, which does NOT destroy the held instance on refcount reaching 0.
#include <typedefs-wrappers.hpp>
Public Member Functions
CountPointer ()
Default constructor for Count Pointer, defaults to a nullptr, with 0 references.
CountPointer (T *p)
Construct a count pointer from the provided pointer, adding to the reference count (if non-null) for the provided pointer.
CountPointer (const CountPointer< T > &other)
Copy constructor, copies and adds to the reference count for the held non-null pointer.
CountPointer (CountPointer &&other)=default
Move constructor is default, moves the pointer and keeps the reference count the same.
~CountPointer ()
Destructor, decreases the ref count for the held non-null pointer.
size_t count () const
Gets the reference count held by this pointer.
void emplace (T *val)
Emplaces a new pointer into the shared pointer, decreasing the existing ref count as necessary.
CountPointer & operator= (T *val)
Assignment operator.
T & operator* () noexcept
Dereference operator.
const T & operator* () const noexcept
T * operator-> () noexcept
T *const operator-> () const noexcept
constexpr operator bool () const noexcept
template<class U >
CountPointer< U > cast () const
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may throw TypeCastException or crash. See try_cast for a version that does not.
template<class U >
std::optional< CountPointer< U > > try_cast () const noexcept
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
constexpr T *const __internal_get () const noexcept
Get the raw pointer. Should ALMOST NEVER BE USED, UNLESS SCOPE GUARANTEES IT DIES BEFORE THIS INSTANCE DOES!
Private Attributes
T * ptr
Detailed Description
template<class T>
struct CountPointer< T >
Represents a smart pointer that has a reference count, which does NOT destroy the held instance on refcount reaching 0.
Template Parameters
T The type to wrap as a pointer.
Definition at line 76 of file typedefs-wrappers.hpp.
Constructor & Destructor Documentation
CountPointer() [1/4]
template<class T > CountPointer< T >::CountPointer () inline explicit
Default constructor for Count Pointer, defaults to a nullptr, with 0 references.
Definition at line 78 of file typedefs-wrappers.hpp.
 : ptr(nullptr) {}
CountPointer() [2/4]
template<class T > CountPointer< T >::CountPointer (T * p) inline explicit
Construct a count pointer from the provided pointer, adding to the reference count (if non-null) for the provided pointer.
Parameters
p The pointer to provide. May be null, which does nothing.
Definition at line 81 of file typedefs-wrappers.hpp.
                                 : ptr(p) {
         if (p) {
             Counter::add(p);
         }
     }
References Counter::add().
CountPointer() [3/4]
template<class T > CountPointer< T >::CountPointer (const CountPointer< T > & other) inline
Copy constructor, copies and adds to the reference count for the held non-null pointer.
Definition at line 87 of file typedefs-wrappers.hpp.
                                                : ptr(other.ptr) {
         if (ptr) {
             Counter::add(ptr);
         }
     }
References Counter::add(), and CountPointer< T >::ptr.
CountPointer() [4/4]
template<class T > CountPointer< T >::CountPointer (CountPointer< T > && other) default
Move constructor is default, moves the pointer and keeps the reference count the same.
~CountPointer()
template<class T > CountPointer< T >::~CountPointer () inline
Destructor, decreases the ref count for the held non-null pointer.
Definition at line 95 of file typedefs-wrappers.hpp.
                     {
         if (ptr) {
             Counter::remove(ptr);
         }
     }
References CountPointer< T >::ptr, and Counter::remove().
Member Function Documentation
__internal_get()
template<class T > constexpr T* const CountPointer< T >::__internal_get () const inline constexpr noexcept
Get the raw pointer. Should ALMOST NEVER BE USED, UNLESS SCOPE GUARANTEES IT DIES BEFORE THIS INSTANCE DOES!
Returns
The raw pointer saved by this instance.
Definition at line 207 of file typedefs-wrappers.hpp.
{
         return ptr;
     }
References CountPointer< T >::ptr.
cast()
template<class T > template<class U > CountPointer<U> CountPointer< T >::cast () const inline
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may throw TypeCastException or crash. See try_cast for a version that does not.
Template Parameters
U The type to cast to.
Returns
A new CountPointer of the cast value.
Definition at line 166 of file typedefs-wrappers.hpp.
{
         // TODO: We currently assume that the first sizeof(void*) bytes of ptr is the klass field.
         // This should hold true for everything except value types.
         auto* k1 = CRASH_UNLESS(classof(U*));
         auto* k2 = *CRASH_UNLESS(reinterpret_cast<Il2CppClass**>(ptr));
         CRASH_UNLESS(k2);
         il2cpp_functions::Init();
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return CountPointer<U>(reinterpret_cast<U*>(ptr));
         }
         #if __has_feature(cxx_exceptions)
         throw TypeCastException();
         #else
         SAFE_ABORT();
         return CountPointer<U>();
         #endif
     }
References il2cpp_functions::class_is_assignable_from, classof, il2cpp_functions::Init(), and CountPointer< T >::ptr.
count()
template<class T > size_t CountPointer< T >::count () const inline
Gets the reference count held by this pointer.
Returns
The reference count for this pointer, or 0 if the held pointer is null.
Definition at line 102 of file typedefs-wrappers.hpp.
{
         if (ptr) {
             return Counter::get(ptr);
         }
         return 0;
     }
References Counter::get(), and CountPointer< T >::ptr.
emplace()
template<class T > void CountPointer< T >::emplace (T * val) inline
Emplaces a new pointer into the shared pointer, decreasing the existing ref count as necessary.
Parameters
val The new pointer to replace the currently held one with.
Definition at line 110 of file typedefs-wrappers.hpp.
{
         if (val != ptr) {
             if (ptr) {
                 Counter::remove(ptr);
             }
             ptr = val;
             if (ptr) {
                 Counter::add(ptr);
             }
         }
     }
References Counter::add(), CountPointer< T >::ptr, and Counter::remove().
Referenced by CountPointer< T >::operator=().
operator bool()
template<class T > constexpr CountPointer< T >::operator bool () const inline constexpr noexcept
Definition at line 155 of file typedefs-wrappers.hpp.
{
         return ptr != nullptr;
     }
References CountPointer< T >::ptr.
operator*() [1/2]
template<class T > const T& CountPointer< T >::operator* () const inline noexcept
Definition at line 134 of file typedefs-wrappers.hpp.
{
         if (ptr) {
             return *ptr;
         }
         SAFE_ABORT();
         return *ptr;
     }
References CountPointer< T >::ptr.
operator*() [2/2]
template<class T > T& CountPointer< T >::operator* () inline noexcept
Dereference operator.
Definition at line 127 of file typedefs-wrappers.hpp.
{
         if (ptr) {
             return *ptr;
         }
         SAFE_ABORT();
         return *ptr;
     }
References CountPointer< T >::ptr.
operator->() [1/2]
template<class T > T* const CountPointer< T >::operator-> () const inline noexcept
Definition at line 148 of file typedefs-wrappers.hpp.
{
         if (ptr) {
             return ptr;
         }
         SAFE_ABORT();
         return nullptr;
     }
References CountPointer< T >::ptr.
operator->() [2/2]
template<class T > T* CountPointer< T >::operator-> () inline noexcept
Definition at line 141 of file typedefs-wrappers.hpp.
{
         if (ptr) {
             return ptr;
         }
         SAFE_ABORT();
         return nullptr;
     }
References CountPointer< T >::ptr.
operator=()
template<class T > CountPointer& CountPointer< T >::operator= (T * val) inline
Assignment operator.
Definition at line 122 of file typedefs-wrappers.hpp.
{
         emplace(val);
         return *this;
     }
References CountPointer< T >::emplace().
try_cast()
template<class T > template<class U > std::optional<CountPointer<U> > CountPointer< T >::try_cast () const inline noexcept
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
Template Parameters
U The type to cast to.
Returns
A new CountPointer of the cast value, if successful.
Definition at line 189 of file typedefs-wrappers.hpp.
{
         auto* k1 = classof(U*);
         if (!ptr || !k1) {
             return std::nullopt;
         }
         auto* k2 = *reinterpret_cast<Il2CppClass**>(ptr);
         if (!k2) {
             return std::nullopt;
         }
         il2cpp_functions::Init();
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return CountPointer<U>(reinterpret_cast<U*>(ptr));
         }
         return std::nullopt;
     }
References il2cpp_functions::class_is_assignable_from, classof, il2cpp_functions::Init(), and CountPointer< T >::ptr.
Field Documentation
ptr
template<class T > T* CountPointer< T >::ptr private
Definition at line 211 of file typedefs-wrappers.hpp.
Referenced by CountPointer< T >::__internal_get(), CountPointer< T >::cast(), CountPointer< T >::count(), CountPointer< T >::CountPointer(), CountPointer< T >::emplace(), CountPointer< T >::operator bool(), CountPointer< T >::operator*(), CountPointer< T >::operator->(), CountPointer< T >::try_cast(), and CountPointer< T >::~CountPointer().
The documentation for this struct was generated from the following file:
shared/utils/typedefs-wrappers.hpp