BeatSaber-Hooks: rapidjson::internal::DiyFp Struct Reference
rapidjson::internal::DiyFp Struct Reference
#include <diyfp.h>
Public Member Functions
DiyFp ()
DiyFp (uint64_t fp, int exp)
DiyFp (double d)
DiyFp operator- (const DiyFp &rhs) const
DiyFp operator* (const DiyFp &rhs) const
DiyFp Normalize () const
DiyFp NormalizeBoundary () const
void NormalizedBoundaries (DiyFp *minus, DiyFp *plus) const
double ToDouble () const
Data Fields
uint64_t f
int e
Static Public Attributes
static const int kDiySignificandSize = 64
static const int kDpSignificandSize = 52
static const int kDpExponentBias = 0x3FF + kDpSignificandSize
static const int kDpMaxExponent = 0x7FF - kDpExponentBias
static const int kDpMinExponent = -kDpExponentBias
static const int kDpDenormalExponent = -kDpExponentBias + 1
static const uint64_t kDpExponentMask = ((static_cast<uint64_t>(0x7FF00000) << 32) | static_cast<uint64_t>(0x00000000))
static const uint64_t kDpSignificandMask = ((static_cast<uint64_t>(0x000FFFFF) << 32) | static_cast<uint64_t>(0xFFFFFFFF))
static const uint64_t kDpHiddenBit = ((static_cast<uint64_t>(0x00100000) << 32) | static_cast<uint64_t>(0x00000000))
Detailed Description
Definition at line 44 of file diyfp.h.
Constructor & Destructor Documentation
DiyFp() [1/3]
rapidjson::internal::DiyFp::DiyFp () inline
Definition at line 45 of file diyfp.h.
 : f(), e() {}
DiyFp() [2/3]
rapidjson::internal::DiyFp::DiyFp (uint64_t fp, int exp) inline
Definition at line 47 of file diyfp.h.
 : f(fp), e(exp) {}
DiyFp() [3/3]
rapidjson::internal::DiyFp::DiyFp (double d) inline explicit
Definition at line 49 of file diyfp.h.
{
         union {
             double d;
             uint64_t u64;
         } u = { d };
         int biased_e = static_cast<int>((u.u64 & kDpExponentMask) >> kDpSignificandSize);
         uint64_t significand = (u.u64 & kDpSignificandMask);
         if (biased_e != 0) {
             f = significand + kDpHiddenBit;
             e = biased_e - kDpExponentBias;
         }
         else {
             f = significand;
             e = kDpMinExponent + 1;
         }
     }
Member Function Documentation
Normalize()
DiyFp rapidjson::internal::DiyFp::Normalize () const inline
Definition at line 102 of file diyfp.h.
{
         int s = static_cast<int>(clzll(f));
         return DiyFp(f << s, e - s);
     }
References rapidjson::internal::clzll().
Referenced by rapidjson::internal::Grisu2(), and rapidjson::internal::StrtodDiyFp().
NormalizeBoundary()
DiyFp rapidjson::internal::DiyFp::NormalizeBoundary () const inline
Definition at line 107 of file diyfp.h.
{
         DiyFp res = *this;
         while (!(res.f & (kDpHiddenBit << 1))) {
             res.f <<= 1;
             res.e--;
         }
         res.f <<= (kDiySignificandSize - kDpSignificandSize - 2);
         res.e = res.e - (kDiySignificandSize - kDpSignificandSize - 2);
         return res;
     }
References e, and f.
Referenced by NormalizedBoundaries().
NormalizedBoundaries()
void rapidjson::internal::DiyFp::NormalizedBoundaries (DiyFp * minus, DiyFp * plus) const inline
Definition at line 118 of file diyfp.h.
{
         DiyFp pl = DiyFp((f << 1) + 1, e - 1).NormalizeBoundary();
         DiyFp mi = (f == kDpHiddenBit) ? DiyFp((f << 2) - 1, e - 2) : DiyFp((f << 1) - 1, e - 1);
         mi.f <<= mi.e - pl.e;
         mi.e = pl.e;
         *plus = pl;
         *minus = mi;
     }
References e, f, and NormalizeBoundary().
Referenced by rapidjson::internal::Grisu2().
operator*()
DiyFp rapidjson::internal::DiyFp::operator* (const DiyFp & rhs) const inline
mult_round
Definition at line 71 of file diyfp.h.
{
 #if defined(_MSC_VER) && defined(_M_AMD64)
         uint64_t h;
         uint64_t l = _umul128(f, rhs.f, &h);
         if (l & (uint64_t(1) << 63)) // rounding
             h++;
         return DiyFp(h, e + rhs.e + 64);
 #elif (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)) && defined(__x86_64__)
         __extension__ typedef unsigned __int128 uint128;
         uint128 p = static_cast<uint128>(f) * static_cast<uint128>(rhs.f);
         uint64_t h = static_cast<uint64_t>(p >> 64);
         uint64_t l = static_cast<uint64_t>(p);
         if (l & (uint64_t(1) << 63)) // rounding
             h++;
         return DiyFp(h, e + rhs.e + 64);
 #else
         const uint64_t M32 = 0xFFFFFFFF;
         const uint64_t a = f >> 32;
         const uint64_t b = f & M32;
         const uint64_t c = rhs.f >> 32;
         const uint64_t d = rhs.f & M32;
         const uint64_t ac = a * c;
         const uint64_t bc = b * c;
         const uint64_t ad = a * d;
         const uint64_t bd = b * d;
         uint64_t tmp = (bd >> 32) + (ad & M32) + (bc & M32);
         tmp += 1U << 31;
         return DiyFp(ac + (ad >> 32) + (bc >> 32) + (tmp >> 32), e + rhs.e + 64);
 #endif
     }
References rapidjson::a, e, and f.
operator-()
DiyFp rapidjson::internal::DiyFp::operator- (const DiyFp & rhs) const inline
Definition at line 67 of file diyfp.h.
{
         return DiyFp(f - rhs.f, e);
     }
References f.
ToDouble()
double rapidjson::internal::DiyFp::ToDouble () const inline
Definition at line 127 of file diyfp.h.
{
         union {
             double d;
             uint64_t u64;
         }u;
         RAPIDJSON_ASSERT(f <= kDpHiddenBit + kDpSignificandMask);
         if (e < kDpDenormalExponent) {
             // Underflow.
             return 0.0;
         }
         if (e >= kDpMaxExponent) {
             // Overflow.
             return std::numeric_limits<double>::infinity();
         }
         const uint64_t be = (e == kDpDenormalExponent && (f & kDpHiddenBit) == 0) ? 0 :
             static_cast<uint64_t>(e + kDpExponentBias);
         u.u64 = (f & kDpSignificandMask) | (be << kDpSignificandSize);
         return u.d;
     }
References RAPIDJSON_ASSERT.
Referenced by rapidjson::internal::StrtodDiyFp().
Field Documentation
e
int rapidjson::internal::DiyFp::e
Definition at line 158 of file diyfp.h.
Referenced by rapidjson::internal::DigitGen(), rapidjson::internal::Grisu2(), NormalizeBoundary(), NormalizedBoundaries(), operator*(), and rapidjson::internal::StrtodDiyFp().
f
uint64_t rapidjson::internal::DiyFp::f
Definition at line 157 of file diyfp.h.
Referenced by rapidjson::internal::DigitGen(), rapidjson::internal::Grisu2(), NormalizeBoundary(), NormalizedBoundaries(), operator*(), operator-(), and rapidjson::internal::StrtodDiyFp().
kDiySignificandSize
const int rapidjson::internal::DiyFp::kDiySignificandSize = 64 static
Definition at line 147 of file diyfp.h.
kDpDenormalExponent
const int rapidjson::internal::DiyFp::kDpDenormalExponent = -kDpExponentBias + 1 static
Definition at line 152 of file diyfp.h.
kDpExponentBias
const int rapidjson::internal::DiyFp::kDpExponentBias = 0x3FF + kDpSignificandSize static
Definition at line 149 of file diyfp.h.
kDpExponentMask
const uint64_t rapidjson::internal::DiyFp::kDpExponentMask = ((static_cast<uint64_t>(0x7FF00000) << 32) | static_cast<uint64_t>(0x00000000)) static
Definition at line 153 of file diyfp.h.
kDpHiddenBit
const uint64_t rapidjson::internal::DiyFp::kDpHiddenBit = ((static_cast<uint64_t>(0x00100000) << 32) | static_cast<uint64_t>(0x00000000)) static
Definition at line 155 of file diyfp.h.
kDpMaxExponent
const int rapidjson::internal::DiyFp::kDpMaxExponent = 0x7FF - kDpExponentBias static
Definition at line 150 of file diyfp.h.
kDpMinExponent
const int rapidjson::internal::DiyFp::kDpMinExponent = -kDpExponentBias static
Definition at line 151 of file diyfp.h.
kDpSignificandMask
const uint64_t rapidjson::internal::DiyFp::kDpSignificandMask = ((static_cast<uint64_t>(0x000FFFFF) << 32) | static_cast<uint64_t>(0xFFFFFFFF)) static
Definition at line 154 of file diyfp.h.
kDpSignificandSize
const int rapidjson::internal::DiyFp::kDpSignificandSize = 52 static
Definition at line 148 of file diyfp.h.
The documentation for this struct was generated from the following file:
shared/rapidjson/include/rapidjson/internal/diyfp.h