BeatSaber-Hooks: il2cpp_utils::FindMethodInfo Struct Reference
il2cpp_utils::FindMethodInfo Struct Reference
#include <il2cpp-utils-methods.hpp>
Public Member Functions
template<typename T , typename... TParams, ::std::enable_if_t<!::std::is_convertible_v< T, ::std::string_view >, int > = 0>
FindMethodInfo (T &&classOrInstance, ::std::string_view methodName, TParams &&... paramTypes)
template<typename T , typename G , typename... TArgs, ::std::enable_if_t<!::std::is_convertible_v< Il2CppType *, G >, int > = 0>
FindMethodInfo (T &&classOrInstance, ::std::string_view methodName, ::std::vector< G > genericArgs, TArgs &&... args)
template<typename T , typename R , typename... TArgs, ::std::enable_if_t<!::std::is_convertible_v< R, ::std::string_view >, int > = 0>
FindMethodInfo (T &&classOrInstance, R returnTypeOrClass, ::std::string_view methodName, TArgs &&... args)
template<typename... TArgs>
FindMethodInfo (::std::string_view namespaceName, ::std::string_view className, TArgs &&... args)
Data Fields
Il2CppClass * klass = nullptr
::std::string name
Il2CppClass * returnType = nullptr
::std::vector< Il2CppClass * > genTypes
::std::vector< const Il2CppType * > argTypes
Detailed Description
Definition at line 43 of file il2cpp-utils-methods.hpp.
Constructor & Destructor Documentation
FindMethodInfo() [1/4]
template<typename T , typename... TParams, ::std::enable_if_t<!::std::is_convertible_v< T, ::std::string_view >, int > = 0> il2cpp_utils::FindMethodInfo::FindMethodInfo (T && classOrInstance, ::std::string_view methodName, TParams &&... paramTypes) inline
Definition at line 57 of file il2cpp-utils-methods.hpp.
{
             klass = ExtractClass(classOrInstance);
             name = methodName;
             if constexpr (sizeof...(TParams) > 0) {
                 if constexpr (sizeof...(TParams) == 1 && (... && is_vector<::std::decay_t<TParams>>::value))
                     argTypes = TypesFrom(paramTypes...);
                 else
                     argTypes = TypesFrom({paramTypes...});
             }
         }
References argTypes, il2cpp_utils::ExtractClass(), klass, name, il2cpp_utils::TypesFrom(), and rapidjson::value.
FindMethodInfo() [2/4]
template<typename T , typename G , typename... TArgs, ::std::enable_if_t<!::std::is_convertible_v< Il2CppType *, G >, int > = 0> il2cpp_utils::FindMethodInfo::FindMethodInfo (T && classOrInstance, ::std::string_view methodName, ::std::vector< G > genericArgs, TArgs &&... args) inline
Definition at line 76 of file il2cpp-utils-methods.hpp.
             : FindMethodInfo(classOrInstance, methodName, args...)
         {
             genTypes = ClassesFrom(genericArgs);
         }
References il2cpp_utils::ClassesFrom(), and genTypes.
FindMethodInfo() [3/4]
template<typename T , typename R , typename... TArgs, ::std::enable_if_t<!::std::is_convertible_v< R, ::std::string_view >, int > = 0> il2cpp_utils::FindMethodInfo::FindMethodInfo (T && classOrInstance, R returnTypeOrClass, ::std::string_view methodName, TArgs &&... args) inline
Definition at line 89 of file il2cpp-utils-methods.hpp.
             : FindMethodInfo(classOrInstance, methodName, args...)
         {
             returnType = ExtractClass(returnTypeOrClass);
         }
References il2cpp_utils::ExtractClass(), and returnType.
FindMethodInfo() [4/4]
template<typename... TArgs> il2cpp_utils::FindMethodInfo::FindMethodInfo (::std::string_view namespaceName, ::std::string_view className, TArgs &&... args) inline
Definition at line 96 of file il2cpp-utils-methods.hpp.
             : FindMethodInfo(GetClassFromName(namespaceName, className), args...) { }
Field Documentation
argTypes
::std::vector<const Il2CppType*> il2cpp_utils::FindMethodInfo::argTypes
Definition at line 48 of file il2cpp-utils-methods.hpp.
Referenced by FindMethodInfo().
genTypes
::std::vector<Il2CppClass*> il2cpp_utils::FindMethodInfo::genTypes
Definition at line 47 of file il2cpp-utils-methods.hpp.
Referenced by FindMethodInfo().
klass
Il2CppClass* il2cpp_utils::FindMethodInfo::klass = nullptr
Definition at line 44 of file il2cpp-utils-methods.hpp.
Referenced by FindMethodInfo().
name
::std::string il2cpp_utils::FindMethodInfo::name
Definition at line 45 of file il2cpp-utils-methods.hpp.
Referenced by FindMethodInfo().
returnType
Il2CppClass* il2cpp_utils::FindMethodInfo::returnType = nullptr
Definition at line 46 of file il2cpp-utils-methods.hpp.
Referenced by FindMethodInfo().
The documentation for this struct was generated from the following file:
shared/utils/il2cpp-utils-methods.hpp