BeatSaber-Hooks: SafePtr< T > Struct Template Reference
SafePtr< T > Struct Template Reference
Represents a C++ type that wraps a C# pointer that will be valid for the entire lifetime of this instance. This instance must be created at a time such that il2cpp_functions::Init is valid, or else it will throw a CreatedTooEarlyException.
#include <typedefs-wrappers.hpp>
Data Structures
struct SafePointerWrapper
Public Member Functions
SafePtr ()
Default constructor. Should be paired with emplace or = to ensure validity.
SafePtr (T *wrappableInstance)
Construct a SafePtr<T> with the provided instance pointer (which may be nullptr). If you wish to wrap a non-existent pointer (ex, use as a default constructor) see the 0 arg constructor instead.
SafePtr (T &wrappableInstance)
Construct a SafePtr<T> with the provided reference.
SafePtr (SafePtr &&other)=default
Move constructor is default, moves the internal handle and keeps reference count the same.
SafePtr (const SafePtr &other)
Copy constructor copies the HANDLE, that is, the held pointer remains the same. Note that this means if you modify one SafePtr's held instance, all others that point to the same location will also reflect this change. In order to avoid a (small) performance overhead, consider using a reference type instead of a value type, or the move constructor instead.
~SafePtr ()
Destructor. Destroys the internal wrapper type, if necessary. Aborts if a wrapper type exists and must be freed, yet GC_free does not exist.
void emplace (T &other)
Emplace a new value into this SafePtr, freeing an existing one, if it exists.
void emplace (T *other)
Emplace a new value into this SafePtr, freeing an existing one, if it exists.
void emplace (CountPointer< T > &other)
Emplace a new pointer into this SafePtr, managing the existing one, if it exists.
void move (CountPointer< T > &other)
Move an existing CountPointer<T> into this SafePtr, deleting the existing one, if necessary.
SafePtr< T > & operator= (T *other)
SafePtr< T > & operator= (T &other)
template<class U >
SafePtr< U > cast () const
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may throw TypeCastException or NullHandleException or otherwise abort. See try_cast for a version that does not.
template<class U >
std::optional< SafePtr< U > > try_cast () const noexcept
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
operator bool () const noexcept
Returns false if this is a defaultly constructed SafePtr, true otherwise. Note that this means that it will return true if it holds a nullptr value explicitly! This means that you should check yourself before calling anything using the held T*.
T & operator* ()
Dereferences the instance pointer to a reference type of the held instance. Throws a NullHandleException if there is no internal handle.
const T & operator* () const
T *const operator-> () const
operator T*const () const
Explicitly cast this instance to a T*. Note, however, that the lifetime of this returned T* is not longer than the lifetime of this instance. Consider passing a SafePtr reference or copy instead.
Private Attributes
CountPointer< SafePointerWrapper > internalHandle
Detailed Description
template<class T>
struct SafePtr< T >
Represents a C++ type that wraps a C# pointer that will be valid for the entire lifetime of this instance. This instance must be created at a time such that il2cpp_functions::Init is valid, or else it will throw a CreatedTooEarlyException.
Template Parameters
T The type of the instance to wrap.
Definition at line 221 of file typedefs-wrappers.hpp.
Constructor & Destructor Documentation
SafePtr() [1/5]
template<class T > SafePtr< T >::SafePtr () inline
Default constructor. Should be paired with emplace or = to ensure validity.
Definition at line 223 of file typedefs-wrappers.hpp.
 {}
SafePtr() [2/5]
template<class T > SafePtr< T >::SafePtr (T * wrappableInstance) inline
Construct a SafePtr<T> with the provided instance pointer (which may be nullptr). If you wish to wrap a non-existent pointer (ex, use as a default constructor) see the 0 arg constructor instead.
Definition at line 226 of file typedefs-wrappers.hpp.
 : internalHandle(SafePointerWrapper::New(wrappableInstance)) {}
SafePtr() [3/5]
template<class T > SafePtr< T >::SafePtr (T & wrappableInstance) inline
Construct a SafePtr<T> with the provided reference.
Definition at line 228 of file typedefs-wrappers.hpp.
 : internalHandle(SafePointerWrapper::New(std::addressof(wrappableInstance))) {}
SafePtr() [4/5]
template<class T > SafePtr< T >::SafePtr (SafePtr< T > && other) default
Move constructor is default, moves the internal handle and keeps reference count the same.
SafePtr() [5/5]
template<class T > SafePtr< T >::SafePtr (const SafePtr< T > & other) inline
Copy constructor copies the HANDLE, that is, the held pointer remains the same. Note that this means if you modify one SafePtr's held instance, all others that point to the same location will also reflect this change. In order to avoid a (small) performance overhead, consider using a reference type instead of a value type, or the move constructor instead.
Definition at line 234 of file typedefs-wrappers.hpp.
 : internalHandle(other.internalHandle) {}
~SafePtr()
template<class T > SafePtr< T >::~SafePtr () inline
Destructor. Destroys the internal wrapper type, if necessary. Aborts if a wrapper type exists and must be freed, yet GC_free does not exist.
Definition at line 237 of file typedefs-wrappers.hpp.
                {
         if (!internalHandle) {
             // Destructor without an internal handle is trivial
             return;
         }
         // If our internal handle has 1 instance, we need to clean up the instance it points to.
         // Otherwise, some other SafePtr is currently holding a reference to this instance, so keep it around.
         if (internalHandle.count() <= 1) {
             il2cpp_functions::Init();
             if (!il2cpp_functions::GC_free) {
                 SAFE_ABORT();
             }
             il2cpp_functions::GC_free(internalHandle.__internal_get());
         }
     }
References il2cpp_functions::GC_free, il2cpp_functions::Init(), and SafePtr< T >::internalHandle.
Referenced by SafePtr< T >::emplace(), and SafePtr< T >::move().
Member Function Documentation
cast()
template<class T > template<class U > SafePtr<U> SafePtr< T >::cast () const inline
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T. This function may throw TypeCastException or NullHandleException or otherwise abort. See try_cast for a version that does not.
Template Parameters
U The type to cast to.
Returns
A new SafePtr of the cast value.
Definition at line 302 of file typedefs-wrappers.hpp.
{
         // TODO: We currently assume that the first sizeof(void*) bytes of ptr is the klass field.
         // This should hold true for everything except value types.
         if (!internalHandle) {
             #if __has_feature(cxx_exceptions)
             throw NullHandleException();
             #else
             SAFE_ABORT();
             return SafePtr<U>();
             #endif
         }
         auto* k1 = CRASH_UNLESS(classof(U*));
         auto* k2 = *CRASH_UNLESS(reinterpret_cast<Il2CppClass**>(internalHandle->instancePointer));
         il2cpp_functions::Init();
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return SafePtr<U>(reinterpret_cast<U*>(internalHandle->instancePointer));
         }
         #if __has_feature(cxx_exceptions)
         throw TypeCastException();
         #else
         SAFE_ABORT();
         return SafePtr<U>();
         #endif
     }
References il2cpp_functions::class_is_assignable_from, classof, il2cpp_functions::Init(), and SafePtr< T >::internalHandle.
emplace() [1/3]
template<class T > void SafePtr< T >::emplace (CountPointer< T > & other) inline
Emplace a new pointer into this SafePtr, managing the existing one, if it exists.
Parameters
other The CountPointer to copy during the emplace.
Definition at line 269 of file typedefs-wrappers.hpp.
{
         // Clear existing instance as necessary
         this->~SafePtr();
         // Copy other into handle
         internalHandle = other;
     }
References SafePtr< T >::internalHandle, and SafePtr< T >::~SafePtr().
emplace() [2/3]
template<class T > void SafePtr< T >::emplace (T & other) inline
Emplace a new value into this SafePtr, freeing an existing one, if it exists.
Parameters
other The instance to emplace.
Definition at line 255 of file typedefs-wrappers.hpp.
{
         this->~SafePtr();
         internalHandle = SafePointerWrapper::New(std::addressof(other));
     }
References SafePtr< T >::internalHandle, SafePtr< T >::SafePointerWrapper::New(), and SafePtr< T >::~SafePtr().
Referenced by SafePtr< T >::operator=().
emplace() [3/3]
template<class T > void SafePtr< T >::emplace (T * other) inline
Emplace a new value into this SafePtr, freeing an existing one, if it exists.
Parameters
other The instance to emplace.
Definition at line 262 of file typedefs-wrappers.hpp.
{
         this->~SafePtr();
         internalHandle = SafePointerWrapper::New(other);
     }
References SafePtr< T >::internalHandle, SafePtr< T >::SafePointerWrapper::New(), and SafePtr< T >::~SafePtr().
move()
template<class T > void SafePtr< T >::move (CountPointer< T > & other) inline
Move an existing CountPointer<T> into this SafePtr, deleting the existing one, if necessary.
Parameters
other The CountPointer to move during this call.
Definition at line 278 of file typedefs-wrappers.hpp.
{
         // Clear existing instance as necessary
         this->~SafePtr();
         // Move into handle
         internalHandle = std::move(other);
     }
References SafePtr< T >::internalHandle, and SafePtr< T >::~SafePtr().
operator bool()
template<class T > SafePtr< T >::operator bool () const inline noexcept
Returns false if this is a defaultly constructed SafePtr, true otherwise. Note that this means that it will return true if it holds a nullptr value explicitly! This means that you should check yourself before calling anything using the held T*.
Definition at line 351 of file typedefs-wrappers.hpp.
{
         return (bool)internalHandle;
     }
References SafePtr< T >::internalHandle.
operator T*const()
template<class T > SafePtr< T >::operator T*const () const inline explicit
Explicitly cast this instance to a T*. Note, however, that the lifetime of this returned T* is not longer than the lifetime of this instance. Consider passing a SafePtr reference or copy instead.
Definition at line 372 of file typedefs-wrappers.hpp.
{
         __SAFE_PTR_NULL_HANDLE_CHECK(internalHandle, internalHandle->instancePointer);
     }
References __SAFE_PTR_NULL_HANDLE_CHECK, and SafePtr< T >::internalHandle.
operator*() [1/2]
template<class T > T& SafePtr< T >::operator* () inline
Dereferences the instance pointer to a reference type of the held instance. Throws a NullHandleException if there is no internal handle.
Definition at line 357 of file typedefs-wrappers.hpp.
                     {
         __SAFE_PTR_NULL_HANDLE_CHECK(internalHandle, *internalHandle->instancePointer);
     }
References __SAFE_PTR_NULL_HANDLE_CHECK, and SafePtr< T >::internalHandle.
operator*() [2/2]
template<class T > const T& SafePtr< T >::operator* () const inline
Definition at line 361 of file typedefs-wrappers.hpp.
{
         __SAFE_PTR_NULL_HANDLE_CHECK(internalHandle, *internalHandle->instancePointer);
     }
References __SAFE_PTR_NULL_HANDLE_CHECK, and SafePtr< T >::internalHandle.
operator->()
template<class T > T* const SafePtr< T >::operator-> () const inline
Definition at line 365 of file typedefs-wrappers.hpp.
{
         __SAFE_PTR_NULL_HANDLE_CHECK(internalHandle, internalHandle->instancePointer);
     }
References __SAFE_PTR_NULL_HANDLE_CHECK, and SafePtr< T >::internalHandle.
operator=() [1/2]
template<class T > SafePtr<T>& SafePtr< T >::operator= (T & other) inline
Definition at line 290 of file typedefs-wrappers.hpp.
{
         emplace(other);
         return *this;
     }
References SafePtr< T >::emplace().
operator=() [2/2]
template<class T > SafePtr<T>& SafePtr< T >::operator= (T * other) inline
Definition at line 285 of file typedefs-wrappers.hpp.
{
         emplace(other);
         return *this;
     }
References SafePtr< T >::emplace().
try_cast()
template<class T > template<class U > std::optional<SafePtr<U> > SafePtr< T >::try_cast () const inline noexcept
Performs an il2cpp type checked cast from T to U. This should only be done if both T and U are reference types Currently assumes the klass field is the first pointer in T.
Template Parameters
U The type to cast to.
Returns
A new SafePtr of the cast value, if successful.
Definition at line 332 of file typedefs-wrappers.hpp.
{
         auto* k1 = classof(U*);
         if (!internalHandle || !internalHandle->instancePointer || k1) {
             return std::nullopt;
         }
         auto* k2 = *reinterpret_cast<Il2CppClass**>(internalHandle->instancePointer);
         if (!k2) {
             return std::nullopt;
         }
         il2cpp_functions::Init();
         if (il2cpp_functions::class_is_assignable_from(k1, k2)) {
             return SafePtr<U>(reinterpret_cast<U*>(internalHandle->instancePointer));
         }
         return std::nullopt;
     }
References il2cpp_functions::class_is_assignable_from, classof, il2cpp_functions::Init(), and SafePtr< T >::internalHandle.
Field Documentation
internalHandle
template<class T > CountPointer<SafePointerWrapper> SafePtr< T >::internalHandle private
Definition at line 398 of file typedefs-wrappers.hpp.
Referenced by SafePtr< T >::cast(), SafePtr< T >::emplace(), SafePtr< T >::move(), SafePtr< T >::operator bool(), SafePtr< T >::operator T*const(), SafePtr< T >::operator*(), SafePtr< T >::operator->(), SafePtr< T >::try_cast(), and SafePtr< T >::~SafePtr().
The documentation for this struct was generated from the following file:
shared/utils/typedefs-wrappers.hpp