BeatSaber-Hooks: shared/rapidjson/test/unittest/unittest.h File Reference
unittest.h File Reference
#include "gtest/gtest.h"
#include <stdexcept>
Data Structures
class AssertException
class Random
Macros
#define __STDC_CONSTANT_MACROS 1
#define RAPIDJSON_HAS_CXX11_NOEXCEPT 0
#define RAPIDJSON_ASSERT(x) (!(x) ? throw AssertException(RAPIDJSON_STRINGIFY(x)) : (void)0u)
#define RAPIDJSON_ASSERT_THROWS
Functions
template<typename Ch >
unsigned StrLen (const Ch *s)
template<typename Ch >
int StrCmp (const Ch *s1, const Ch *s2)
template<typename Ch >
Ch * StrDup (const Ch *str)
FILE * TempFile (char *filename)
Macro Definition Documentation
__STDC_CONSTANT_MACROS
#define __STDC_CONSTANT_MACROS 1
Definition at line 27 of file unittest.h.
RAPIDJSON_ASSERT
#define RAPIDJSON_ASSERT (x) (!(x) ? throw AssertException(RAPIDJSON_STRINGIFY(x)) : (void)0u)
Definition at line 124 of file unittest.h.
RAPIDJSON_ASSERT_THROWS
#define RAPIDJSON_ASSERT_THROWS
Definition at line 126 of file unittest.h.
RAPIDJSON_HAS_CXX11_NOEXCEPT
#define RAPIDJSON_HAS_CXX11_NOEXCEPT 0
Definition at line 121 of file unittest.h.
Function Documentation
StrCmp()
template<typename Ch > int StrCmp (const Ch * s1, const Ch * s2) inline
Definition at line 67 of file unittest.h.
{
     while(*s1 && (*s1 == *s2)) { s1++; s2++; }
     return static_cast<unsigned>(*s1) < static_cast<unsigned>(*s2) ? -1 : static_cast<unsigned>(*s1) > static_cast<unsigned>(*s2);
 }
Referenced by TEST().
StrDup()
template<typename Ch > Ch* StrDup (const Ch * str) inline
Definition at line 73 of file unittest.h.
{
     size_t bufferSize = sizeof(Ch) * (StrLen(str) + 1);
     Ch* buffer = static_cast<Ch*>(malloc(bufferSize));
     memcpy(buffer, str, bufferSize);
     return buffer;
 }
References StrLen().
Referenced by TEST().
StrLen()
template<typename Ch > unsigned StrLen (const Ch * s) inline
Definition at line 60 of file unittest.h.
{
     const Ch* p = s;
     while (*p) p++;
     return unsigned(p - s);
 }
Referenced by rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), rapidjson::GenericStringRef< CharType >::NotNullStrLen(), StrDup(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and TEST().
TempFile()
FILE* TempFile (char * filename) inline
Definition at line 80 of file unittest.h.
{
 #if defined(__WIN32__) || defined(_MSC_VER)
     filename = tmpnam(filename);
     // For Visual Studio, tmpnam() adds a backslash in front. Remove it.
     if (filename[0] == '\\')
         for (int i = 0; filename[i] != '\0'; i++)
             filename[i] = filename[i + 1];
     return fopen(filename, "wb");
 #else
     strcpy(filename, "/tmp/fileXXXXXX");
     int fd = mkstemp(filename);
     return fdopen(fd, "w");
 #endif
 }
Referenced by TEST(), TEST_F(), EncodedStreamTest::TestAutoUTFOutputStream(), EncodedStreamTest::TestEncodedOutputStream(), and TestFileStream().