BeatSaber-Hooks: src/utils/utils.cpp File Reference
utils.cpp File Reference
#include "../../shared/utils/utils.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dlfcn.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_set>
#include "il2cpp-object-internals.h"
#include "modloader/shared/modloader.hpp"
#include "shared/utils/gc-alloc.hpp"
Macros
#define in_range(x, a, b) (x >= a && x <= b)
#define get_bits(x) (in_range((x & (~0x20)), 'A', 'F') ? ((x & (~0x20)) - 'A' + 0xA): (in_range(x, '0', '9') ? x - '0': 0))
#define get_byte(x) (get_bits(x[0]) << 4 | get_bits(x[1]))
Functions
void safeAbort (const char *func, const char *file, int line)
void resetSS (std::stringstream &ss)
void tabs (std::ostream &os, int tabs, int spacesPerTab)
void print (std::stringstream &ss, Logging::Level lvl)
std::string string_vformat (const std::string_view format, va_list args)
void analyzeBytes (std::stringstream &ss, const void *ptr, int indent)
uintptr_t getLibil2cppSize ()
Get the size of the libil2cpp.so file.
void analyzeBytes (const void *ptr)
uintptr_t baseAddr (const char *soname)
uintptr_t getRealOffset (const void *offset)
int mkpath (std::string_view file_path)
uintptr_t findPattern (uintptr_t dwAddress, const char *pattern, uintptr_t dwSearchRangeLen)
uintptr_t findUniquePattern (bool &multiple, uintptr_t dwAddress, const char *pattern, const char *label, uintptr_t dwSearchRangeLen)
uintptr_t findUniquePatternInLibil2cpp (bool &multiple, const char *pattern, const char *label)
Attempts to match the pattern provided with all regions of mapped read memory with the libil2cpp.so.
void setcsstr (Il2CppString *in, std::u16string_view str)
std::string to_utf8 (std::u16string_view view)
std::u16string to_utf16 (std::string_view view)
std::u16string_view csstrtostr (Il2CppString *in)
void dump (int before, int after, void *ptr)
bool fileexists (std::string_view filename)
bool direxists (std::string_view dirname)
std::string readfile (std::string_view filename)
std::vector< char > readbytes (std::string_view filename)
bool writefile (std::string_view filename, std::string_view text)
bool deletefile (std::string_view filename)
Variables
static std::unordered_set< const void * > analyzed
static uintptr_t soSize = 0
uintptr_t location
Macro Definition Documentation
get_bits
#define get_bits (x) (in_range((x & (~0x20)), 'A', 'F') ? ((x & (~0x20)) - 'A' + 0xA): (in_range(x, '0', '9') ? x - '0': 0))
get_byte
#define get_byte (x) (get_bits(x[0]) << 4 | get_bits(x[1]))
in_range
#define in_range (x, a, b) (x >= a && x <= b)
Function Documentation
analyzeBytes() [1/2]
void analyzeBytes (const void * ptr)
Definition at line 119 of file utils.cpp.
{
     analyzed.clear();
     std::stringstream ss;
     ss << std::setfill('0');
     ss << "ptr: " << std::hex << std::setw(16) << (uintptr_t) ptr;
     print(ss);
     analyzeBytes(ss, ptr, 0);
 }
References analyzeBytes(), analyzed, and print().
analyzeBytes() [2/2]
void analyzeBytes (std::stringstream & ss, const void * ptr, int indent)
Definition at line 56 of file utils.cpp.
{
     if (!ptr || ((const uintptr_t)ptr) > 0x7fffffffffll) return;
     tabs(ss, indent);
     if (analyzed.count(ptr)) {
         ss << "! loop at 0x" << std::hex << ptr << "!";
         print(ss);
         return;
     }
     analyzed.insert(ptr);
     auto asUInts = reinterpret_cast<const uintptr_t*>(ptr);
     auto asInts = reinterpret_cast<const intptr_t*>(ptr);
     auto asChars = reinterpret_cast<const char*>(ptr);
     if (asUInts[0] >= 0x1000000000000ll && isprint(asChars[0])) {
         ss << "chars: \"" << asChars << "\"";
         ss << " (first 8 bytes in hex = 0x" << std::hex << std::setw(16) << asUInts[0] << ")";
         print(ss);
         return;
     }
     for (int i = 0; i < 4; i++) {
         if (i != 0) tabs(ss, indent);
         ss << "pos " << std::dec << i << ": 0x" << std::hex << std::setw(16) << asUInts[i];
         if (asUInts[i] >= 0x8000000000ll) {
             // todo: read no more than 8 chars or move asInts to last aligned point in string
             ss << " (as chars = \"" << reinterpret_cast<const char*>(asUInts + i) << "\")";
             ss << " (as int = " << std::dec << asInts[i] << ")";  // signed int
         } else if (asUInts[i] <= 0x7f00000000ll) {
             ss << " (as int = " << std::dec << asUInts[i] << ")";
         }
         else {
             Dl_info inf;
             if (dladdr((void*)asUInts[i], &inf)) {
                 ss << " (dli_fname: " << inf.dli_fname << ", dli_fbase: " << std::hex << std::setw(16) << (uintptr_t)inf.dli_fbase;
                 ss << ", offset = 0x" << std::hex << std::setw(8) << (asUInts[i] - (uintptr_t)inf.dli_fbase);
                 if (inf.dli_sname) {
                     ss << ", dli_sname: " << inf.dli_sname << ", dli_saddr: " << std::hex << std::setw(16) << (uintptr_t)inf.dli_saddr;
                 }
                 ss << ")";
             }
         }
         print(ss);
         if (asUInts[i] > 0x7f00000000ll) {
             analyzeBytes(ss, (void*)asUInts[i], indent + 1);
         }
     }
 }
References analyzed, il2cpp_utils::indent, print(), and tabs().
Referenced by analyzeBytes().
baseAddr()
uintptr_t baseAddr (const char * soname)
Definition at line 128 of file utils.cpp.
 {
     void *imagehandle = dlopen(soname, RTLD_LOCAL | RTLD_LAZY);
     if (soname == NULL)
         return (uintptr_t)NULL;
     if (imagehandle == NULL)
         return (uintptr_t)NULL;
     FILE *f = NULL;
     char line[200] = {0};
     char *state = NULL;
     char *tok = NULL;
     char * baseAddr = NULL;
     if ((f = fopen("/proc/self/maps", "r")) == NULL)
         return (uintptr_t)NULL;
     while (fgets(line, 199, f) != NULL)
     {
         tok = strtok_r(line, "-", &state);
         baseAddr = tok;
         tok = strtok_r(NULL, "\t ", &state);
         tok = strtok_r(NULL, "\t ", &state); // "r-xp" field
         tok = strtok_r(NULL, "\t ", &state); // "0000000" field
         tok = strtok_r(NULL, "\t ", &state); // "01:02" field
         tok = strtok_r(NULL, "\t ", &state); // "133224" field
         tok = strtok_r(NULL, "\t ", &state); // path field
         if (tok != NULL) {
             int i;
             for (i = (int)strlen(tok)-1; i >= 0; --i) {
                 if (!(tok[i] == ' ' || tok[i] == '\r' || tok[i] == '\n' || tok[i] == '\t'))
                     break;
                 tok[i] = 0;
             }
             {
                 size_t toklen = strlen(tok);
                 size_t solen = strlen(soname);
                 if (toklen > 0) {
                     if (toklen >= solen && strcmp(tok + (toklen - solen), soname) == 0) {
                         fclose(f);
                         return (uintptr_t)strtoll(baseAddr,NULL,16);
                     }
                 }
             }
         }
     }
     fclose(f);
     return (uintptr_t)NULL;
 }
Referenced by getRealOffset().
csstrtostr()
std::u16string_view csstrtostr (Il2CppString * in)
Definition at line 328 of file utils.cpp.
 {
     return {in->chars, static_cast<uint32_t>(in->length)};
 }
deletefile()
bool deletefile (std::string_view filename)
Definition at line 387 of file utils.cpp.
{
     if (fileexists(filename))
         return remove(filename.data()) == 0;
     return false;
 }
References fileexists().
Referenced by get_global(), and Logger::init().
direxists()
bool direxists (std::string_view dirname)
Definition at line 349 of file utils.cpp.
{
     struct stat info;
     if (stat(dirname.data(), &info) != 0) {
         return false;
     } if (info.st_mode & S_IFDIR) {
         return true;
     }
     return false;
 }
References info.
Referenced by Configuration::getConfigFilePath(), getDataDir(), and Logger::init().
dump()
void dump (int before, int after, void * ptr)
Definition at line 334 of file utils.cpp.
{
     Logger::get().debug("Dumping Immediate Pointer: %p: %08x", ptr, *reinterpret_cast<int*>(ptr));
     auto begin = static_cast<int*>(ptr) - before;
     auto end = static_cast<int*>(ptr) + after;
     for (auto cur = begin; cur != end; ++cur) {
         Logger::get().debug("%p: %08x", cur, *cur);
     }
 }
References Logger::debug(), and Logger::get().
fileexists()
bool fileexists (std::string_view filename)
Definition at line 345 of file utils.cpp.
{
     return access(filename.data(), W_OK | R_OK) != -1;
 }
Referenced by deletefile(), get_global(), Logger::init(), Configuration::Load(), and parsejsonfile().
findPattern()
uintptr_t findPattern (uintptr_t dwAddress, const char * pattern, uintptr_t dwSearchRangeLen)
Definition at line 195 of file utils.cpp.
{
     #define in_range(x, a, b) (x >= a && x <= b)
     #define get_bits(x) (in_range((x & (~0x20)), 'A', 'F') ? ((x & (~0x20)) - 'A' + 0xA): (in_range(x, '0', '9') ? x - '0': 0))
     #define get_byte(x) (get_bits(x[0]) << 4 | get_bits(x[1]))
     // To avoid a lot of bad match candidates, pre-process wildcards at the front of the pattern
     uintptr_t skippedStartBytes = 0;
     while(pattern[0] == '\?') {
         // see comments below for insight on these numbers
         pattern += (pattern[1] == '\?') ? 3 : 2;
         skippedStartBytes++;
     }
     uintptr_t match = 0;  // current match candidate
     uintptr_t len = strlen(CRASH_UNLESS(pattern));
     if (dwSearchRangeLen < len) {
         return 0;
     }
     const char* pat = pattern;  // current spot in the pattern
     for (uintptr_t pCur = dwAddress + skippedStartBytes; pCur < dwAddress + dwSearchRangeLen; pCur++) {
         // If pat[0] is null char, we are done, or if pat >= pattern + len
         if (pat >= pattern + len || !pat[0] || !pat[1]) {
             return match;
         }
         // For each byte, if the pattern starts with a ? or the current byte matches:
         if (pat[0] == '\?' || *(char *)pCur == get_byte(pat)) {
             // If we do not have a match, begin it
             if (!match) {
                 match = pCur - skippedStartBytes;
             }
             // If our next character is at the end of our pattern, we have a match
             if (pat + 1 >= pattern + len) {
                 return match;
             }
             if (pat[0] != '\?' || pat[1] == '\?') {
                 pat += 3;  // advance past "xy " or "?? "
             } else {
                 pat += 2;  // advance past "? "
             }
         }
         else {
             // reset search position to beginning of the failed match; for loop will begin new search at match + 1
             if (match) pCur = match + skippedStartBytes;
             pat = pattern;
             match = 0;
         }
     }
     return 0;
 }
References get_byte.
Referenced by findUniquePattern().
findUniquePattern()
uintptr_t findUniquePattern (bool & multiple, uintptr_t dwAddress, const char * pattern, const char * label, uintptr_t dwSearchRangeLen)
Definition at line 245 of file utils.cpp.
{
     uintptr_t firstMatchAddr = 0, newMatchAddr, start = dwAddress, dwEnd = dwAddress + dwSearchRangeLen;
     int matches = 0;
     Logger::get().debug("Sigscan for pattern: %s", pattern);
     while (start > 0 && start < dwEnd && (newMatchAddr = findPattern(start, pattern, dwEnd - start))) {
         if (!firstMatchAddr) firstMatchAddr = newMatchAddr;
         matches++;
         if (label) Logger::get().debug("Sigscan found possible \"%s\": offset 0x%lX, pointer 0x%lX", label, newMatchAddr - dwAddress, newMatchAddr);
         start = newMatchAddr + 1;
         Logger::get().debug("start = 0x%lX, end = 0x%lX", start, dwEnd);
         usleep(1000);
     }
     if (matches > 1) {
         multiple = true;
         Logger::get().warning("Multiple sig scan matches for \"%s\"!", label);
     }
     return firstMatchAddr;
 }
References Logger::debug(), findPattern(), Logger::get(), and Logger::warning().
Referenced by findUniquePatternInLibil2cpp().
findUniquePatternInLibil2cpp()
uintptr_t findUniquePatternInLibil2cpp (bool & multiple, const char * pattern, const char * label)
Attempts to match the pattern provided with all regions of mapped read memory with the libil2cpp.so.
Definition at line 264 of file utils.cpp.
{
     // Essentially call findUniquePattern for each segment listed in /proc/self/maps
     std::ifstream procMap("/proc/self/maps");
     std::string line;
     uintptr_t match = 0;
     while (std::getline(procMap, line)) {
         if (line.find("libil2cpp.so") == std::string::npos) {
             continue;
         }
         auto idx = line.find_first_of('-');
         if (idx == std::string::npos) {
             CRASH_UNLESS(false);
         }
         auto startAddr = std::stoul(line.substr(0, idx), nullptr, 16);
         auto spaceIdx = line.find_first_of(' ');
         if (spaceIdx == std::string::npos) {
             CRASH_UNLESS(false);
         }
         auto endAddr = std::stoul(line.substr(idx + 1, spaceIdx - idx - 1), nullptr, 16);
         // Permissions are 4 characters
         auto perms = line.substr(spaceIdx + 1, 4);
         if (perms.find('r') != std::string::npos) {
             // Search between start and end
             match = findUniquePattern(multiple, startAddr, pattern, label, endAddr - startAddr);
         }
     }
     procMap.close();
     return match;
 }
References findUniquePattern().
Referenced by find_GC_AllocFixed(), and find_GC_free().
getLibil2cppSize()
uintptr_t getLibil2cppSize ()
Get the size of the libil2cpp.so file.
Returns
The size of the .so
Definition at line 107 of file utils.cpp.
{
     static auto contextLogger = Logger::get().WithContext("getSize");
     if (soSize == 0) {
         struct stat st;
         if (!stat(Modloader::getLibIl2CppPath().c_str(), &st)) {
             soSize = st.st_size;
         }
         contextLogger.debug("libil2cpp.so size: 0x%x", soSize);
     }
     return soSize;
 }
References Logger::get(), soSize, and Logger::WithContext().
getRealOffset()
uintptr_t getRealOffset (const void * offset)
Definition at line 179 of file utils.cpp.
 {
     if (location == 0)
     {
         //arm
         // TOOD: Lets get the instance via some sort of initialization function
         // OR we make EVERYTHING on an instance level
         location = baseAddr(Modloader::getLibIl2CppPath().c_str());
     }
     return location + (uintptr_t)offset;
 }
References baseAddr(), and location.
Referenced by il2cpp_utils::BuildGenericsMap(), Instruction::findNth(), and il2cpp_functions::Init().
mkpath()
int mkpath (std::string_view file_path)
Definition at line 191 of file utils.cpp.
{
     return system((std::string("mkdir -p -m +rw ") + file_path.data()).c_str());
 }
Referenced by Configuration::getConfigFilePath(), getDataDir(), and Logger::init().
print()
void print (std::stringstream & ss, Logging::Level lvl)
Definition at line 40 of file utils.cpp.
{
     ss << std::endl;
     Logger::get().log(lvl, "%s", ss.str().c_str());
     resetSS(ss);
 }
References Logger::get(), Logger::log(), and resetSS().
Referenced by analyzeBytes().
readbytes()
std::vector<char> readbytes (std::string_view filename)
Definition at line 370 of file utils.cpp.
{
     std::ifstream infile(filename.data(), std::ios_base::binary);
     if (!infile.is_open()) {
         return std::vector<char>();
     }
     return std::vector<char>(std::istreambuf_iterator<char>(infile), std::istreambuf_iterator<char>());
 }
readfile()
std::string readfile (std::string_view filename)
Definition at line 360 of file utils.cpp.
{
     std::ifstream t(filename.data());
     if (!t.is_open()) {
         return "";
     }
     std::stringstream buffer;
     buffer << t.rdbuf();
     return buffer.str();
 }
resetSS()
void resetSS (std::stringstream & ss)
Definition at line 29 of file utils.cpp.
{
     ss.str("");
     ss.clear();  // Clear state flags.
 }
Referenced by print().
safeAbort()
void safeAbort (const char * func, const char * file, int line)
Definition at line 16 of file utils.cpp.
{
     static auto logger = Logger::get().WithContext("CRASH_UNLESS");
     // we REALLY want this to appear at least once in the log (for fastest fixing)
     for (int i = 0; i < 2; i++) {
         usleep(100000L);  // 0.1s
         // TODO: Make this eventually have a passed in context
         logger.critical("Aborting in %s at %s:%i", func, file, line);
     }
     Logger::closeAll();
     usleep(100000L);  // 0.1s
     std::terminate();  // cleans things up and then calls abort
 }
References Logger::closeAll(), Logger::get(), and Logger::WithContext().
setcsstr()
void setcsstr (Il2CppString * in, std::u16string_view str)
Definition at line 296 of file utils.cpp.
{
     in->length = str.length();
     for(int i = 0; i < in->length; i++) {
         // Can assume that each char is only a single char (a single word --> double word)
         in->chars[i] = str[i];
     }
     in->chars[in->length] = (Il2CppChar)'\u0000';
 }
string_vformat()
std::string string_vformat (const std::string_view format, va_list args)
Definition at line 46 of file utils.cpp.
{
     size_t size = vsnprintf(nullptr, 0, format.data(), args) + 1; // Extra space for '\0'
     if (size <= 0)
         return "";
     std::unique_ptr<char[]> buf(new char[size]);
     vsnprintf(buf.get(), size, format.data(), args);
     return std::string(buf.get(), buf.get() + size - 1);
 }
References il2cpp_utils::args.
tabs()
void tabs (std::ostream & os, int tabs, int spacesPerTab)
Definition at line 34 of file utils.cpp.
{
     for (int i = 0; i < tabs * spacesPerTab; i++) {
         os << " ";
     }
 }
Referenced by analyzeBytes().
to_utf16()
std::u16string to_utf16 (std::string_view view)
Definition at line 317 of file utils.cpp.
{
     char16_t* dat = static_cast<char16_t*>(calloc(view.length() + 1, sizeof(char16_t)));
     std::transform(view.data(), view.data() + view.size(), dat, [](auto standardChar) {
         return static_cast<char16_t>(standardChar);
     });
     dat[view.length()] = '\0';
     std::u16string out(dat);
     free(dat);
     return out;
 }
to_utf8()
std::string to_utf8 (std::u16string_view view)
Definition at line 306 of file utils.cpp.
{
     char* dat = static_cast<char*>(calloc(view.length() + 1, sizeof(char)));
     std::transform(view.data(), view.data() + view.size(), dat, [](auto utf16_char) {
         return static_cast<char>(utf16_char);
     });
     dat[view.length()] = '\0';
     std::string out(dat);
     free(dat);
     return out;
 }
writefile()
bool writefile (std::string_view filename, std::string_view text)
Definition at line 378 of file utils.cpp.
{
     std::ofstream t(filename.data());
     if (t.is_open()) {
         t << text;
         return true;
     }
     return false;
 }
Referenced by Configuration::Load(), and Configuration::Write().
Variable Documentation
analyzed
std::unordered_set<const void*> analyzed static
Definition at line 55 of file utils.cpp.
Referenced by analyzeBytes().
location
uintptr_t location
Definition at line 177 of file utils.cpp.
Referenced by HookTracker::GetHooks(), HookTracker::GetOrig(), getOrigHelper(), HookTracker::GetOrigInternal(), getRealOffset(), HookTracker::InstructionGetOrig(), HookTracker::InstructionIsHooked(), HookTracker::IsHooked(), and HookTracker::RemoveHooks().
soSize
uintptr_t soSize = 0 static
Definition at line 105 of file utils.cpp.
Referenced by getLibil2cppSize().