BeatSaber-Hooks: shared/utils/utils-functions.h File Reference
utils-functions.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <string_view>
#include <vector>
Functions
std::string string_vformat (const std::string_view format, va_list args)
std::u16string_view csstrtostr (Il2CppString *in)
void setcsstr (Il2CppString *in, std::u16string_view str)
std::string to_utf8 (std::u16string_view view)
std::u16string to_utf16 (std::string_view view)
void dump (int before, int after, void *ptr)
std::string readfile (std::string_view filename)
std::vector< char > readbytes (std::string_view filename)
bool writefile (std::string_view filename, std::string_view text)
bool deletefile (std::string_view filename)
bool fileexists (std::string_view filename)
bool direxists (std::string_view dirname)
template<typename... TArgs>
std::string string_format (const std::string_view format, TArgs ... args)
uintptr_t getLibil2cppSize ()
Get the size of the libil2cpp.so file.
Variables
bool = uchar8_t
Function Documentation
csstrtostr()
std::u16string_view csstrtostr (Il2CppString * in)
Definition at line 328 of file utils.cpp.
 {
     return {in->chars, static_cast<uint32_t>(in->length)};
 }
deletefile()
bool deletefile (std::string_view filename)
Definition at line 387 of file utils.cpp.
{
     if (fileexists(filename))
         return remove(filename.data()) == 0;
     return false;
 }
References fileexists().
Referenced by get_global(), and Logger::init().
direxists()
bool direxists (std::string_view dirname)
Definition at line 349 of file utils.cpp.
{
     struct stat info;
     if (stat(dirname.data(), &info) != 0) {
         return false;
     } if (info.st_mode & S_IFDIR) {
         return true;
     }
     return false;
 }
References info.
Referenced by Configuration::getConfigFilePath(), getDataDir(), and Logger::init().
dump()
void dump (int before, int after, void * ptr)
Definition at line 334 of file utils.cpp.
{
     Logger::get().debug("Dumping Immediate Pointer: %p: %08x", ptr, *reinterpret_cast<int*>(ptr));
     auto begin = static_cast<int*>(ptr) - before;
     auto end = static_cast<int*>(ptr) + after;
     for (auto cur = begin; cur != end; ++cur) {
         Logger::get().debug("%p: %08x", cur, *cur);
     }
 }
References Logger::debug(), and Logger::get().
fileexists()
bool fileexists (std::string_view filename)
Definition at line 345 of file utils.cpp.
{
     return access(filename.data(), W_OK | R_OK) != -1;
 }
Referenced by deletefile(), get_global(), Logger::init(), Configuration::Load(), and parsejsonfile().
getLibil2cppSize()
uintptr_t getLibil2cppSize ()
Get the size of the libil2cpp.so file.
Returns
The size of the .so
Definition at line 107 of file utils.cpp.
{
     static auto contextLogger = Logger::get().WithContext("getSize");
     if (soSize == 0) {
         struct stat st;
         if (!stat(Modloader::getLibIl2CppPath().c_str(), &st)) {
             soSize = st.st_size;
         }
         contextLogger.debug("libil2cpp.so size: 0x%x", soSize);
     }
     return soSize;
 }
References Logger::get(), Modloader::getLibIl2CppPath(), soSize, and Logger::WithContext().
readbytes()
std::vector<char> readbytes (std::string_view filename)
Definition at line 370 of file utils.cpp.
{
     std::ifstream infile(filename.data(), std::ios_base::binary);
     if (!infile.is_open()) {
         return std::vector<char>();
     }
     return std::vector<char>(std::istreambuf_iterator<char>(infile), std::istreambuf_iterator<char>());
 }
readfile()
std::string readfile (std::string_view filename)
Definition at line 360 of file utils.cpp.
{
     std::ifstream t(filename.data());
     if (!t.is_open()) {
         return "";
     }
     std::stringstream buffer;
     buffer << t.rdbuf();
     return buffer.str();
 }
setcsstr()
void setcsstr (Il2CppString * in, std::u16string_view str)
Definition at line 296 of file utils.cpp.
{
     in->length = str.length();
     for(int i = 0; i < in->length; i++) {
         // Can assume that each char is only a single char (a single word --> double word)
         in->chars[i] = str[i];
     }
     in->chars[in->length] = (Il2CppChar)'\u0000';
 }
string_format()
template<typename... TArgs> std::string string_format (const std::string_view format, TArgs ... args)
Definition at line 42 of file utils-functions.h.
 {
 #pragma GCC diagnostic ignored "-Wformat-security"
 #pragma GCC diagnostic push
     size_t size = snprintf(nullptr, 0, format.data(), args ...) + 1; // Extra space for '\0'
     if (size <= 0)
         return "";
     std::unique_ptr<char[]> buf(new char[size]);
     snprintf(buf.get(), size, format.data(), args...);
     return std::string(buf.get(), buf.get() + size - 1); // We don't want the '\0' inside
 #pragma GCC diagnostic pop
 }
References il2cpp_utils::args.
Referenced by HookTracker::CombineHooks(), Logger::critical(), Logger::debug(), Logger::error(), LoggerBuffer::get_logDir(), Configuration::getConfigFilePath(), getDataDir(), Logger::info(), Logger::log(), and Logger::warning().
string_vformat()
std::string string_vformat (const std::string_view format, va_list args)
Definition at line 46 of file utils.cpp.
{
     size_t size = vsnprintf(nullptr, 0, format.data(), args) + 1; // Extra space for '\0'
     if (size <= 0)
         return "";
     std::unique_ptr<char[]> buf(new char[size]);
     vsnprintf(buf.get(), size, format.data(), args);
     return std::string(buf.get(), buf.get() + size - 1);
 }
References il2cpp_utils::args.
to_utf16()
std::u16string to_utf16 (std::string_view view)
Definition at line 317 of file utils.cpp.
{
     char16_t* dat = static_cast<char16_t*>(calloc(view.length() + 1, sizeof(char16_t)));
     std::transform(view.data(), view.data() + view.size(), dat, [](auto standardChar) {
         return static_cast<char16_t>(standardChar);
     });
     dat[view.length()] = '\0';
     std::u16string out(dat);
     free(dat);
     return out;
 }
to_utf8()
std::string to_utf8 (std::u16string_view view)
Definition at line 306 of file utils.cpp.
{
     char* dat = static_cast<char*>(calloc(view.length() + 1, sizeof(char)));
     std::transform(view.data(), view.data() + view.size(), dat, [](auto utf16_char) {
         return static_cast<char>(utf16_char);
     });
     dat[view.length()] = '\0';
     std::string out(dat);
     free(dat);
     return out;
 }
writefile()
bool writefile (std::string_view filename, std::string_view text)
Definition at line 378 of file utils.cpp.
{
     std::ofstream t(filename.data());
     if (t.is_open()) {
         t << text;
         return true;
     }
     return false;
 }
Referenced by Configuration::Load(), and Configuration::Write().
Variable Documentation
bool
bool = uchar8_t
Definition at line 12 of file utils-functions.h.
Referenced by rapidjson::AutoUTF< CharType >::Decode(), and rapidjson::AutoUTF< CharType >::Validate().