BeatSaber-Hooks: shared/utils/utils.h File Reference
utils.h File Reference
#include <cxxabi.h>
#include <thread>
#include <optional>
#include "hook-tracker.hpp"
#include "utils-functions.h"
#include "../inline-hook/And64InlineHook.hpp"
#include "logging.hpp"
Data Structures
struct is_vector< Container >
struct is_vector< std::vector< Ts... > >
struct is_instance< class, class >
struct is_instance< U< Ts... >, U >
struct std::is_complete_impl< _Tp >
struct is_value_type< T, Enable >
struct check_size< s, t >
Macros
#define MACRO_WRAP(...)
#define RET_UNLESS(retval, loggerContext, ...)
#define THROW_OR_RET_NULL(contextLogger, ...)
#define RET_V_UNLESS(loggerContext, ...) RET_UNLESS(, loggerContext, __VA_ARGS__)
#define RET_DEFAULT_UNLESS(loggerContext, ...) RET_UNLESS({}, loggerContext, __VA_ARGS__)
#define RET_0_UNLESS(loggerContext, ...) RET_DEFAULT_UNLESS(loggerContext, __VA_ARGS__)
#define RET_NULLOPT_UNLESS(loggerContext, ...) RET_DEFAULT_UNLESS(loggerContext, __VA_ARGS__)
#define DEFINE_MEMBER_CHECKER(member)
#define MAKE_HOOK(name, addr, retval, ...)
#define MAKE_HOOK_OFFSETLESS(name, retval, ...)
#define MAKE_HOOK_NAT(name, addr, retval, ...)
#define INSTALL_HOOK(logger, name)
#define INSTALL_HOOK_OFFSETLESS(logger, name, methodInfo)
#define INSTALL_HOOK_NAT(logger, name)
#define INSTALL_HOOK_DIRECT(logger, name, addr)
Typedefs
template<typename _Tp >
using std::is_complete = typename is_complete_impl< _Tp >::type
Functions
template<class T >
auto && unwrap_optionals (T &&arg)
int mkpath (std::string_view file_path)
void resetSS (std::stringstream &ss)
void tabs (std::ostream &os, int tabs, int spacesPerTab=2)
void print (std::stringstream &ss, Logging::Level lvl=Logging::INFO)
void analyzeBytes (const void *ptr)
uintptr_t getRealOffset (const void *offset)
uintptr_t baseAddr (const char *soname)
uintptr_t findPattern (uintptr_t dwAddress, const char *pattern, uintptr_t dwSearchRangeLen=0x1000000)
uintptr_t findUniquePattern (bool &multiple, uintptr_t dwAddress, const char *pattern, const char *label=0, uintptr_t dwSearchRangeLen=0x1000000)
uintptr_t findUniquePatternInLibil2cpp (bool &multiple, const char *pattern, const char *label=0)
Attempts to match the pattern provided with all regions of mapped read memory with the libil2cpp.so.
Variables
template<typename _Tp >
constexpr bool std::is_complete_v = is_complete<_Tp>::value
template<class _T >
constexpr bool is_value_type_v = is_value_type<_T>::value
template<class... >
constexpr std::false_type false_t {}
Macro Definition Documentation
DEFINE_MEMBER_CHECKER
#define DEFINE_MEMBER_CHECKER (member)
Value:
    template<typename T, typename U, typename Enable = void> \
    struct has_ ## member : std::false_type { }; \
    template<typename T, typename U> \
    struct has_ ## member<T, U, \
        typename std::enable_if_t< \
            std::is_same_v<decltype(T::member), U>> \
        > : std::true_type { };
Definition at line 163 of file utils.h.
INSTALL_HOOK
#define INSTALL_HOOK (logger, name)
Value:
MACRO_WRAP(\
logger.info("Installing 32 bit hook!"); \
registerInlineHook((uint32_t)getRealOffset(addr_ ## name), (uint32_t)hook_ ## name, (uint32_t **)&name); \
inlineHook((uint32_t)getRealOffset(addr_ ## name)); \
)
Definition at line 398 of file utils.h.
INSTALL_HOOK_DIRECT
#define INSTALL_HOOK_DIRECT (logger, name, addr)
Value:
MACRO_WRAP(\
logger.info("Installing 32 bit offsetless hook!"); \
registerInlineHook((uint32_t)addr, (uint32_t)hook_ ## name, (uint32_t **)&name); \
inlineHook((uint32_t)addr); \
)
Definition at line 416 of file utils.h.
INSTALL_HOOK_NAT
#define INSTALL_HOOK_NAT (logger, name)
Value:
MACRO_WRAP(\
logger.info("Installing 32 bit native hook!"); \
registerInlineHook((uint32_t)(addr_ ## name), (uint32_t)hook_ ## name, (uint32_t **)&name); \
inlineHook((uint32_t)(addr_ ## name)); \
)
Definition at line 410 of file utils.h.
INSTALL_HOOK_OFFSETLESS
#define INSTALL_HOOK_OFFSETLESS (logger, name, methodInfo)
Value:
MACRO_WRAP(\
logger.info("Installing 32 bit offsetless hook: %s at %lX", #name, asOffset(methodInfo->methodPointer)); \
registerInlineHook((uint32_t)methodInfo->methodPointer, (uint32_t)hook_ ## name, (uint32_t **)&name); \
inlineHook((uint32_t)methodInfo->methodPointer); \
)
Definition at line 404 of file utils.h.
MACRO_WRAP
#define MACRO_WRAP (...)
Value:
    do { \
    __VA_ARGS__; \
} while(0)
Definition at line 42 of file utils.h.
MAKE_HOOK
#define MAKE_HOOK (name, addr, retval, ...)
Value:
void* addr_ ## name = (void*) addr; \
retval (*name)(__VA_ARGS__) = NULL; \
retval hook_ ## name(__VA_ARGS__)
Definition at line 310 of file utils.h.
MAKE_HOOK_NAT
#define MAKE_HOOK_NAT (name, addr, retval, ...)
Value:
void* addr_ ## name = (void*) addr; \
retval (*name)(__VA_ARGS__) = NULL; \
retval hook_ ## name(__VA_ARGS__)
Definition at line 319 of file utils.h.
MAKE_HOOK_OFFSETLESS
#define MAKE_HOOK_OFFSETLESS (name, retval, ...)
Value:
retval (*name)(__VA_ARGS__) = NULL; \
retval hook_ ## name(__VA_ARGS__)
Definition at line 315 of file utils.h.
RET_0_UNLESS
#define RET_0_UNLESS (loggerContext, ...) RET_DEFAULT_UNLESS(loggerContext, __VA_ARGS__)
Definition at line 152 of file utils.h.
RET_DEFAULT_UNLESS
#define RET_DEFAULT_UNLESS (loggerContext, ...) RET_UNLESS({}, loggerContext, __VA_ARGS__)
Definition at line 151 of file utils.h.
RET_NULLOPT_UNLESS
#define RET_NULLOPT_UNLESS (loggerContext, ...) RET_DEFAULT_UNLESS(loggerContext, __VA_ARGS__)
Definition at line 153 of file utils.h.
RET_UNLESS
#define RET_UNLESS (retval, loggerContext, ...)
Value:
    ({ \
    auto&& __temp__ = (__VA_ARGS__); \
    if (!__temp__) { \
        loggerContext.error("%s (in %s at %s:%i) returned false!", #__VA_ARGS__, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
        return retval; \
    } \
    unwrap_optionals(__temp__); })
Definition at line 98 of file utils.h.
RET_V_UNLESS
#define RET_V_UNLESS (loggerContext, ...) RET_UNLESS(, loggerContext, __VA_ARGS__)
Definition at line 150 of file utils.h.
THROW_OR_RET_NULL
#define THROW_OR_RET_NULL (contextLogger, ...)
Value:
    ({ \
    auto&& __temp__ = (__VA_ARGS__); \
    if (!__temp__) { \
        contextLogger.error("%s (in %s at %s:%i) returned false!", #__VA_ARGS__, __PRETTY_FUNCTION__, __FILE__, __LINE__); \
        return nullptr; \
    } \
    unwrap_optionals(__temp__); })
Definition at line 133 of file utils.h.
Typedef Documentation
is_complete
template<typename _Tp > using std::is_complete = typedef typename is_complete_impl<_Tp>::type
Definition at line 67 of file utils.h.
Function Documentation
analyzeBytes()
void analyzeBytes (const void * ptr)
Definition at line 119 of file utils.cpp.
{
     analyzed.clear();
     std::stringstream ss;
     ss << std::setfill('0');
     ss << "ptr: " << std::hex << std::setw(16) << (uintptr_t) ptr;
     print(ss);
     analyzeBytes(ss, ptr, 0);
 }
References analyzeBytes(), analyzed, and print().
baseAddr()
uintptr_t baseAddr (const char * soname)
Definition at line 128 of file utils.cpp.
 {
     void *imagehandle = dlopen(soname, RTLD_LOCAL | RTLD_LAZY);
     if (soname == NULL)
         return (uintptr_t)NULL;
     if (imagehandle == NULL)
         return (uintptr_t)NULL;
     FILE *f = NULL;
     char line[200] = {0};
     char *state = NULL;
     char *tok = NULL;
     char * baseAddr = NULL;
     if ((f = fopen("/proc/self/maps", "r")) == NULL)
         return (uintptr_t)NULL;
     while (fgets(line, 199, f) != NULL)
     {
         tok = strtok_r(line, "-", &state);
         baseAddr = tok;
         tok = strtok_r(NULL, "\t ", &state);
         tok = strtok_r(NULL, "\t ", &state); // "r-xp" field
         tok = strtok_r(NULL, "\t ", &state); // "0000000" field
         tok = strtok_r(NULL, "\t ", &state); // "01:02" field
         tok = strtok_r(NULL, "\t ", &state); // "133224" field
         tok = strtok_r(NULL, "\t ", &state); // path field
         if (tok != NULL) {
             int i;
             for (i = (int)strlen(tok)-1; i >= 0; --i) {
                 if (!(tok[i] == ' ' || tok[i] == '\r' || tok[i] == '\n' || tok[i] == '\t'))
                     break;
                 tok[i] = 0;
             }
             {
                 size_t toklen = strlen(tok);
                 size_t solen = strlen(soname);
                 if (toklen > 0) {
                     if (toklen >= solen && strcmp(tok + (toklen - solen), soname) == 0) {
                         fclose(f);
                         return (uintptr_t)strtoll(baseAddr,NULL,16);
                     }
                 }
             }
         }
     }
     fclose(f);
     return (uintptr_t)NULL;
 }
Referenced by getRealOffset().
findPattern()
uintptr_t findPattern (uintptr_t dwAddress, const char * pattern, uintptr_t dwSearchRangeLen = 0x1000000)
Definition at line 195 of file utils.cpp.
{
     #define in_range(x, a, b) (x >= a && x <= b)
     #define get_bits(x) (in_range((x & (~0x20)), 'A', 'F') ? ((x & (~0x20)) - 'A' + 0xA): (in_range(x, '0', '9') ? x - '0': 0))
     #define get_byte(x) (get_bits(x[0]) << 4 | get_bits(x[1]))
     // To avoid a lot of bad match candidates, pre-process wildcards at the front of the pattern
     uintptr_t skippedStartBytes = 0;
     while(pattern[0] == '\?') {
         // see comments below for insight on these numbers
         pattern += (pattern[1] == '\?') ? 3 : 2;
         skippedStartBytes++;
     }
     uintptr_t match = 0;  // current match candidate
     uintptr_t len = strlen(CRASH_UNLESS(pattern));
     if (dwSearchRangeLen < len) {
         return 0;
     }
     const char* pat = pattern;  // current spot in the pattern
     for (uintptr_t pCur = dwAddress + skippedStartBytes; pCur < dwAddress + dwSearchRangeLen; pCur++) {
         // If pat[0] is null char, we are done, or if pat >= pattern + len
         if (pat >= pattern + len || !pat[0] || !pat[1]) {
             return match;
         }
         // For each byte, if the pattern starts with a ? or the current byte matches:
         if (pat[0] == '\?' || *(char *)pCur == get_byte(pat)) {
             // If we do not have a match, begin it
             if (!match) {
                 match = pCur - skippedStartBytes;
             }
             // If our next character is at the end of our pattern, we have a match
             if (pat + 1 >= pattern + len) {
                 return match;
             }
             if (pat[0] != '\?' || pat[1] == '\?') {
                 pat += 3;  // advance past "xy " or "?? "
             } else {
                 pat += 2;  // advance past "? "
             }
         }
         else {
             // reset search position to beginning of the failed match; for loop will begin new search at match + 1
             if (match) pCur = match + skippedStartBytes;
             pat = pattern;
             match = 0;
         }
     }
     return 0;
 }
References get_byte.
Referenced by findUniquePattern().
findUniquePattern()
uintptr_t findUniquePattern (bool & multiple, uintptr_t dwAddress, const char * pattern, const char * label = 0, uintptr_t dwSearchRangeLen = 0x1000000)
Definition at line 245 of file utils.cpp.
{
     uintptr_t firstMatchAddr = 0, newMatchAddr, start = dwAddress, dwEnd = dwAddress + dwSearchRangeLen;
     int matches = 0;
     Logger::get().debug("Sigscan for pattern: %s", pattern);
     while (start > 0 && start < dwEnd && (newMatchAddr = findPattern(start, pattern, dwEnd - start))) {
         if (!firstMatchAddr) firstMatchAddr = newMatchAddr;
         matches++;
         if (label) Logger::get().debug("Sigscan found possible \"%s\": offset 0x%lX, pointer 0x%lX", label, newMatchAddr - dwAddress, newMatchAddr);
         start = newMatchAddr + 1;
         Logger::get().debug("start = 0x%lX, end = 0x%lX", start, dwEnd);
         usleep(1000);
     }
     if (matches > 1) {
         multiple = true;
         Logger::get().warning("Multiple sig scan matches for \"%s\"!", label);
     }
     return firstMatchAddr;
 }
References Logger::debug(), findPattern(), Logger::get(), and Logger::warning().
Referenced by findUniquePatternInLibil2cpp().
findUniquePatternInLibil2cpp()
uintptr_t findUniquePatternInLibil2cpp (bool & multiple, const char * pattern, const char * label = 0)
Attempts to match the pattern provided with all regions of mapped read memory with the libil2cpp.so.
Definition at line 264 of file utils.cpp.
{
     // Essentially call findUniquePattern for each segment listed in /proc/self/maps
     std::ifstream procMap("/proc/self/maps");
     std::string line;
     uintptr_t match = 0;
     while (std::getline(procMap, line)) {
         if (line.find("libil2cpp.so") == std::string::npos) {
             continue;
         }
         auto idx = line.find_first_of('-');
         if (idx == std::string::npos) {
             CRASH_UNLESS(false);
         }
         auto startAddr = std::stoul(line.substr(0, idx), nullptr, 16);
         auto spaceIdx = line.find_first_of(' ');
         if (spaceIdx == std::string::npos) {
             CRASH_UNLESS(false);
         }
         auto endAddr = std::stoul(line.substr(idx + 1, spaceIdx - idx - 1), nullptr, 16);
         // Permissions are 4 characters
         auto perms = line.substr(spaceIdx + 1, 4);
         if (perms.find('r') != std::string::npos) {
             // Search between start and end
             match = findUniquePattern(multiple, startAddr, pattern, label, endAddr - startAddr);
         }
     }
     procMap.close();
     return match;
 }
References findUniquePattern().
Referenced by find_GC_AllocFixed(), and find_GC_free().
getRealOffset()
uintptr_t getRealOffset (const void * offset)
Definition at line 179 of file utils.cpp.
 {
     if (location == 0)
     {
         //arm
         // TOOD: Lets get the instance via some sort of initialization function
         // OR we make EVERYTHING on an instance level
         location = baseAddr(Modloader::getLibIl2CppPath().c_str());
     }
     return location + (uintptr_t)offset;
 }
References baseAddr(), and location.
Referenced by il2cpp_utils::BuildGenericsMap(), Instruction::findNth(), and il2cpp_functions::Init().
mkpath()
int mkpath (std::string_view file_path)
Definition at line 191 of file utils.cpp.
{
     return system((std::string("mkdir -p -m +rw ") + file_path.data()).c_str());
 }
Referenced by Configuration::getConfigFilePath(), getDataDir(), and Logger::init().
print()
void print (std::stringstream & ss, Logging::Level lvl = Logging::INFO)
Definition at line 40 of file utils.cpp.
{
     ss << std::endl;
     Logger::get().log(lvl, "%s", ss.str().c_str());
     resetSS(ss);
 }
References Logger::get(), Logger::log(), and resetSS().
Referenced by analyzeBytes().
resetSS()
void resetSS (std::stringstream & ss)
Definition at line 29 of file utils.cpp.
{
     ss.str("");
     ss.clear();  // Clear state flags.
 }
Referenced by print().
tabs()
void tabs (std::ostream & os, int tabs, int spacesPerTab = 2)
Definition at line 34 of file utils.cpp.
{
     for (int i = 0; i < tabs * spacesPerTab; i++) {
         os << " ";
     }
 }
Referenced by analyzeBytes().
unwrap_optionals()
template<class T > auto&& unwrap_optionals (T && arg)
Definition at line 84 of file utils.h.
{
     if constexpr (is_instance<std::decay_t<T>, std::optional>::value) {
         return *arg;
     } else {
         return arg;
     }
 }
References rapidjson::value.
Variable Documentation
false_t
template<class... > constexpr std::false_type false_t {} constexpr
Definition at line 195 of file utils.h.
Referenced by il2cpp_utils::il2cpp_type_check::il2cpp_no_arg_class< S< TArgs... > * >::get().
is_complete_v
template<typename _Tp > constexpr bool std::is_complete_v = is_complete<_Tp>::value constexpr
Definition at line 71 of file utils.h.
is_value_type_v
template<class _T > constexpr bool is_value_type_v = is_value_type<_T>::value constexpr
Definition at line 81 of file utils.h.